Re-implement a wrench that was locked solely to aftershock
CleverRaven/Cataclysm-DDA pull request #42496
Opened 2020-07-28 04:28 UTC by HotCupOfJava

SUMMARY: Content "Re-implement the chain wrench"

#### Purpose of change

The chain wrench is a real life tool that is far easier craft out of scrap than a normal wrench. It can be used for bolt turning nearly as effective as a normal wrench though.

#### Describe the solution

Add a recipe and the item file to the main game locations

#### Describe alternatives you've considered

Make wrenches more common

#### Testing

I spawned in a character and tested if I had access to the recipe

#### Additional context

2020-07-28 04:29 UTC, John-Candlebury commented
You should probably remove it from aftershock too!

2020-07-28 04:31 UTC, anothersimulacrum commented on data/json/recipes/other/tool.json
> +    "components": [ [ [ "scrap", 20 ] ], [ [ "pipe", 1 ] ], [ [ "chain", 1 ] ] ]
This recipes does not produce any of these:
![image](https://user-images.githubusercontent.com/42699974/88619444-6b0a0000-d050-11ea-8e31-aaf1aa1ef5f9.png)
![image](https://user-images.githubusercontent.com/42699974/88619454-6e9d8700-d050-11ea-9bf6-0165458bc16b.png)
![image](https://user-images.githubusercontent.com/42699974/88619468-74936800-d050-11ea-84c1-d2d674f629cf.png)
![image](https://user-images.githubusercontent.com/42699974/88619474-765d2b80-d050-11ea-8e6a-6a75430ceb64.png)

2020-07-31 10:09 UTC, ZhilkinSerg commented
> 
> 
> Shouldn't the recipe ask for a chain?

And a specific one probably.

2020-08-23 18:52 UTC, kevingranade requested changes
This needs a bicycle chain as an input of the recipe.
It also needs a more robust set of requirements for the handle assembly, there's a reason these things are usually beefy forged things, though there are various sources that indicate you can get away with welding on a pipe.

2020-09-10 09:08 UTC, ZhilkinSerg commented
Feel free implement requested changes and reopen.

2020-09-10 09:08 UTC, closed without merging