Add folding guns
CleverRaven/Cataclysm-DDA pull request #42721
Opened 2020-08-05 03:32 UTC by NoahGoldFox

#### Summary

SUMMARY: content "add several folding guns"

#### Purpose of change
I saw that there were no folding guns in the game, and that folding guns would be very convenient, especially with the new nested inventory and "longest side" making it much harder to carry guns around. These folding guns add realistic but somewhat rare loot that are really useful, especially to survivors who pack light.

#### Describe the solution

adding in new folding guns and putting them in item-groups

#### Describe alternatives you've considered
Adding a tool kit that can take down any rifle, but thats not very realistic.

#### Testing

Spawn in each gun, fold and unfold each one several times. Fold with gun attachments and while reloaded, try shooting while fold to make sure it cant. Unfold in backpack and make sure it falls out of backpack since it got too long.

#### Additional context
This PR adds the : 
[ruger 10/22 takdown](https://ruger.com/products/1022Takedown/models.html)
[chiappa little badger](https://www.chiappafirearms.com/family.php?id=26)
[Ruger PC carbine](https://ruger.com/products/pcCarbine/models.html)
[Keltec su-16](https://www.keltecweapons.com/firearms/rifles/su16/)
[foldAR](https://foldar.com/product/double-foldar15-pistol-9-5-56-nato-2020-gen3/)
[chiappa alaskan takedown 44](https://www.chiappafirearms.com/product.php?id=124)
[chiappa wildlands 45-70](https://www.chiappafirearms.com/product.php?id=646)

I was going to add more guns, like the [Paratus folding battle rifle](https://drdtactical.com/paratus/) and the [m96 windrunner takedown 12.7mm](http://www.edmarms.com/products/m96.htm) among others, but i decided not to since those were slightly too rare.

2020-08-05 05:39 UTC, Qrox commented on data/json/items/gun/22.json
> +    "description": "A lightweight, ultra-compact, break-action folding rifle.  It is extremely basic, with a simple wire stock (which includes little 5 shot ammo holder) and a plain barrel.  Use to f
```suggestion
    "description": "A lightweight, ultra-compact, break-action folding rifle.  It is extremely basic, with a simple wire stock (which includes little 5 shot ammo holder) and a plain barrel.  Use to fold.",
```

2020-08-05 05:40 UTC, Qrox commented on data/json/items/gun/22.json
> +    "description": "A folded chiappa badger 22LR rifle.  It is very compact in this form.  Use to unfold",
```suggestion
    "description": "A folded chiappa badger 22LR rifle.  It is very compact in this form.  Use to unfold.",
```

2020-08-05 05:40 UTC, Qrox commented on data/json/items/gun/22.json
> +    "description": "A ruger 10/22 version with the ability to be easily taken down into 2 parts for easier carrying.  It has polymer furniture and is also slightly lighter then the normal 10/22.  ",
```suggestion
    "description": "A ruger 10/22 version with the ability to be easily taken down into 2 parts for easier carrying.  It has polymer furniture and is also slightly lighter then the normal 10/22.",
```
No need for spaces at the end of description.

2020-08-05 06:31 UTC, Hirmuolio commented
The foldable weapons could probably shoot while folded. Just with really bad accuracy.

Also it would be a bit weird to have both folding stock weapon mod and separate folding weapons.

2020-08-05 06:36 UTC, NoahGoldFox commented
> The foldable weapons could probably shoot while folded. Just with really bad accuracy.
> 
> Also it would be a bit weird to have both folding stock weapon mod and separate folding weapons.

Actually of the guns this adds only the su-16 can fire at all while folded, and the version i added has a stock which makes that harder.

2020-08-06 00:24 UTC, dissociativity commented
you might want to make sure they allow less attachments than a standard rifle to prevent awkward folding stock further reducing volume exploits if you haven't already.

2020-08-06 01:17 UTC, NoahGoldFox commented
> you might want to make sure they allow less attachments than a standard rifle to prevent awkward folding stock further reducing volume exploits if you haven't already.

ah yee. i removed the stock mount from the foldar since its folding stock is part of its foldiness.

2020-08-23 18:56 UTC, kevingranade requested changes
I'm not sure if you're aware, but the primary holdup is you have a bunch of load errors.

2020-09-13 08:22 UTC, NoahGoldFox commented
I will fix those in a while, its not abandoned.

2020-10-19 22:11 UTC, NoahGoldFox commented
Im going to come back to this sometime later, but for now im closing it.

2020-10-19 22:11 UTC, closed without merging