Longest Side Audit for archery.json, 500.json, 22.json, 38.json and atgm.json
CleverRaven/Cataclysm-DDA pull request #43424
Opened 2020-09-03 13:30 UTC by venum4k

#### Summary

SUMMARY: Content "Added and checked lengths for several guns, bows and arrows"

#### Purpose of change

Addresses some of the issues with item longest_side being inaccurate, assisting with #41691 and the bows for #43420.

#### Describe the solution

I added some longest_side lines to jsons and changed some numbers.

#### Describe alternatives you've considered

I'm not sure there are any real alternatives to inputting numbers

#### Testing

I checked the in-game inventory screens for updated values.

#### Additional context

A lot of the bow lengths were taken from the existing descriptions in the json files. Some of the gun lengths were from manufacturer websites, some educated guesses were made (hey, the numbers are probably more accurate than they were before).

2020-09-03 13:31 UTC, venum4k commented
Attempt #2 cause I haven't done git in a while and apparently I'm dumb

2020-09-03 14:18 UTC, LaVeyanFiend commented
longest_side is based on Feret distance, not OAL. All the gun lengths will be too short. Please use the tutorial on #37374.

2020-09-03 16:37 UTC, venum4k commented
I had a hunch that it wasn't just the length, I've tried out the tutorial on the Big Horn 89.
![image](https://user-images.githubusercontent.com/1928247/92136251-b491fb80-ee03-11ea-95d9-f3e6b4be4160.png)
S&W 500
![image](https://user-images.githubusercontent.com/1928247/92137978-bbba0900-ee05-11ea-8277-e7b27a175767.png)
Ruger LCR 22
![image](https://user-images.githubusercontent.com/1928247/92138867-df318380-ee06-11ea-9766-08ebc21653c2.png)
Ruger LCR 38 - 0.2mm off from the previous length that I thought was wrong. 
![image](https://user-images.githubusercontent.com/1928247/92139385-93330e80-ee07-11ea-8212-184702ef7758.png)
BGM-71F TOW - Couldn't find a good image for the F variant but I doubt the Feret distance would be any longer. I haven't included the tripod.
![image](https://user-images.githubusercontent.com/1928247/92141978-15710200-ee0b-11ea-9cf6-e3b4d0094169.png)
Sig Mosquito
![image](https://user-images.githubusercontent.com/1928247/92142464-c5df0600-ee0b-11ea-92e9-ee8779655026.png)
That should be all the guns I've modified. Bow length should be the same as their Feret distance from what I understand.

2020-09-03 16:41 UTC, LaVeyanFiend requested changes

2020-09-03 16:41 UTC, LaVeyanFiend commented on data/json/items/gun/500.json
> +    "longest_side": "940 mm",
```suggestion
    "volume": "1995 ml",
    "longest_side": "953 mm",
```
Listing of the gun with 18" configuration as you chose for the longest side with views on all sides: https://www.gunsinternational.com/guns-for-sale-online/rifles/big-horn-armory/big-horn-armory---89----500-s-w.cfm?gun_id=101297785#lg-1
Extraction of gun from image for scaling: https://imgur.com/a/HAU8mtY
SA+Feret: https://imgur.com/a/3IxR2ni
Measuring width of grip cap to match to the bottom view of the rifle to get width: https://imgur.com/a/wERhTUn
Width after scaling to grip cap's width from bottom view of gun: https://imgur.com/a/plqdfrx

2020-09-03 18:40 UTC, LaVeyanFiend commented on data/json/items/gun/500.json
>      "volume": "3 L",
```suggestion
    "weight": "3742 g",
    "volume": "1995 ml",
```
Swapped the field to change, whoops :3
(The weight on Big Horn's website is for the 16" model, I got this from the listing I used for volume+length calculations)

2020-09-04 05:21 UTC, ZhilkinSerg commented
Apparently it fails some ranged balance tests now.

2020-09-05 14:18 UTC, venum4k commented
As I've only recently started adding things to cdda, I'm not really sure what the ranged balance tests are. What do they do and how would I address failing them?

2020-09-05 19:53 UTC, kevingranade commented
The failure says you can no longer load arrows into bows, you may need to update the pocket data for the bows to make that work again.

2020-09-10 02:18 UTC, kevingranade commented
Had a chance to look at this, it turns out the problem is in the test itself.
The arrow is now too long to fit in the character/s backpack, so the arrow displaces the already wielded bow, and since the wielded arrow is not itself reloadable, much less with other errors, the test rightfully throws it's hands up and goes to have a beer.

2020-09-10 02:42 UTC, merged