[WIP][CR] Brain Cylinders as items you can talk to
CleverRaven/Cataclysm-DDA pull request #44358
Opened 2020-09-23 02:34 UTC by Light-Wave

Adds TALK_TO function to items, which lets you talk to an NPC that lives inside the item.
Adds brain cylinders and an NPC that lives inside them.

#### Summary

SUMMARY: Features "Adds Brain Cylinders, items that you can talk to. Also adds functionality for talking to items."

#### Purpose of change

- Adds functionality to talk to items (through C++)
- Adds item to talk to

#### Describe the solution

- Adds TALK_TO as an available use_action for items
  - When Talk_To is invoked, the code will check if the item contains data about an existing NPC
    - If not, create an NPC of id "<item name>_talker" // TODO: Get name dynamically
    - If it does, load the NPC from memory
  - Make sure the NPC has no hunger, thirst, or fatigue, and isn't sleeping
  - Open Dialogue with the NPC
  - Save changes to the NPC
    - // TODO: Make sure the NPC's inventory can not contain the item that contain the NPC
- Adds a Brain Cylinder item that can be talked to
- Adds NPC data for the NPC inside the brain cylinder
- Adds dialogue for the NPC
  - // TODO: Intro quest inspired by prototype cyborgs
  - // TODO: Make brain offer to teach skills and/or recepies if befriended
- // TODO: Possibly some JSON data about starting equipment, class, name list, material, deconstruction, background, etc
- // TODO: Documentation for TALK_TO
- // TODO: item image
- // TODO: Make item apear in world, possibly in mi-go related locations, and perhaps as dropp from mi-go surgeons
- // TODO: Merge item with living_brain_jar from Aftershock? Make Aftershock recipes accept this item?

// TODO: Move JSON from mod folder to main JSON files
// TODO: Verify style

#### Describe alternatives you've considered

- Spawn an invisible NPC that imediately starts a dialogue and despawns directly after being talked to. Might be problematic if there is no space for them to spawn.
- Use a global NPC stored in the map or something instead of storing them in the item, would maybe prevent risk of infinite regress if you manage to get the item inside the NPCs inventory.
- Use the computer interface to create dialogue instead. Unfortunately, the computer interface seems to be hard-coded into C++ and not modifiable by JSON.

#### Testing

Spawning in the item and talking to it seems to work. Data is saved between talks. It is possible to trade with the NPC, which is unintended, but will be left in in case someone want to use that functionality for something like a Minecraft Equivalent Exhange Transmutation Tablet.
Trading the Item to the NPC did not crash the game.

#### Additional context

![brain1](https://user-images.githubusercontent.com/66904273/93956636-edfabe80-fd52-11ea-89a2-9667f17eeca5.PNG)
![brain2](https://user-images.githubusercontent.com/66904273/93956639-f0f5af00-fd52-11ea-9c44-09e59ec3e4ed.PNG)
![brain3](https://user-images.githubusercontent.com/66904273/93956643-f3580900-fd52-11ea-8c75-43aa7fe1915c.PNG)

2020-09-23 02:36 UTC, anothersimulacrum commented
It would be preferred that you add talker_item (like talker)character/npc/avatar) instead of using an NPC.

2020-09-23 19:14 UTC, Leland commented
Nice, feels very Futurama. Where in the CDDA world can you find one of these brain jars? The lab seems like a natural choice.

This also feels like something that would do great in Crazy Cataclysm!

2020-09-23 19:43 UTC, Amoebka commented
This is most certainly a mi-go thing, not a futurama thing.

2020-09-23 20:27 UTC, Light-Wave commented
It would indeed be a mi-go thing. I'm thinking having them spawn in mi-go scout towers and outposts, as well as possible drop from mi-go surgeons.

2020-09-24 06:34 UTC, ScampsAdams commented
Furniture next? (intercom)

2020-09-24 09:48 UTC, Zireael07 commented
Is this a mod thing, or a core thing? When I read the title, I thought "that's cyberpunk [Aftershock] as hell" <3

2020-09-24 13:56 UTC, matskuman5 commented on data/mods/Brain_Cylinders/items.json
> +    "description": "This is a glass cylinder containing a brain. Strange organic-looking growths of resin caps both ends. There apears to be a button on the bottom.",
```suggestion
    "description": "This is a glass cylinder containing a brain. Strange organic-looking growths of resin cap both ends. There appears to be a button on the bottom.",
```

2020-09-24 17:19 UTC, Light-Wave commented
@ScampsAdams That sounds like a great idea. That would allow people to easier make intercom-like furniture without having to hide a dummy NPC nearby.

@Zireael07 It is intended to be a core thing. This is mi-go tech. That being said, I think it should be possible to use these to create Frankenstein monsters from Aftershock

2020-09-24 19:39 UTC, I-am-Erk commented
How hard would it be to make furniture able to talk as well as part of this?

2020-09-24 19:58 UTC, Light-Wave commented
@I-am-Erk I believe it would be fairly easy to make furniture able to talk as well. I'll add it to my to-do list.

2020-09-25 00:12 UTC, aoae23 commented
Really exciting feature. As mentioned above, if you're up for it, you should apply it to the Hub 01 intercom NPC

2020-09-29 05:42 UTC, Light-Wave commented
@anothersimulacrum I fear I do not have a deep enough understanding of the differences between different talker_ classes to know what differences there would be between a talker_item and a talker_npc. Would you care to elaborate what differences you have in mind?

@aoae23 I will attempt to apply it to the Hub 01 intercom, yes.

2020-10-14 12:06 UTC, mlangsdorf requested changes
NAK.  Please implement `talker_item` for this functionality

2020-10-14 12:14 UTC, mlangsdorf commented
The `talker` class is a virtual abstract class that implements all the function calls used by existing dialogue conditions and dialogue effects.  Any child class of `talker` is guaranteed to work with all existing TALK_TOPICs.

The `talker` child classes all take an entity (currently player, avatar, or npc but it can be extended to anything) as an argument to their constructor, and create a `talker_` child class that can be passed to `npctalk.cpp` for dialogue handling.  This gets around a lot of the limitations of the current intercom workaround (there aren't any NPCs that need to be hidden, for instance) and expands the game to allow the player to talk to a brain cylinder, an intercom, or whatever else is needed.

Please read the talker classes (I think they're reasonably well documented) and ping me at mark.langsdorf@gmail.com or mlangsdorf on the dev Discord as you have more questions.

2020-10-26 22:23 UTC, mlangsdorf requested changes
I'm still seeing a lack of a `talker_item` class that is necessary for this to get merged.

2020-10-31 00:16 UTC, Light-Wave commented
> I'm still seeing a lack of a `talker_item` class that is necessary for this to get merged.

2020-10-31 00:18 UTC, Light-Wave commented
> I'm still seeing a lack of a `talker_item` class that is necessary for this to get merged.

I haven't gotten around to it, but intend to implement it.

2020-12-31 01:52 UTC, closed without merging