Minor optimizations
CleverRaven/Cataclysm-DDA pull request #44759
Opened 2020-10-09 08:50 UTC by Farseer2

#### Summary
SUMMARY: Performance "Minor optimizations"

#### Purpose of change

Slightly improves some of the hotspots encountered when profiling #44157

#### Describe the solution
This commit includes 4 changes:
* Add an `unsafe` variant to get_submap_at, as there are _a lot_ of places in map.cpp which bound check multiple times. I converted most I found, but I'm sure there are still a few more.
* Move several tiny yet hot functions to headers so they will be inlined
* Use ref instead of copy in map::shoot
* Small std container usage changes (reserve upfront, count+insert -> insert)

#### Testing
Loaded up the given save, walked around a bit and slept
#### Additional notes
Not sure where to put this, but I think most of the class location should be made non-virtual.
All uses of pos(x/y/z) of it are the same, which begs the question why waste an indirect call whenever using any of them?
I can add this to the PR, but didn't know if this was done intentionally, so I haven't made this change yet.

2020-10-09 09:40 UTC, Qrox commented on src/mtype.cpp
> +    if( species.size() ) {
```suggestion
    if( !species.empty() ) {
```

2020-10-09 20:39 UTC, kevingranade requested changes
I need to see some specific results showing that
``Move several tiny yet hot functions to headers so they will be inlined``
is significant.

The change to map::move_cost() is breaking in some tests and I strongly suspect it will trigger that debug mesage in-game as well.  Overall I'm very leary of sprinkling around a lot of calls that skip bounds checks, these changes will require some very careful review.

2020-10-10 09:02 UTC, Farseer2 commented
As for inlining, here's monster::pos (Which still won't be inlined as its virtual, pointing back to my question), which is a mov instruction when inlined:
![image](https://user-images.githubusercontent.com/318789/95651066-2559c100-0af0-11eb-89cd-c2c780b90b87.png)
The second one I inlined was is_hallucination, which should only be a single mov instruction (If inlined):
![image](https://user-images.githubusercontent.com/318789/95651089-4d492480-0af0-11eb-8808-1f38e5e31945.png)

2020-10-12 15:04 UTC, jbytheway commented
In some cases we can get virtual functions inlined by marking them (or the classes containing them) `final`.  That's a low-risk change which might alleviate your concern.

2020-10-13 19:42 UTC, Farseer2 commented
Well, if you're already making all the uses of location both final and the same, why not just de-virtualize it?

2020-10-14 11:57 UTC, mlangsdorf commented
Can we also get some overall performance numbers?  How long does it take to sleep for 8 hours without these changes versus with them?

2020-10-14 12:04 UTC, mlangsdorf reviewed
These look like sensible changes to me but reviewing this is outside my comfort zone.

2020-10-18 20:58 UTC, kevingranade commented
Okiedokie, I finally had a chance to review this line-by-line, and yes every instance of get_submap_at_unsafe() comes after an explicit inbounds() check.  That's a very clear "do less work" change, so I don't need to see explicit profiling, though I'll try to grab some anyway.

I think it will be worthwhile to go back and evaluate whether these callsites can instead just try to retrieve the submap and treat failures as a bounds check failure, but for now this is worth merging as is.

Thanks for the supporting information WRT the inlining, that's convincing to me.

2020-10-18 23:38 UTC, kevingranade commented
Profiling shows a notable improvement from the map accesses.
Before:
![20201018_140722](https://user-imagithubusercontent.com/860276/96388791-19a97280-1160-11eb-923a-1afcb9c074f1.jpg)
After:
![20201018_163508](https://user-images.githubusercontent.com/860276/96388794-27f78e80-1160-11eb-969a-f4606cdffa2f.jpg)

Specifically monster::move() and map::process_items() both picked up a few percent.

2020-10-18 23:39 UTC, merged