WIP Oversized recipes and clothing items
CleverRaven/Cataclysm-DDA pull request #44783
Opened 2020-10-10 22:15 UTC by Maleclypse

#### Summary

SUMMARY: Content "Oversize recipes and clothing"

#### Purpose of change

Adding oversized items on the scratch made list.  

#### Describe the solution

Originally added an Oversized Costuming Proficiency but eso and mlangsdorf walked me through what they feel is a better near term direction.

#### Describe alternatives you've considered

Most alternatives discussed would involve recreating all aspects of tailoring it seems.

#### Testing
TBD

#### Additional context

2020-10-12 20:37 UTC, LaVeyanFiend requested changes

2020-10-12 20:37 UTC, LaVeyanFiend commented on data/json/items/armor/arms_armor.json
> +    "description": "A pair of arm guards hammered out from metal.  Perfect for the Post-Apocalyptic Warrior look. Larger than average.",
Extra space before "Larger" to fix error.

2020-10-12 20:37 UTC, LaVeyanFiend commented on data/json/items/armor/arms_armor.json
> +    "description": "Customized oversized leather vambraces, made for archery. ",
```suggestion
    "description": "Customized oversized leather vambraces, made for archery.",
```

2020-10-12 20:37 UTC, LaVeyanFiend commented on data/json/recipes/armor/feet.json
> +    "subcategory": "CSC_ARMOR_FEET",
```suggestion
```

2020-10-12 20:37 UTC, LaVeyanFiend commented on data/json/recipes/armor/feet.json
> +    "subcategory": "CSC_ARMOR_FEET",
```suggestion
```

2020-10-12 20:37 UTC, LaVeyanFiend commented on data/json/recipes/armor/feet.json
> +    "subcategory": "CSC_ARMOR_FEET",
```suggestion
```

2020-10-12 20:37 UTC, LaVeyanFiend commented on data/json/recipes/armor/feet.json
> +    "subcategory": "CSC_ARMOR_FEET",
```suggestion
```

2020-10-18 00:47 UTC, Maleclypse commented on data/json/items/armor/hoods.json
> +    "description": "A customized chainmail hood.  Can be worn comfortably under helmets. Comes in size XL.",
```suggestion
    "description": "A customized chainmail hood.  Can be worn comfortably under helmets.  Comes in size XL.",
```

2020-10-18 00:47 UTC, Maleclypse commented on data/json/items/armor/hoods.json
> +    "description": "A customized armored Nomex and Kevlar hood, very strong and durable. Made in Muspelheim.",
```suggestion
    "description": "A customized armored Nomex and Kevlar hood, very strong and durable.  Made in Muspelheim.",
```

2020-10-20 04:08 UTC, Maleclypse commented on data/json/recipes/armor/suit.json
> +    "time": "8 h",
```suggestion
    "time": "8 h",
    "type": "recipe",
```

2020-12-01 20:22 UTC, Maleclypse commented
@ZhilkinSerg Is there anything you need me to do on this PR for it to get merged?

2020-12-04 01:54 UTC, merged