Improvised Quivers and Holster
CleverRaven/Cataclysm-DDA pull request #44951
Opened 2020-10-19 15:13 UTC by maibock-ell

#### Summary
Two new improvised quivers for the early game, as well as a holster.
#### Purpose of change
I believe that the early game should have more options for storing firearms, and ammunition for bows/crossbows. Obtaining holsters and quivers with early game characters is dependant on RNG. Decided to make these as well due to it being easy for a first PR.
#### Describe the solution
Three new items are added as craftables whose recipes are known by default. Two are made from boots, a thigh-high quiver and a knee-high quiver respectively. A flip-flop holster is also here. All three require a leather or webbing belt, and are worse than their non-improvised relatives.
#### Describe alternatives you've considered
As an altenative, one could make birchbark quivers or gamble with RNG in cities. But for those who are in a city and not innawoods, one could make boot quivers. 

#### Testing
I have looked over the JSON at least four times for formatting errors, and so on. I also have done a test in game to make sure that the recipes are able to be used, and so on. The recipes for these items are known by default.

2020-10-26 01:05 UTC, dissociativity commented
it just occurred to me, you're only using one boot, so you should in theory get scrap material for the other boot left over as a crafting result, correct?

Seems like plenty of materials are disappearing from reality through the recipe.

2020-10-26 04:54 UTC, maibock-ell commented
> it just occurred to me, you're only using one boot, so you should in theory get scrap material for the other boot left over as a crafting result, correct?
> 
> Seems like plenty of materials are disappearing from reality through the recipe.

Oh! You seemed to read what I had said wrong. To be fair, it might have been confusing. There are actually two kinds of boot-quivers in this PR, "knee-high boot quiver" and "thigh-high boot quiver".  The difference is that the knee-high boot quiver can only hold bolts due to its size.

2020-12-24 15:33 UTC, int-ua commented
What's this `h.txt`?

2020-12-24 22:46 UTC, maibock-ell commented
> What's this `h.txt` supposed to be?

Huh, have no clue how that managed to get into the PR.

2021-01-22 04:07 UTC, Maleclypse requested changes

2021-01-22 04:07 UTC, Maleclypse commented on data/json/items/armor/ammo_pouch.json
> +    "pocket_data": [ { "ammo_restriction": { "arrow": 40, "bolt": 40 }, "moves": 25 } ],
```suggestion
    "pocket_data": [ { "ammo_restriction": { "arrow": 40, "bolt": 40 }, "moves": 25 } ],
```
Sources on historic quivers suggest between 20 and 30 arrows in a made for arrows quiver.  I think we should assume significantly less for a makeshift quiver.

2021-01-22 04:07 UTC, Maleclypse commented on data/json/items/armor/holster.json
> +    "description": "A improvised solution for the lack of a holster.  Rather comedic, but gets the job done albeit with more encumbrance when commpared to a regular holster.",
Is there a source for this working?

2021-01-22 04:07 UTC, Maleclypse commented on h.txt
> +!src/chkjson
Delete this file?

2021-07-04 07:26 UTC, kevingranade requested changes
No problem in broad strokes, but the existing feedback needs to be addressed.

2021-07-04 20:44 UTC, closed without merging

2021-07-04 20:45 UTC, maibock-ell commented
Haven't had the time to properly work on this PR, so I'm closing it for now.