[Aftershock] Add standard laptop-functionality to control laptop
CleverRaven/Cataclysm-DDA pull request #45028
Opened 2020-10-23 17:18 UTC by Pupsi-Mupsi

#### Summary

`SUMMARY: Mods "Add standard laptop-functionality to control laptop"`

#### Purpose of change

Control laptop is a normal laptop with a "hack-extension" and should therefore have all the functions of a normal laptop. This adds standard laptop-functionality to the control laptop.

---

#### Screenshot(s)

After:

![grafik](https://user-images.githubusercontent.com/44737997/97033345-7ee7d400-1563-11eb-9b87-89b6e35af864.png)

2020-10-23 19:00 UTC, Maleclypse commented
Maybe I need to go and review normal laptop functions. But what are the differences between use, hack a robot and turn on?  Is there any way to make those functions clearer?

2020-10-23 19:04 UTC, Pupsi-Mupsi commented
You're right. That should be clearer.

2020-10-23 19:04 UTC, John-Candlebury requested changes
As Maleclypse mentioned, the iuse menu looks rather confusing. Especially with the `Turn On` and `Use` options, since they dont give any real context on what will happen. Please rename them through making new `item_actions` for them.

2020-10-23 19:39 UTC, Pupsi-Mupsi commented
"Turn on" is a result of `"type": "transform"` which is used in numerous ways. I changed all other menu entries. These changes also affect other items such as regular laptops or game watches.

2020-10-23 19:47 UTC, Pupsi-Mupsi commented
Found a way to get around that. Added `"menu_text": "Light up the screen"` to laptop and control laptop.

2020-10-23 20:09 UTC, Pupsi-Mupsi commented
@John-Candlebury and @Maleclypse 
Are you okay with the recent changes?

2020-10-24 03:22 UTC, Maleclypse commented
> @Maleclypse
> Are you okay with the recent changes?

Thank you! This looks great!

2020-10-24 04:23 UTC, John-Candlebury approved these changes

2020-10-24 07:30 UTC, merged