[Dinomod] Add Qianzhousaurus to Dinoclysm
CleverRaven/Cataclysm-DDA pull request #45282
Opened 2020-11-07 02:23 UTC by Theawesomeboophis

Adds Qianzhousaurus to Dinomod, along with baby and zombie variants.

2020-11-07 02:24 UTC, Theawesomeboophis commented
Previous Commits tried to add orcs as well, orcs are coming btw, still working on them.

2020-11-07 04:40 UTC, LaVeyanFiend requested changes
ID formatting issues, also throw all the files in [the linter.](https://dev.narc.ro/cataclysm/format.html)

2020-11-07 04:40 UTC, LaVeyanFiend commented on data/mods/DinoMod/monsters/dinosaur.json
> +    "id": "mon_Qianzhousaurus",
```suggestion
    "id": "mon_qianzhousaurus",
```
ID formatting is supposed to be all lowercase.

2020-11-07 04:40 UTC, LaVeyanFiend commented on data/mods/DinoMod/monsters/hatchling.json
> +    "id": "mon_Qianzhousaurus_hatchling",
```suggestion
    "id": "mon_qianzhousaurus_hatchling",
```

2020-11-07 04:40 UTC, LaVeyanFiend commented on data/mods/DinoMod/monsters/hatchling.json
> +    "name": "Baby Qianzhousaurus",
```suggestion
    "name": "baby Qianzhousaurus",
```

2020-11-07 04:40 UTC, LaVeyanFiend commented on data/mods/DinoMod/monstergroups/wilderness.json
> +        "monster": "mon_Qianzhousaurus",
```suggestion
        "monster": "mon_qianzhousaurus",
```

2020-11-07 04:40 UTC, LaVeyanFiend commented on data/mods/DinoMod/monstergroups/wilderness.json
> +        "monster": "mon_Qianzhousaurus_juvenile",
```suggestion
        "monster": "mon_qianzhousaurus_juvenile",
```

2020-11-07 04:40 UTC, LaVeyanFiend commented on data/mods/DinoMod/monstergroups/zinosaur.json
> +      { "monster": "mon_Zianzhousaurus", "freq": 4, "cost_multiplier": 70, "starts": 72, "pack_size": [ 4, 8 ] }
```suggestion
      { "monster": "mon_zianzhousaurus", "freq": 4, "cost_multiplier": 70, "starts": 72, "pack_size": [ 4, 8 ] }
```

2020-11-07 04:40 UTC, LaVeyanFiend commented on data/mods/DinoMod/monsters/dinosaur.json
> +
```suggestion
  }
```

2020-11-07 04:40 UTC, LaVeyanFiend commented on data/mods/DinoMod/monsters/zed-dinosaur.json
> +    "name": { "str": "Zombie Qianzhousaurus" },
```suggestion
    "id": "mon_Zianzhousaurus",
    "name": { "str": "Qianz zombie" },
```

2020-11-07 04:40 UTC, LaVeyanFiend commented on data/mods/DinoMod/monsters/zed-dinosaur.json
> +    "description": " An undead Qianzhousaurus, it looks at you with a furious rage in it's eyes and seems intent on eating you.",
```suggestion
    "description": "An undead Qianzhousaurus, looking at you with a furious rage in its eyes and seeming intent on eating you.",
```

2020-11-07 14:02 UTC, Theawesomeboophis commented
Thanks, I'll fix these lines today.

2020-11-07 14:05 UTC, Theawesomeboophis commented
Just commited changes, thanks btw.

2020-11-07 16:02 UTC, LyleSY commented
Looks like your SUMMARY up top is failing formatting requirements. Try adding the word "Mods" between "SUMMARY:" and "Add"
It should look like this:

#### Summary

SUMMARY: Mods "Add Qianzhousaurus as well as baby and zombie variants."

2020-11-07 16:04 UTC, Theawesomeboophis commented
Changed all instances to lowercase.

2020-11-07 16:07 UTC, Theawesomeboophis commented
And changed summary to recommended.

2020-11-07 16:27 UTC, Theawesomeboophis commented
How do I fix json validation?

2020-11-07 16:38 UTC, LyleSY commented
Some of it is linting, just copy your code, paste it here https://dev.narc.ro/cataclysm/format.html
...hit the lint button, then copy the results without the extra blank lines to use instead with nice clean formatting. If it throws an error there's probably a stray comma like I noted above.

2020-11-07 17:12 UTC, Theawesomeboophis commented
It's a syntax error, how do I fix that?

2020-11-07 17:28 UTC, LyleSY requested changes
I've noted the little easy ones. Big picture, please make sure the size and weight of the dino and zombie variant are as realistic as possible, that the speed is same, and I would look at T Rex and Z Rex as a guide on stats. That's the closest comparison I can think of.

2020-11-07 17:34 UTC, LyleSY commented
There's a full list of JSON style issues to look for here https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_STYLE.md

2020-11-07 17:40 UTC, Theawesomeboophis commented on data/mods/DinoMod/monstergroups/wilderness.json
> +      },
No, I'll Make it spawn in wilderness and Lab.

2020-11-07 17:46 UTC, Theawesomeboophis commented on data/mods/DinoMod/monstergroups/zinosaur.json
> +      { "monster": "mon_zianzhousaurus", "freq": 4, "cost_multiplier": 70, "starts": 72, "pack_size": [ 4, 8 ] }
Didn't Realize It spawned in cities, gonna fix that and make it spawn in forest.

2020-11-07 17:51 UTC, Theawesomeboophis commented on data/mods/DinoMod/monsters/juvenile.json
> +
How do I delete those lines?

2020-11-07 17:58 UTC, Theawesomeboophis commented on data/mods/DinoMod/monsters/juvenile.json
> +
Nevermind.

2020-11-07 17:59 UTC, LyleSY commented
It looks like you're not defining a Qianzhousaurus  egg here. That will need to be added to egg.json to spawn dinos without an error

2020-11-07 18:01 UTC, Theawesomeboophis commented
Ok, also made it so Zianzhousaurus spawns in forest, not cities.

2020-11-07 18:17 UTC, Theawesomeboophis commented
I didn't mean for zianzhousaurus to spawn in cities so I fixed it( I think, it might still be wrong).

2020-11-07 18:20 UTC, Theawesomeboophis commented
Added eggs, forgot to add them earlier today.

2020-11-07 18:22 UTC, Theawesomeboophis commented
json validation still failing, must have missed something.

2020-11-07 18:23 UTC, LyleSY commented
Please review the Design doc https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/DinoMod/DESIGN.md
No big dangerous predators or zombies in the forest, we don't want to murder players on day 1 with something they can't fight. Not a lore thing, just gameplay balance
I'd recommend spawning this in the dinosaur spawn groups, specifically GROUP_DINOSAUR and GROUP_DINOSAUR_DANGEROUS and maybe the hatchling in GROUP_DINOSAUR_DANGEROUS_HATCHLING and the juvenile in GROUP_DINOSAUR_DANGEROUS_JUVENILE . 
Jumping into the lore, the reason dinos are coming back is that portals to parallel Earths are popping up as part of the Cataclyms and dinos are crossing over into our world. Science and Swamper locations can grab dinos from anywhere on Earth because they are/were actively going out and grabbing samples and moving them around and messing with them, but dinos in the wilderness groups should be North American dinos, at least until we change the lore again. The old lore was anything goes because they only spawned in swamps and players don't go there anyway.

2020-11-07 18:24 UTC, Theawesomeboophis commented
Where should I make them spawn, in order to balance gameplay?

2020-11-07 18:25 UTC, LyleSY commented
Looks like a comma missing before the new egg
![image](https://user-images.githubusercontent.com/26608431/98448773-a9f22c00-20fc-11eb-8789-2f53ee464ee7.png)

2020-11-07 18:25 UTC, Theawesomeboophis commented
Ok, I'll add the comma.

2020-11-07 18:27 UTC, Theawesomeboophis commented
Should they spawn in lab only?

2020-11-07 18:29 UTC, Theawesomeboophis commented
Looks like I forgot another comma in the hatchlings.json

2020-11-07 18:29 UTC, LyleSY commented
I was thinking about the dinosaur spawn lists here https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/DinoMod/monstergroups/dinosaur.json
...but I would support lab spawns too, sure

2020-11-07 18:32 UTC, Theawesomeboophis commented
So I should remove from wilderness.json and move to lab.json, right?

2020-11-07 18:34 UTC, Theawesomeboophis commented
My mistake, comma is missing in the egg groups json not hatchling json.

2020-11-07 18:42 UTC, Theawesomeboophis commented
Where should Zianzhousaurus spawn, and how do I get it to spawn in that location?

2020-11-07 20:16 UTC, LyleSY commented
GROUP_DINOSAUR_ZOMBIE would be a good place for it. That will add it to DinoMod locations and quests

2020-11-07 22:47 UTC, Theawesomeboophis commented
I can't track down the validator error.

2020-11-07 22:50 UTC, Theawesomeboophis commented
It has seasons and I don't know where it is.

2020-11-07 22:50 UTC, LyleSY commented
Looks like two files need linting and wherever you're spawning juveniles needs a comma before the juveniles
![image](https://user-images.githubusercontent.com/26608431/98452913-b2109280-2121-11eb-9cf3-69cd9e419d38.png)

2020-11-07 22:50 UTC, Theawesomeboophis commented
Thanks, I couldn't find it.

2020-11-07 22:52 UTC, Theawesomeboophis commented
That's in eggs json right?

2020-11-07 22:56 UTC, LyleSY commented
Just checked, it's in wilderness

2020-11-07 22:59 UTC, Theawesomeboophis commented
It was a problem in labs too.

2020-11-07 23:01 UTC, Theawesomeboophis commented
I seem to have added commas to wilderness.

2020-11-07 23:05 UTC, Theawesomeboophis commented
Fixing Qianzhousaurus in wilderness has for some reason broken Eoraptor.

2020-11-07 23:10 UTC, Theawesomeboophis commented
Gonna try and copy old unbroken Eoraptor to file.

2020-11-07 23:13 UTC, Theawesomeboophis commented
Nope, Eoraptor still broken, must be spacing problem or something similar.

2020-11-07 23:31 UTC, LyleSY commented
Oh I see. It's treating the "{" leading in to eoraptor as an unknown character. Deleting that and replacing it in a JSON editor should fix

2020-11-07 23:31 UTC, LyleSY commented
I swear this gets easier

2020-11-08 01:42 UTC, Qrox commented on data/mods/DinoMod/monstergroups/wilderness.json
> +         {
```suggestion
         },
         {
```
Missing a closing bracket here.

2020-11-08 01:42 UTC, Qrox commented on data/mods/DinoMod/monsters/hatchling.json
> +    ]
```suggestion
```

2020-11-08 01:42 UTC, Qrox commented on data/mods/DinoMod/monsters/juvenile.json
>      ]
```suggestion
```

2020-11-08 01:42 UTC, Qrox commented on data/mods/DinoMod/monsters/zed-dinosaur.json
> +
```suggestion
  }
```

2020-11-08 01:57 UTC, Theawesomeboophis commented
Applied suggested changes.

2020-11-08 02:04 UTC, Theawesomeboophis commented
xargs -0 -L 1 tools/format/json_formatter.cgi
Needs linting : data/mods/DinoMod/egg.json
Please read doc/JSON_STYLE.md
Needs linting : data/mods/DinoMod/monstergroups/monstergroups_egg.json
Please read doc/JSON_STYLE.md
terminate called after throwing an instance of 'JsonError'
  what():  Json error: <unknown source file>:76:8: separator not strictly allowed at end of array

        "pack_size": [ 4, 12 ],
        "conditions": [ "SPRING", "SUMMER", "AUTUMN" ]
      },
       ^

    ]
  }

xargs: tools/format/json_formatter.cgi: terminated by signal 6
grep: write error: Broken pipe
find: ‘standard output’: Broken pipe
find: write error
make: *** [style-json] Error 123
Makefile:1149: recipe for target 'style-json' failed
Error: Process completed with exit code 2.

2020-11-08 02:16 UTC, Theawesomeboophis commented
json validation should (hopefully) be fixed now.

2020-11-08 02:19 UTC, Theawesomeboophis commented
oops, forgot another comma.

2020-11-08 02:29 UTC, Qrox reviewed
Please lint the changes.

2020-11-08 02:29 UTC, Qrox commented on data/mods/DinoMod/monsters/dinosaur.json
> +    "description": " Also known as pinnochio rex, this bipedal dinosaur is slower than most and covered in fur, it also looks very hungry.",
```suggestion
    "description": "Also known as pinnochio rex, this bipedal dinosaur is slower than most and covered in fur, it also looks very hungry.",
```

2020-11-08 14:39 UTC, LyleSY commented
Whew, that is a powerful error
![image](https://user-images.githubusercontent.com/26608431/98467943-2ee55000-21a6-11eb-92f1-77e33960679a.png)

Please just revert wilderness back to where it is in the current game. That will disappear that file from these checks. The rest need linting.

2020-11-08 18:48 UTC, Theawesomeboophis commented
Linted all files that needed linting.

2020-11-08 18:51 UTC, Theawesomeboophis commented
That doesn't look good.

2020-11-08 18:58 UTC, Theawesomeboophis commented
How do I restore it to the previous version? I messed up linting.

2020-11-08 21:46 UTC, LyleSY commented
Not sure about your specific setup. Personally I just use the website so less can go wrong. I would just copy and lint the files, hit that edit button, drop the linted data in and submit each one like normal. That should clear the conflicts if I understand the situation correctly

2020-11-09 06:27 UTC, Qrox commented
I think you used the wrong linting tool. You lint a file by going to `http://dev.narc.ro/cataclysm/format.html`, paste the entire file into the text box, click lint, and copy the result back to replace the content of the file.

2020-11-09 18:55 UTC, LyleSY commented
Okay, looks like this needs to be rebased to fix. That's super complicated. Are you on the Discord? https://discord.gg/jFEc7Yp  We can try and walk you through it in dev-help there.

2020-11-10 20:47 UTC, Theawesomeboophis commented
I'll try relinting first, and I'm not a discord person
On Nov 9, 2020 1:55 PM, "LyleSY" <notifications@github.com> wrote:

> Okay, looks like this needs to be rebased to fix. That's super
> complicated. Are you on the Discord? https://discord.gg/jFEc7Yp We can
> try and walk you through it in dev-help there.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/CleverRaven/Cataclysm-DDA/pull/45282#issuecomment-724208682>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARDXS5YLCTDYDLBS6EOQETDSPA3JJANCNFSM4TNLH73A>
> .
>

2020-11-10 20:49 UTC, Theawesomeboophis commented
Do you have a link to a tutorial for rebasing in case relint doesn't work?
On Nov 10, 2020 3:47 PM, "Nerdsplosion X" <xnerdsplosion@gmail.com> wrote:

> I'll try relinting first, and I'm not a discord person
> On Nov 9, 2020 1:55 PM, "LyleSY" <notifications@github.com> wrote:
>
>> Okay, looks like this needs to be rebased to fix. That's super
>> complicated. Are you on the Discord? https://discord.gg/jFEc7Yp We can
>> try and walk you through it in dev-help there.
>>
>> —
>> You are receiving this because you modified the open/close state.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/CleverRaven/Cataclysm-DDA/pull/45282#issuecomment-724208682>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ARDXS5YLCTDYDLBS6EOQETDSPA3JJANCNFSM4TNLH73A>
>> .
>>
>

2020-11-10 20:50 UTC, Theawesomeboophis commented
I'll work on this over the weekend and try and get it in a mergeable state.
On Nov 10, 2020 3:49 PM, "Nerdsplosion X" <xnerdsplosion@gmail.com> wrote:

> Do you have a link to a tutorial for rebasing in case relint doesn't work?
> On Nov 10, 2020 3:47 PM, "Nerdsplosion X" <xnerdsplosion@gmail.com> wrote:
>
>> I'll try relinting first, and I'm not a discord person
>> On Nov 9, 2020 1:55 PM, "LyleSY" <notifications@github.com> wrote:
>>
>>> Okay, looks like this needs to be rebased to fix. That's super
>>> complicated. Are you on the Discord? https://discord.gg/jFEc7Yp We can
>>> try and walk you through it in dev-help there.
>>>
>>> —
>>> You are receiving this because you modified the open/close state.
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/CleverRaven/Cataclysm-DDA/pull/45282#issuecomment-724208682>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/ARDXS5YLCTDYDLBS6EOQETDSPA3JJANCNFSM4TNLH73A>
>>> .
>>>
>>

2020-11-11 00:10 UTC, Theawesomeboophis commented
Almost erased conflicts by using proper linting website, just have to fix eggs.

2020-11-11 00:12 UTC, Theawesomeboophis commented
All conflicts eliminated.

2020-11-11 00:13 UTC, Theawesomeboophis commented
Json validation should pass this time.

2020-11-11 00:13 UTC, Theawesomeboophis commented
Thanks for the help btw.

2020-11-11 00:15 UTC, Theawesomeboophis commented
Hatchlings need relint.

2020-11-11 00:17 UTC, Theawesomeboophis commented
Relint seems to have killed conflicts, didn't use the right linter.

2020-11-11 00:19 UTC, Theawesomeboophis commented
json validation finally passed.

2020-11-11 00:21 UTC, Theawesomeboophis commented
Thx for helping, sorry this took so long, I have no coding experience at all.

2020-11-11 02:56 UTC, LyleSY commented
You're great, this is how I learned too. It seriously does get way easier, just the first time sucks

2020-11-11 03:35 UTC, LyleSY requested changes
Hey, I finally figured out how to do a review properly! Hope these make sense. Trying to work with limits of game and fit with existing dinos. Overall good stuff. If you approve these, please drop these in your local mods folder and try and spawn the regular and zombie version. Ideally they'll spawn without errors and look and act right. If they do, this is good to go.

2020-11-11 03:35 UTC, LyleSY commented on data/mods/DinoMod/monsters/dinosaur.json
> +    "volume": "5000 L",
```suggestion
    "volume": "550 L",
```
Match zombie and not disappear body

2020-11-11 03:35 UTC, LyleSY commented on data/mods/DinoMod/monsters/dinosaur.json
> +    "symbol": "d",
```suggestion
    "symbol": "D",
```
Match other dinos

2020-11-11 03:35 UTC, LyleSY commented on data/mods/DinoMod/monsters/dinosaur.json
> +    "bodytype": "elephant",
```suggestion
    "bodytype": "ostrich",
```
Not sure it even matters

2020-11-11 03:35 UTC, LyleSY commented on data/mods/DinoMod/monsters/dinosaur.json
> +    "aggression": 300,
```suggestion
    "aggression": 90,
```
100 is max, which is zombies. This gives them some basic survival instinct, at least in theory

2020-11-11 03:35 UTC, LyleSY commented on data/mods/DinoMod/monsters/dinosaur.json
> +    "speed": 110,
```suggestion
    "speed": 70,
```
Still faster than Albertosaurus but slower than player

2020-11-11 03:35 UTC, LyleSY commented on data/mods/DinoMod/monsters/dinosaur.json
> +    "melee_dice": 10,
```suggestion
    "melee_dice": 4,
```
More in line with other dinos

2020-11-11 03:35 UTC, LyleSY commented on data/mods/DinoMod/monsters/dinosaur.json
> +    "melee_cut": 16,
```suggestion
    "melee_cut": 12,
```
More in line with other dinos

2020-11-11 03:35 UTC, LyleSY commented on data/mods/DinoMod/monsters/dinosaur.json
> +    "armor_bullet": 12,
```suggestion
    "armor_bash": 4,
    "armor_cut": 2,
    "armor_bullet": 2,
```
Match Albertosaurus

2020-11-11 03:35 UTC, LyleSY commented on data/mods/DinoMod/monsters/dinosaur.json
> +    "hp": 45,
```suggestion
    "hp": 100,
```
Similar to Ceratosaurus, closest body type I see quickly

2020-11-11 03:35 UTC, LyleSY commented on data/mods/DinoMod/monsters/dinosaur.json
> +    "special_attacks": [ [ "Poke", 20 ], { "type": "hit", "cooldown": 10 } ],
```suggestion
    "special_attacks": [ { "type": "bite", "cooldown": 5 }, [ "LUNGE", 10 ] ],
```
Match Albertosaurus without its special grab. Don't think poke exists, would need to be defined.

2020-11-11 03:35 UTC, LyleSY commented on data/mods/DinoMod/monsters/dinosaur.json
> +      "CATFOOD",
```suggestion
```
Convention so far is to not make dangerous adult predators able to be tamed.

2020-11-11 03:35 UTC, LyleSY commented on data/mods/DinoMod/monsters/zed-dinosaur.json
> +    "speed": 175,
```suggestion
    "speed": 60,
```
Zombies are a little slower, about 80% speed

2020-11-11 03:35 UTC, LyleSY commented on data/mods/DinoMod/monsters/zed-dinosaur.json
> +    "melee_dice": 6,
```suggestion
    "melee_dice": 4,
```
Match living version

2020-11-11 03:35 UTC, LyleSY commented on data/mods/DinoMod/monsters/zed-dinosaur.json
> +    "upgrades": { "half_life": 14, "into_group": "GROUP_Zianzhousaurus_UPGRADE" },
```suggestion
```
Either cut this or define this upgrade group and create at least two upgrades for it.

2020-11-11 03:35 UTC, LyleSY commented on data/mods/DinoMod/monsters/zed-dinosaur.json
> +    "armor_bullet": 20,
```suggestion
    "armor_bash": 5,
    "armor_cut": 5,
    "armor_bullet": 3,
```
Match zombie Albertosaurus

2020-11-11 12:39 UTC, Theawesomeboophis commented
Just added suggestions, gonna relint to properly integrate and then test.

2020-11-11 12:44 UTC, Theawesomeboophis commented
Dinosaur.json had to be relinted. Going to test now.

2020-11-11 13:00 UTC, Theawesomeboophis commented
Gonna retest.

2020-11-11 13:50 UTC, Theawesomeboophis commented
DEBUG    : Error: Json error: data/mods//DinoMod/monsters/hatchling.json:685:1: requested non-existing member "symbol" in {
    "id": "mon_qianzhousaurus_hatchling",
    "type": "MONSTER",
    "name": "baby Qianzhousaurus",
    "default_faction": "qianzhousaurus",
    "upgrades": { "age_grow": 40, "into": "mon_qianzhousaurus_juvenile" }
  }


    "upgrades": { "age_grow": 40, "into": "mon_qianzhousaurus_juvenile" }
  }
]
^



 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 948
This Is what I got while testing.

2020-11-11 14:47 UTC, AMurkin commented
Did you forget the `"copy-from"` line?

2020-11-11 15:08 UTC, Theawesomeboophis commented
I don't know, gonna check.

2020-11-11 15:12 UTC, Theawesomeboophis commented
Added copy_from to hatchling, gonna retest.

2020-11-11 15:33 UTC, Theawesomeboophis commented
Loads properly now.

2020-11-11 15:44 UTC, Theawesomeboophis commented
prehistoric creatures mod has begun production btw.

2020-11-11 21:11 UTC, Theawesomeboophis commented
Why is continuous integration failing?

2020-11-11 21:20 UTC, Theawesomeboophis commented
It says command exited with code 1 on appveyor.

2020-11-11 21:27 UTC, anothersimulacrum commented
Not your fault, https://ci.appveyor.com/project/kevingranade/cataclysm-dda/builds/36255225#L704
Same thing on travis too.

2020-11-11 22:36 UTC, Theawesomeboophis commented
> Not your fault, https://ci.appveyor.com/project/kevingranade/cataclysm-dda/builds/36255225#L704
> Same thing on travis too.
Thanks, thought I broke something again.

2020-11-12 21:08 UTC, merged

2020-11-12 22:07 UTC, Theawesomeboophis commented
Gonna work on adding the other 2, then I'll work on Orcs and Ogres.