Antiseptic bandages
CleverRaven/Cataclysm-DDA pull request #45804
Opened 2020-12-04 09:52 UTC by Entity-y

#### Summary
SUMMARY: Content "adds bandages coated in antiseptic powder"

#### Purpose of change
Getting the best healing rates requires the use of a bandage and antiseptic, two trips to the consume menu.

#### Describe the solution
Add QoL item combining antiseptic powder and a bandage to make a slightly faster wound dressing experience.

#### Describe alternatives you've considered
Also using liquid antiseptic, opted not to because it would dry out and just become a normal bandage once again. Perhaps in the future soaked bandages could be contained in a ziplock bag and get hardcoded like a wet towel that dries out over time outside of the container.

Considered making variants for makeshift and boiled bandages, decided it wouldn't be sterile enough to have antiseptic properties with powder alone, the recipe for bandages uses antiseptic.

#### Testing
Made new character, confirmed recipe unlocked at health care 2. Spawned zombie and got myself bleeding and infected, used bandage and verified that both bandage properties and disinfectant took place.

#### Additional context
Requires health care 2 to craft as it takes some skill to distribute the powder effectively and efficiently.

2020-12-04 14:55 UTC, Positronic-Girl commented
I believe in game, the bandages item is implied to already have anti-septic, or something to prevent bacteria growth 
+
This wouldn't really properly dis-infect a wound? you'd basically just be putting a damp rag around your wound, ideally you want to pour it or rub the anti-septic in with cotton balls, and then apply the bandage

2020-12-04 18:31 UTC, Entity-y commented
I don't know how putting a bandage coated in antiseptic powder would be equivalent to a damp rag.
The logic is that the powder is concentrated in one spot on the bandage, that part gets pressed on the wound, then the rest of the bandage gets tightly wrapped around the body part. 
The act of wrapping the bandage would be enough to work the powder onto the wound, then any subtle movements after application would just cause the powder to be rubbed around the wound even more.

2020-12-09 02:38 UTC, kevingranade requested changes
To achieve the same QoL improvement, you can add an "apply antiseptic and apply bandage" action to the menu instead of inventing an item that AFAICT doesn't exist.  There are certainly antiseptic bandages, but from a brief search they're all quick-apply adhesive bandages for extremely minor cuts and abrasions.

Even if such a thing is a real product, I'm quite certain that it's a bit more involved than sprinkling antiseptic powder on a bandage.

2020-12-09 02:44 UTC, Entity-y commented
The only alternative I could think of for this particular idea is making a recipe for a wound dressing kit that bundles individual items together as a single use consumables that achieves this same result.

Modifying menus is beyond my capabilities, maybe once the new wound system is in place with its own dedicated menu, there could be a hotkey for using best available antiseptic and one for best available bandage.

2020-12-09 03:10 UTC, closed without merging