Fixes Compare items color bug
CleverRaven/Cataclysm-DDA pull request #45808
Opened 2020-12-04 15:43 UTC by YoungBlood01

#### Summary

SUMMARY: Bugfixes "Compare items now uses correct font colours."

#### Purpose of change

Fixes #45712 - Font colour for 'Coverage' in Encumbrance section of Compare Items will now be Green for higher coverage, red for lower, to match with average coverage above it.

#### Describe the solution

Removed :lower_is_better from Encumbrance-Coverage section to make the font colour match average coverage above it. 

#### Describe alternatives you've considered

Leaving as it is.

#### Testing

Compiles and runs. Spawned multiple armour items and compared - Font colour is now correct.

#### Additional context

First PR here so any issues please let me know!

2020-12-04 20:20 UTC, Pupsi-Mupsi commented
Not an issue, but can you add a screenshot.

2020-12-05 03:37 UTC, YoungBlood01 commented
> Not an issue, but can you add a screenshot.

There you go!

2020-12-05 18:00 UTC, Aivean requested changes
Take a look at the failed test:
![image](https://user-images.githubusercontent.com/2865203/101259849-46015a00-36e0-11eb-86da-62cfe92e3f44.png)
Notice that `Torso` is expected to be on the new line. 
You need to use `iteminfo::no_flags` for Coverage to preserve the old newline behavior, while removing the incorrect `iteminfo::lower_is_better`.

2020-12-05 21:54 UTC, YoungBlood01 commented
> Take a look at the failed test:
> ![image](https://user-images.githubusercontent.com/2865203/101259849-46015a00-36e0-11eb-86da-62cfe92e3f44.png)
> Notice that `Torso` is expected to be on the new line.
> You need to use `iteminfo::no_flags` for Coverage to preserve the old newline behavior, while removing the incorrect `iteminfo::lower_is_better`.

That's great, thanks for the help.

2020-12-05 22:35 UTC, Aivean approved these changes

2020-12-07 08:39 UTC, ZhilkinSerg commented on msvc-full-features/Cataclysm-vcpkg-static.vcxproj
> +</Project>
```suggestion
</Project>

```

2020-12-07 08:40 UTC, merged