Avoid fusing with the last critter if no proper critter is found
CleverRaven/Cataclysm-DDA pull request #45886
Opened 2020-12-07 12:57 UTC by l29ah

#### Summary

SUMMARY: Bugfixes "Avoid fusing with the last critter if no proper critter is found"

#### Purpose of change

fixes https://github.com/CleverRaven/Cataclysm-DDA/issues/36348

#### Describe the solution
https://github.com/CleverRaven/Cataclysm-DDA/issues/36348#issuecomment-642371872

#### Describe alternatives you've considered

#### Testing
Observed that a dissoluted devourer no longer fuses with my manhacks.

#### Additional context

2020-12-07 18:15 UTC, Aivean approved these changes

2020-12-08 03:15 UTC, kevingranade commented on src/monattack.cpp
>          }
This makes it always fail, you need to clear if it does not find a match instead, like so.
```suggestion
            break;
        }
        critter = nullptr;
```

2020-12-08 03:59 UTC, Aivean reviewed
Oof, I totally missed that. Thanks, Kevin, for spotting.

2020-12-08 04:01 UTC, Aivean requested changes
Withdrawing my approval to avoid confusion. Please see Kevin's comment.

2020-12-08 21:33 UTC, merged