Amorphous 'bars' interaction requires all checked parts unencumbered
CleverRaven/Cataclysm-DDA pull request #46720
Opened 2021-01-13 10:19 UTC by NoddingCrow

#### Summary

SUMMARY: Bugfixes "Amorphous Bars interaction correctly checks all body parts are unencumbered"

#### Purpose of change

Currently the check for amorphous characters to pass through metal bars is 
IF head AND torso AND (either foot) THEN FAIL - i.e. a character in full power armor can simply take off their helmet to pass the check, then somehow phase a full suit of tank plating through a three-inch gap. 
Players can no longer remove their boots to pass through bars in full plate armor.

Reproducible: Aquire character with AQUEOUS and AMORPHOUS traits, spawn metal_bars (t_bars) terrain, examine it. Don full power armor, examine it again. Remove _just_ the helmet, and examine it a third time.

#### Describe the solution

Simply changes the && (AND) checks to || (OR) - so if _any one_ of those body parts is over-encumbered, you'll get caught on the bars.

#### Describe alternatives you've considered

Perhaps change this to a sum-total encumberance check - it wouldn't be outrageous to be able to force medium-encumberance gear through the bars with a time penalty. However, this works for now.

#### Testing

Code compiled, t_bars and t_window_bars (per other PR) examined by aqueous/amorphous character with and without encumbering gear, and again with amorphous trait removed to check the special action is cleared correctly. Checked with single pieces of encumbering gear in each checked slot, and combinations thereof.

2021-01-13 12:35 UTC, Fris0uman commented
Wha about hands abd arms? You could unharcode this check by iterating over every bodyparts using `get_all_bodyparts()`.
Unhardcoding stuff is good and it would make a bit more sense if all parts were concerned byt the check.

2021-01-13 13:12 UTC, NoddingCrow commented
Hi there, @Fris0uman 
I'm a _very_ junior C++ coder so I absolutely went for the simplest solution I could find, partially to fix this problem while working on my other PR and partially just proof-of-viability for running compilation.
That said, I agree with your assessment and if there's an easy way to do this I'll 100% investigate. Thanks for the tip!

2021-01-13 13:25 UTC, NoddingCrow commented
oh dang, you right. That's super easy. One hell of a tip, there.

2021-01-13 14:03 UTC, BrettDong requested changes
Have to follow C++ style convention in this repository to pass CI checks. You can run `make astyle` to format C++ source code before making a commit.

2021-01-13 14:03 UTC, BrettDong commented on src/iexamine.cpp
> +                    here.tername(examp));
```suggestion
    for( const bodypart_id &bp : p.get_all_body_parts() ) {
        if( p.encumb( bp ) >= 10 ) {
            add_msg( m_info,
                     _( "Your amorphous body could slip though the %s, but your cumbersome gear can't." ),
                     here.tername( examp ) );
```

2021-01-14 01:17 UTC, BrettDong approved these changes

2021-01-14 07:26 UTC, merged