Allow Amorphous characters to pass through barred window frames
CleverRaven/Cataclysm-DDA pull request #46721
Opened 2021-01-13 10:19 UTC by NoddingCrow

#### Summary

SUMMARY: Balance "Amorphous trait characters can pass through barred window frames"

#### Purpose of change

The Amorphous trait's unique interaction with metal bars terrain (t_bars) is currently extremely niche and almost never used outside of police buildings. With this change, an unencumbered Amorphous character can perform the same ability on an _empty_ windowframe with metal bars (t_window_bars), giving them a little more use from their ability and improving consistency of behaviour with visually identical tiles.

#### Describe the solution

Apply the examine-action 'bars' to t_window_bars.

#### Describe alternatives you've considered

Also applying this to other permeable objects e.g. chain link fences, though they already have the ability to be vaulted over so I consider them less important.

#### Testing

Characters with and without Aqueous/Amorphous spawned and used to examine t_bars, t_window_bars and the derivatives (alarm, curtain, etc).
Only the empty bars - no glass - support the slime movement as desired. No phasing through glass! Options successfully do not present to characters without the trait. Dialogue box correctly pulls the name of the tile.

2021-01-13 13:17 UTC, Night-Pryanik commented
There are several types of windows with metal grating (t_metal_grate_window_noglass) which could also benefit from this.

2021-01-13 14:00 UTC, BrettDong requested changes
Have to follow the JSON style convention in this repository to pass CI checks. You can run `make style-json` to format JSON files before making a commit.

2021-01-13 14:00 UTC, BrettDong commented on data/json/furniture_and_terrain/terrain-windows.json
> +    "examine_action":"bars",
```suggestion
    "examine_action": "bars",
```

2021-01-13 14:43 UTC, NoddingCrow commented
Okiedoke! 
@Night-Pryanik - I agree, and have added the action to the grated window and grated window noglass too (since they're functionally identical and neither have glass in them. Weird.) 
The ones further down the tree, the heavily grated windows with curtains on, I'm gonna make an executive decision and say they're too densely packed to slime through. Gotta give 'em some disadvantage, much as I love the idea.

2021-01-15 02:58 UTC, BrettDong approved these changes

2021-01-15 06:58 UTC, merged