[Magiclysm] Add bag of infite knives
CleverRaven/Cataclysm-DDA pull request #47610
Opened 2021-02-19 18:02 UTC by Salty-Panda

#### Summary
Mods "[Magiclysm] Add bag of infinite knives"

#### Purpose of change

I wanted it.

#### Describe the solution

Added recharge_type::worn to artifacts. It works like periodic, but require the item to be worn/wielded
Added the bag, it casts a spell that summons one fake item, a throwing knife. The knife is kinda lackluster, in the future the enchantments will be able to modify skills though, so it shall be updated.
Changed description and reduced the price ( KorGenT blocked wearing multiple rings at once recently ) of an existing ring that was doing something similar.

#### Describe alternatives you've considered

Adding the possibility to modify skills via enchantment, but KorGenT already has specific plans on how to do it.

#### Testing

Spawned, used

2021-03-25 19:41 UTC, KorGgenT requested changes
in the artifact code, worn should not be a "charge type" it should be a "prerequisite"; that way you can have worn be required for any charge type, isntead of adding worn enums forr each charge type. see also: how i implemented artifact::has

2021-03-25 19:41 UTC, KorGgenT requested changes
in the artifact code, worn should not be a "charge type" it should be a "prerequisite"; that way you can have worn be required for any charge type, isntead of adding worn enums forr each charge type. see also: how i implemented artifact::has

2021-03-26 10:19 UTC, Salty-Panda commented
> in the artifact code, worn should not be a "charge type" it should be a "prerequisite"; that way you can have worn be required for any charge type, instead of adding worn enums for each charge type. see also: how i implemented artifact::has

So I should add a struct to relic.h
```cpp
enum relic_recharge_condition {
    solar_sunny,
    worn,
    num
};
```
and to recharging function some check before the switch with `charge.type`?
```cpp
    if(charge.requirement == relic_recharge_condition::worn){
        if( ! ( item.is_wield || item.is_held ) ) ) {
            return;
        }
    }
```

Essentially make it work in a way similar to how "has" and "condition" behave?

2021-07-11 13:56 UTC, KorGgenT commented
> So I should add a struct to relic.h [...]
yes, exactly. sorry it took me so long to get back to your question!

2021-08-15 15:05 UTC, Salty-Panda commented
@KorGgenT done and tested

2021-08-16 08:12 UTC, Salty-Panda commented
Forgot to add spawning for POC item though, will add to some item groups today

2021-08-29 15:15 UTC, Salty-Panda commented
Added a few variants using WONDER flag, sadly you can't use copy-from in spells.
Increased price since it's more powerful overall and added it to itemgroups

2021-08-29 15:28 UTC, Salty-Panda commented on src/relic.cpp
> +            debugmsg( "solar" );
```suggestion
```

2021-08-29 20:54 UTC, Salty-Panda commented
The only failed test is vehicle_turrets_test.cpp
AFAIK, this PR is finally done and ready to review

2021-08-30 02:13 UTC, KorGgenT commented
i don't have the time to review this tonight, but have you tested how loading previously saved artifacts will work with your change? it's important that they be able to load without errors.

2021-08-30 08:03 UTC, Salty-Panda commented
Loaded save with two artifacts, Dim Sky(2/2) and Fire Rain(1/1), used both and both refilled to full.
No errors, no visible debug messages

2021-09-24 10:52 UTC, merged