fix ups converted RM13 combat armor
CleverRaven/Cataclysm-DDA pull request #49038
Opened 2021-05-26 13:54 UTC by Terrorforge

#### Summary
Bugfixes "fixes RM13 Combat Armor not working with UPS conversion"

#### Purpose of change
RM13 Combat Armor refuses to turn on when converted to UPS. Spawn a UPS (w/ battery), RM13 and UPS Conversion Mod, install the mod. It will allow you try to turn it on, but will say the fuel cells are dead.

#### Describe the solution

Added a check to the function so it only exits and gives the "dead cells" message if the armor has no charge AND it's not a UPS-converted armor with enough UPS charge to run.

#### Describe alternatives you've considered

There probably needs to be a larger-scale reworking of powered items so this doesn't need to be done individually for every single one, i.e. #48608, but this is a much quicker fix that will get this particular item working right away.

#### Testing

1. Spawn a UPS (w/ battery), RM13 and UPS Conversion Mod
2. Install UPS Conversion Mod in RM13
3. Turn on RM13

2021-05-26 22:08 UTC, Saicchi requested changes

2021-05-26 22:08 UTC, Saicchi commented on src/iuse.cpp
> +    if( !it->ammo_sufficient() && !( it->has_flag( flag_USE_UPS ) && p->has_enough_charges( *it, false )) ) {
```suggestion
    if( !it->ammo_sufficient() && !( it->has_flag( flag_USE_UPS ) &&
                                     p->has_enough_charges( *it, false ) ) ) {
```

2021-05-27 01:00 UTC, andrei8l commented
Using the UPS conversion mod with the RM13 is technically a bug, probably introduced by this other [bugfix](https://github.com/CleverRaven/Cataclysm-DDA/pull/41599).

2021-05-27 07:11 UTC, Terrorforge commented
> Using the UPS conversion mod with the RM13 is technically a bug, probably introduced by this other [bugfix](https://github.com/CleverRaven/Cataclysm-DDA/pull/41599).

Hrm. Well, this fix is probably still preferable to the current situation where installing the mod permanently destroys the armor. You could just disable it entirely, but I have no idea how to do that.

I'd argue it's also preferable to the "intended" behavior, because in my experience the batteries it's supposed to use and the recipe for crafting them are essentially non-existent.

UPS conversion is probably a little too convenient, but I'd say it's an acceptable stopgap until the other problems can be addressed.

2021-05-27 21:35 UTC, andrei8l commented
> You could just disable the modification entirely, but I have no idea how to do that.

Easiest way is to add an `IIREMOVABLE` dummy toolmod, then modify the RM13 spawn group to include that toolmod (by adding `contents-item` to its entry). This works but it's quite ugly and will break in the future if tools are allowed to have multiple mods.

Another hacky way is to add an extra flag check in the filtering lambda in `iuse::toolmod_attach()`, then add the new flag to the RM13's JSON definition.

The best way is only a little more involved. You'd have to first modify `Item_factory::load( islot_mod &slot, ...)` to load a new blacklist array (probably still with a flag rather than item ids), then integrate that into `iuse::toolmod_attach`.

2021-05-28 07:29 UTC, Hirmuolio commented
Does the `"valid_mod_locations"` that is used on guns work on other items?
Some new mod locations could be defined for all the electronic mods and then the slots would have to be defined on all electronic items.

2021-09-23 20:46 UTC, I-am-Erk commented
Any intention to pick this one back up?

2021-09-24 15:24 UTC, Terrorforge commented
> Any intention to pick this one back up?

It's been fixed by the rework I mentioned in the OP. I converted an RM13 to UPS just the other day.

Hot tip, though: unless you have the internal UPS CBM and want to run it off bionic power, just convert it to using heavy batteries directly. The RM13 doesn't have any pockets, and the UPS is too bulky to fit in anything but a backpack.

2021-09-25 07:08 UTC, Night-Pryanik commented
@Terrorforge could you please resolve conflicts?

2021-09-25 23:25 UTC, closed without merging

2021-09-25 23:26 UTC, Terrorforge commented
> @Terrorforge could you please resolve conflicts?

No, this fix is no longer relevant. I'm closing this.