Adding more attunement spells (2/3)
CleverRaven/Cataclysm-DDA pull request #49810
Opened 2021-07-10 11:29 UTC by GuardianDll

#### Summary
Mods "Adding more attunement spells"
#### Purpose of change
Adding:
Magnetism mage "Electrolaser" spell (high damage electric attack) (maybe need to reduce his cost)
Ice elemental "Cold heart" spell (cheam middle damage slow down attack)
Cleansing flame "Hermes reborn" spell (healing and pain split spell with small damage for not 100% healing)
#### Testing
I didnt test it yet, cause i did it a long time ago, but ill test if in few hours
#### Additional context
Some of the changes that was maded by maintainers were lost, like some descriptions errors (sorry for that), so i hope someone can check them and some stuff that was added after content freeze that i didnt notice.
Also its not linted yet.

2021-07-12 05:47 UTC, actual-nh commented
I'm not a maintainer, BTW.

2021-07-12 05:52 UTC, actual-nh commented on data/mods/Magiclysm/Spells/attunements/Magnetism_Mage.json
> +    "description": "Creates a conductive channel from the caster's hand to the target by ionizing air molecules using a high-powered laser beam, then sends a powerful half million volt charge down th
```suggestion
    "description": "Creates a conductive channel from the caster's hand to the target by ionizing air molecules using a high-powered laser beam, then sends a powerful half-million volt charge down the channel.",
```

2021-07-24 12:28 UTC, KorGgenT commented on data/mods/Magiclysm/Spells/attunements/Cleansing_Flame.json
> +    "max_level": 40,
```suggestion
    "max_level": 35,
```

2021-07-24 12:29 UTC, KorGgenT commented on data/mods/Magiclysm/Spells/attunements/Cleansing_Flame.json
> +    "id": "cleansingflame_hermes_burn",
this spell doesn't have a max level

2021-07-24 12:29 UTC, KorGgenT commented on data/mods/Magiclysm/Spells/attunements/Ice_Elemental.json
> +    "max_level": 40,
```suggestion
    "max_level": 35,
```

2021-07-24 12:29 UTC, KorGgenT commented on data/mods/Magiclysm/Spells/attunements/Ice_Elemental.json
> +    "max_level": 40,
```suggestion
    "max_level": 35,
```

2021-07-24 12:31 UTC, KorGgenT commented on data/mods/Magiclysm/Spells/attunements/Magnetism_Mage.json
> +    "max_level": 40,
```suggestion
    "max_level": 35,
```

2021-07-24 12:31 UTC, KorGgenT requested changes
the max level needs to be 35, as stated in the magic balance doc. all of the attunement spells need max level 35 for symmetry reasons.

2021-08-02 15:17 UTC, merged