Add blade dullness
CleverRaven/Cataclysm-DDA pull request #49898
Opened 2021-07-12 22:08 UTC by natsirt721

#### Summary
Features "Add blade dulling"

#### Purpose of change
Fixes #49712 

#### Describe the solution
Adds a `DULLABLE` item flag and two dullness faults. Items will the `DULLABLE` flag have an internal variable 'dullness' which starts at 0 and increments to 10,000 as the item is used. Currently, only butchering and melee combat will increment the dullness. Items with a dullness above 2000 are considered 'dull' and receive a 10% penalty to cutting damage, and have the `fault_blade_dull` applied. Items will a dullness above 7500 are considered 'blunted' and receive a 20% damage cutting damage penalty, and have the second stage fault `fault_blade_blunt` replace the other fault. 

These changes were based largely on the firearm fouling fault, with a few exceptions. 
- There is no indicator on the name of the item as to the dullness.
- The fault is only applies once the internal tracking variable reaches a certain threshold.

There are still a few things to do here, in loose order:

- [x] Base implementation and proof-of-concept
- [ ] Add dulling for other activities (ie forestry)
- [ ] Add `SHARPENING` tool quality, add items that have it, change mend recipe to use it.
- [ ] Add `DULLABLE` flag to all applicable items
- [ ] Add dulling for crafting and vehicle modification work, if possible.

#### Describe alternatives you've considered
Not doing this.

#### Testing
Playtesting. Still need to update the unit tests. Playtesting by others would be greatly appreciated.

#### Additional context

2021-07-12 22:13 UTC, actual-nh commented
A "DULLS_FAST" flag with reduced thresholds would be nice for the inferior-grade medieval weapons.

2021-07-12 22:28 UTC, I-am-Erk requested changes
I believe we have nixed this sort of maintenance until we can package it under a no-micromanagenent passive maintenance action. I already don't think gun faults should have been added before a feature like that.

2021-07-13 03:27 UTC, kevingranade commented
Erk beat me to it, this is only ok if we have some kind of thing where you can go "maintain my equipment" when you have down time and automatically handle any issues like this you have, which restricts it to requiring the tools to do it and sufficient skill, depending on what kind of maintenance we're talking about.

2021-07-13 06:39 UTC, Aerotinge commented
Yeah when I come up with this idea, I forgot people not doing laundry frequently in CDDA. 
I was doing some kind of weapon maintanace in early game. A knife spear getting broken easily and I have to reassemble after disassembly in every zombie killing morning.
It's somehow boring and time consuming, but realistic.

2021-07-13 13:37 UTC, RDru commented
I think we should just stay with weapon getting damaged from use and not add extra on top of that. If anything add some sharpening tools required to repair some weapons from damage.

2021-07-13 15:26 UTC, natsirt721 commented
When you say "no-micro passive maintenance action" are you referring to just a user-facing action that handles maintenance, or something that also provides hooks for tracking maintenance and adjusting items appropriately? If the former, I feel like delaying the addition of this feature until then is putting the cart before the horse - there isn't a whole lot right now (apart from repairing your gear) that would benefit from such an system. If the latter though, then I understand that the gun fouling code would need to be re-written to utilize that, and this feature should wait until the hooks are in place. Just looking for clarity on what the objective vision is.

2021-12-11 18:20 UTC, kevingranade commented
This feature has to wait until we have a regular maintenance infrastructure in place.

2021-12-11 18:20 UTC, closed without merging

2021-12-11 18:39 UTC, Zireael07 commented
Do we have a project/issue for maintenance and/or related infrastructure? I could've sworn we did, but I can't find it...

2021-12-11 19:32 UTC, I-am-Erk commented
I have an old issue posted for it that probably needs updating