Add hemostatic chushion
CleverRaven/Cataclysm-DDA pull request #49913
Opened 2021-07-13 15:44 UTC by Mysteriou85

#### Summary
Content "Add a item for heavy bloodloss in the form of the hemostatic chushion"

#### Purpose of change
Add a hemostatic chushion for stopping heavy bloodloss, in real life this is use during accident as a substitute for manual compression when the victime can't do it itself or when there is multiple heavy wound.

#### Describe the solution
Add the hemostatic chushion as item to the game.

#### Describe alternatives you've considered
None.

#### Testing
None.

#### Additional context
This item isn't actually in any item group at the moment and so can't be found by the player.

2021-07-13 15:52 UTC, ThatIdiotMonro commented
I think the correct spelling is cushion.

2021-07-13 15:56 UTC, Mysteriou85 commented
> I think the correct spelling is cushion.

Yeah you right, I don't know why I wrote it like that.

2021-07-13 15:58 UTC, ThatIdiotMonro commented
> > I think the correct spelling is cushion.
> 
> Yeah you right, I don't know why I wrote it like that.

Sorry for my pedantry. Saves making another PR, though 😊

2021-07-13 19:13 UTC, Venera3 commented
Not a fan of this, to be honest. Bleed removal from bandages is already instantaneous, and `"bleed": 25` means they can be applied to all bleeding wounds and can cure even the heaviest bleeding with only two applications at zero healthcare skill. The whole system deserves a balance pass, but adding an overpowered item in the meantime would just serve to keep tourniquets even more underused.

2021-07-13 20:20 UTC, Mysteriou85 commented
> Not a fan of this, to be honest. Bleed removal from bandages is already instantaneous, and `"bleed": 25` means they can be applied to all bleeding wounds and can cure even the heaviest bleeding with only two applications at zero healthcare skill. The whole system deserves a balance pass, but adding an overpowered item in the meantime would just serve to keep tourniquets even more underused.

I see your consern, but I don't think it will change many thing. We already can use multiple bandage on one wound to stop heavy bleeding, so a item who do it in one go isn't a big thing. And I think it will be a non craftable item and a bit rarer. If more people think this is a problem I will tone down the "bleed" and if it still too much I will delete it.

2021-07-14 18:21 UTC, Venera3 commented
The system as a whole being overtuned is no reason to add an even more broken item. Also, pharmacies randomly stocking advanced care supplies feels unrealistic, but I'm not familiar with US customs.

2021-07-14 19:28 UTC, Mysteriou85 commented
> The system as a whole being overtuned is no reason to add an even more broken item. Also, pharmacies randomly stocking advanced care supplies feels unrealistic, but I'm not familiar with US customs.

That not a advanced care supply, well not to my knowledge, were I live each factory need it for their employees. And for a realiste standpoint you will more likely want to use that than a tourniquet, I mean a tourniquet is used in a last resort and will likely break youre bones and make you lose your member with the interrupted blood circulation.

2021-07-14 19:35 UTC, actual-nh commented
I've never noticed such in a US pharmacy; I suspect they're ordered from a supplier if they're in factories (factories where?)... unless you count blood pressure cuffs, which actually make an excellent partial tourniquet for blood draws and (even more) starting IVs.

2021-07-14 19:43 UTC, Mysteriou85 commented
> I've never noticed such in a US pharmacy; I suspect they're ordered from a supplier if they're in factories (factories where?)... unless you count blood pressure cuffs, which actually make an excellent partial tourniquet for blood draws and (even more) starting IVs.

My bad after research it's commun were I live in france, I forget that not the same thing that america, and when I searched for information (For volume and composition) I found it on what I assumed was a US site, but probably It was just a UK site.

So I don't really know what to do with it, clearly it exist, but I'm not sure where to find it in the US. Also this stuff it's only made for the arm's and leg's, you can't use it for the torso or the head, but I don't know how limit this usage.

2021-07-15 05:54 UTC, Venera3 commented
This would be the point where I'd say "hey, just rebalance the existing bandages and it'll be fine", but in this case it's a good bit more complicated: the underlying bleeding system needs tuning (as it stands bandages can mitigate a `bleed*3` intensity bleeding, so you can treat proper Bleeding with a band-aid) and treatment needs to move into a effect-based bleed mitigation - the bandages getting destroyed should mean the bleeding's back, whereas now it's magiced away. 

But if we make bleeding worse (and we should) we'd need to add at least some forms of treating shock in the form of iv fluids.

2021-07-15 09:55 UTC, Mysteriou85 commented
I don't know, that way away from what I wanted to do for now, I was just trying to get used to use github and mess a bit with the json to add a item.

I see what you say and I think It will probably add to the realysm of the game, but getting a bleeding is easy and can rapidly accumulate, I'm woried that will made combat a chore. But if it is well implemented why not.

2021-07-19 05:37 UTC, kevingranade requested changes
I have two sets of concerns about this item.
One is that it seems to be taking stated effacy of the product at face value with minimal or no insight into its drawbacks.
For example, does a hemostatic cusion allow mobility while applied? Everything I see indicates it's use only on an immobilized patient.
Similarly, is it reasonable to apply this dressing to yourself? I'm skeptical but can't find any information one way or the other, but the only uses I see cited are being applied by a medical professional of some kind.
Then there's the known issue of applicability only to the extremities, at a minimum this restriction must be respected.
Finally, the regional issue, this dressing does not seem to have penetration in the US market, so certainly appearing in pharmacies is uncalled for, and I would like to see some indication that these are in use in the American medical systembefore adding them.

The other concern is what @Venera3 brings up, that the bleeding system as it exists is in an incomplete state that does not have room for another wound dressing.

2021-07-19 08:47 UTC, Mysteriou85 commented
> For example, does a hemostatic cusion allow mobility while applied? Everything I see indicates it's use only on an immobilized patient.

A hemostatic cusion is more cumbersome that a simple bandage, but it does not prevent mouvement, at least to a noticable point in game. It doesn't mean you should move with, but that the same as we should'nt move with a simple bandage applied.

> Similarly, is it reasonable to apply this dressing to yourself? I'm skeptical but can't find any information one way or the other, but the only uses I see cited are being applied by a medical professional of some kind.

It's harder that a simple bandage to applied but that suposed to be translated with the extra time to use it. I'm not a doctor but I learn how to use it, it's clearly not hard at all but if you don't know you can mess up, I think first aid 1 should be more than enough for that.

> Finally, the regional issue, this dressing does not seem to have penetration in the US market, so certainly appearing in pharmacies is uncalled for, and I would like to see some indication that these are in use in the American medical systembefore adding them.

For that, I should have make more research before. If it does not exist in America, to a point where you need to command it online to get some, then it shouldn't be added because it's not here to be found.

I don't know what to do with it for now, if somebody has a solution, maybe we can do something. But for now I think it's no use to add this sort of item, it does not fit the context or the actual system, sorry I sould have looked better.

2021-07-23 18:37 UTC, kevingranade commented
No apologies needed, this is how the process works.  Checking more thoroughly first does more to save you from wasted effort than anything.

2021-10-11 14:00 UTC, closed without merging