Add a construction recipe for the Trash Can
CleverRaven/Cataclysm-DDA pull request #50004
Opened 2021-07-17 11:32 UTC by definitelynotklip

#### Summary
Content "Adds a Construction menu recipe for the Trash Can and makes it metal (drops steel chunks)."

#### Purpose of change

This change makes the basic Trash Can storage container craftable from the Construction menu, like any other existing piece of decor and / or furniture. Its recipe fits the earlygame well and can be both used for functional and decorative purposes.

Recipe:
```
Skills: Fabrication (2).
Tool #1: Hammering of 2 or more.
Tool #2: Metal Saw of 2 or more.
Components: Sheet metal (2).
```

The description was slightly altered to reflect on the fact that this furniture is now craftable, and its yields were also changed from `plastic_chunk (1-2)` to `steel_chunk (3-6)` to reflect upon this change.

#### Testing

The change was fully tested using a local copy of CDDA version 0.F-7b88ade (Experimental, July 15th). I made sure the entry appeared in the Construction list, that the requirements were correct, and that the construction yielded the correct piece of terrain upon completion.

#### Additional context

![image](https://user-images.githubusercontent.com/87395743/126035387-40d3ca29-9540-4a16-b47e-102660c2acca.png)

2021-07-18 18:07 UTC, Atsumari commented
Looks good!

2021-07-18 19:34 UTC, I-am-Erk commented
The current trash can is described as being plastic, though. You will need an "f_trashcan_metal" for this, which I totally approve of.

All in all I think you'd be better off making a "metal trashcan" item you can construct, and then place as furniture, and the furniture can be dismantled to give you a "metal trashcan" item. Then people can walk around using trashcans as a wielded container to hold a bunch of big items.

2021-07-19 00:02 UTC, definitelynotklip commented
> The current trash can is described as being plastic, though. You will need an "f_trashcan_metal" for this, which I totally approve of.
> 
> All in all I think you'd be better off making a "metal trashcan" item you can construct, and then place as furniture, and the furniture can be dismantled to give you a "metal trashcan" item. Then people can walk around using trashcans as a wielded container to hold a bunch of big items.

I changed the description to describe the trash can as metal. The change of material was necessary because crafting a large plastic trash can would be much harder realistically. This is a better solution than making an entire new item, giving it new properties, adding a new deconstruct recipe for said item then adding another step to the existing deconstruction recipe of the furniture.

The point is not to introduce a new container with which you can carry items, it's to let you spawn an existing object (that is also simple enough to craft, hence the PR) without having you resort to using debug. The rest of the steps are unnecessary. You can still drop items into it and (`G`)rab it to move it around, although I don't see players ever utilizing either one of those options.

2021-07-19 01:12 UTC, I-am-Erk commented
I would rather you not change the present trash can. All the tilesets show it as a plastic trash can, and it spawns in places where a plastic can is appropriate. Having large metal trash cans in kitchens all of a sudden is not going to look right. This needs to be a new furniture; it could copy-from f_trashcan which would make it simpler. Or you could create a "plastic trash can" item that f_trashcan deconstructs into, exactly as with f_washer. Making a current widely used furniture item into quite a different furniture item isn't an option.

2021-07-19 01:12 UTC, I-am-Erk requested changes
(see comments)

2021-07-26 15:26 UTC, I-am-Erk commented on data/json/furniture_and_terrain/furniture-storage.json
> +      "items": [ { "item": "steel_chunk", "count": [ 12, 24 ] } ]
```suggestion
      "items": [ { "item": "sheet_metal", "count": [ 1, 2 ] } ]
```

2021-07-30 16:55 UTC, merged