added trap that summons spiders as well as the corresponding spell
CleverRaven/Cataclysm-DDA pull request #50070
Opened 2021-07-19 22:22 UTC by Lady-Aranae

#### Summary
Content "Added a trap that summons spiders as well as the required spell"

#### Purpose of change
Trapdoor spiders didn't feel like actual Trappers. Wanted to change that 

#### Describe the solution
Added trap with the ID "trapdoor spiderden" that spawns hostile spiders and an attached classless spell 

#### Describe alternatives you've considered
Considered changing how trapdoor spiders move and fight

#### Testing
Spawned trap, activated trap, checked error log for any issues

2021-07-19 22:26 UTC, actual-nh commented
Ping: @Venera3?

2021-07-21 15:53 UTC, Maleclypse commented
Can you add a place where this trap occurs?   Maybe in whatever map extra that trapdoor spiders spawn in?  Or a basement?  I can approve once the trap is somewhere in the game.

2021-07-21 18:37 UTC, Venera3 commented
You could well include it in vanilla, potentially as a random forest map extra - including it in the existing web spider den would be nicer, but it would involve c++ since those are hardcoded.

2021-08-11 20:24 UTC, KorGgenT commented on data/mods/Magiclysm/Spells/classless.json
> +    "id": "Summon_trapspider",
```suggestion
    "id": "summon_trapspider",
```

2021-08-11 20:24 UTC, KorGgenT commented on data/mods/Magiclysm/Spells/classless.json
> +    "name": "summon trapdoor spider" ,
```suggestion
    "name": "Summon Trapdoor Spider" ,
```

2021-08-11 20:24 UTC, KorGgenT commented on data/mods/Magiclysm/traps.json
> +	  "spell_data": { "id": "Summon_trapspider" },
```suggestion
	  "spell_data": { "id": "summon_trapspider" },
```

2021-08-11 20:25 UTC, KorGgenT requested changes
The concept looks good, but like maleclypse said, maybe spawn this trap somewhere? also you need to lint your json.

2021-08-13 22:06 UTC, Lady-Aranae commented
Hi, I Added the map extra and linted the json. do I make a new pr or are those changes considered part of this pr?

2021-08-13 22:26 UTC, actual-nh commented
> Hi, I Added the map extra and linted the json. do I make a new pr or are those changes considered part of this pr?

No, just push those to your Github Lady-Aranae:Trapdoor-spiders branch, and also accept the changes that KorGgenT suggested.

2021-08-22 19:49 UTC, KorGgenT commented
sorry about the delay, we've got a json validation error here.

2021-08-22 20:47 UTC, actual-nh reviewed
This may not fix all of the JSON errors, but it should help.

2021-08-22 20:47 UTC, actual-nh commented on data/mods/Magiclysm/Spells/classless.json
> +	"max_range": 3,
```suggestion
	  "min_aoe": 2,
	  "max_aoe": 3,
    "min_damage": 1,
    "max_damage": 1,
	  "min_range": 1,
	  "max_range": 3,
```

2021-08-22 20:47 UTC, actual-nh commented on data/mods/Magiclysm/Spells/classless.json
> +
```suggestion
```

2021-08-22 20:47 UTC, actual-nh commented on data/mods/Magiclysm/traps.json
> +  "always_invisible": true
```suggestion
  {
    "type": "trap",
    "id": "tr_spiderden",
    "name": "Trapdoor spiderden",
    "color": "green",
    "symbol": "#",
    "visibility": 99,
    "avoidance": 99,
    "difficulty": 99,
    "trap_radius": 4,
    "action": "spell",
    "spell_data": {
      "id": "Summon_trapspider"
    },
    "always_invisible": true
```

2021-08-22 20:49 UTC, actual-nh commented on data/mods/Magiclysm/Spells/classless.json
> +    "name": "Summon Trapdoor Spider" ,
```suggestion
    "name": "Summon Trapdoor Spider",
```

2021-08-22 20:50 UTC, actual-nh commented on data/mods/Magiclysm/Spells/classless.json
> +    "flags": [ "PERMANENT", "HOSTILE_SUMMON"],
```suggestion
    "flags": [ "PERMANENT", "HOSTILE_SUMMON" ],
```

2021-08-22 21:59 UTC, Lady-Aranae commented
All the suggested changes should be committed now

2021-08-23 19:30 UTC, KorGgenT commented
you need to run magiclysm/traps.json through the linter. http://dev.narc.ro/cataclysm/format.html

2021-12-04 01:36 UTC, Maleclypse commented on data/mods/Magiclysm/traps.json
> +    "id": "tr_spiderden",
```suggestion
    "id": "tr_spider",
```

2021-12-05 05:45 UTC, closed without merging