Apple2
CleverRaven/Cataclysm-DDA pull request #50225
Opened 2021-07-25 21:53 UTC by GalacticApple

#### Summary
Content "Adds new Numb mutation"

#### Purpose of change
Wanted a new RP-able mutation made in the same vein as Psychopath. Numb takes this even further and will cause players to not feel the effects of morale no matter what they see or do. Could be useful to some players who might not be good at managed morale. 

#### Describe the solution
Mostly C++ mutation that removes the ability for players to feel morale. Is a starting trait (3 pts) but can be gained through medical mutation tree. Certain morale mutations, specifically stylish,  nomad and gourmand have had their morale bonuses/maluses changed to add/remove directly from the player's focus pool (assuming you have numb). 

#### Describe alternatives you've considered
Mostly just an issue of balancing. It might be too costly and it remains to be seen if it's actually fun to play, RP aside. Also could potentially expand the direct morale-to-focus conversion for more mutations or remove the feature entirely. 

#### Testing
Compiled and ran with VS-vcpkg. No obvious issues. 

#### Additional context
This is my first request and I am new to C++.

2021-07-25 22:19 UTC, GalacticApple commented
I forgot some json files.

2021-07-25 22:35 UTC, anothersimulacrum commented
Please change the PR title to describe the PR.

2021-07-26 06:04 UTC, kevingranade requested changes
You seem to have triggered some kind of line ending bug, resulting in every line of every file you touched being changed.
I'm not really sure that a mutation with the effect of "turn the morale system off" is reasonable to have, and you don't seem particularly confident that it adds anything either, so I'm not particularly excited about the prospects.  To be fair though, I can't review it yet since the diff is mangled.

2021-07-26 12:18 UTC, GalacticApple commented
Any suggestions on where I might want to start looking to root this out? I was able to compile and run a debug version with visual studio. I then uploaded the files I changed to github. visual studio says these files all have CRLF line endings.

2021-07-26 14:09 UTC, Brambor commented
@GalacticApple You probably don't use git in the command line, but if you did, [this Stack Overflow answer](https://stackoverflow.com/a/20653073/5057078) would answer your question completely. You will have to google a bit for where Visual Studio has these files, probably.

2021-07-26 20:46 UTC, GalacticApple commented
I'm going to try and sort this out though it may take a bit. I'm also going to see about tweaking the mutations affects to see if I can't make more interesting. Would it be alright if I closed this request and started fresh from a new fork?

2021-07-26 20:51 UTC, anothersimulacrum commented
It would be preferable if that were something you did not have to do, but it's a not a problem if you do.

2021-07-26 20:54 UTC, GalacticApple commented
The issue is with the committed files. Could I just delete them and fetch fresh ones from master and work from there?

2021-07-26 21:29 UTC, anothersimulacrum commented
You could perform a hard reset https://git-scm.com/docs/git-reset

2021-07-26 21:42 UTC, Brambor commented
You can also make a new commit containing the correct line endings. Then [squash](https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git) them all in one. I believe this is such a simple thing it will be okay to be in one commit. But then, I didn't see the code, the diff is enormous.

When you are done, you have to force push to remote `git push --force` to tell the git to really overwrite the remote files. But you can see the diff locally before you push anything [`git diff`](https://git-scm.com/docs/git-diff).

I would try it on my machine, but I would have to download the entire CDDA repo...

2021-07-26 22:23 UTC, GalacticApple commented
Git isn't pushing to GitHub. I think I'm just going to start fresh. Sorry for the trouble.

2021-07-26 22:27 UTC, Brambor commented
> Git isn't pushing to GitHub. I think I'm just going to start fresh. Sorry for the trouble.

[`git add remote`](https://articles.assembla.com/en/articles/1136998-how-to-add-a-new-remote-to-your-git-repo)

2021-07-26 22:33 UTC, GalacticApple commented
That's not the issue. Git knows my remote, its just that when I try to push, it prompts me to authenticate. Then when I try to log in the authentication window closes and nothing else happens. My remote isn't changed near as I can tell.

2021-07-26 22:43 UTC, GalacticApple commented
I'm not done with this. I shall return.

2021-07-26 22:44 UTC, Saicchi commented
> That's not the issue. Git knows my remote, its just that when I try to push, it prompts me to authenticate. Then when I try to log in the authentication window closes and nothing else happens. My remote isn't changed near as I can tell.

Are you perhaps using vscode and trying to push via its terminal? If you do it tries to use vscode github extension for that and you'll need to disable it. Sadly I forgot how I did it.

2021-07-26 23:59 UTC, GalacticApple commented
One question, the line endings are supposed to be LF right?

2021-07-27 00:00 UTC, anothersimulacrum commented
Yes.

2021-07-27 01:52 UTC, closed without merging