Archer's forms training do not require focus
CleverRaven/Cataclysm-DDA pull request #50359
Opened 2021-07-31 14:46 UTC by AccountAlias

#### Summary
Bugfixes "Archer's forms training do not require focus"

#### Purpose of change
Fix #50295. Archer's form training drains stamina focus, as well as applying focus to -which leads away from the intended arrow count to learning.

#### Describe the solution
Remove focus as a consideration for training archery proficiencies by calling `practice()` directly

#### Testing
Shoot arrows, and compare before and after for focus and proficiency xp

2021-07-31 14:51 UTC, anothersimulacrum requested changes
Ignoring focus should be a thing any proficiency can do, either through a flag or field. (E.g. the code for it should live in practice_procifiency, and the opt-in in the JSON def).

2021-07-31 14:56 UTC, AccountAlias commented
I could apply a json flag to focus that so its not so hardcoded to just bows in particular. Certainly there's other proficiencies that are mostly muscle memory which don't require that much focus

2021-07-31 16:08 UTC, AccountAlias commented
Ready for review :)

2021-07-31 16:09 UTC, anothersimulacrum commented on src/character.cpp
> +    const bool ignore_focus = prof.obj().ignore_focus();
Stylistic nit.
```suggestion
    const bool ignore_focus = prof->ignore_focus();
```

2021-07-31 16:10 UTC, anothersimulacrum approved these changes
Looks good to me! Requesting Erk's review on the proficiencies which ignore focus.

2021-07-31 20:59 UTC, I-am-Erk commented
Hmm. Would it be much more work to do a "focus_cost_multiplier"?

The only ones of these I agree with reducing focus on are archery and speed ones (knitting and knapping). However for many proficiencies we could reduce focus costs to a fraction of what they are now if that's doable

2021-07-31 21:09 UTC, anothersimulacrum commented
Focus cost is pretty irrelevant for proficiencies, it's the impact of skills on focus then impacting proficiency xp gain that is the problem.
That needs a smarter solution than a simple multiplier.

2021-08-01 18:16 UTC, AccountAlias commented
only the bow proficiencies and the speed proficiencies now have the ignore_focus property. Another problem with `focus_cost_multiplier` is that focus decrement by 1, so anytime focus is drained. Multipliers won't work unless we want to do another layer of rng on focus drain. Its not that much more work, but I would suggest it be a separate PR after more discussion

2021-08-09 02:46 UTC, merged