Make driver speed not cause problems with driving
CleverRaven/Cataclysm-DDA pull request #50539
Opened 2021-08-06 21:27 UTC by actual-nh

#### Summary
None

#### Purpose of change

A high driver speed, such as from a Magiclysm haste spell, was causing increased - not decreased - fumbles. Fixes #50462.

#### Describe the solution

400 was being compared to a cost that was partially determined by driver speed; instead, compare to `std::max( driver.get_speed() * 4, 400 )`.

#### Testing

CI; would appreciate playtesting by people with familiarity with vehicles in CDDA.

#### Additional context

Ping: @mlangsdorf?

2021-08-06 22:36 UTC, eltank commented
Personally, I would lean towards hard-capping the number of steering actions to 3 per turn regardless of player speed.

That means changing the line above:
```
cost = std::max( driver.get_speed(), 100 ) * ( 1.0f - ( -penalty / 10.0f ) * 2 / 3 );
```
to
```
cost = 100  * ( 1.0f - ( -penalty / 10.0f ) * 2 / 3 );
```

2021-08-07 02:03 UTC, eltank requested changes

2021-08-07 02:03 UTC, eltank commented on src/vehicle_move.cpp
> +        if( penalty > skill || cost > std::max( driver.get_speed() * 4, 400 ) ) {
I would write it as:
```suggestion
        if( penalty > skill || ( penalty > 0 && cost > std::max( driver.get_speed() * 4, 400 ) ) ) {
```
Basically, we should never fumble if the penalty is less than 0 (meaning we have more than enough skill).

2021-08-07 02:12 UTC, eltank commented
I'll update soon with results of playtesting the latest code change.

2021-08-07 02:19 UTC, eltank commented
> I'll update soon with results of playtesting the latest code change.

Drove a motorcycle, mojocycle and SWAT truck at 60mph while hasted to 631 player speed with no fumbling. I had debug code printing the penalty and skill at every turn. Skill was capped at 10 (due to high stats and vehicles skill) and penalty was always negative.

2021-08-07 02:19 UTC, eltank approved these changes

2021-08-07 02:52 UTC, mqrause commented
> ```
> cost = std::max( driver.get_speed(), 100 ) * ( 1.0f - ( -penalty / 10.0f ) * 2 / 3 );
> ```

Not relevant to the PR, but what's with the calculation there? Why not shorten the second part to `(1.0f + penalty / 15.0f)` and add a comment what it means?

2021-08-07 02:59 UTC, eltank commented
> > ```
> > cost = std::max( driver.get_speed(), 100 ) * ( 1.0f - ( -penalty / 10.0f ) * 2 / 3 );
> > ```
> 
> Not relevant to the PR, but what's with the calculation there? Why not shorten the second part to `(1.0f + penalty / 15.0f)` and add a comment what it means?

Due to skill being capped at 10, penalty can't go below -10, so this "/ 10" is normalizing it to [0,1], which makes it clearer that it gives at most a 2/3 reduction in cost.
I think @mlangsdorf would say that this magic number 10 needs to be defined as a constant (shared with the skill capping code above) and we shouldn't introduce more magic numbers (such as the 15 you suggested).

2021-08-07 03:11 UTC, mqrause commented
Sure, I just don't think the way it's written makes it clearer what it's doing than a comment and a magic number.

2021-08-07 03:33 UTC, eltank commented
> Sure, I just don't think the way it's written makes it clearer what it's doing than a comment and a magic number.

I will have reason to mess with this code later (need to refactor the cost calculation outside of pldrive in order to improve autodrive) and I'll try to clean it up then.

2021-08-07 07:29 UTC, merged