Jsonize Pet Food
CleverRaven/Cataclysm-DDA pull request #50948
Opened 2021-08-21 03:05 UTC by Saicchi

# Title
Jsonize Pet Food

#### Summary
Infrastrucute "Jsonize Pet Food"

#### Purpose of change
Player is currently locked at 4 categories of pet food: `DOGFOOD`, `CATFOOD`, `CATTLEFODDER` and `BIRDFOOD`.

Allow different types of pet food to tame any monster if they have the matching food type.

#### Describe the solution

Add a new field for comestibles:
`"petfood": [ "FUNGALFRUIT", "MIGOFOOD" ]`

Add a new field for monsters:
```c++
"petfood": {
    "food": [ "CATFOOD", "YULECATFOOD" ], // food categories this monster accepts
    "feed": "The gigantic %s decides not to maul you today.", // (optional) message when feeding the monster the food
    "pet": "The %s is enjoying hunting the red laser dot." // (optional) message when playing with pet
}
```

If both of these categories match the player can feed the item to the monster.

#### Describe alternatives you've considered
Add a new bool to allow / prevent playing with the pet.

Make `feed` and `pet` a list of strings which gets randomly chosen when they're needed.

#### Testing
- Optional parameters
  - [x] feed
  - [x] pet
- [x] Player does not eat the item they're trying to feed.
- [x] Feeding animals
- [x] Feeding the "dog"
- [x] Loading Aftershock and DinoMod
- [x] Loading Dark Skies Above

I'm not testing `Desert Region` as the mod is marked as obsolete.

#### Additional context
Can't wait until we see zombie dog pet food.

Since I removed the `BIRDFOOD`, `CATFOOD` and `CATTLEFODDER` monster flags, monsters now need the `CANPLAY` flag if you wan't to play with them. Note that I did not remove `DOGFOOD` since it is still used with `iuse::dog_whistle`.

| Flag         | Mod           | Monster                     | Can Play | Feed                                 | Pet                                      |
| :---:        | :---          | :---                        | :---: | :---                                 | :---                                     |
| DOGFOOD      | DDA           | mon_dog                     | Yes | The %s seems to like you!  It lets you pat its head and seems friendly. | The %s happily wags it's tail while you pat their head. |
| DOGFOOD      | DDA           | mon_dog_bull                | Yes | The %s seems to like you!  It lets you pat its head and seems friendly. | The %s happily wags it's tail while you pat their head. |
| DOGFOOD      | DDA           | mon_dog_bull_pup            | Yes | The %s seems to like you!  It lets you pat its head and seems friendly. | The %s happily wags it's tail while you pat their head. |
| DOGFOOD      | DDA           | mon_dog_pitbullmix          | Yes | The %s seems to like you!  It lets you pat its head and seems friendly. | The %s happily wags it's tail while you pat their head. |
| DOGFOOD      | DDA           | mon_dog_pitbullmix_pup      | Yes | The %s seems to like you!  It lets you pat its head and seems friendly. | The %s happily wags it's tail while you pat their head. |
| DOGFOOD      | DDA           | mon_dog_beagle              | Yes | The %s seems to like you!  It lets you pat its head and seems friendly. | The %s happily wags it's tail while you pat their head. |
| DOGFOOD      | DDA           | mon_dog_beagle_pup          | Yes | The %s seems to like you!  It lets you pat its head and seems friendly. | The %s happily wags it's tail while you pat their head. |
| DOGFOOD      | DDA           | mon_dog_bcollie             | Yes | The %s seems to like you!  It lets you pat its head and seems friendly. | The %s happily wags it's tail while you pat their head. |
| DOGFOOD      | DDA           | mon_dog_bcollie_pup         | Yes | The %s seems to like you!  It lets you pat its head and seems friendly. | The %s happily wags it's tail while you pat their head. |
| DOGFOOD      | DDA           | mon_dog_boxer_pup           | Yes | The %s seems to like you!  It lets you pat its head and seems friendly. | The %s happily wags it's tail while you pat their head. |
| DOGFOOD      | DDA           | mon_dog_chihuahua           | Yes | The %s seems to like you!  It lets you pat its head and seems friendly. | The %s happily wags it's tail while you pat their head. |
| DOGFOOD      | DDA           | mon_dog_chihuahua_pup       | Yes | The %s seems to like you!  It lets you pat its head and seems friendly. | The %s happily wags it's tail while you pat their head. |
| DOGFOOD      | DDA           | mon_dog_dachshund           | Yes | The %s seems to like you!  It lets you pat its head and seems friendly. | The %s happily wags it's tail while you pat their head. |
| DOGFOOD      | DDA           | mon_dog_dachshund_pup       | Yes | The %s seems to like you!  It lets you pat its head and seems friendly. | The %s happily wags it's tail while you pat their head. |
| DOGFOOD      | DDA           | mon_dog_gshepherd           | Yes | The %s seems to like you!  It lets you pat its head and seems friendly. | The %s happily wags it's tail while you pat their head. |
| DOGFOOD      | DDA           | mon_dog_gshepherd_pup       | Yes | The %s seems to like you!  It lets you pat its head and seems friendly. | The %s happily wags it's tail while you pat their head. |
| DOGFOOD      | DDA           | mon_dog_gpyrenees           | Yes | The %s seems to like you!  It lets you pat its head and seems friendly. | The %s happily wags it's tail while you pat their head. |
| DOGFOOD      | DDA           | mon_dog_gpyrenees_pup       | Yes | The %s seems to like you!  It lets you pat its head and seems friendly. | The %s happily wags it's tail while you pat their head. |
| DOGFOOD      | DDA           | mon_dog_rottweiler          | Yes | The %s seems to like you!  It lets you pat its head and seems friendly. | The %s happily wags it's tail while you pat their head. |
| DOGFOOD      | DDA           | mon_dog_rottweiler_pup      | Yes | The %s seems to like you!  It lets you pat its head and seems friendly. | The %s happily wags it's tail while you pat their head. |
| DOGFOOD      | DDA           | mon_dog_auscattle           | Yes | The %s seems to like you!  It lets you pat its head and seems friendly. | The %s happily wags it's tail while you pat their head. |
| DOGFOOD      | DDA           | mon_dog_auscattle_pup       | Yes | The %s seems to like you!  It lets you pat its head and seems friendly. | The %s happily wags it's tail while you pat their head. |
| DOGFOOD      | DDA           | mon_dog_mutant_mongrel      | Yes | The %s seems to like you!  It lets you pat its head and seems friendly. | The %s happily wags it's tail while you pat their head. |
| DOGFOOD      | Aftershock    | afs_mon_cyber_mastiff_pup   | Yes | The %s seems to like you!  It lets you pat its head and seems friendly. | The %s happily wags it's tail while you pat their head. |
| DOGFOOD      | DinoMod       | mon_eoraptor_hatchling      | Yes | The %s seems to like you!  It lets you pat its head and seems friendly. | The %s happily wags it's tail while you pat their head. |
| CATFOOD      | DDA           | mon_cat_kitten              | Yes | The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with felines. | The %s sofly purrs as you pet it.  It demands more. |
| CATFOOD      | DDA           | mon_cat_kitten              | Yes | The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with felines. | The %s sofly purrs as you pet it.  It demands more. |
| CATFOOD      | DDA           | mon_cat                     | Yes | The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with felines. | The %s sofly purrs as you pet it.  It demands more. |
| CATFOOD      | DDA           | mon_cat_mutant_prism        | Yes | The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with felines. | The %s sofly purrs as you pet it.  It demands more. |
| CATFOOD      | DDA           | mon_cat_mutant_kitten_prism | Yes | The %s seems to like you [...]

2021-08-21 03:27 UTC, actual-nh reviewed
"CATFOOD" for dinosaurs, at least, does not indicate they're felines - it indicates they're obligate (and, for optimal health, almost pure) carnivores, like domestic cats. I will let @LyleSY comment on the other parts including petting responses.

2021-08-21 03:27 UTC, actual-nh commented on data/mods/DinoMod/monsters/dinosaur.json
> +      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with felines.",
```suggestion
      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with reptiles.",
```

2021-08-21 03:27 UTC, actual-nh commented on data/mods/DinoMod/monsters/dinosaur.json
> +      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with felines.",
```suggestion
      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with reptiles.",
```

2021-08-21 03:27 UTC, actual-nh commented on data/mods/DinoMod/monsters/dinosaur.json
> +      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with felines.",
```suggestion
      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with reptiles.",
```

2021-08-21 03:27 UTC, actual-nh commented on data/mods/DinoMod/monsters/hatchling.json
> +      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with felines.",
```suggestion
      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with reptiles.",
```

2021-08-21 03:27 UTC, actual-nh commented on data/mods/DinoMod/monsters/hatchling.json
> +      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with felines.",
```suggestion
      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with reptiles.",
```

2021-08-21 03:27 UTC, actual-nh commented on data/mods/DinoMod/monsters/juvenile.json
> +      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with felines.",
```suggestion
      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with reptiles.",
```

2021-08-21 03:27 UTC, actual-nh commented on data/mods/DinoMod/monsters/juvenile.json
> +      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with felines.",
```suggestion
      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with reptiles.",
```

2021-08-21 03:27 UTC, actual-nh commented on data/mods/DinoMod/monsters/juvenile.json
> +      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with felines.",
```suggestion
      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with reptiles.",
```

2021-08-21 03:27 UTC, actual-nh commented on data/mods/DinoMod/monsters/juvenile.json
> +      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with felines.",
```suggestion
      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with reptiles.",
```

2021-08-21 03:27 UTC, actual-nh commented on data/mods/DinoMod/monsters/juvenile.json
> +      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with felines.",
```suggestion
      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with reptiles.",
```

2021-08-21 03:27 UTC, actual-nh commented on data/mods/DinoMod/monsters/juvenile.json
> +      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with felines.",
```suggestion
      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with reptiles.",
```

2021-08-21 03:27 UTC, actual-nh commented on data/mods/DinoMod/monsters/juvenile.json
> +      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with felines.",
```suggestion
      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with reptiles.",
```

2021-08-21 03:27 UTC, actual-nh commented on data/mods/DinoMod/monsters/juvenile.json
> +      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with felines.",
```suggestion
      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with reptiles.",
```

2021-08-21 03:27 UTC, actual-nh commented on data/mods/DinoMod/monsters/juvenile.json
> +      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with felines.",
```suggestion
      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with reptiles.",
```

2021-08-21 03:27 UTC, actual-nh commented on data/mods/DinoMod/monsters/juvenile.json
> +      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with felines.",
```suggestion
      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with reptiles.",
```

2021-08-21 03:27 UTC, actual-nh commented on data/mods/DinoMod/monsters/juvenile.json
> +      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with felines.",
```suggestion
      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with reptiles.",
```

2021-08-21 03:27 UTC, actual-nh commented on data/mods/DinoMod/monsters/juvenile.json
> +      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with felines.",
```suggestion
      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with reptiles.",
```

2021-08-21 03:27 UTC, actual-nh commented on data/mods/DinoMod/monsters/juvenile.json
> +      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with felines.",
```suggestion
      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with reptiles.",
```

2021-08-21 03:27 UTC, actual-nh commented on data/mods/DinoMod/monsters/juvenile.json
> +      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with felines.",
```suggestion
      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with reptiles.",
```

2021-08-21 03:29 UTC, Saicchi commented
My plan was to give them all the basic string first like all the other monsters then fix each mod individually to make things more organized. But doing it in this PR works too.

2021-08-21 05:47 UTC, PatrikLundell commented
Dinosaurs aren't reptiles, but their own category (i.e. dinosaurs). If you have to cram them into any current day category it would have to be birds.

I would also expect different dinosaur species to have very different diets, as there were carnovors, herbivores, and, probably, omnivores. It makes about as much sense to give them all the same diet as it would to do the same with mammals.

2021-08-21 15:17 UTC, Saicchi commented
I also had the idea of removing `feed` and `pet` strings from monsters from mod but I left them there so the mod contributors know where to look.

2021-08-21 20:12 UTC, kevingranade commented on data/mods/DinoMod/monsters/dinosaur.json
> +      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell with felines.",
```suggestion
      "feed": "The %s seems to like you!  Or maybe it just tolerates your presence better.  It's hard to tell...",
```

2021-08-21 20:19 UTC, actual-nh commented
> Dinosaurs aren't reptiles, but their own category (i.e. dinosaurs). If you have to cram them into any current day category it would have to be birds.

OK, "dinosaurs"? (Or if someone _else_ wishes to do ellipses - they're entirely too difficult to enter and edit for me.)

> I would also expect different dinosaur species to have very different diets, as there were carnovors, herbivores, and, probably, omnivores. It makes about as much sense to give them all the same diet as it would to do the same with mammals.

As I mentioned above:

>"CATFOOD" for dinosaurs, at least, does not indicate they're felines - it indicates they're obligate (and, for optimal health, almost pure) carnivores, like domestic cats.

"CATTLEFODDER" indicates a herbivore; "DOGFOOD" indicates an omnivore.

2021-08-21 20:26 UTC, Saicchi commented
> "CATTLEFODDER" indicates a herbivore; "DOGFOOD" indicates an omnivore.
In this PR the name doesn't matter at all, it just keeps things organized. As long as they have at least one category in common, the food item can be used with the monster. I'll the food categories for dinosaurs and add them to their respective food items.

2021-08-21 20:27 UTC, actual-nh commented
> I also had the idea of removing `feed` and `pet` strings from monsters from mod but I left them there so the mod contributors know where to look. Like changing `CATFOOD` to `DINOFOOD` or let the cyber mastiff puppy only eat cyber-cookies.

The latter is amusing; the former would not work properly because of variable diets, if done that way. Documentation of "CATFOOD" as simply indicating a carnivore could help, apparently.

2021-08-21 20:30 UTC, actual-nh commented
For most carnivores anything that would give someone with a predator mutation pleasure to eat is _potentially_ edible, although too much fat will not be appetizing for most.

2021-08-21 20:33 UTC, actual-nh commented
DOGFOOD, once the actual preferred diet is indicated, can be eliminated from most unless there's some reason to think they'd respond to a dog whistle - good point about that.

2021-08-21 20:48 UTC, actual-nh commented
OK, that works re DinoMod; thanks! (I may do a PR rearranging the letters for which one is which among DINOFOOD_A, DINOFOOD_B, and DINOFOOD_C so it's DINOFOOD_C for carnivores, DINOFOOD_H for herbivores, and DINOFOOD_O for omnivores. Dunno whether a separate one for piscivores (fish-eaters) is needed.)

2021-08-21 20:53 UTC, Saicchi commented
Both the monster and item can have any number of categories, and you can put the category in any comestible. So create as many categories as needed.

2021-08-21 20:54 UTC, PatrikLundell commented
(Almost) exclusive fish eaters are likely to be aquatic or amphibian, and so not really candidates for taming.

2021-08-21 21:04 UTC, LyleSY requested changes
Eh, I'm going with Sea World rules for DinoMod. This implementation is much smarter than I understood, the flexibility is amazing. I made a suggestion to allow omnivores to eat all the things, and either Kevin or actual-nh's customizations seem fine to me. Really great stuff here.

2021-08-21 21:34 UTC, actual-nh commented
> Sea World rules

?

2021-08-21 22:22 UTC, LyleSY commented
SeaWorld trains killer whales and dolphins with treats. They aren't truly tame like a dog, but they'll perform commands. Granted those are both mammals. https://en.wikipedia.org/wiki/Captive_killer_whales#Training

2021-08-22 00:19 UTC, LyleSY approved these changes

2021-08-22 03:52 UTC, Maleclypse approved these changes
This is really impressive and the Aftershock section is complete.  Thank you!

2021-09-08 06:44 UTC, merged