Uncraft kevlar suits and torso armor.
CleverRaven/Cataclysm-DDA pull request #51318
Opened 2021-09-02 17:05 UTC by Craftomega

#### Summary
Bugfixes "uncraft kevlar suits and torso armor."

#### Purpose of change
Nearly all suits and armors can be uncrafted and there are extremely few ways to get sheet_kevlar_layered or sheet_kevlar. This is a quick and dirty change.

#### Describe the solution
Using the existing xlhsurvivor_suit and xlsurvivor_suit as a template I gathered all suits and torso armors that have use kevlar and created recipes to uncraft them.

#### Describe alternatives you've considered
This is clearly unbalanced in terms of crafting times, however, I am not sure what the correct times should be. Feel free to change them.

#### Testing
Spawned and uncrafted each item and found no errors.

#### Additional context

2021-09-02 18:31 UTC, Craftomega reviewed
Fixed missed comma

2021-09-04 02:37 UTC, kevingranade commented on data/json/uncraft/armor/suit.json
> +  },
These are both obsoleted.
```suggestion
```

2021-09-25 04:36 UTC, Maleclypse requested changes
I've taken a swing at trying to get this directionally correct.

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +    "time": "5 m",
```suggestion
    "time": "75 m",
```

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +    "time": "10 m",
```suggestion
    "time": "90 m",
```

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +    "time": "10 m",
```suggestion
    "time": "90 m",
```

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +      [ [ "steel_chunk", 4 ] ],
```suggestion
      [ [ "scrap", 14 ] ],
```

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +    "time": "10 m",
```suggestion
    "time": "90 m",
```

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +    "time": "10 m",
```suggestion
    "time": "90 m",
```

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +      [ [ "duct_tape", 200 ] ],
```suggestion

```
Duct tape is never salvageable.

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +      [ [ "duct_tape", 300 ] ],
```suggestion

```
Duct tape is never salvageable.

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +      [ [ "duct_tape", 200 ] ]
```suggestion

```
Duct tape is never salvageable.

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +      [ [ "duct_tape", 300 ] ],
```suggestion

```
Duct tape is never salvageable.

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +    "time": "10 m",
```suggestion
    "time": "90 m",
```

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +      [ [ "duct_tape", 300 ] ],
```suggestion

```
Duct tape is never salvageable.

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +    "time": "10 m",
```suggestion
    "time": "90 m",
```

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +      [ [ "duct_tape", 200 ] ],
```suggestion

```
Duct tape is never salvageable.

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +    "time": "10 m",
```suggestion
    "time": "110 m",
```

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +      [ [ "duct_tape", 300 ] ],
```suggestion

```
Duct tape is never salvageable.

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +    "time": "10 m",
```suggestion
    "time": "110 m",
```

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +      [ [ "duct_tape", 300 ] ],
```suggestion

```
Duct tape is never salvageable.

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +      [ [ "duct_tape", 300 ] ]
```suggestion

```
Duct tape is never salvageable.

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +    "time": "10 m",
```suggestion
    "time": "110 m",
```

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +      [ [ "duct_tape", 300 ] ],
```suggestion

```
Duct tape is never salvageable.

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +    "time": "10 m",
```suggestion
    "time": "110 m",
```

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +      [ [ "duct_tape", 135 ] ]
```suggestion

```
Duct tape is never salvageable.

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +    "time": "10 m",
```suggestion
    "time": "70 m",
```

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +      [ [ "duct_tape", 135 ] ]
```suggestion

```
Duct tape is never salvageable.

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +      [ [ "coat_rain", 1 ] ],
```suggestion

```
Rain coat won't be salvageable.

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +      [ [ "coat_rain", 2 ] ],
```suggestion

```

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +      [ [ "duct_tape", 200 ] ]
```suggestion

```

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +    "time": "10 m",
```suggestion
    "time": "80 m",
```

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +      [ [ "coat_rain", 1 ] ],
```suggestion

```

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +      [ [ "duct_tape", 85 ] ]
```suggestion

```

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +    "time": "10 m",
```suggestion
    "time": "80 m",
```

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +      [ [ "coat_rain", 1 ] ],
```suggestion

```

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +      [ [ "duct_tape", 85 ] ]
```suggestion

```

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +    "time": "10 m",
```suggestion
    "time": "90 m",
```

2021-09-25 04:36 UTC, Maleclypse commented on data/json/uncraft/armor/suit.json
> +      [ [ "duct_tape", 400 ] ],
```suggestion

```

2021-12-15 04:26 UTC, I-am-Erk commented
Closing as stale. Feel free to reopen and continue.

2021-12-15 04:26 UTC, closed without merging