New mine variant
CleverRaven/Cataclysm-DDA pull request #51471
Opened 2021-09-08 13:22 UTC by Night-Pryanik

#### Summary
Content "New mine variant"

#### Purpose of change
To add more content and homages.

#### Describe the solution
~Moria~ New mine consists of two levels (not counting the first underground level): 
- hallway with traces of battle, with skeletons of long-dead ~dwarves and orcs~ humanoids with their arms and armor in very bad shape.
- finale with long and winding pathway among the rocks, bottomless pits and streams of lava. Pathway concludes with a straight ~Bridge of Khazad-dûm~ bridge that leads to a closed room with a ~Balrog~ new `fiery nightmare` monster.
- The monster is very tough, very fast, has very high melee skills, an assortment of existing melee special attacks, and a new melee attack with its flaming whip. All attacks deal `HEAT` type of damage, so your armor most probably won't help you a lot. The new attack can even set you on fire (10% chance), and despite it's max duration is only 1 turn, it's almost certain death sentence for the unprepared.
- loot consists of new fabrication book which can learn you to forge a longsword from a ~mithril~ mysterious silvery metal. I shamelessly copied the stats for the material and the ingot from Magiclysm. I hope @KorGgenT won't yell at me for that.
#### Describe alternatives you've considered
Put it into Magiclysm instead of vanilla.

#### Testing
Debug-spawned new mine, teleported around it, checked for errors.

#### Additional context
Part of the hallway
![изображение](https://user-images.githubusercontent.com/11132525/132516256-b29bf07f-9bdc-4354-9534-4e78cf06b7a6.png)

Finale
![изображение](https://user-images.githubusercontent.com/11132525/132517044-ad3e2583-2ccd-4b7b-8270-47cf7d82115c.png)

2021-09-08 14:03 UTC, chaohedgehogs commented on data/json/items/book/fabrication.json
> +    "description": "This book is written on some runic language you have not a slightest idea about.  Fortunately, there are several very detailed colored pictures demonstrating the process of forgin
```suggestion
    "description": "This book is written in a runic language you are unfamilliar with.  Fortunately, there are several very detailed pictures that demonstrate the process of forging a sword from an ingot of silvery metal.  You get the impression that this is some sort of textbook for blacksmiths.",
```

2021-09-08 14:05 UTC, chaohedgehogs commented on data/json/items/chemicals_and_resources.json
> +    "description": "An ingot of mithril.  About 3 cm by 7 cm by 12 cm in size, ready to be used for various blacksmithing tasks.",
```suggestion
    "description": "An ingot forged from an exotic silvery metal.  Aproximately 3 cm by 7 cm by 12 cm in size, ready to be used for various blacksmithing tasks.",
```

2021-09-08 14:15 UTC, chaohedgehogs commented on data/json/items/melee/swords_and_blades.json
> +    "description": "This is a classic medieval sword, in between the lighter arming sword and later two-handed swords in size.  Most probably thanks to mysterious silvery metal it was forged from, it
```suggestion
    "description": "This is a classic medieval sword, the size being in-between the lighter arming sword and later two-handed swords.  Thanks to the mysterious silvery metal it was forged from, it is stronger than tempered steel while weighing substantially less.",
```

2021-09-08 14:20 UTC, chaohedgehogs commented on data/json/monsters/nether.json
> +    "description": "A colossal figure which seems to consist entirely of shadows engulfed by flames.  Its immense dark wings extend from wall to wall.  Two eyes, like two burning charcoals, are looki
```suggestion
    "description": "A colossal figure which seems to consist entirely of shadows engulfed in flames.  Its immense dark wings extend from wall to wall.  Two eyes that resemble burning coals are gazing down on you with hatred.  In one hand it holds a huge sword, in the other it has a many thonged whip, both glowing with red-hot flames.",
```

2021-09-08 21:02 UTC, Maleclypse commented on data/json/monsters/nether.json
> +    "armor_bullet": 12,
```suggestion
    "armor_bullet": 25,
```
I think animate shadows & flames should ignore more damage from small projectiles comparatively to what they take from cut and bash.

2021-09-08 21:19 UTC, actual-nh reviewed
I suspect this may better go into Magiclysm, but very nice in any event!

2021-09-08 21:19 UTC, actual-nh commented on data/json/items/book/fabrication.json
> +    "description": "This book is written in a runic language that you are unfamilliar with.  Fortunately, there are several very detailed pictures that demonstrate the process of forging a sword from
```suggestion
    "description": "This book is written in a runic language unfamiliar to you.  Fortunately, there are several very detailed pictures that demonstrate the process of forging a sword from an ingot of silvery metal.  You get the impression that this is some sort of textbook for blacksmiths.",
```

2021-09-08 21:19 UTC, actual-nh commented on data/json/monsters/nether.json
> +    "flags": [ "SEES", "WARM", "BASHES", "DESTROYS", "NO_BREATHE", "PUSH_MON", "PUSH_VEH", "FIREY", "PATH_AVOID_DANGER_2" ]
```suggestion
    "path_settings": { "avoid_traps": true, "avoid_sharp": true },
    "flags": [ "SEES", "WARM", "BASHES", "DESTROYS", "NO_BREATHE", "PUSH_MON", "PUSH_VEH", "FIREY", "PATH_AVOID_DANGER_1" ]
```
PATH_AVOID_DANGER_2 is unfortunately not working right currently. IIRC, see #48588 for more info

2021-09-13 19:49 UTC, SirPendrak commented
Since this new sword is lighter, should it do a bit less bash damage?
And what about being able to use it with martial arts?

2021-09-14 04:09 UTC, Night-Pryanik commented
Yeah, both suggestions are good. Will work on them a bit later today.

2021-09-21 04:10 UTC, kevingranade requested changes
> Put it into Magiclysm instead of vanilla.

Go with this please, too far into fantasy-land for vanilla.

2021-10-07 08:17 UTC, merged