new components to basic wraps
CleverRaven/Cataclysm-DDA pull request #51576
Opened 2021-09-13 03:34 UTC by dissociativity

#### Summary
Balance "Adds new cotton components to basic wrap recipes"

#### Purpose of change
less extremity freezing from being unable turn cotton rags into the abstracted other kind of cotton rag

#### Describe the solution
add patchwork and standard cotton sheets to wrap recipes

#### Describe alternatives you've considered
don't do this

#### Testing
load into game, take apart sheet, make recipes

2021-09-13 03:35 UTC, dissociativity commented
I'll probably do more PRs as this happens, a better solution may be to obsolete "rag" for the newer materials and auto-replace the recipe stuff?

2021-09-13 05:42 UTC, cainiaowu commented
you can make them into a "requirement" like 
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/json/requirements/materials.json

2021-09-14 15:15 UTC, dissociativity commented
neat, I'll work on that tomorrow

2021-09-15 06:57 UTC, dissociativity commented
oops now the scope is huge, but I'll work on this for at least an hour a day and be done with it all without too much time, should make for far more tailoring flexibility in game, please let me know if specific items /should/ strictly be made from cotton that used rags before and I'll make them use a new cotton requirement instead of allowing non-stretchy fabrics in general.

2021-10-02 02:44 UTC, dissociativity commented
wow, really need a proper json editor that'll point out syntax errors, the web linter just kind of cries at you and notepad++ just helps highlight syntax, not actually let me know where something is missing or broken

2021-10-02 15:22 UTC, Maleclypse submitted a review, later dismissed
This is a pretty good update.  Thanks!

2021-10-02 15:24 UTC, Maleclypse commented on data/json/recipes/armor/torso.json
> +    "using": [ [ "sewing_standard", 45 ], [ "fabric_fur_pelt", 5 ]  [ "fastener_large", 1 ] ],
```suggestion
    "using": [ [ "sewing_standard", 45 ], [ "fabric_fur_pelt", 5 ],  [ "fastener_large", 1 ] ],
```

2021-10-02 18:42 UTC, Maleclypse commented
I fixed the errors in the torso file but can't carry linting over in the edit function apparently.  But I think linting would be all you need to have this ready for merge.

2021-10-03 00:28 UTC, dissociativity commented
> 
> 
> I fixed the errors in the torso file but can't carry linting over in the edit function apparently. But I think linting would be all you need to have this ready for merge.

the scope of this PR is actually to include all clothing files, but it can be reduced if you'd like the smaller changes in more immediately, suits.json and torso.json are both finished other than the lint, with a few minor changes to other jsons, mostly for early-game clothing to stop the player from freezing easily

2021-10-03 01:11 UTC, Maleclypse commented
Smaller PRs that cover a coherent chapter of the entire work are best. It reduces the load on reviewers. And in the event that something slips through reviews and automated testing and bricks the build it’s easier to find the error.

2021-10-03 01:28 UTC, dissociativity commented
part 1 is done and ready to merge I suppose then

2021-10-03 02:45 UTC, Maleclypse commented on data/json/recipes/armor/torso.json
> +    "using": [ [ [ "sewing_standard", 4 ], [ "fabric_standard_nostretch", 5 ] ] ]
```suggestion
    "using": [ [ "sewing_standard", 4 ], [ "fabric_standard_nostretch", 5 ] ]
```

2021-10-03 21:07 UTC, Maleclypse commented
Are these working on your local machine?   `felt in fabric_felt is not a valid item template
(~[slow] ~[.])=> 03:14:30.091 ERROR : src/requirements.cpp:531 [void component::check_consistency(const string&) const] sheet_fur_patchwork in fabric_fur is not a valid item template`  I've got a ton of errors popping up here

2021-10-04 00:19 UTC, dissociativity commented
> 
> 
> Are these working on your local machine? `felt in fabric_felt is not a valid item template (~[slow] ~[.])=> 03:14:30.091 ERROR : src/requirements.cpp:531 [void component::check_consistency(const string&) const] sheet_fur_patchwork in fabric_fur is not a valid item template` I've got a ton of errors popping up here

my bad, must've missed it and done some changes /after/ things were tested, and messed up a bit, I'll figure it out

2021-10-04 06:32 UTC, dissociativity commented
this is odd,
`17:28:49.374 ERROR : src/requirements.cpp:531 [void component::check_consistency(const string&) const] felt in fabric_felt is not a valid item template
17:29:12.324 ERROR : src/requirements.cpp:531 [void component::check_consistency(const string&) const] sheet_fur_patchwork in fabric_fur is not a valid item template
17:29:20.616 ERROR : src/requirements.cpp:531 [void component::check_consistency(const string&) const] sheet_fur in fabric_fur is not a valid item template
17:29:21.585 ERROR : src/requirements.cpp:531 [void component::check_consistency(const string&) const] sheet_fur_patchwork in fabric_fur_pelt is not a valid item template
17:29:22.088 ERROR : src/requirements.cpp:531 [void component::check_consistency(const string&) const] sheet_fur in fabric_fur_pelt is not a valid item template`
all of these items as far as I'm aware exist in tailoring.json, why are they not considered valid as items within the materials.json?

2021-10-04 06:34 UTC, dissociativity commented
oh, or not, must be dissociating a bit too much and missing a handful of things, where are the old "rag" and "leather" even stored? it's bizzare they're not in tailoring.json

2021-10-07 03:02 UTC, dissociativity commented
okay, I think this is good to go?

2021-10-07 07:09 UTC, dissociativity commented
wait, nope

2021-10-07 07:10 UTC, dissociativity commented
nevermind, that was an issue on my end, it loads fine now, just doing a little testing

2021-10-08 02:11 UTC, dissociativity commented
> 
> 
> The blueprint test failed because of a recipe you changed. You’d need to change what the faction camp recipe calls for to match your updated recipe.

not experienced with faction camp recipe stuff, how would I go about that?

2021-10-12 12:07 UTC, dissociativity commented
okay, so I've compiled it all and it's still asking for the json formatter, what am I doing wrong? the exe for the json formatter is in the correct directory, does it need to be renamed?

2021-10-12 16:07 UTC, mqrause commented
`Specified blueprint requirements of faction_base_modular_hub_core_kitchen_butchery_center does not match calculated requirements.` So it's `faction_base_modular_hub_core_kitchen_butchery_center` that needs updating. There might also be others, I didn't look through the whole report.
Also the issue isn't the formatting but that the requirements for the faction camp recipe(s) need to be adjusted since your changes affected some relevant recipes.

2021-10-13 05:53 UTC, dissociativity commented
to which search responds "no items match your search" as there is no json named that at all, no-one has really taught me to use some sort of github search files for lines function yet, so my only choice is to go through them one by one and hope I bump into the recipe, and then do that again if the test fails again.

2021-10-16 06:06 UTC, dissociativity commented
starting a new medication and having difficulty focusing is fun, let's get this PR finished

2021-10-17 09:46 UTC, dissociativity commented
how should I resolve conflicts here? merge from upstream/master or?

2021-10-17 21:06 UTC, mqrause commented
The recommended solution is to rebase onto master, but merging master into your branch works, too.

2021-11-07 19:33 UTC, Termineitor244 requested changes
I checked that all the numbers and requirements were in order with respect to their previous numbers and components, I found some that need to be adjusted (Like fax fur clothing using fur haha), but after this changes this should be ready to merge.

2021-11-07 19:33 UTC, Termineitor244 commented on data/json/recipes/armor/torso.json
> +    "using": [ [ "sewing_standard", 80 ], [ "fabric_fur", 30 ] ]
```suggestion
    "using": [ [ "sewing_standard", 80 ], [ "fabric_felt", 30 ] ]
```

2021-11-07 19:33 UTC, Termineitor244 commented on data/json/recipes/armor/torso.json
> +    "using": [ [ "sewing_standard", 45 ], [ "fabric_standard_nostretch", 14 ], [ "fabric_fur", 12 ], [ "fastener_large", 1 ] ],
```suggestion
    "using": [ [ "sewing_standard", 45 ], [ "fabric_standard_nostretch", 14 ], [ "fabric_fauxfur", 12 ], [ "fastener_large", 1 ] ],
```

2021-11-07 19:33 UTC, Termineitor244 commented on data/json/recipes/armor/suit.json
> +    "using": [ [ "sewing_standard", 76 ], [ "fabric_leather_fur_hide", 6 ] ],
```suggestion
    "using": [ [ "sewing_standard", 76 ], [ "fabric_leather_fur_hide", 7 ] ],
```

2021-11-07 19:33 UTC, Termineitor244 commented on data/json/recipes/armor/suit.json
> +    ]
This was moved to another file and is now an exodii given recipe, see #51987
```suggestion
```

2021-11-07 19:33 UTC, Termineitor244 commented on data/json/recipes/armor/suit.json
> +      [ "fabric_leather_hide", 4 ],
```suggestion
```

2021-11-07 19:33 UTC, Termineitor244 commented on data/json/recipes/armor/suit.json
> +    "using": [ [ "sewing_standard", 40 ], [ "fabric_standard_nostretch", 20 ] ]
```suggestion
    "using": [ [ "sewing_standard", 40 ], [ "fabric_standard_nostretch", 30 ] ]
```

2021-11-07 19:33 UTC, Termineitor244 commented on data/json/recipes/armor/suit.json
> +    "using": [ [ "sewing_standard", 50 ], [ "fabric_standard_nostretch", 12 ], [ "fabric_neoprene", 8 ] ],
```suggestion
    "using": [ [ "sewing_standard", 50 ], [ "fabric_standard_nostretch", 12 ], [ "fabric_neoprene", 12 ] ],
```

2021-11-08 03:27 UTC, dissociativity commented
yeah, I dissociate a lot and make mistakes on larger stuff like this a lot oops

2021-11-08 03:48 UTC, Termineitor244 commented
You're welcome! Thanks for doing all this work! I don't know if it means anything, but I approve this changes.

2021-11-08 03:49 UTC, Termineitor244 approved these changes

2021-11-17 07:29 UTC, dissociativity commented
this is ready to merge, just to be clear

2021-11-23 18:10 UTC, Termineitor244 commented
> this is ready to merge, just to be clear

New conflicts have arisen... I will comment about this PR in discord again, it would be really good to have it merged before conflicts arise even more.

2021-11-23 18:50 UTC, Termineitor244 requested changes

2021-11-23 18:50 UTC, Termineitor244 commented on data/json/recipes/armor/suit.json
> +    "components": [ [ [ "rag", 26 ] ], [ "fastener_large", 1 ] ]
```suggestion
    "using": [ [ "sewing_standard", 30 ], [ "fabric_standard_nostretch", 26 ], [ "fastener_large", 1 ] ]
    "components": [ [ [ "rag", 26 ] ] ]
```

2021-11-23 18:56 UTC, Maleclypse commented on data/json/recipes/armor/suit.json
> +    "using": [ [ "sewing_standard", 30 ], [ "fabric_standard_nostretch", 26 ] ]
```suggestion
    "using": [ [ "sewing_standard", 30 ], [ "fabric_standard_nostretch", 26 ] ],
```

2021-11-23 18:57 UTC, Termineitor244 requested changes

2021-11-23 18:57 UTC, Termineitor244 commented on data/json/recipes/armor/suit.json
> +    "components": [ [ [ "rag", 26 ] ], [ "fastener_large", 1 ] ]
```suggestion
    "using": [ [ "sewing_standard", 35 ], [ "fabric_standard_nostretch", 26 ], [ "fastener_large", 1 ] ]
```

2021-11-23 18:57 UTC, Termineitor244 commented on data/json/recipes/armor/suit.json
> +    "components": [ [ [ "fastener_large", 2 ] ] ]
```suggestion
    "using": [ [ "sewing_standard", 45 ], [ "fabric_standard_nostretch", 52 ], [ "fastener_large", 2 ] ]
```

2021-11-23 19:17 UTC, Termineitor244 commented on data/json/recipes/armor/suit.json
> +    "components": [ [ [ "rag", 26 ] ], [ "fastener_large", 1 ] ]
@Maleclypse I think this change was lost when you applied your changes... The fastener should be in "using" and the rags are already included in fabric_standard_nostretch.

2021-11-23 19:34 UTC, Maleclypse commented on data/json/recipes/armor/suit.json
> +    "components": [ [ [ "rag", 26 ] ], [ "fastener_large", 1 ] ]
```suggestion
    "components": [ [ [ "fastener_large", 1 ] ] ]
```
```suggestion
    "components": [ [ [ "rag", 26 ] ], [ "fastener_large", 1 ] ]
```

2021-11-23 19:42 UTC, Termineitor244 requested changes

2021-11-23 19:42 UTC, Termineitor244 commented on data/json/recipes/armor/suit.json
> +    "components": [ [ [ "fastener_large", 1 ] ] ]
```suggestion
    "using": [ [ "sewing_standard", 35 ], [ "fabric_standard_nostretch", 26 ], [ "fastener_large", 1 ] ]
```

2021-11-23 19:57 UTC, Maleclypse commented
Probably, between work and family distractions I probably should have let someone else fix conflicts today.

2021-11-23 19:59 UTC, Termineitor244 commented
> Probably, between work and family distractions I probably should have let someone else fix conflicts today.

Doesn't matter, thanks for realizing the changes!

2021-11-25 06:28 UTC, merged