wearable smokes
CleverRaven/Cataclysm-DDA pull request #51635
Opened 2021-09-15 04:44 UTC by Entity-y

#### Summary
Features "makes lit cigar, cigs, and joints wearable"

#### Purpose of change
Tilesets have smoking animations but require you to wield the cigarette, sacrificing usability for immersion.

#### Describe the solution

- Made lit cigars, cigarettes, and joints wearable.

- Lit cigars and cigarettes have the `FANCY` flag to benefit stylish characters, along with `FRAGILE` flag.

#### Describe alternatives you've considered
Also making unlit cigs and butts wearable, this would have been exploitable with how drugs stack, the player could potentially have hundreds of them in their mouth with no consideration of volume.

#### Testing
Started a new world with changes and wore the different lit smokes.

2021-09-15 16:27 UTC, Cactoideae commented
Basic cigarettes shouldn't be FANCY, imo. They aren't associated with rich or high-class people.

Cigars are an example of what is fancy. Maybe add fancy cigarette holders for that stereotypical flapper look, but smoking a pack of cheap trash you found in a semitruck isn't classy.

2021-09-15 18:16 UTC, Entity-y commented
It doesn't need to be associated with rich or high class people to have the fancy flag. I've also thought about adding cigarette holders that provide the very fancy flag, maybe in a future PR.

2021-09-15 18:33 UTC, Cactoideae commented
Kevin has recently removed the FANCY flag from most items that used to have it, the new definition is "formal dress", not just things that make you "look cool".

#49078 for context.

2021-09-15 19:16 UTC, Entity-y commented
Things like the clown suit had the fancy flag, which didn't really make sense to begin with. That being said, I think smoking would fit under "formal dress". 

It's already circumstantial as it is with players needing to have the stylish trait and go through the effort of wearing the smoke just for a temporary fancy flag for as long as the cig burns for. It seems balanced enough to me.

Notice joints aren't fancy due to it's handrolled appearance. Personally, I see cigarettes as fancy, not cigars. But that's more up to how the player wants to roleplay.

2021-09-15 23:12 UTC, faefux commented
We know that people of low socioeconomic status (unemployed or or below poverty line) people, that tobacco products are consistently marketed towards lower income people than higher. and the least educated people are far more likely to be smokers than their opposites.  I'm not sure how we measure what is fancy but we can at least say that it is certainly not regular 'high society' or formal behavior.  
I'd take an educated guess also that smoking is far less socially acceptable and looked down on in 'polite' or upper class, formal society.

2021-09-15 23:30 UTC, Entity-y commented
This PR isn't meant to tear into the philosophy and psychology of smoking. It's just another feature that stylish players can take advantage of, or decide to never use.

2021-09-15 23:33 UTC, kevingranade requested changes
Not going in with FANCY tag.

2021-09-15 23:34 UTC, faefux commented
> philosophy and psychology

That is not what is happening here and I would appreciate it if you wouldn't make some inane straw-man to dismiss constructive commentary.
I am trying to show you that nicotine is very much a poor persons drug. It isn't 'fancy' in the same way most of our stylish items are, at least to my understanding, that is; formal, high-society.

2021-09-16 00:28 UTC, Entity-y commented
I don't agree with this change as it nearly defeats the entire goal of this PR, but since I've already made the sprites for wielded and worn smokes I'll remove the fancy flag.

2021-09-16 01:05 UTC, Entity-y commented
Since stylish characters won't benefit from smoking, maybe a new smoker trait could be added that gives additional moral boost when smoking, though I wouldn't know how to implement that.

2021-09-16 22:34 UTC, merged