Metal sword
CleverRaven/Cataclysm-DDA pull request #51865
Opened 2021-09-25 04:21 UTC by Malorn-Deslor

#### Summary
Content "Added new weapon to act as intermediate step between crude sword and real swords like the broadsword"

#### Purpose of change

While playing a sword based character, I noticed that after you make a crude sword, which can be made at fabrication 2 with only a hammer and very basic materials... you are done until you find 'The historic weaponsmith' and can make actual fully functional amazing swords. Or until you find one, of course. 

I felt that was a little unreasonable, since the crude sword is just scrap metal hammered over wood, and thus is incredibly crude and simple. It seemed reasonable for a character who now had high fabrication and fully blacksmithing abilities to be able to make something a bit better, even if they hadn't found any manuals on swordsmithing.

#### Describe the solution

I created a new item called 'metal sword' which is still very inferior to any of the historic weapons, even the broadsword. It is basically just the attempt of a skilled (fabrication 7) blacksmith to create a sword, just based on what they know swords are supposed to look like.

It does 5 more cutting damage then a crude sword (23 cutting), is better at blocking, and is made of steel not wood--otherwise it does not differ greatly. Broadswords are the weakest historic sword, and they do 27 cutting damage, so this felt like a nice mid-point. It blocks as well as a broadsword, but it's to-hit is lacking and equal to the crude sword. The metal sword requires high fabrication, and all the normal metalworking tools. It uses materials similar to a broadsword crafting requirements.

Of course, it is usable with medieval swordsmanship, that was the entire point of the item.

#### Describe alternatives you've considered

Well... I considered not having any weapon upgrade from the time you find a hammer until the time you have full metalworking and a very rare book... but I didn't like that option. There are many more powerful weapons that can be made without any book recipes at fabrication 7 with full metalworking tools. So it's nice to give a mid-range upgrade to the medieval swordsmanship path.

#### Testing

I loaded the game up, checked to see if the item was craftable, crafted it, wielded it, attacked a zombie with it. Worked as expected.

#### Additional context

2021-09-25 04:37 UTC, BrettDong commented on data/json/items/melee/swords_and_blades.json
> +    "description": "An imitation of a true sword forged by someone who knows what swords look like, at least. It has the general shape of a sword, and it is sharp, yet the quality is lacking and the
```suggestion
    "description": "An imitation of a true sword forged by someone who knows what swords look like, at least.  It has the general shape of a sword, and it is sharp, yet the quality is lacking and the balance isn't quite right.",
```

2021-09-25 04:43 UTC, Termineitor244 commented
Please add this sword to Ninjutsu and Niten Ichi-Ryu, both styles more than qualify to use this weapon.

I'm working on the weapon categories for Ninjutsu, so all of these would be easier in the future.

2021-09-25 05:01 UTC, Malorn-Deslor commented
I'll check for the crude sword in either of them, but if the crude sword works for this, I see no reason to not do that...

2021-09-25 05:11 UTC, Termineitor244 commented
Thanks! And it has more to do with if the style would work with the weapon in question or not, but anyways, those long lists of weapons in the martial arts json are things of the past! With weapon categories, the only thing that will matter is if the martial art can use the kind of weapon in question.

2021-09-25 05:35 UTC, Wokko1 commented
Please add looks_like for tilesets

2021-09-25 05:47 UTC, Malorn-Deslor commented
> "looks_like": "sword_crude"

That's a wonderful idea, thank you.

2021-09-25 14:04 UTC, Malorn-Deslor commented
Hmm... it looks like the checks are not running themselves properly, I'm going to try to close and reopen the PR.

2021-09-25 23:19 UTC, Malorn-Deslor commented
Does anyone know how to make it possible to dissemble an item without adding an uncrafting recipe? Many other weapons can be broken down into scrap despite not having an explicit recipe? I'd like the new sword to be something that can be broken down.

2021-09-26 13:44 UTC, anothersimulacrum commented
If the crafting recipe is reversible, it can be used as both a crafting and uncrafting recipe.

2021-09-27 05:46 UTC, Termineitor244 requested changes
Sorry, the weapon categories to Ninjutsu were merged first.

2021-09-27 05:46 UTC, Termineitor244 commented on data/json/items/melee/swords_and_blades.json
> +    "flags": [ "SHEATH_SWORD" ],
```suggestion
    "flags": [ "SHEATH_SWORD" ],
    "weapon_category": [ "MEDIUM_SWORDS" ],
```

2021-09-27 05:46 UTC, Termineitor244 commented on data/json/martialarts.json
> +      "sword_metal",
```suggestion
```

2021-09-27 06:27 UTC, Malorn-Deslor commented
> Sorry, the weapon categories for Ninjutsu were merged first.

No worries!

2021-09-27 18:31 UTC, kevingranade commented
No issue with the content of the PR, but it looks like Github Actions has been disabled for your repository, see https://github.com/Malorn-Deslor/Cataclysm-DDA/actions

It's possible you fiddled with switching your repository to private or something at some point, which will enable billiong, and if you don't pay it'll disable features of your repository.  That's PURE speculation though.
Options you can pursue:
1. Contact Github support by following the link on the above page.
2. Just make a new repository and who knows, an account? I believe a similar issue happened here: https://github.com/CleverRaven/Cataclysm-DDA/pull/51389

2021-09-27 23:55 UTC, Malorn-Deslor commented
> 
> 
> No issue with the content of the PR, but it looks like Github Actions has been disabled for your repository, see https://github.com/Malorn-Deslor/Cataclysm-DDA/actions
> 
> It's possible you fiddled with switching your repository to private or something at some point, which will enable billing, and if you don't pay it'll disable features of your repository. That's PURE speculation though.
> Options you can pursue:
> 
>     1. Contact Github support by following the link on the above page.
> 
>     2. Just make a new repository and who knows, an account? I believe a similar issue happened here: [Mythos Mod - Start of conversion, remove zombies from zombie game! #51389](https://github.com/CleverRaven/Cataclysm-DDA/pull/51389)

I didn't much with making it private or anything like that. The good news is that it is telling that actions are disabled and I should contact GitHub support. So I did that. Thank you for the warning and the information.

Is that the reason that the automatic checks for this PR are 'Waiting for status to be reported'?

2021-09-28 16:22 UTC, kevingranade commented
Yes, for whatever reason it seems that if there's an issue with your account it impacts pull requests you open on other repositories as well, and it's causing our checks to not run.

2021-09-29 11:54 UTC, Malorn-Deslor commented
I am attempting to talk to github support at this point. It's not really working out very well, since they just linked the entire terms and conditions of use, and said I violated it in some unspecified fashion. If anyone wants to mirror the pull request, feel free.

I'm sorry this is causing so many problems. It's strange, this account exists only to contribute to this repo, so I'm not really sure what's going on.

2021-09-29 12:35 UTC, BrettDong commented
Mirrored in #51970.

2021-09-30 05:06 UTC, BrettDong commented
Merged in #51970.

2021-09-30 05:06 UTC, closed without merging