Maid clothes improvements 2
CleverRaven/Cataclysm-DDA pull request #53018
Opened 2021-11-25 07:10 UTC by Termineitor244

#### Summary
Content "Adjust some values of the maid clothes and adds a new maid dress"

#### Purpose of change
#52971 had some problems so I started this PR to try again:
I was passing over the items and they seemed a little weird in some values, so I decided to adjust them while I was there. When I was modifying the maid clothes and searching for models of the clothing, I realized that the current maid dress is a "functional" maid dress, meaning, a normal dress that would use someone cleaning... But most maid dresses over there are just for cosplay, so I decided to introduce a new one. 

#### Describe the solution
Adjust the values of the maid dress, hat and long white gloves, as well as creating a new, shorter maid dress.

#### Describe alternatives you've considered
None.

#### Testing
Started a new game, searched for the new item, it spawns correctly and the other items are still there too.

#### Additional context
Who decided to implement the maid dress in the game as a blue dress?

[This](https://www.aliexpress.com/item/New-Women-Vintage-French-Maid-Long-Dress-Costume-Cosplay-Stage-Fancy-Dress-Plus-size-House-Keeper/32869838224.html) is how its supposed to be the original maid dress, the new one would be... Maybe something like [this](https://www.pinterest.com/pin/393502086165519236/), there are a lot of similar models on the internet of these types of maid clothes.

2021-11-25 19:57 UTC, Termineitor244 commented
> monster_attack_test.cpp:230: FAILED

I don't think its related to this PR.

2021-11-27 15:20 UTC, bombasticSlacks requested changes
something like this

2021-11-27 15:20 UTC, bombasticSlacks commented on data/json/items/armor/gloves.json
> +        "specifically_covers": [ "arm_upper_l", "arm_upper_r", "arm_elbow_l", "arm_elbow_r", "arm_lower_l", "arm_lower_r" ],
```suggestion
        "specifically_covers": [ "arm_elbow_l", "arm_elbow_r", "arm_lower_l", "arm_lower_r" ],
```

2021-11-27 15:20 UTC, bombasticSlacks commented on data/json/items/armor/gloves.json
> +        "coverage": 50,
```suggestion
        "coverage": 100,
```

2021-11-27 15:20 UTC, bombasticSlacks commented on data/json/items/armor/gloves.json
> +      }
```suggestion
      },
      {
        "covers": [ "arm_l", "arm_r" ],
        "specifically_covers": [ "arm_upper_l", "arm_upper_r" ],
        "coverage": 50,
      }
```

2021-11-27 15:20 UTC, bombasticSlacks commented on data/json/items/armor/torso_clothes.json
> +        "specifically_covers": [ "leg_hip_l", "leg_hip_r", "leg_upper_l", "leg_upper_r" ],
```suggestion
        "specifically_covers": [ "leg_hip_l", "leg_hip_r" ],
```

2021-11-27 15:20 UTC, bombasticSlacks commented on data/json/items/armor/torso_clothes.json
> +        "coverage": 40,
```suggestion
        "coverage": 100,
```

2021-11-27 15:20 UTC, bombasticSlacks commented on data/json/items/armor/torso_clothes.json
> +      },
```suggestion
      },
      {
        "covers": [ "leg_l", "leg_r" ],
        "specifically_covers": [  "leg_upper_l", "leg_upper_r" ],
        "coverage": 50,
      },
```

2021-11-27 22:12 UTC, closed without merging