Defudding of the fudd round
CleverRaven/Cataclysm-DDA pull request #53233
Opened 2021-12-05 19:44 UTC by Paprika-H

#### Summary
Bugfixes "Description fix"

#### Purpose of change

Stopping power is a stupid phrase and I hate it, so I've updated it to be less fuddy.

#### Describe the solution

Changes the description of the round.

#### Describe alternatives you've considered

Remove any and all ammo, returning to the time of true stopping power that is of trebuchets. 

#### Testing

Do I have to test it if it's a description change? Serious question. 

#### Additional context

2021-12-05 19:55 UTC, Scorch-Mechanic commented
> "It has good power but above average recoil compared to ~~it's~~ its now more widespread counterpart, 9mm."

"its" is the possessive, not "it's"

2021-12-05 20:00 UTC, Maleclypse approved these changes

2021-12-05 20:26 UTC, Alex-Folts commented
> Stopping power is a stupid phrase

Yet it is [valid term](https://en.wikipedia.org/wiki/Stopping_power), blame english for didn't coin better sounding name for a thing. Not the end of the world if you change description though.

2021-12-05 20:48 UTC, Paprika-H commented
> > "It has good power but above average recoil compared to ~it's~ its now more widespread counterpart, 9mm."
> 
> "its" is the possessive, not "it's"

Ah, thanks for catching that! "Its" now fixed

2021-12-05 23:09 UTC, kevingranade requested changes
Replacing "stopping power" with "power" is no good, the first is a term of art regardless of misuse that occurs, but the later is not a typical use at all.
If you want to work around this you need to rewrite the description more thoroughly.

2021-12-06 02:13 UTC, Paprika-H commented
> Replacing "stopping power" with "power" is no good, the first is a term of art regardless of misuse that occurs, but the later is not a typical use at all. If you want to work around this you need to rewrite the description more thoroughly.

I really need to think these things more thoroughly, my apologies. I've adjusted it now

2021-12-06 10:45 UTC, PatrikLundell commented
If you've made a change to a description, I'd say you'd need to verify that the changed description actually appears in the game (you could potentially have made the mistake of editing a copy of the file, or the object you edited may be a duplicate the loading of the game ignores [unless duplicate definitions are now flagged], etc.).
Whether you'd need to verify every changed instance when you've made a bunch of them is a judgement call, but if it's a matter of debug spawning items and looking at their descriptions it should be easy to do, and there would be little reason not to verify it in that case (but posting images of each and every item before and after is overkill, while one example item provides an illustration of the change within its context).

2021-12-13 02:14 UTC, kevingranade commented on data/json/items/ammo/45.json
> +    "description": ".45 ACP ammunition with 230gr FMJ bullets.  Due to the projectile weight causing significant tissue damage, and previous adoption by the US military, the .45 ACP round has been co
```suggestion
    "description": ".45 ACP ammunition with 230gr FMJ bullets.  Due to a reputation for effectiveness, the .45 ACP round has been common for over a century.",
```

2021-12-17 06:08 UTC, merged