Unarmed weapons are wearable and added wrist sub-limbs
CleverRaven/Cataclysm-DDA pull request #54313
Opened 2022-01-12 00:43 UTC by Hymore246

#### Summary
Balance "Unarmed weapons are wearable and added wrist sub-limbs"

#### Purpose of change

Unarmed weapons are wearable. Added Wrist sub-limbs

#### Describe the solution

This PR is focused on several changes regarding the character's "hand" limb. 

**Unarmed Weapons are now wearable.** Following the example of #41209 all other non-CBM unarmed weapons have been converted to `ARMOR` items that are worn on the hands. These items no longer have the `UNARMED_WEAPON` flag meaning they must be worn to add their damage to unarmed attacks. The follow items have been changed:

Name | Encumbrance | Coverage 
--- | --- | --- 
pair of brass knuckles | 5 | 10
pair of nail knuckles | 7 | 20
pair of scrap knuckles | 7 | 20
pair of steel knuckles | 5 | 10

In addition, these items are no longer classified as style weapons for Aikido and Judo. Wearing the above items and attacking without a weapon will still make them contribute unarmed damage as normal. Due to the nature of tiger claws (bagh nakha) and bionic claws, they are still classified as style weapons for Aikido and Judo and retain the `UNARMED_WEAPON` flag.

**Added wrist sub-limbs.** `arm_wrist_r` and `arm_wrist_l` have been added to the body parts list as a sub-limbs of `hand_r` and `hand_l` respectively. Items that cover the wrist have been updated to state they specifically cover the wrist part of the hand. These items are all watches:

* diver's watch
* gold watch
* silver watch
* fancy watch
* platinum watch
* wrist watch

2022-01-12 00:49 UTC, bombasticSlacks commented
if something doesn't specify sublocations it is assumed to cover all sublocations on that body part.

So if the intent is for there to be two distinct zones "fingers" where you have brass knuckles or whatever and "wrist" where you have a watch. you have to make a fingers sublocation too.

2022-01-12 00:52 UTC, bombasticSlacks commented
also the overall limb needs to have a list of sub parts too. See line 307 for an example
![image](https://user-images.githubusercontent.com/4514073/149044457-b08ce4e6-36c4-4702-b89b-d88eac8f32d6.png)

2022-01-12 01:05 UTC, Shodan14 commented
There's also the fitness band and bracelets.

2022-01-12 01:19 UTC, NetSysFire commented
Relevant: #53822

2022-02-10 02:05 UTC, catdach commented
It seems that in the comments of #41209 it was decided not to have the "knuckles" items be wearable as they actually [take up space in the palm](https://upload.wikimedia.org/wikipedia/commons/1/1d/Brass_knuckles.jpg) and therefore prevent other things from being held in the hands. They don't just wrap around the fingers like the cestus.

2022-02-10 13:47 UTC, bombasticSlacks requested changes
these shouldn't have secondary. Basically no sublimbs should

2022-02-12 03:44 UTC, catdach commented
> > It seems that in the comments of #41209 it was decided not to have the "knuckles" items be wearable as they actually [take up space in the palm](https://upload.wikimedia.org/wikipedia/commons/1/1d/Brass_knuckles.jpg) and therefore prevent other things from being held in the hands. They don't just wrap around the fingers like the cestus.
> 
> I see where that is coming from but there is no mistake that Brass Knuckles and the like need to be placed on the fingers to be used. You couldn't just hold a pair of Spiked Brass Knuckles in your hand and attack with them the same way as if they were worn. The best idea I can think of as a compromise is to make these weapon have a large amount of hand encumbrance to discourage holding another item.

But increasing hand encumbrance would also make unarmed attacks worse too, right?

2022-02-14 12:57 UTC, bombasticSlacks requested changes
Alright so this makes the wrist 10% of the hand, fingers 50%, and adds a palm to round it out covering 40%.

When defining coverage for a place with sublocations you are telling the game *how much of the sublocation is covered* not *how much of the overall location*. So for example when a watch is 10 coverage, on the wrist the game thinks its 10% of the wrist (which is 10% of the hand). So I've adjusted the coverage values to maintain the numbers you already had but in that system where it converts.

2022-02-14 12:57 UTC, bombasticSlacks commented on data/json/body_parts.json
> +    "max_coverage": 5,
```suggestion
    "max_coverage": 50,
```

2022-02-14 12:57 UTC, bombasticSlacks commented on data/json/body_parts.json
> +    "max_coverage": 5,
```suggestion
    "max_coverage": 10,
```

2022-02-14 12:57 UTC, bombasticSlacks commented on data/json/body_parts.json
>    }
```suggestion
  },
    {
    "id": "hand_palm_l",
    "type": "sub_body_part",
    "max_coverage": 40,
    "parent": "hand_l",
    "side": 1,
    "opposite": "hand_palm_l",
    "name_multiple": "palms",
    "name": "left palm"
  }
```

2022-02-14 12:57 UTC, bombasticSlacks commented on data/json/items/armor/jewelry.json
> +    "armor": [ { "coverage": 5, "covers": [ "hand_l", "hand_r" ], "specifically_covers": [ "hand_wrist_l", "hand_wrist_r" ] } ]
```suggestion
    "armor": [ { "coverage": 50, "covers": [ "hand_l", "hand_r" ], "specifically_covers": [ "hand_wrist_l", "hand_wrist_r" ] } ]
```

2022-02-14 12:57 UTC, bombasticSlacks commented on data/json/items/armor/jewelry.json
> +    "armor": [ { "coverage": 5, "covers": [ "hand_l", "hand_r" ], "specifically_covers": [ "hand_wrist_l", "hand_wrist_r" ] } ]
```suggestion
    "armor": [ { "coverage": 100, "covers": [ "hand_l", "hand_r" ], "specifically_covers": [ "hand_wrist_l", "hand_wrist_r" ] } ]
```

2022-02-14 12:57 UTC, bombasticSlacks commented on data/json/items/armor/jewelry.json
> +    "armor": [ { "coverage": 10, "covers": [ "hand_l", "hand_r" ], "specifically_covers": [ "hand_wrist_l", "hand_wrist_r" ] } ]
```suggestion
    "armor": [ { "coverage": 100, "covers": [ "hand_l", "hand_r" ], "specifically_covers": [ "hand_wrist_l", "hand_wrist_r" ] } ]
```

2022-02-14 12:57 UTC, bombasticSlacks commented on data/json/items/melee/unarmed_weapons.json
> +        "coverage": 10,
```suggestion
        "coverage": 20,
```

2022-02-14 12:57 UTC, bombasticSlacks commented on data/json/items/melee/unarmed_weapons.json
> +        "coverage": 40,
```suggestion
        "coverage": 80,
```

2022-02-14 12:57 UTC, bombasticSlacks commented on data/json/items/tool_armor.json
> +    "armor": [ { "coverage": 5, "covers": [ "hand_l", "hand_r" ], "specifically_covers": [ "hand_wrist_l", "hand_wrist_r" ] } ]
```suggestion
    "armor": [ { "coverage": 50, "covers": [ "hand_l", "hand_r" ], "specifically_covers": [ "hand_wrist_l", "hand_wrist_r" ] } ]
```

2022-02-15 03:34 UTC, bombasticSlacks requested changes

2022-02-15 03:34 UTC, bombasticSlacks commented on data/json/body_parts.json
> +    "parent": "hand_r",
```suggestion
    "parent": "hand_l",
```

2022-02-15 03:34 UTC, bombasticSlacks commented on data/json/body_parts.json
> +    "parent": "hand_r",
```suggestion
    "parent": "hand_l",
```

2022-02-17 00:45 UTC, merged