Suspenders! (And subsequent recipes.)
CleverRaven/Cataclysm-DDA pull request #55032
Opened 2022-02-02 20:59 UTC by slimeboy460

#### Summary
Category "Content"

#### Purpose of change

This is a content update that adds three new times of suspenders. Cotton, Leather, and Holster.

#### Describe the solution

This was simply developed to add alternate forms of belts. For players who want their character to have more of a western or victorian era vibe to them.

#### Describe alternatives you've considered

N/A

#### Testing

I ran it through the baseline tests, using JSONlint and the baseline tests. I think it should all be clear but if there are any more issues I'll fix them if I notice them!

#### Additional context

The recipes might be due to some tuning, more for the cotton suspenders than anything. The leather Suspenders and Holster Suspenders should be good, however!

2022-02-05 17:32 UTC, BrettDong commented on data/json/recipes/armor/torso.json
> +    "difficulty": 1
```suggestion
    "difficulty": 1,
```

2022-02-05 17:32 UTC, BrettDong commented on data/json/recipes/armor/torso.json
> +    "difficulty": 1
```suggestion
    "difficulty": 1,
```

2022-02-05 17:32 UTC, BrettDong commented on data/json/recipes/armor/storage.json
> +    "difficulty": 3
```suggestion
    "difficulty": 3,
```

2022-02-07 15:32 UTC, BrettDong commented on data/json/recipes/armor/torso.json
> +  },
```suggestion
  }
```

2022-02-19 17:52 UTC, Maleclypse commented
This needs a rebase and linting. Do you need any help with that?

2022-02-20 19:27 UTC, slimeboy460 commented
> This needs a rebase and linting. Do you need any help with that?

I can do the linting but not the rebase, I kinda got caught up with some things irl but I'll try and do the linting by tomorrow

2022-02-21 16:12 UTC, slimeboy460 commented
Noticed the problem, i accidentally stuck commas where the EOF should've been, which I think was causing the conflicts

2022-03-14 01:58 UTC, TheShadowFerret requested changes
Plurals + no caps

2022-03-14 01:58 UTC, TheShadowFerret commented on data/json/items/armor/belts.json
> +    "name": { "str": "Suspenders" },
```suggestion
    "name": { "str": "suspenders", "str_pl": "pairs of suspenders" },
```

2022-03-14 01:58 UTC, TheShadowFerret commented on data/json/items/armor/belts.json
> +    "name": { "str": "Leather Suspenders" },
```suggestion
    "name": { "str": "leather suspenders", "str_pl": "pairs of leather suspenders" },
```

2022-03-14 01:58 UTC, TheShadowFerret commented on data/json/items/armor/belts.json
> +    "name": { "str": "Holster Suspenders" },
```suggestion
    "name": { "str": "holster suspenders", "str_pl": "pairs of holster suspenders" },
```

2022-03-26 15:42 UTC, slimeboy460 commented
Thank you for that, sorry about not replying sooner, College kicked my ass with a ten page paper

2022-04-19 01:51 UTC, dseguin commented on data/json/items/armor/belts.json
> +    "flags": [ "WAIST", "WATER_FRIENDLY" ],
```suggestion
    "flags": [ "WAIST", "WATER_FRIENDLY" ],
```

2022-04-21 08:30 UTC, Termineitor244 requested changes
I adjusted your items to use the new "torso_waist" sublocation and your holster suspender to use corrected values for its pocket (since you are building it with a normal holster) and added some encumbrance.

You need to add these items to some spawn lists if you want them to be found in game and not only crafted.

2022-04-21 08:30 UTC, Termineitor244 commented on data/json/items/armor/belts.json
> +    "armor": [ { "coverage": 5, "covers": [ "torso" ] } ]
```suggestion    
    "flags": [ "BELTED", "WATER_FRIENDLY" ],
    "armor": [ { "coverage": 50, "covers": [ "torso" ], "specifically_covers": [ "torso_waist" ] } ]
```

2022-04-21 08:30 UTC, Termineitor244 commented on data/json/items/armor/belts.json
> +    "flags": [ "WAIST", "WATER_FRIENDLY", "NO_QUICKDRAW" ],
```suggestion
    "flags": [ "BELTED", "WATER_FRIENDLY", "NO_QUICKDRAW" ],
```

2022-04-21 08:30 UTC, Termineitor244 commented on data/json/items/armor/belts.json
> +    ]
```suggestion
    "pocket_data": [
      {
        "magazine_well": "350 ml",
        "pocket_type": "CONTAINER",
        "holster": true,
        "min_item_volume": "250 ml",
        "max_contains_volume": "1000 ml",
        "max_contains_weight": "2 kg",
        "max_item_length": "30 cm",
        "moves": 50
      }
    ],
    "use_action": { "type": "holster" },
    "armor": [ { "encumbrance": [ 3, 4 ], "coverage": 75, "covers": [ "torso" ], "specifically_covers": [ "torso_waist" ] } ]
  }
```

2022-04-21 08:30 UTC, Termineitor244 commented on data/json/items/armor/belts.json
> +    "description": "A pair of leather suspenders with a holster placed near the stomach. It was designed with subtlety in mind so it can hold no more than a small revolver.",
```suggestion
    "description": "A pair of leather suspenders with a holster placed near the stomach.",
```

2022-04-21 08:33 UTC, Termineitor244 commented on data/json/items/armor/belts.json
> +    "flags": [ "WAIST", "WATER_FRIENDLY", "NO_QUICKDRAW" ],
I'm not sure if you really want "NO_QUICKDRAW" for this item too.

2022-04-21 08:34 UTC, Termineitor244 commented on data/json/items/armor/belts.json
> +    ]
If you want another value for its pocket and encumbrance (And to retain its original description) then you need to build the item with another, smaller holster.

2022-04-22 01:21 UTC, dseguin commented on data/json/items/armor/belts.json
> +  }
```suggestion
```

2022-04-22 02:46 UTC, dseguin commented on data/json/items/armor/belts.json
> +    "use_action": { "type": "holster" },
```suggestion
```

2022-04-22 02:46 UTC, dseguin commented on data/json/items/armor/belts.json
> +    "copy_from": "suspenders_leather",
```suggestion
    "copy-from": "suspenders_leather",
```

2022-04-22 02:46 UTC, dseguin commented on data/json/items/armor/belts.json
> +    "copy_from": "suspenders_cloth"
```suggestion
    "copy-from": "suspenders_cloth"
```

2022-04-22 02:46 UTC, dseguin commented on data/json/recipes/armor/torso.json
> +    "type": "recipe",
```suggestion
    "type": "recipe",
    "activity_level": "LIGHT_EXERCISE",
    "category": "CC_ARMOR",
    "subcategory": "CSC_ARMOR_TORSO",
```

2022-04-22 02:46 UTC, dseguin commented on data/json/recipes/armor/torso.json
> +    "result": "suspenders_cotton",
```suggestion
    "type": "recipe",
    "activity_level": "LIGHT_EXERCISE",
    "category": "CC_ARMOR",
    "subcategory": "CSC_ARMOR_TORSO",
    "result": "suspenders_cloth",
```

2022-04-22 02:46 UTC, dseguin commented on data/json/recipes/armor/torso.json
> +    "using": [ [ "rag", 5 ], [ "clasps", 3 ] ],
```suggestion
    "using": [ [ "tailoring_cotton", 1 ], [ "clasps", 3 ], [ "fabric_standard_nostretch", 5 ] ],
```

Not super sure about this one, but "rag" is not a valid requirement. It also needs some kind of tool requirement ("tailoring_cotton").

2022-04-22 02:46 UTC, dseguin commented on data/json/recipes/armor/storage.json
> +    "using": [ [ "tailoring_leather_small", 4 ], [ "clasps", 3 ], [ "holster", 1 ] ],
```suggestion
    "using": [ [ "tailoring_leather_small", 4 ], [ "clasps", 3 ] ],
    "components": [ [ [ "holster", 1 ] ] ],
```

2022-04-22 20:17 UTC, merged