[Magiclysm] Adding new magic plants (halp)
CleverRaven/Cataclysm-DDA pull request #55164
Opened 2022-02-06 19:19 UTC by GuardianDll

#### Summary

Mods "Adding new magic plants"

#### Purpose of change
Reopened #37103 with some changes, but its still draft, due the ton of errors i cant understand

- [ ] fix errors

- [ ] add them to maps

#### Errors i cant fix 
```
Json error: data/mods/Magiclysm/items/herbs_and_flowers.json:42:50: str_pl not supported here

    "type": "furniture",
    "id": "olieribos",
    "name": { "str": "olieribos sheaf", "str_pl":
                                                 ^
                                                  "olieribos sheaves" },
    "description": "Dark colored leaves and bitter roots, firmly tied together in a small sheaf.",
    "color": "light_grey",
```
does it mean i need to delete the `str_pl`? there would be `olieribos sheafs`, which is wrong, isnt it?

```
Json error: data/mods/Magiclysm/items/herbs_and_flowers.json:42:73: missing mandatory member "move_cost_mod"

    "type": "furniture",
    "id": "olieribos",
    "name": { "str": "olieribos sheaf", "str_pl": "olieribos sheaves" },
                                                                        ^
    "description": "Dark colored leaves and bitter roots, firmly tied together in a small sheaf.",
    "color": "light_grey",
    "looks_like": "wheat"
```
as you can see in file, no one of previous herb use the `move_cost_mod`, so i dont understand why the game troubled with it
would be glad if someone explain me whats wrong here

2022-02-06 19:21 UTC, GuardianDll commented
btw am i need to add this herb names to spell checker ignore list?

2022-02-06 19:24 UTC, anothersimulacrum commented
I don't believe furniture and terrain can appear as plurals in-game, which is why you are seeing those problems.

2022-02-06 19:27 UTC, GuardianDll commented
DAAAAAMN
its a furniture, when it must be `COMESTIBLE`
🤦

2022-02-06 19:45 UTC, GuardianDll commented
Accidentally turn off the draft mode, sorry

2022-02-06 20:47 UTC, anothersimulacrum commented on data/mods/Magiclysm/items/herbs_and_flowers.json
> +    "name": { "str": "kämpuch", "str_pl": "kämpuch" },
Plural is probably +es

2022-02-06 20:47 UTC, anothersimulacrum commented on data/mods/Magiclysm/items/herbs_and_flowers.json
> +    "name": { "str": "philosopher's flower", "str_pl": "philosopher's flowers" },
No need for explicit plural here

2022-02-06 20:47 UTC, anothersimulacrum commented on data/mods/Magiclysm/items/herbs_and_flowers.json
> +    "name": { "str": "wood barnacle", "str_pl": "wood barnacles" },
No need for explicit plural

2022-02-06 20:48 UTC, anothersimulacrum commented on data/mods/Magiclysm/items/herbs_and_flowers.json
> +    "name": { "str": "dragon nails", "str_pl": "dragonails" },
Looks like a typo

2022-02-06 20:48 UTC, anothersimulacrum commented on data/mods/Magiclysm/items/herbs_and_flowers.json
> +    "name": { "str": "moly tuber", "str_pl": "moly tubers" },
No need for explicit plural

2022-02-06 20:48 UTC, anothersimulacrum commented on data/mods/Magiclysm/items/herbs_and_flowers.json
> +    "name": { "str": "moly tuber", "str_pl": "moly tubers" },
This should probably have a different name

2022-02-06 20:49 UTC, anothersimulacrum commented on data/mods/Magiclysm/items/herbs_and_flowers.json
> +    "name": { "str": "funnelcap chunk", "str_pl": "funnelcap chunks" },
No need for explicit plural

2022-02-06 20:49 UTC, anothersimulacrum commented on data/mods/Magiclysm/items/herbs_and_flowers.json
> +    "name": { "str": "sojourner's flower", "str_pl": "sojourner's flowers" },
No need for explicit plural

2022-02-06 20:49 UTC, anothersimulacrum commented on data/mods/Magiclysm/items/herbs_and_flowers.json
> +    "name": { "str": "whiskflower", "str_pl": "whiskflowers" },
No need for explicit plural

2022-04-10 22:18 UTC, esotericist requested changes
this is a good start, and they sound interesting, but as discussed on discord i think before we can move forward we're going to want to fill out those checkboxes from @John-Candlebury 's original pr:

* there need to be basic effects for consuming them (or at the very least solid concepts for what they *might* do, if their basic consumption wouldn't be useful/reasonable compared to their future alchemy implementation uses)
* they need to properly be distributed in worldgen so that they can be found in places that make sense to look for them.

also note that one option if you can only think of a subset of things to do with them is to make a new PR with a subset of the changes, that just implement a smaller number of plants with effects and spawn locations. if you need help implementing those, i'm sure someone in #dev-help can give you some pointers once you have some specific questions.

2022-04-19 05:45 UTC, GuardianDll commented
Left it here so i wont miss it in the future
![IMG_20220419_074422](https://user-images.githubusercontent.com/67688115/163928148-6aef2dac-6bfc-429c-9c50-6cbbafe6648e.jpg)

2022-08-02 16:22 UTC, Night-Pryanik commented on data/mods/Magiclysm/furniture_and_terrain/furniture_plants.json
> +    "name": "Moonflower Bush",
I suppose this flower should be named somehow different?

2022-08-02 16:23 UTC, Night-Pryanik commented on data/mods/Magiclysm/furniture_and_terrain/furniture_plants.json
> +    "name": "t_underbrush",
Name, not id.

2022-08-02 16:23 UTC, Night-Pryanik commented on data/mods/Magiclysm/furniture_and_terrain/furniture_plants.json
> +    "name": "glowing mushrooms",
Plural name needed.

2022-08-02 16:26 UTC, Night-Pryanik commented on data/mods/Magiclysm/furniture_and_terrain/furniture_plants.json
> +    "description": "A small plant with curled leaves and  pink whisk-shaped flowers.  It has a very strong alcoholic smell.",
```suggestion
    "description": "A small plant with curled leaves and pink whisk-shaped flowers.  It has a very strong alcoholic smell.",
```

2022-08-02 16:28 UTC, Night-Pryanik commented on data/mods/Magiclysm/items/herbs_and_flowers.json
> +    "description": "Slim stripes cut from a bioluminescent mushroom, still surrounded by a fain glowing aura.",
```suggestion
    "description": "Slim stripes cut from a bioluminescent mushroom, still surrounded by a faint glowing aura.",
```

2022-08-02 16:29 UTC, Night-Pryanik commented on data/mods/Magiclysm/items/herbs_and_flowers.json
> +    "description": "Pure white moss capsules, shaped like a goat's horn.  The fine spores contained within are a powerfull magical reagent, and can be consumed to recover small amounts of health.",
```suggestion
    "description": "Pure white moss capsules, shaped like a goat's horn.  The fine spores contained within are a powerful magical reagent, and can be consumed to recover small amounts of health.",
```

2022-08-13 22:39 UTC, merged