Lightening up the hard chest/arm/leg guards a bit.
CleverRaven/Cataclysm-DDA pull request #55378
Opened 2022-02-14 17:10 UTC by Aerin-of-the-Toast

#### Summary
None

#### Purpose of change

Part 4 of my attempts at sanity-checking early game armors.

While the "hard X guard(s)" items are a bit generic, I've been looking at examples of items that fall under that umbrella of armor. For being made of neoprene (a very light and breathable material) and plastic padding that had a lot of gaps in the coverage, they were awfully warm and a bit too encumbering for something that's light and doesn't really block joint movement that much. The hard chest guard was the worst offender at a massive 20 encumbrance, more than some variants of plate armor, despite (as mentioned) being rather light and not blocking movement too much. This is especially egregious in comparison to an empty US ballistic vest, which has more coverage (which, it probably shouldn't but that's a separate PR) and better defense stats at a much lower 6 encumbrance.

#### Describe the solution

Chopped the encumbrance values of the arms, legs, and chest guards down to 4, since they all seemed similarly easy to move in, as many are made for contact sports or riding on your day-to-day. Also, chopped warmth on the arm and leg guards to 5 due to neoprene being a very breathable material and the plastic padding having large gaps that wouldn't impede air flow much, and the chest guard to 10 warmth due to the large plastic plate not having as many gaps for air flow and being better covering. They often are made to be wearable in summer after all, and a plastic chest guard won't keep you too warm in fall on its own. I've also evened out the thickness so it's the same 4 across all the pads.

#### Describe alternatives you've considered

I debated between making a separate chest armor for motorcycle armor vests specifically, but the difference between a hard plastic plate for contact sports and a hard plastic plate for riding motorcycles didn't seem different enough to make a noticeable gameplay impact, and the coverages between the various vests is roughly the same anyway.

#### Testing

Game didn't explode when loading.

#### Additional context

No wonder the summer meta in the game seems to be "go naked" or "wear chainmail," it seems a lot of armors, even ones designed to be worn in summer and made with breathable materials had warmth values on par with thick jackets.

Also, while this is a MASSIVE buff to the hard chest guard, it's not going to shake up the meta much since the empty US ballistic vest is *still* better unless you really need that 2 encumbrance or to keep a bit cooler in summer. It's just the hard chest guard is no longer as restricting as actual plate armor now.

Also also, 10th PR! 🥳

2022-02-14 19:38 UTC, bombasticSlacks commented
Since you mentioned it this is the SPCS which is what the US ballistic vest is based on.
![image](https://user-images.githubusercontent.com/4514073/153933926-3c6d17c5-bef8-4f5d-a69c-12ea6a508a81.png)


I guess the under arms are not protected which I thought was the case. Also worth remembering that the real protection on the US Ballistic Vest comes from the Kevlar insert which already only covers 95% of the torso. So a change might be worth it but not too much.

Also the Heavy is based on the IOTV which does basically fully cover the body.

2022-02-16 17:30 UTC, bombasticSlacks requested changes

2022-02-17 06:01 UTC, kevingranade commented
The encumbrance change makes sense, but neoprene is the opposite of breathable, it's a foam that allows zero passage of air or moisture.  The only way it's partially breathable is if it's perforated, and even then it's not *very* breathable.

2022-02-17 08:28 UTC, Aerin-of-the-Toast commented
> The encumbrance change makes sense, but neoprene is the opposite of breathable, it's a foam that allows zero passage of air or moisture. The only way it's partially breathable is if it's perforated, and even then it's not _very_ breathable.

Oh, I see my mistake. I've spent so long staring at motorcycle armors I was confusing the neoprene backing for being similar material to the mesh jacket on some motorcycle armors. Which looking at it more closely seems to usually be a stretch fabric like lycra. Also, a mesh. I returned the warmth of the hard guards to 20 to account for the neoprene then.

2022-02-19 21:55 UTC, merged