Add horse breeding
CleverRaven/Cataclysm-DDA pull request #55907
Opened 2022-03-06 20:53 UTC by AtomicFox556

#### Summary
Content "Add horse breeding"

#### Purpose of change
Let horses reproduce just like other tamed animals, in order to make more horses.

#### Describe the solution
Add a foal monster that grows into an adult horse over time, and reproduction data for horses.

#### Describe alternatives you've considered
None.

#### Testing
Load the game with these changes, made sure that no errors happen.

#### Additional context
None.

2022-03-06 23:37 UTC, Maleclypse approved these changes

2022-03-29 19:40 UTC, LyleSY approved these changes

2022-03-29 19:46 UTC, LyleSY requested changes
Mostly great, I'd just suggest making it so foals don't breed until maturity

2022-03-29 19:46 UTC, LyleSY commented on data/json/monsters/mammal.json
> +    "flags": [ "SEES", "HEARS", "SMELLS", "ANIMAL", "PET_WONT_FOLLOW", "PATH_AVOID_DANGER_1", "WARM" ]
```suggestion
    "flags": [ "SEES", "HEARS", "SMELLS", "ANIMAL", "PET_WONT_FOLLOW", "PATH_AVOID_DANGER_1", "WARM", "NO_BREED" ]
```

2022-03-30 16:24 UTC, AtomicFox556 commented
Done.

2022-03-30 16:49 UTC, LyleSY approved these changes

2022-04-05 21:15 UTC, merged