Weakpoint proficiencies: (some) zombies and insects
CleverRaven/Cataclysm-DDA pull request #56487
Opened 2022-03-31 02:51 UTC by dseguin

#### Summary
None

#### Purpose of change
Even though Joshua-Chin added the infrastructure in #52081, no weakpoint proficiencies have ever been added to the game.

#### Describe the solution
Add proficiencies for the currently defined weakpoints (which as of now only includes some zombies and some insects).

Weakpoint proficiencies are defined per monster using the `"families"` field. These proficiencies can be practiced by dissecting monsters that define the "families" field:

![dissect_msg](https://user-images.githubusercontent.com/12537966/160963418-36db340a-5376-48e4-b9a1-17199792aa57.png)
![at_menu](https://user-images.githubusercontent.com/12537966/160963426-19e44f53-ff27-44ef-a4cc-dc80458f2316.png)

The bonus/penalty values are based on `melee_skill`, which is used along with proficiencies in `weakpoint_attack::compute_wp_skill` to determine weakpoint weapon skill:

https://github.com/CleverRaven/Cataclysm-DDA/blob/3d0002bc4491ffed11874cd2031c10478ead5891/src/mtype.h#L328

https://github.com/CleverRaven/Cataclysm-DDA/blob/3d0002bc4491ffed11874cd2031c10478ead5891/src/weakpoint.cpp#L72-L75

#### Describe alternatives you've considered
There's certainly more weakpoints and proficiencies that could be added, but I don't have an eye for balance :P

#### Testing
See screenshots above. Also tested by stepping through `weakpoint_attack::compute_wp_skill` and `monster::absorb_hit` to see how the modified wp skill affects the weakpoint selection.

#### Additional context
Hopefully this inspires someone more balance-oriented to add some more weakpoints and weakpoint proficiencies

2022-03-31 16:13 UTC, Shodan14 commented
We're going to need a better way to organize the proficiencies list with that..

2022-03-31 16:25 UTC, bananapheasant commented
i fully second some new way to view and organize proficiencies as it becomes more comprehensive. Proficiencies having levels like skills would perhaps be a good direction to head as well. Currently many have beginner, advanced, etc. Just viewing the proficiencies and their level, possibly with a description of the advantages, would be cool.

2022-03-31 20:37 UTC, dseguin commented
I hear you. I'm working on a UI to more clearly display proficiencies, which will be accessible from a shortcut in the @ menu. That will come in a separate PR.

2022-04-01 15:25 UTC, TheShadowFerret commented
> This PR adds proficiencies about the PC knowing where to strike to hurt a particuliar creature the most. Those you quoted seems like more about knowing what to do with their remains

Dissection of remains also trains these, I'm not seeing a significant difference here.

2022-04-02 03:10 UTC, dseguin commented
> We already have Principles of Biology, Physiology, and Xenology as proficiencies. Shouldn't they be used instead of using _only_ new proficiencies?

I'm not sure, to be honest. They didn't seem appropriate for zombies or insects, but Xenology could be appropriate for migo weakpoints for example.

Maybe I'm wrong, though. I can be convinced otherwise.

2022-04-07 05:11 UTC, dseguin commented
I updated the weakpoint proficiencies to use more original names/descriptions and reused some existing proficiencies (list included in PR description). Erk suggested a distribution that makes much more sense than what I was using.

C.C.: @I-am-Erk

2022-04-07 19:16 UTC, Termineitor244 requested changes
Looks pretty good to me! But I think there could be a basic/general weakpoint proficiency for zombies and ferals in general, you could use the "Principles of Biology" proficiency for that, since its related, and already used as a prerequisite for the already existing proficiencies.

You could decrease the time it takes to learn basic biology, and in turn increase the time for the most specific proficiencies, since they are most specific (and difficult) disciplines into biology, different than "If you hit the neck, it will hit harder", or "The legs are essential for balance, hit that", hulk biology would be more like "The hulks, because of their overgrown size and mutations, are stronger and more resistant overall, but after carefully analysis, it has been revealed that they lack balance/resistance in... areas, so a good and measured strike there could bring them down"

I'm not sure how the proficiencies code works, but I think the family entries of each monster would need "prof_intro_biology" added too for one to learn it (and then learn the specifics too)...
But that is already a problem, since some of the proficiencies require it, but you cannot learn it by combat.

2022-04-07 19:16 UTC, Termineitor244 commented on data/json/proficiencies/weakpoints.json
> +    "time_to_learn": "6 h",
```suggestion
    "time_to_learn": "6 h",
    "required_proficiencies": [ "prof_intro_biology" ],
```

2022-04-07 19:16 UTC, Termineitor244 commented on data/json/proficiencies/weakpoints.json
> +    "time_to_learn": "4 h",
```suggestion
    "time_to_learn": "4 h",
    "required_proficiencies": [ "prof_intro_biology" ],
```

2022-04-07 19:16 UTC, Termineitor244 commented on data/json/proficiencies/weakpoints.json
> +    "time_to_learn": "8 h",
```suggestion
    "time_to_learn": "8 h",
    "required_proficiencies": [ "prof_intro_biology" ],
```

2022-04-07 19:16 UTC, Termineitor244 commented on data/json/proficiencies/weakpoints.json
> +    "time_to_learn": "6 h",
```suggestion
    "time_to_learn": "6 h",
    "required_proficiencies": [ "prof_intro_biology" ],
```

2022-04-07 19:37 UTC, dseguin commented
> I'm not sure how the proficiencies code works, but I think the family entries of each monster would need "prof_intro_biology" added too for one to learn it (and then learn the specifics too)... But that is already a problem, since some of the proficiencies require it, but you cannot learn it by combat.
> 
> Edit: I suggested changes in the proficiencies that I think should have "prof_intro_biology" as a requisite at the very least, the armor and flying proficiencies could do well without it, but these ones I feel would need it.

Thanks! Adding `prof_intro_biology` to the "families" field should be enough to make it learnable. You can't practice a proficiency if you don't have the pre-requisites, but adding the pre-requisite makes it so that you can practice it first before learning others (in this case via dissection).

2022-04-07 19:48 UTC, Termineitor244 commented
> Thanks! Adding `prof_intro_biology` to the "families" field should be enough to make it learnable. You can't practice a proficiency if you don't have the pre-requisites, but adding the pre-requisite makes it so that you can practice it first before learning others (in this case via dissection).

Good to know! And thanks for the good work!

2022-04-09 05:32 UTC, merged