Show item contents in `V` menu
CleverRaven/Cataclysm-DDA pull request #56623
Opened 2022-04-06 08:01 UTC by mqrause

#### Summary
Bugfixes "Show item contents in `V` menu"

#### Purpose of change

Pockets broke this, so make it work again.

#### Describe the solution

Add item contents to the list recursively.

#### Describe alternatives you've considered

Use a preset to filter out some stuff like in `inventory_selector` menus.

#### Testing

Open the menu with a zombie corpse or a filled container nearby.

#### Additional context

Extracted from #55503 because it's gonna be a while until that's finished and this is a useful small standalone change.

2022-04-06 09:33 UTC, andrei8l commented
<details>
<summary>
I don't think that'll work very well without the collapsing functionality from `inventory_selector`
</summary>

![Screenshot from 2022-04-06 12-30-56](https://user-images.githubusercontent.com/68240139/161944601-4fa6b48f-8300-4b24-852a-f6c4a2885a34.png)
</details>

2022-04-06 10:02 UTC, mqrause commented
I didn't check how much work it'd be to implement that here (probably not too bad), but is that really necessary? Collapsible entries might actually reduce the usability when there's a ton of different items and you have to navigate to some because you want to uncollapse them.

2022-04-06 10:18 UTC, andrei8l commented
> you have to navigate to some because you want to uncollapse them.

That's somewhat balanced by the need to hide items you already know and don't care about (ex: items in your dropped backpack). People have also complained specifically about MREs polluting item menus in the past.

2022-04-06 12:12 UTC, mqrause commented
> hide items you already know and don't care about

I'm not sure about the specifics of how it works right now. Is that something the inventory selector functionality can do? I know some stuff is collapsed by default, which I don't think is appropriate here, because the purpose of the menu is to show everything around you, But I can agree with collapsing your looting backpack when you dropped it for a fight.

Another way to reduce clutter could be to only show things you can actually see. Like you can only see the contents of open or transparent pockets. To give that authentic looting experience.

Whatever the preferred solution is in the end, it can probably be it's own PR, though. At least I don't think this creates more issues than it solves as it is.

2022-04-22 18:13 UTC, I-am-Erk commented
I am not sure this is the desired behaviour. I think we need something a bit more complex: you can't just look at a cardboard box and know what's in it. We need to track:
- have you looked in this container before? Then show the contents.  If not,
- Is this container transparent? Then show the contents. If not,
- Is this container sealed? Then we should check if there's some kind of label and display that. If not,
- Don't show the contents and display "contents hidden" in `V`.

I think fixing it this way will make people real mad when we implement the above behavior, which is annoying for people who work hard to add the more granular features. If you want a good first pass you could see about showing the contents of previously examined containers, for example.

2022-04-22 18:21 UTC, I-am-Erk requested changes
See above comment. If kevin or someone disagrees I'll remove this.

2022-04-22 19:06 UTC, mqrause commented
> I think fixing it this way will make people real mad when we implement the above behavior, which is annoying for people who work hard to add the more granular features. If you want a good first pass you could see about showing the contents of previously examined containers, for example.

Yeah, that might be a problem. Gating it behind explicitly examining an item wouldn't be hard, but also sounds annoying from a player perspective. Also counterintuitive because all the inventory menus don't care about these things. I won't be able to do any kind of more complex implementation any time soon, though.

2022-04-22 19:27 UTC, I-am-Erk commented
The concept here would basically be, if you interact with the item in any way it becomes 'examined' and now you can see the contents, whether it's by picking it up, examining it, or something else.

2022-04-22 21:16 UTC, mqrause commented
It has to be maintainable, so setting the "examined" flag shouldn't be sprinkled everywhere in the code. That's my primary worry with implementing this. Ideally there's just one place where it's set, but I'll have to dive in the code to see if that's possible.

2022-04-22 22:53 UTC, I-am-Erk commented
Another, perhaps easier, first option would be to try to determine what containers should be transparent.

2022-05-06 06:59 UTC, mqrause commented
Reworked this to a somewhat basic implementation that only supports transparency of pockets for now. I only changed the pocket of corpses because that's the biggest issue and I don't enjoy auditing items. That's a lot of potential for easy PRs for first time contributors, too.

2022-05-15 15:21 UTC, merged