[Innawoods] Trapper packs and grass headwear
CleverRaven/Cataclysm-DDA pull request #57276
Opened 2022-04-29 23:16 UTC by Sathra225

#### Summary
Mods "More primitive backpacks and grass keffiyeh"

#### Purpose of change
Adds 2 new backpacks made of cloth and wood, based on the Nelson Trapper packs for early Innawoods games. Also adds a grass sheet version of the keffiyeh, as early head warmth/mouth was missing.

#### Describe the solution
Adds the items and crafting recipes.

#### Describe alternatives you've considered
None

#### Testing
Made changes, loaded save. Made and wore both packs and the keffiyeh. No errors.

#### Additional context

2022-04-29 23:21 UTC, Sathra225 commented
@Light-Wave for review

2022-04-30 00:00 UTC, TheShadowFerret commented
Can vanilla have these too? ❤️

2022-04-30 03:44 UTC, NetSysFire commented
I do not see why not. Only thing I would look into is the actual realism of the grass keffiyeh.

2022-04-30 10:23 UTC, Sathra225 commented
I'm not sure how feasible these would actually be for mainline, as the small one is 5kg and the big one is 10kg. They're big, crude packs. In mainline it would make more sense to to have them made of aluminium replacing the wood if player-craftable.

As for the grass keffiyeh...its more of a best fit for the concept (which is basically a loose grass sheet, secured to the head that you can tuck into itself to cover the mouth and nose). So its not quite a headwrap, its more loose. 
Are there real examples that I know of? Doubtful, it'd be uncomfortable and archeological records wouldn't show it as its basically a grass sheet and some cords. 
Is it something a survivor would do if they had nothing else? Yes, kinda. It'd be more likely to cover the head with a worn grass sheet and hunch, but the current sheets aren't worn over the head for some reason and fixing that would involve adding flags to something I'm not actually sure of the size of.

2022-04-30 11:44 UTC, Light-Wave commented
I agree that these fits beter in mainline than in Innawood. Putting it in mainline also means more scrutiny regarding how balanced these things are, which I would also consider a good thing.

2022-04-30 11:45 UTC, Light-Wave requested changes
Request these changes be moved to mainline.

2022-04-30 12:14 UTC, Sathra225 commented
Shifted over to main.

2022-04-30 21:09 UTC, casswedson commented on data/json/items/armor/storage.json
> +    "description": "A wooden frame with waterproofed cloth stretched around it, and a drawstring at the top to hold things in.  It has straps to wear it on your back",
```suggestion
    "description": "A wooden frame with waterproofed cloth stretched around it, and a drawstring at the top to hold things in.  It has straps to wear it on your back.",
```

2022-05-02 18:04 UTC, merged