Magic bracelets
CleverRaven/Cataclysm-DDA pull request #57506
Opened 2022-05-07 08:33 UTC by GuardianDll

#### Summary
Mods "Adding magic bracelets"

#### Purpose of change

adding some cool magic bracelets, mostly oriented to save your life in critical situation

#### Describe the solution

4 new bracelets:

missile volley bracelet - activated a bunch of mana bolts to damage enemies nearby
petrification bracelet - totally freeze your enemies in big range
disorientation bracelet - disorient your enemies in smaller range
propulsion bracelet - make you really fast

#### Describe alternatives you've considered

transform bracelets to bracers

#### Testing

works fine

2022-05-07 16:23 UTC, TheShadowFerret requested changes

2022-05-07 16:23 UTC, TheShadowFerret commented on data/mods/Magiclysm/items/enchanted_bracelet.json
> +    "description": "A bracelet, completely covered with a large amount of runes from both sides.  Wizards love to name it \"ultima ratio\", describing his colossal might.  Require almost a whole week
```suggestion
    "description": "A bracelet, completely covered with a large amount of runes from both sides.  Wizards love to name it \"Ultima Ratio\", describing its colossal might.  Require almost a whole week to restore its charge.",
```
I don't think rings have a sex 🤔

2022-05-07 16:23 UTC, TheShadowFerret commented on data/mods/Magiclysm/items/enchanted_bracelet.json
> +    "description": "A bracelet, completely covered with a large amount of runes from both sides.  You don't really know how it works, but after using enemies literally freeze in the middle of their m
```suggestion
    "description": "A bracelet, completely covered with a large amount of runes from both sides.  You don't really know how it works, but after use enemies literally freeze in the middle of their movement.  Require almost 7 days to restore its charge.",
```

2022-05-07 16:23 UTC, TheShadowFerret commented on data/mods/Magiclysm/items/enchanted_bracelet.json
> +    "description": "Known as a \"worse version of petrification bracelet\", this tool cast a spell, that temporary break the whole movement system of creature, disabling his movement for a short time
```suggestion
    "description": "Known as \"a worse version of petrification bracelet\", this tool casts a spell that temporarily breaks the whole movement system of creature, disabling its movement for a short time.  Require almost a week to restore its charge.",
```

2022-05-07 16:23 UTC, TheShadowFerret commented on data/mods/Magiclysm/items/enchanted_bracelet.json
> +    "description": "It feels like the world aroud you just stop.  Thats not true, thats just a combination of really fast speed and some mana tricks you can't understand.  Require a whole week to res
```suggestion
    "description": "It feels like the world around you just stops.  That's not true, that's just a combination of really fast speed and some mana tricks you can't understand.  Require a whole week to restore its charge.",
```

2022-05-07 18:13 UTC, GuardianDll commented on data/mods/Magiclysm/items/enchanted_bracelet.json
> +    "description": "It feels like the world aroud you just stop.  Thats not true, thats just a combination of really fast speed and some mana tricks you can't understand.  Require a whole week to res
thank you!

2022-06-10 23:20 UTC, KorGgenT commented on data/mods/Magiclysm/Spells/item_only.json
> +    "description": "Freeze!.",
```suggestion
    "description": "Freeze!",
```

2022-06-10 23:23 UTC, KorGgenT approved these changes

2022-06-11 02:32 UTC, merged