Restricted Gasoline Zeds to Gas Stations (w/ rare chance)
CleverRaven/Cataclysm-DDA pull request #58649
Opened 2022-06-23 12:16 UTC by sonphantrung

#### Summary
Balance "Restricted Gasoline Zeds to Gas Stations"

#### Purpose of change
Gasoline zombies are currently quite problematic:
- Appears everywhere, even under the most nonsensical places (labs for example)
- Occasionally "hurt" itself offscreen, explode into fireballs, ruining loots, giving players nothing but anger.
This solves those

#### Describe the solution
- Removed gasoline zeds from zombies' evolution
- Added it as a rare, late spawned (`"starts": "7 days"`) gas station zombie, suggested that it has consumed LOTS OF GAS there

#### Describe alternatives you've considered
Not doing this, and seeing more players complaining about the BS of gas zeds

#### Testing
If it doesn't throw errors, it should be good

#### Additional context
For me, playing w/ blacklist mods is considered a weak-minded, last ditch solution to undesired zeds

2022-06-23 13:20 UTC, bombasticSlacks approved these changes
I'm not the only one with a voice on this but I think this is a reasonable solution to the odd interactions gasoline zombies cause when paired with the reality bubble.

2022-06-23 15:36 UTC, LovamKicsiGazsii commented on data/json/mapgen/gas_stations/s_gas.json
> +      "place_monsters": [ { "monster": "GROUP_ZOMBIE_GAS", "x": [ 5, 10 ], "y": [ 6, 10 ], "chance": 2 } ]
`place_monsters` calculates chance a bit differently. Here, `chance` represents a 1 in N chance that the entire group will spawn (according to the mapgen doc). This means gasoline zeds have a 50% chance of spawning.

2022-06-23 17:21 UTC, Inglonias commented
If merged, this would close #56862

2022-06-23 17:31 UTC, Inglonias requested changes
Strongly advise avoiding `place_monsters` flag, as it will place every entry in the group once if that chance procs. Use `place_monster` with the `repeat` field instead.

2022-06-23 17:31 UTC, Inglonias commented on data/json/mapgen/gas_stations/s_gas.json
> +      "place_monsters": [ { "monster": "GROUP_ZOMBIE_GAS", "x": [ 5, 10 ], "y": [ 6, 10 ], "chance": 2 } ]
```suggestion
      "place_monster": [ { "group": "GROUP_ZOMBIE_GAS", "x": [ 5, 10 ], "y": [ 6, 10 ], "repeat": 5, "chance": 2 } ]
```

2022-06-25 07:53 UTC, merged

2022-07-02 02:01 UTC, LyranRenegade commented
My 2 cts, don't nerf stuff too extremely just because of a potential ruined run.
I mean, I dont have any problems with the gas-z's and have a lot of fun using them tactically against their brethren.
Now, I'm sure there are cases you'd wish they weren't there, but hey..