Allow using ash for making glass
CleverRaven/Cataclysm-DDA pull request #58800
Opened 2022-06-28 20:18 UTC by AtomicFox556

#### Summary
Balance "Allow using ash for making glass"

#### Purpose of change
#58538 introduced a way to make glass using ash for Innawood mod, but this method is inaccessible in main game despite it apparently being possible.

#### Describe the solution
Add ash as a possible substitution to washing soda for glassmaking.

Also added sand casting mold as a possible alternative to sheet metal; as far as I could figure out, glass can indeed be cast in a sand mold. This substitution makes more sense than Innawood recipe allowing to substitute it with a metal pot.

Current glass recipe in Innawood is not removed or modified because in main game the glass recipe is not autolearned.

#### Describe alternatives you've considered
None.

#### Testing
Launched the game, made sure that no errors happen.

#### Additional context
Source (as provided in #58538 ):  https://etheses.whiterose.ac.uk/3464/1/287681.pdf

2022-06-28 21:50 UTC, Sathra225 commented
The pot/sheet metal is for annealing/slow cooling so it doesn't crystallise and shatter into powder.

2022-06-29 03:24 UTC, AtomicFox556 commented
> The pot/sheet metal is for annealing/slow cooling so it doesn't crystallise and shatter into powder.

Noted. I'll revert this change for now, but there's probably some way around it as glass items historically were produced even before steel could be produced.

2022-07-23 17:26 UTC, I-am-Erk requested changes
The type of ash that is used in modern glass making isn't just wood ash, it's specifically [soda ash](https://www.stretchglasssociety.org/the-making-of-glass). My understanding is that wood ash needs at least some additional treatment steps to be alkaline enough to have similar properties. My understanding could be wrong but at the very least I think some sources would be good, and I suspect you'll need a little more intermediary production steps in here. In the long run that's a good thing because more ash industry stuff will open up more fun chemistry stuff

2022-07-23 17:44 UTC, AtomicFox556 commented
> The type of ash that is used in modern glass making isn't just wood ash, it's specifically [soda ash](https://www.stretchglasssociety.org/the-making-of-glass). My understanding is that wood ash needs at least some additional treatment steps to be alkaline enough to have similar properties. My understanding could be wrong but at the very least I think some sources would be good, and I suspect you'll need a little more intermediary production steps in here. In the long run that's a good thing because more ash industry stuff will open up more fun chemistry stuff

It's all true. According to source listed above, ash indeed works as a source of alkali/flux for making glass.

Page 22:

>The second major ingredient in medieval glass batches is ash. Ash was the primary source of alkali for the production of glass. The major source of ash in the production of medieval `forest' glass was trees. Medieval glass production in England can be distinguished by the reliance on wood ash as the form of fluxing agent. Often this results in a glass having a high potash and low soda content. This contrasts with ancient glass from Egypt where the source of alkali may have been natron, a salt that contains a high level of sodium carbonate.

Page 23, stating that it's added as-is without any extra processing:

> The ashes are added to silica to act as a fluxing agent. Fluxes lower the temperature at which a liquid will form, and as silica melts at a temperature above 1600 °C, it is necessary to combine it with fluxes which firstly melt at a lower temperature, and secondly, will form compounds which can produce glasses. Of such compounds the salts of sodium and potassium are by far the most important ones when discussing medieval glass, where the wood ash may contain a mixture of these alkalis. These fluxing agents and the silica form a eutectic mixture that may reduce the temperature at which liquid forms.

2022-07-23 18:33 UTC, I-am-Erk commented
[Forest glass](https://en.m.wikipedia.org/wiki/Forest_glass) tends to be of variable quality, because not all ash is the same. Yes, forest glass is made by adding ash directly, but you can't just add any old ash and get a useful product.

I think the best solution would be to identify some of the plants in game with alkaline ash products and devise a way to burn them to make alkaline ash.

2022-07-23 18:45 UTC, AtomicFox556 commented
> [Forest glass](https://en.m.wikipedia.org/wiki/Forest_glass) tends to be of variable quality, because not all ash is the same. Yes, forest glass is made by adding ash directly, but you can't just add any old ash and get a useful product. Specifically one of the easiest ways to get ash in game is from lab incinerators, and I am unfortunately pretty sure that ain't wood ash.
> 
> I think the best solution would be to identify some of the plants in game with alkaline ash products and devise a way to burn them to make alkaline ash.

In that case any such sources probably shouldn't be producing ash (at least the useful kind, but I don't see any point in anything being produced at all if it's a completely useless item).
All current in-game uses (even beside this one) for ash seem to assume that it's wood ash, or at the very least that it has alkaline properties like wood ash.

2022-07-23 18:53 UTC, I-am-Erk commented
We could potentially differentiate ash from animal products from ash from plant products, which would also allow for some more emergent storytelling. I'd say we would want "plant ash", which is specifically from plants, "burnt junk" which is from random stuff, and "greasy ash" from creatures. I do not know how much would be involved in separating them, I suspect it dives into legacy code... That's why it may be easier to pick a few specific sources for alkaline ash.

2022-07-23 19:01 UTC, AtomicFox556 commented
> We could potentially differentiate ash from animal products from ash from plant products, which would also allow for some more emergent storytelling. I'd say we would want "plant ash", which is specifically from plants, "burnt junk" which is from random stuff, and "greasy ash" from creatures. I do not know how much would be involved in separating them, I suspect it dives into legacy code... That's why it may be easier to pick a few specific sources for alkaline ash.

At first glance it seems pretty simple actually; material definitions have "burn_products" entries, so I could just make some new ash types and have things made of this material produce those ashes once they are burned. I'll look into doing that soon.

I don't know how much effort it'd take to review ash spawning in some places, but I'll look into that as well.

2022-07-24 16:48 UTC, AtomicFox556 commented
Done. I've added three new ash types: greasy ash (from animals/zombies/humans/whatever), burnt food (from burning edible stuff), and burnt junk (from burning anything else that would remain some kind of residue, such as plastic); at the moment all three are useless.

Wood ash in item groups was replaced by other ash types where wood ash didn't make sense.

2022-07-24 17:05 UTC, Night-Pryanik commented on data/json/items/chemicals_and_resources.json
> +    "name": { "str_sp": "greasy ash" },
```suggestion
    "name": { "str_sp": "greasy ash", "str_pl": "greasy ashes" },
```

2022-07-24 17:33 UTC, I-am-Erk commented on data/json/itemgroups/Locations_MapExtras/locations.json
> +    "items": [ [ "ash", 10 ], [ "ash_other", 80 ], [ "ash_food", 5 ], [ "ash_flesh", 5 ] ]
I'd just use ash_other here, it would be challenging to determine what exactly it is in a dump.

2022-07-24 18:35 UTC, AtomicFox556 commented
Made changes as suggested.

2022-07-29 20:58 UTC, AtomicFox556 commented
Changed amount of ash produced when burning flesh and bones. Source: https://www.urnsforashes.co.uk/what-size-urn/

2022-08-02 05:30 UTC, Merikona commented
Hey Atomic, I ended up borrowing most of your ideas for what should generate corpse ash (namely the chitin, wool, leather and alien carapace), but I didn't use some: cured meat, eggs, and feces off the top of my head. My PR was designed to let players honor a NPC, pet, or player character they care about who passed away, so I didn't want someone taking a canvas bag, collecting some manure, tossing it in a fire, and for corpse ash to pop out. I also don't like the name, greasy ash, for this reason. With things like eggs, cured meat, and manure, I hope there's a different category of ash we can place them in, or simply have them not yield ash when burnt. Not everything has to yield ash imo.

2022-08-15 22:02 UTC, closed without merging