Leads to fix v2
CleverRaven/Cataclysm-DDA pull request #59569
Opened 2022-07-24 21:19 UTC by Stadler76

#### Summary
Bugfixes "Change leads_to consistency check to check for 'not disjunct'"

#### Purpose of change
Closes #59299

The consistency check for `leads_to` required, that all categories in the additive mutation are present in the mutation that `leads_to` it. This was undesirable and therefore it now checks, if the categories of both mutations are not disjunct aka any match is fine.

#### Describe the solution
Made the consistency check for `leads_to`-mutations to check, if at least one category is present in both the mutation and its addition(s).

- [x] Undo the changes to `mutations.json` once the checks give me a thumbs up and convert the draft to a PR.

#### Describe alternatives you've considered
The alternative would be removing `leads_to` upon removing `prereqs` when I just want to remove a category from the 'not prereq anymore'-mutation, which is also undesirable, I'd say.

#### Testing
1. Removed `"prereqs": [ "EYEBULGE" ],` from `MEMBRANE` and `LIZARD`-category from `EYEBULGE` and it succeeded as expected.
2. In addition to the first test: Removed `FISH` and `BATRACHIAN` from `MEMBRANE` and thus making the categories of `MEMBRANE` and `EYEBULGE` disjunct and it failed as expected.

2022-07-26 22:25 UTC, actually-a-cat requested changes
Aside from this LGTM. For context, with #58803,

2022-07-26 22:25 UTC, actually-a-cat commented on src/mutation_data.cpp
> +                continue;
```suggestion
            if( mdata.category.empty() ) {
                break;
```

This is equivalent to previous behavior in regard to those obsoleted mutations and also generally a little bit safer (will catch a mistake in which a mutation somehow ends up without category but still has `leads_to` from a normal mutation)

2022-07-30 15:38 UTC, Stadler76 commented
@actually-a-cat: For some reason I can't Re-request review from you. But can you approve those changes?

2022-08-01 12:53 UTC, actually-a-cat approved these changes

2022-08-06 23:01 UTC, Stadler76 commented
If anyone wants to know, why I'm merging again after a few hours. The answer is bad timing:
![grafik](https://user-images.githubusercontent.com/13157984/183268473-dbc258c4-d328-4de3-8298-9e716247fab2.png)
![grafik](https://user-images.githubusercontent.com/13157984/183268486-90d6695c-089d-4bf2-aca8-652f3918dcbb.png)

2022-08-07 16:12 UTC, merged