Add ability to merge appliance into grid
CleverRaven/Cataclysm-DDA pull request #60681
Opened 2022-09-02 12:21 UTC by Fris0uman

#### Summary
Infrastructure "Add ability to merge appliance into grid"

#### Purpose of change

For performance purposes it would make sense to merge powergen and battery appliances into the grid to reduce the number of vehicles the code has to walk through

#### Describe the solution

- [x] Encapsulate code to merge appliances
- [x] Add menu to merge an appliance into a grid
- [ ] Limit the option to powergen and batteries
- [ ] Make sure `Take down appliance` still works properly
#### Describe alternatives you've considered

#### Testing

#### Additional context

2022-09-04 05:50 UTC, robob27 commented
Hey @Fris0uman I was just wondering if this is considered working minus the outstanding checklist items? I was testing it with my save and had some odd results after merging an appliance. Obviously this is still a draft so good chance it's not done yet, but I am watching this with great anticipation to test it asap 😄.

If the merge part is supposed to be working now though I can share my save for debugging purposes. I don't really understand the vehicle mount stuff 😅

2022-09-04 07:49 UTC, Fris0uman commented
It works but I need to add restrictions to it, becasue for exemple if you put down a fridge aplliance, drag it a bit to make it turn and then merge it into the grid the grid will probably rotate and mess up everything

2022-09-04 15:23 UTC, irwiss commented
Is there a need to expose these choices to the player?

As in, what are the factors players need to consider whether they want to merge a particular appliance or not?

And what are the conditions where you wouldn't want to merge? If it's transparent to the player, may be appliances should automatically merge by default

2022-09-04 15:47 UTC, robob27 commented
>the grid will probably rotate and mess up everything

Ahh okay, yeah that's what I was seeing. I saw your note about restricting it to powergen and batteries so I was trying with only solar panel and batteries, but I see there has been some more updates so I will continue testing.

I have a save I haven't really been able to play due to appliance slowdown so this is very exciting to me. Huge personal thanks from me for your efforts on this.

2022-09-04 16:06 UTC, robob27 commented
Still having some rotation issues after the latest changes. After merging the battery directly north of my character into the wall wiring to the east of the battery, the wall wiring ends up south of my character.

![image](https://user-images.githubusercontent.com/2104555/188322417-29ed559d-c8b7-43f4-9a29-d4865bcf326a.png)
![image](https://user-images.githubusercontent.com/2104555/188322458-15ee493a-6cca-4d28-843b-1db6b5afb268.png)

I also noticed that solar panels don't count as `vehicle::is_powergrid()` at night so they can only be merged during the day.

2022-09-06 16:22 UTC, Fris0uman commented
So maybe we would need some migration code to reset all facing on previousy installed appliances?

2022-09-07 22:08 UTC, robob27 commented
I noticed that when I check voltage on wall wiring/battery that has been merged with solar panels it says "The solar panel has voltage" instead of the name of the specific appliance I'm checking.

2022-09-07 23:50 UTC, robob27 commented
My experiences with taking down appliances with these changes in case it's helpful:

- Taking down an appliance in a merged vehicle removes all power connections from the entire vehicle. So if you remove a solar panel off the end of your array, you'll have to plug your fridge back in.
- Using appliance removal, you can make large gaps in the vehicle, larger than what you'd be able to pull off with deploying/merging appliances only (without the use of extension cords). In the first screenshot below, all of the wires are a single merged vehicle and there is a kiln connected with "plug in vehicle" to the northeast wire. In the second screenshot, I removed all of those wires. The remaining wires are still the same vehicle - powering one of them powers both of them despite the lack of any real connection.

![image](https://user-images.githubusercontent.com/2104555/189001091-785018eb-dc47-4af4-9caa-de2afffbe8cc.png)

![image](https://user-images.githubusercontent.com/2104555/189000395-dfe0fd14-b24e-448d-a6d8-52cd8060cded.png)

This actually seems kinda cool with wall wiring. It's like I'm installing the wires and then covering them up. I guess it's a bit weirder in the case of solar panels or batteries though.

2022-09-09 07:35 UTC, dseguin commented
Here's the fix for the "Take down appliance" bug:

```diff
diff --git a/src/veh_interact.cpp b/src/veh_interact.cpp
index 09a577a161..63c1487c46 100644
--- a/src/veh_interact.cpp
+++ b/src/veh_interact.cpp
@@ -3495,14 +3495,13 @@ void veh_interact::complete_vehicle( Character &you )
             }
 
             // Remove any leftover power cords from the appliance
-            if( appliance_removal && veh->part_count() >= 2 ) {
+            if( appliance_removal ) {
                 veh->shed_loose_parts();
-                veh->part_removal_cleanup();
                 //always stop after removing an appliance
                 you.activity.set_to_null();
             }
 
-            if( veh->part_count( true ) < 2 ) {
+            if( veh->part_count( true ) - veh->removed_part_count < 2 ) {
                 you.add_msg_if_player( _( "You completely dismantle the %s." ), veh->name );
                 you.activity.set_to_null();
                 // destroy vehicle clears the cache
```

The issue is was that `vehicle::part_removal_cleanup` can shuffle the part indexes so that the selected part to remove now points to a different part (or nothing!). So instead of calling `part_removal_cleanup` early, subtract the removed part count from the check, which achieves the same behaviour without touching the part indexes. Also, we don't have to worry about checking the part count when calling `vehicle::shed_loose_parts`, just need to check if it's an appliance.

2022-09-10 11:51 UTC, Fris0uman commented
It's almost working, there's still a bug where if you remove an appliance and then reinstall it it messes up the whole grid. For exemple place 3 wires, remove the middle one, reinstall it, examine the grid, now one of the tiles has two wire on the same spot. I don't know why

2022-09-24 04:06 UTC, robob27 commented
Hey @Fris0uman, in case it helps at all here's a branch with these changes re-applied on the latest master without conflicts: https://github.com/CleverRaven/Cataclysm-DDA/compare/master...robob27:merge_app_rebase?expand=1

I've testing merging an appliance and it worked. I haven't tried to resolve the last bug you mentioned, or tested anything else yet. I set this branch up because for a while I had been building my game with this branch on top of the latest master. A couple weeks ago there were some pretty significant changes so I was no longer able to easily do this, so I did this.

The rebase was complex for me, so I didn't do a true rebase. I found it easier to start fresh from master and use this PR as a reference. Since I couldn't use your actual commits, I put you as a co-author in my commit just in case. Let me know if you'd like me to remove this. Didn't feel right copy/pasting your code without doing it, but also feels weird putting your name on it without consulting you 😅

2022-09-25 08:01 UTC, dseguin commented
It seems like there are two issues when placing wall wiring:
- Fake parts interfere with the bounding box and vehicle part merging
- All mounting points get shifted if the "origin" part is removed, but `vehicle::coord_translate` doesn't reflect the updated position

I tested briefly with this patch. This will only merge "real" parts, and the merge target is shifted back to zero if the origin part was previously removed (I'm really not sure why `vehicle::coord_translate` doesn't account for the pivot point). There might be other issues but this seems to solve those two above.
```diff
diff --git a/src/vehicle.cpp b/src/vehicle.cpp
index e296cde447..5a89dff4a7 100644
--- a/src/vehicle.cpp
+++ b/src/vehicle.cpp
@@ -1827,6 +1827,9 @@ bool vehicle::merge_rackable_vehicle( vehicle *carry_veh, const std::vector<int>
 bool vehicle::merge_vehicle_parts( vehicle *veh )
 {
     for( const vehicle_part &part : veh->parts ) {
+        if( part.is_fake || part.removed ) {
+            continue;
+        }
         point part_loc = veh->mount_to_tripoint( part.mount ).xy();
 
         parts.push_back( part );
@@ -1847,13 +1850,14 @@ void vehicle::merge_appliance_into_grid( vehicle &veh_target )
     if( &veh_target == this ) {
         return;
     }
+    veh_target.shift_parts( get_map(), veh_target.pivot_displacement() );
 
-    bounding_box vehicle_box = get_bounding_box( false );
+    bounding_box vehicle_box = get_bounding_box( true, true );
     point size;
     size.x = std::abs( ( vehicle_box.p2 - vehicle_box.p1 ).x ) + 1;
     size.y = std::abs( ( vehicle_box.p2 - vehicle_box.p1 ).y ) + 1;
 
-    bounding_box target_vehicle_box = veh_target.get_bounding_box( false );
+    bounding_box target_vehicle_box = veh_target.get_bounding_box( true, true );
 
     point target_size;
     target_size.x = std::abs( ( target_vehicle_box.p2 - target_vehicle_box.p1 ).x ) + 1;
@@ -7310,7 +7314,7 @@ bool vehicle::restore_folded_parts( const item &it )
     return true;
 }
 
-const std::set<tripoint> &vehicle::get_points( const bool force_refresh ) const
+const std::set<tripoint> &vehicle::get_points( const bool force_refresh, const bool no_fake ) const
 {
     if( force_refresh || occupied_cache_pos != global_pos3() ||
         occupied_cache_direction != face.dir() ) {
@@ -7318,6 +7322,9 @@ const std::set<tripoint> &vehicle::get_points( const bool force_refresh ) const
         occupied_cache_direction = face.dir();
         occupied_points.clear();
         for( const std::pair<const point, std::vector<int>> &part_location : relative_parts ) {
+            if( no_fake && part( part_location.second.front() ).is_fake ) {
+                continue;
+            }
             occupied_points.insert( global_part_pos3( part_location.second.front() ) );
         }
     }
@@ -7656,7 +7663,7 @@ void vehicle::calc_mass_center( bool use_precalc ) const
     }
 }
 
-bounding_box vehicle::get_bounding_box( bool use_precalc )
+bounding_box vehicle::get_bounding_box( bool use_precalc, bool no_fake )
 {
     int min_x = INT_MAX;
     int max_x = INT_MIN;
@@ -7667,7 +7674,7 @@ bounding_box vehicle::get_bounding_box( bool use_precalc )
 
     precalc_mounts( 0, turn_dir, point() );
 
-    for( const tripoint &p : get_points( true ) ) {
+    for( const tripoint &p : get_points( true, no_fake ) ) {
         point pt;
         if( use_precalc ) {
             const int i_use = 0;
diff --git a/src/vehicle.h b/src/vehicle.h
index 5632670155..4d55e69dcd 100644
--- a/src/vehicle.h
+++ b/src/vehicle.h
@@ -1760,7 +1760,7 @@ class vehicle
         bool assign_seat( vehicle_part &pt, const npc &who );
 
         // Update the set of occupied points and return a reference to it
-        const std::set<tripoint> &get_points( bool force_refresh = false ) const;
+        const std::set<tripoint> &get_points( bool force_refresh = false, bool no_fake = false ) const;
 
         /**
         * Consumes specified charges (or fewer) from the vehicle part
@@ -1909,7 +1909,7 @@ class vehicle
         // Called by map.cpp to make sure the real position of each zone_data is accurate
         bool refresh_zones();
 
-        bounding_box get_bounding_box( bool use_precalc = true );
+        bounding_box get_bounding_box( bool use_precalc = true, bool no_fake = false );
         // Retroactively pass time spent outside bubble
         // Funnels, solar panels
         void update_time( const time_point &update_to );
```

2022-09-26 09:16 UTC, robob27 commented
I tried testing with this patch and noticed a couple issues. If I reveal wall wiring on a tile with no other appliances adjacent, this works normally. If I then reveal another wall wiring in an adjacent tile, it causes the first one to look like the fake part sprite, Then if I remove the wall wiring that looks like a fake part, it seems to shift the second wall wiring up

After revealing first wire:
![image](https://user-images.githubusercontent.com/2104555/192236027-7f826163-303f-404b-b08e-516e9414ef3c.png)

After revealing the second:
![image](https://user-images.githubusercontent.com/2104555/192236079-c04af964-83b2-479b-8df6-239bff351eaf.png)

After removing the first:
![image](https://user-images.githubusercontent.com/2104555/192236127-d704a3b8-0a15-43fb-a659-d2a1c156c8fb.png)

This gets us closer though.. fake parts definitely explain the weirdness.

2022-10-09 18:15 UTC, actually-a-cat commented
Some observations from trying to figure out the "missing part after merge" issue:

* When you examine a vehicle tile, parts to list are looked up from `vehicle::relative_parts`. The broken "empty" tile actually contains the part it's supposed to, but `relative_parts` doesn't.
* `relative_parts` is populated on `vehicle::refresh` in this loop:
```cpp
    // Main loop over all vehicle parts.
    for( const vpart_reference &vp : get_all_parts() ) {
```
but this only runs once even after the merge, when the vehicle definitely contains two real parts.

and, possibly unrelated but:
* Freshly placed appliances seem to come with an inactive fake part. When merging two of those, the real part is copied over without its fake, but it still has `has_fake == true`.

2022-10-09 23:12 UTC, dseguin commented
Sorry, I forgot to include this line originally:

```diff
diff --git a/src/vehicle.cpp b/src/vehicle.cpp
index d6d85e6143..ea61ea7e7f 100644
--- a/src/vehicle.cpp
+++ b/src/vehicle.cpp
@@ -1833,6 +1833,7 @@ bool vehicle::merge_vehicle_parts( vehicle *veh )
         }
         point part_loc = veh->mount_to_tripoint( part.mount ).xy();
 
+        remove_fake_parts();
         parts.push_back( part );
         vehicle_part &copied_part = parts.back();
         copied_part.mount = part_loc - global_pos3().xy();
```

Otherwise the relative part list doesn't match the part list order. Seems to fix the issue.

2022-11-15 16:55 UTC, Fris0uman commented
I think it works now

2022-11-16 09:43 UTC, andrei8l commented
You'll have to check for vehicle splitting whenever you take down an appliance:
<details>
<summary>I built this power grid</summary>

![Screenshot from 2022-11-16 11-37-46](https://user-images.githubusercontent.com/68240139/202145171-4fa4f902-2c19-423f-96d0-e082d6514fbc.png)
</details>

<details>
<summary>Removed one wiring</summary>

![Screenshot from 2022-11-16 11-37-57](https://user-images.githubusercontent.com/68240139/202145170-31e3cc48-ad39-4498-995b-9773722b8146.png)
</details>

<details>
<summary>But the two halves are still connected</summary>

![Screenshot from 2022-11-16 11-38-08](https://user-images.githubusercontent.com/68240139/202145166-36ab29f6-9a14-479f-843e-7fda9adbbe3b.png)
</details>


<details>
<summary>Physically too</summary>

![Screenshot from 2022-11-16 11-38-24](https://user-images.githubusercontent.com/68240139/202145158-43790f1a-855f-4791-8a10-9a0e405a9ca0.png)
</details>

but that doesn't have to block this PR.

2022-11-29 21:10 UTC, Fris0uman commented
so the last commit fixes the issue of grids not splitting but brings back the weird rotation and wrong index issues. Basically make a grid, remove a piece, install a new piece > the whole grid might rotate
OR remove a pievce, remove a second piece > it uninstall something different than what you selected or two parts at the same time. I don't know how to fix this

2023-01-25 18:16 UTC, Brambor requested changes
Tidy code according to Clang-tidy

2023-01-25 18:16 UTC, Brambor commented on src/vehicle.h
> +                                              const bool no_fake = false ) const;
```suggestion
        const std::set<tripoint> &get_points( bool force_refresh = false, bool no_fake = false ) const;
```

2023-01-25 18:16 UTC, Brambor commented on src/veh_appliance.cpp
> +    return;
```suggestion
```

2023-05-29 18:05 UTC, Fris0uman commented
Can't reproduce the bug that make the grid rotate around, so as far as I can tell it works

2023-05-30 07:15 UTC, Fris0uman commented
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/41293484/d9dfdad3-c6b8-4b30-8f23-c161b14b3fd3)
I did get one situation where removing a solar panel and placing it back teleported some part of it away, not sure how to reproduce

2023-05-30 07:21 UTC, Fris0uman commented
Initial setup with everything connected:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/41293484/c5e1e30c-a2d8-4e71-8fec-62c2442b3835)

Remove the panel and re place it:
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/41293484/5906558d-e4be-45ba-aa56-321ab4b17e24)
 The wires are moved

2023-08-09 14:02 UTC, Fris0uman commented
I'm going to list the bugs I find here to keep track of them, there are at least two things going on:
- First is if you have a line of wires and you merge into it one other aplliance when you remove the extra appliance the wire grid loses it's appliance and wire flags
- Second is remove something and add something back and the grid shifts around

2023-08-19 17:13 UTC, merged