Add PSL Rifle
CleverRaven/Cataclysm-DDA pull request #60972
Opened 2022-09-13 21:59 UTC by DPavonis

#### Summary
Content "Added PSL rifle"

#### Purpose of change

Adds in a Romanian PSL as a somewhat rare option for players who want a semi-automatic rifle in 7.62x54R with detachable box magazines. The reason I chose the PSL specifically is that it seems to have been imported into the US in significant enough numbers under various names that it wouldn't be too far-fetched to see one show up in a gun store.

#### Describe the solution

#### Describe alternatives you've considered

~~Somehow make a case for a Dragunov PR despite the fact actual Dragunovs are pretty rare in the US.~~

#### Testing

Fire up game, make sure the rifle and its magazines show up in debug, ~~pray I understand how item distribution works~~

#### Additional context

I'm not 100% confident on the volumes and weights of the magazines, these are just my best guesses based off taking measurements off of images for the volume and guesstimating for the weight.

2022-09-14 00:54 UTC, TheShadowFerret commented on data/json/items/gun/762R.json
> +      [ "sights mount", 1 ],
```suggestion
      [ "sights mount", 1 ],
```
I don't think a DMR is going to need you to add a mount to it for a scope(esp. as Century includes an optic with their imports of it https://www.centuryarms.com/psl-54c-semi-auto-rifle-cal-7-62x54r.html) 🤔

2022-09-14 00:58 UTC, DPavonis commented on data/json/items/gun/762R.json
> +      [ "sights mount", 1 ],
Fair enough. I was thinking of just a bare, unmodified PSL, but eh, works for me. ¯\_(ツ)_/¯

2022-09-16 16:07 UTC, tenmillimaster commented
Could you include a default mod of a sights adapter, as opposed to natively having a sights slot on the gun?

2022-10-26 06:21 UTC, Night-Pryanik commented
@DPavonis could you please resolve conflicts?

2022-11-09 01:45 UTC, nopenoperson requested changes

2022-11-09 01:45 UTC, nopenoperson commented on data/json/items/gun/762R.json
> +    "weight": "4100 g",
weight without a pso1 style scope should be about 3600g

2023-03-13 00:21 UTC, merged