backport z-level draw
CleverRaven/Cataclysm-DDA pull request #61074
Opened 2022-09-17 14:10 UTC by sonphantrung

#### Summary
None

#### Purpose of change
I want to see zeds from below

#### Describe the solution
Port the change from [BN](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1743) by @joveeater

#### Describe alternatives you've considered
Not doing this

#### Testing
TBD, I don't have a good machine to compile

#### Additional context
my head is currently sleepy, I'll keep an eye on the code later ;)

2022-09-17 21:30 UTC, I2pRandom commented
It took a while to bring Z-levels to BN in the first place, i don't recommend not testing this. it had a few bugs and problems along the way of getting it working.

2022-09-18 09:13 UTC, Lamandus commented
yes, I would consider to wait just a few days until the bugs are ironed out, for example the thing with the cardboard box. It should also be tested with DDA since your code is different in some places.

2022-09-20 05:17 UTC, sonphantrung commented
@jbytheway How do I deal with ["construction of (tri)point can be simplified"](https://github.com/CleverRaven/Cataclysm-DDA/pull/61074/files#diff-c8561880131eb6314d85f58032f9063284bcfc226b75b3b5df585dcaa219605cR1379)? I'm not a C++ professional

2022-09-21 05:48 UTC, scarf005 commented
many of the warnings are from usage of `{temp.x, temp.y, center.z}`.
since there's a variable `pos` defined as `const tripoint pos( temp, center.z );`,
you could replace them with `pos`.

- check [`struct tripoint` at src/point.h](https://github.com/CleverRaven/Cataclysm-DDA/blob/89803505c4ed1651a01169f1e8c207a4e86e8b87/src/point.h#L142) for more constructor options.
- check `CHECK-FIXES` in [clang-tidy plugin for simplify point constructor](https://github.com/CleverRaven/Cataclysm-DDA/blob/89803505c4ed1651a01169f1e8c207a4e86e8b87/tools/clang-tidy-plugin/test/simplify-point-constructors.cpp) for available fixes.

2022-09-21 12:22 UTC, scarf005 requested changes
`point ( temp )` can be furthur simplified to `temp`, since type of `temp` is `point`.
https://github.com/CleverRaven/Cataclysm-DDA/blob/5a592543b7a34c868ac33d78c0479ab7293f2d66/src/cata_tiles.cpp#L1362-L1375

2022-09-21 12:22 UTC, scarf005 commented on src/cata_tiles.cpp
> +                    overlay_strings.emplace( player_to_screen( point( temp ) ) + half_tile,
```suggestion
                    overlay_strings.emplace( player_to_screen( temp ) + half_tile,
```
`temp` is already of type `point`, so you don't need to wrap it

2022-09-21 12:22 UTC, scarf005 commented on src/cata_tiles.cpp
> +                    overlay_strings.emplace( player_to_screen( point( temp ) ) + half_tile,
```suggestion
                    overlay_strings.emplace( player_to_screen( temp ) + half_tile,
```

2022-09-21 12:22 UTC, scarf005 commented on src/cata_tiles.cpp
> +                    overlay_strings.emplace( player_to_screen( point( temp ) ) + half_tile,
```suggestion
                    overlay_strings.emplace( player_to_screen( temp ) + half_tile,
```

2022-09-21 12:22 UTC, scarf005 commented on src/cata_tiles.cpp
> +                    overlay_strings.emplace( player_to_screen( point( temp ) + half_tile,
```suggestion
                    overlay_strings.emplace( player_to_screen( temp + half_tile,
```

2022-09-21 12:22 UTC, scarf005 commented on src/cata_tiles.cpp
> +                overlay_strings.emplace( player_to_screen( point( temp ) ) + half_tile,
```suggestion
                overlay_strings.emplace( player_to_screen( temp ) + half_tile,
```

2022-09-21 12:22 UTC, scarf005 commented on src/cata_tiles.cpp
> +                color_blocks.second.emplace( player_to_screen( point( temp ) ), block_color );
```suggestion
                color_blocks.second.emplace( player_to_screen( temp ), block_color );
```

2022-09-21 12:22 UTC, scarf005 commented on src/cata_tiles.cpp
> +                overlay_strings.emplace( player_to_screen( point( temp ) + quarter_tile ),
```suggestion
                overlay_strings.emplace( player_to_screen( temp + quarter_tile ),
```

2022-09-21 12:22 UTC, scarf005 commented on src/cata_tiles.cpp
> +                point tile_pos = player_to_screen( point( temp ) );
```suggestion
                point tile_pos = player_to_screen( temp );
```

2022-09-24 23:55 UTC, kevingranade commented
This needs feature parity with curses, I also need to see what it does to memory requirements for tilesets as it essentially makes one (or more?!?) copies of the tileset in use.

2022-09-25 13:23 UTC, sonphantrung commented
Oh yeah, I wish I could test this, but I currently don’t have something good to compile, and I’m fairly busy now. Shall we discuss?

2022-09-25 20:18 UTC, kevingranade commented
I'm not clear what there is to discuss. There's certain criteria that I briefly outlined that need to be met and that either gets met or it doesn't.

2022-09-25 20:28 UTC, Fris0uman commented
Porting the feature will probably require a fair bit of work on one of the most obscure part of the codebase, are you sure you're able to do that? Might be better to see what RAldrich comes up with since they were apparently intereted in fixing #58479

2022-09-30 06:57 UTC, sonphantrung commented
I'm currently having some pretty ugly merge conflict problems, plus seems like the code is pretty messed up since the PR initially opened, so I'll close this for the better second attempt, when my head isn't sleepy ;)

2022-09-30 06:57 UTC, closed without merging

2022-10-25 17:19 UTC, RAldrich commented
Bit of thread necromancy here, but I wanted to say not to wait on me to do anything with #58479. That's on hold indefinitely; getting it to an acceptable state of polish requires large changes to the rendering engine itself, which (like FrisOuman called out) is an extremely major project. For some perspective, I'm a sr. software engineer and I haven't been able to fully wrap my head around how it currently works (much less how it **should** work). Maybe someday when I have more time!