tweaks to basic kevlar vest
CleverRaven/Cataclysm-DDA pull request #61328
Opened 2022-09-28 17:54 UTC by anoobindisguise

#### Summary
Balance "kevlar vest rebalance"

#### Purpose of change
Kevlar vest was still using the old style of armor, and had some issues because of this. it was made of layered kevlar despite being an abnormal thickness compared to the standard 4.4mm. It also occupied the skintight layer despite that layer no longer being intended for such thick gear.

#### Describe the solution
Kevlar vest -> Kevlar torso armor, as it is no longer a "vest" (compared to the other ballistic vests which are OUTER and have storage) and now occupies the normal layer. made of 0.5mm nylon and 3.3mm kevlar. Weight reduced. 
I searched for numerous "concealable ballistic vests" and found most were level II or IIA, and that the thinnest one I could find was 3.5mm, and that level II typically caps out at about 4.2mm (1/6th inch). Also, these were roughly 1.5-2kg depending on body fit. Coverage is 94% on upper torso and 85% on lower torso, this should hopefully about match up with real life. Although some of these vests were depicted like "tank tops" worn directly on the skin, many more were worn on top of t-shirts, so NORMAL layer feels right to me. Encumbrance lowered to 3 since it is lighter than a III or IIIa vest.

#### Describe alternatives you've considered
Different coverage, lower torso coverage may be slightly too high. 
move it from torso_armor to ballistic_armor

#### Testing

#### Additional context

2022-09-29 20:08 UTC, MNG-cataclysm requested changes

2022-09-29 20:08 UTC, MNG-cataclysm commented on data/json/items/armor/torso_armor.json
> +    "description": "A lightweight level II ballistic vest, suitable for wearing under a coat or other outerwear.",
```suggestion
    "description": "A lightweight level II ballistic vest, suitable for wearing under a coat or other outer wear.",
```

2022-09-29 20:08 UTC, MNG-cataclysm commented on data/json/items/armor/torso_armor.json
> +    "name": { "str": "Kevlar torso armor" },
```suggestion
    "name": { "str": "Kevlar vest" },
```
I think vest works better for this situation. "Torso armor" sounds a bit unnatural.

2022-09-29 20:32 UTC, MNG-cataclysm approved these changes
You've done a good job with this.

2022-09-29 21:28 UTC, MNG-cataclysm commented
The Windows build test is failing because of this:
 20:51:10.318 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item.cpp:1501 [put_in] tried to put an item (creepy_doll) count (1) in a container (purse) that cannot contain it: pocket unacceptable because not enough space

@Maleclypse Could you restart the Windows build test, please?

2022-10-01 02:09 UTC, Maleclypse commented
Can you make an issue regarding the failure of the test on `20:51:10.318 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item.cpp:1501 [put_in] tried to put an item (creepy_doll) count (1) in a container (purse) that cannot contain it: pocket unacceptable because not enough space`

2022-10-01 06:09 UTC, merged