#61451 - rebalance methanol from planks
CleverRaven/Cataclysm-DDA pull request #61452
Opened 2022-10-04 01:33 UTC by jim-huynh

#### Summary
Bugfixes "Methanol from wood planks recipe needs rebalancing"

#### Purpose of change
Rebalance the methanol recipe so that it is more approximately correct.
Also fixes trying to create a batch of 50 from disappearing due to excessive volume.

#### Describe the solution
The current recipe uses 12 planks which is 52.8L or 31.2kg to make 0.25L/0.25kg of methanol.  I've changed it to 2 planks which is 8.8L or 5.2kg to make 1L/1kg of methanol.  This is roughly 20% efficiency, which is lower than some of the other listed efficiencies reported by industrial processes.

#### Describe alternatives you've considered

#### Testing

#### Additional context

2022-10-04 03:16 UTC, Maleclypse commented
The method that article is referencing uses a catalytic reactor process similar to #58234.  The simple distillation method https://sciencing.com/make-wood-alcohol-through-distillation-7762993.html will have a much lower rate, probably closer to the industrial rates of the 1910's which seems to be just in the low single digits of methanol production.  http://journeytoforever.org/biofuel_library/wood_alcohol.html

2022-10-04 03:26 UTC, Maleclypse requested changes
So I went ahead and tried to match the math to the resources on the more low tech versions that this recipe represents.   The time and heat are probably low but I haven't really found any references on the time it takes to do this in any of my searches.   If you want to do an industrial scale one I would suggest looking at the recipe for kerosene to get an idea of the types of equipment and the like needed.

2022-10-04 03:26 UTC, Maleclypse commented on data/json/recipes/recipe_medsandchemicals.json
> +    "result_mult": 4,
```suggestion
```

2022-10-04 03:26 UTC, Maleclypse commented on data/json/recipes/recipe_medsandchemicals.json
> +    "components": [ [ [ "splinter", 40 ], [ "2x4", 2 ] ], [ [ "water", 3 ], [ "water_clean", 3 ] ] ]
```suggestion
    "components": [ [ [ "splinter", 55 ] ], [ [ "water", 50 ], [ "water_clean", 50 ] ] ]
```

2022-10-04 03:27 UTC, Maleclypse commented on data/json/recipes/recipe_medsandchemicals.json
> +    "components": [ [ [ "splinter", 40 ], [ "2x4", 2 ] ], [ [ "water", 3 ], [ "water_clean", 3 ] ] ]
I also removed all the planks as you can't use this method with wood that hasn't been broken down into pellet sizes.  And one hour doesn't get the wood broken down and processed into methanol from planks.

2022-10-04 19:20 UTC, Maleclypse approved these changes

2022-10-04 22:37 UTC, jim-huynh commented
> So I went ahead and tried to match the math to the resources on the more low tech versions that this recipe represents. The time and heat are probably low but I haven't really found any references on the time it takes to do this in any of my searches. If you want to do an industrial scale one I would suggest looking at the recipe for kerosene to get an idea of the types of equipment and the like needed.

Oh, there is something to point out regarding this change you did.  When you create a batch of 50 of this, would the resulting in progress item be >1000L causing it to disappear on placement on the workbench/ground?

2022-10-05 04:39 UTC, Maleclypse commented
> > So I went ahead and tried to match the math to the resources on the more low tech versions that this recipe represents. The time and heat are probably low but I haven't really found any references on the time it takes to do this in any of my searches. If you want to do an industrial scale one I would suggest looking at the recipe for kerosene to get an idea of the types of equipment and the like needed.
> 
> Oh, there is something to point out regarding this change you did. When you create a batch of 50 of this, would the resulting in progress item be >1000L causing it to disappear on placement on the workbench/ground?



> > So I went ahead and tried to match the math to the resources on the more low tech versions that this recipe represents. The time and heat are probably low but I haven't really found any references on the time it takes to do this in any of my searches. If you want to do an industrial scale one I would suggest looking at the recipe for kerosene to get an idea of the types of equipment and the like needed.
> 
> Oh, there is something to point out regarding this change you did. When you create a batch of 50 of this, would the resulting in progress item be >1000L causing it to disappear on placement on the workbench/ground?

It might go over but i don't actually think this recipe should get any batch savings.  You'd really have to design specialty equipment to achieve any time savings from reading over those articles.

2022-10-10 23:33 UTC, jim-huynh commented
> > > So I went ahead and tried to match the math to the resources on the more low tech versions that this recipe represents. The time and heat are probably low but I haven't really found any references on the time it takes to do this in any of my searches. If you want to do an industrial scale one I would suggest looking at the recipe for kerosene to get an idea of the types of equipment and the like needed.
> > 
> > 
> > Oh, there is something to point out regarding this change you did. When you create a batch of 50 of this, would the resulting in progress item be >1000L causing it to disappear on placement on the workbench/ground?
> 
> > > So I went ahead and tried to match the math to the resources on the more low tech versions that this recipe represents. The time and heat are probably low but I haven't really found any references on the time it takes to do this in any of my searches. If you want to do an industrial scale one I would suggest looking at the recipe for kerosene to get an idea of the types of equipment and the like needed.
> > 
> > 
> > Oh, there is something to point out regarding this change you did. When you create a batch of 50 of this, would the resulting in progress item be >1000L causing it to disappear on placement on the workbench/ground?
> 
> It might go over but i don't actually think this recipe should get any batch savings. You'd really have to design specialty equipment to achieve any time savings from reading over those articles.

This merge should probably just get cancelled then since one of the reasons for trying to merge it in was because the batch of 50 kept on disappearing on me when I attempted to craft it.

2022-11-28 05:06 UTC, merged