Nopenoperson mr73
CleverRaven/Cataclysm-DDA pull request #61564
Opened 2022-10-09 03:07 UTC by nopenoperson

#### Summary
Content "rare high end .357 revolver"

#### Purpose of change
the game has very six shooters so i wanted to add one

#### Describe the solution
did a bunch of research online and some calculations then put the stuff in 38.json. used .38 as a template for the nested ammo stuff.

#### Describe alternatives you've considered
making it more or less accurate. spending more time figuring out volume. asking for advice on item groups. not making this pr

#### Testing

#### Additional context

2022-10-09 03:26 UTC, TheShadowFerret commented on data/json/items/gun/38.json
> +    "name": { "str_sp": " Manurhin MR 73 " },
```suggestion
    "name": { "str_sp": "Manurhin MR 73" },
```

2022-10-09 04:07 UTC, tenmillimaster commented
Looks like the rarity is about right . I compared it to the raging bull in 454 and BFR in 45-70.

I suggest adding .38 special to the on hand, 357 mag ammo  item group.

I question the mod locations this has available, but that's a problem with most guns.

2022-10-09 04:16 UTC, nopenoperson commented
> I suggest adding .38 special to the on hand, 357 mag ammo item group.
you can type out out what you think it should be as suggestion if you feel like it

2022-10-20 06:59 UTC, tenmillimaster requested changes
Please review the mod location comments.

2022-10-20 06:59 UTC, tenmillimaster commented on data/json/items/gun/38.json
> +      [ "sights", 1 ],
This should be a sight mount if there's no rail.

2022-10-20 06:59 UTC, tenmillimaster commented on data/json/items/gun/38.json
> +      [ "rail", 1 ],
Same here, there's no side rail.

2022-10-20 06:59 UTC, tenmillimaster commented on data/json/items/gun/38.json
> +      [ "underbarrel", 1 ]
And definitely no underbarrel rail.

2022-10-20 11:49 UTC, tenmillimaster approved these changes
Looks good to me.

2022-10-21 01:11 UTC, merged