Chainmail fix
CleverRaven/Cataclysm-DDA pull request #61569
Opened 2022-10-09 16:01 UTC by Dan1ss1mo

#### Summary
Bugfixes "Chainmail fix"

#### Purpose of change
Curantly there is 2 problems with chainmail
1) chainmails suit and hauberk magicaly weights more than its component
2) Hauberk do not have chainmail leggings attached to them. Turning your chainmail into jumpsuit isn't reary a good idea because chain is not particulary elastic material 

#### Describe the solution
Adjust chainmails suit and hauberk weight and detach leggings from them

#### Describe alternatives you've considered
Also removing chainmails suit. Ability to combine differnt chain parts with other armor(like ballistic vests) is one of it advateges and combining it into a single item doesn't offer any benefits, only needlessly clutter crafting menu

#### Testing

#### Additional context

2022-10-11 20:26 UTC, Drew4484 commented on data/json/items/armor/suits_protection.json
> +        "covers": [ "torso", "arm_l", "arm_r" ],
Replace existing leg coverage with sublocation coverage for upper thighs and hips.

2022-10-11 20:28 UTC, Drew4484 commented on data/json/items/armor/suits_protection.json
>      "name": { "str": "low steel chainmail armor" },
```suggestion
    "name": { "str": "mild steel chainmail armor" },
```

2022-10-11 20:28 UTC, Drew4484 commented on data/json/items/armor/suits_protection.json
>      "description": "A fully customized low steel chainmail suit.  Combine with a gambeson or other padded layer for optimal protection.",
```suggestion
    "description": "A fully customized mild steel chainmail suit.  Combine with a gambeson or other padded layer for optimal protection.",
```

2022-10-11 20:32 UTC, Drew4484 commented on data/json/items/armor/suits_protection.json
>      "name": { "str": "low steel chainmail hauberk" },
```suggestion
    "name": { "str": "mild steel chainmail hauberk" },
```

2022-10-11 20:32 UTC, Drew4484 commented on data/json/items/armor/suits_protection.json
>      "description": "A fully customized low steel chainmail outfit, leaving the head uncovered.  Combine with a gambeson or other padded layer for optimal protection.",
```suggestion
    "description": "A fully customized mild steel chainmail outfit, leaving the head uncovered.  Combine with a gambeson or other padded layer for optimal protection.",
```

2022-10-11 20:33 UTC, Drew4484 commented
The hauberk should cover the subparts "leg_upper" and "leg_hip", as they typically extended to mid-thigh (see <https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/ARMOR_BALANCE_AND_DESIGN.md#explanation-3> for more information about covering sublocations). Please let me know if you need assistance with converting to detailed coverage.
The legs should remain on the chainmail suit, there are many examples of full-body chainmail and using the term **Suit** in game refers to something that generally covers the torso and limbs at a minimum. If you want to add variants of the hauberk that includes a hood but no sleeves, that should be a separate item with a distinct name ("Hooded hauberk"?) to avoid confusion.

2022-10-11 20:34 UTC, Drew4484 requested changes
The hauberk should cover the subparts "leg_upper" and "leg_hip", as they typically extended to mid-thigh (see <https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/ARMOR_BALANCE_AND_DESIGN.md#explanation-3> for more information about covering sublocations). Please let me know if you need assistance with converting to detailed coverage.

The legs should remain on the chainmail suit, there are many examples of full-body chainmail and using the term **Suit** in game refers to something that generally covers the torso and limbs at a minimum. If you want to add variants of the hauberk that includes a hood but no sleeves, that should be a separate item with a distinct name ("Hooded hauberk"?) to avoid confusion.

2022-10-11 21:09 UTC, Dan1ss1mo commented
> The hauberk should cover the subparts "leg_upper" and "leg_hip", as they typically extended to mid-thigh (see https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/ARMOR_BALANCE_AND_DESIGN.md#explanation-3 for more information about covering sublocations). Please let me know if you need assistance with converting to detailed coverage.
> 
> The legs should remain on the chainmail suit, there are many examples of full-body chainmail and using the term **Suit** in game refers to something that generally covers the torso and limbs at a minimum. If you want to add variants of the hauberk that includes a hood but no sleeves, that should be a separate item with a distinct name ("Hooded hauberk"?) to avoid confusion.

Yeah, i know that hauberk should also cover upper legs, but in that case it's recipe should be adjusted to reqire some extra chainmail sheets, also it would conflict with chainmail leggings. It wold also be nessesary to change protection of suit, to have higher thickness on upper legs and hips. In order to avoid all of that i think it would make sense to keep it a bit shorter than historical one, especially if it supposed to be part of full body suit(it seems that hauberks mostly worn on they own). Maybe there is also proper name for such variant but i am not sure. I will revert chainmail suit change though. Also, shouldn't weigh for chain gloves and chausses should be reduced? Currently they weight almost as much as sleeves. Recipe should also probably give some linceges back as byproduct, as you probably won't need 2 full sheets

2022-10-11 21:12 UTC, Dan1ss1mo commented
Maybe call it long sleeve Haubergeon

2022-10-11 21:47 UTC, Dan1ss1mo commented
It also seems that chain gloves wasn't fully made from chainmail. They commonly looks like leather gloves with chain coverege on outer side

2022-10-12 04:48 UTC, Drew4484 commented
> > The hauberk should cover the subparts "leg_upper" and "leg_hip", as they typically extended to mid-thigh (see https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/ARMOR_BALANCE_AND_DESIGN.md#explanation-3 for more information about covering sublocations). Please let me know if you need assistance with converting to detailed coverage.
> > 
> > The legs should remain on the chainmail suit, there are many examples of full-body chainmail and using the term **Suit** in game refers to something that generally covers the torso and limbs at a minimum. If you want to add variants of the hauberk that includes a hood but no sleeves, that should be a separate item with a distinct name ("Hooded hauberk"?) to avoid confusion.
> 
> Yeah, i know that hauberk should also cover upper legs, but in that case it's recipe should be adjusted to reqire some extra chainmail sheets, also it would conflict with chainmail leggings. It wold also be nessesary to change protection of suit, to have higher thickness on upper legs and hips. In order to avoid all of that i think it would make sense to keep it a bit shorter than historical one, especially if it supposed to be part of full body suit(it seems that hauberks mostly worn on they own). Maybe there is also proper name for such variant but i am not sure. I will revert chainmail suit change though. Also, shouldn't weigh for chain gloves and chausses should be reduced? Currently they weight almost as much as sleeves. Recipe should also probably give some links back as byproduct, as you probably won't need 2 full sheets.
> Edit: maybe also reduce weight for hauberk a bit as well? According to my research it weight 10 kg, but consider that in-game variant lack leg coverege it should be slightly lighter

We can actually use the layers added in #60862 to avoid conflict for the legs. Alternatively if the hauberk gets trimmed, let's add to the description indicating that it stops at the waist. I'm perfectly okay with updating designs as long as they remain practical. Chainmail is probably too heavy, I only updated the existing suit materials, so they could use an overall review.

2022-10-12 04:53 UTC, Drew4484 commented
> It also seems that chain gloves wasn't fully made from chainmail. They commonly looks like leather gloves with chain coverege on outer side

There's both but the full chain is usually PPE for working around sharp knives. Adding a version with leather and adjusting the encumbrance would be good. I don't think there's enough of a gameplay difference to worry about fully articulated gloves vs. mittens or half-mitten versions. While these are often integrated into a hauberk I suggest keeping them separate if you're adding a new version of the gloves.

2022-10-12 05:03 UTC, Dan1ss1mo commented
> > > The hauberk should cover the subparts "leg_upper" and "leg_hip", as they typically extended to mid-thigh (see https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/ARMOR_BALANCE_AND_DESIGN.md#explanation-3 for more information about covering sublocations). Please let me know if you need assistance with converting to detailed coverage.
> > > The legs should remain on the chainmail suit, there are many examples of full-body chainmail and using the term **Suit** in game refers to something that generally covers the torso and limbs at a minimum. If you want to add variants of the hauberk that includes a hood but no sleeves, that should be a separate item with a distinct name ("Hooded hauberk"?) to avoid confusion.
> > 
> > 
> > Yeah, i know that hauberk should also cover upper legs, but in that case it's recipe should be adjusted to reqire some extra chainmail sheets, also it would conflict with chainmail leggings. It wold also be nessesary to change protection of suit, to have higher thickness on upper legs and hips. In order to avoid all of that i think it would make sense to keep it a bit shorter than historical one, especially if it supposed to be part of full body suit(it seems that hauberks mostly worn on they own). Maybe there is also proper name for such variant but i am not sure. I will revert chainmail suit change though. Also, shouldn't weigh for chain gloves and chausses should be reduced? Currently they weight almost as much as sleeves. Recipe should also probably give some links back as byproduct, as you probably won't need 2 full sheets.
> > Edit: maybe also reduce weight for hauberk a bit as well? According to my research it weight 10 kg, but consider that in-game variant lack leg coverege it should be slightly lighter
> 
> We can actually use the layers added in #60862 to avoid conflict for the legs. Alternatively if the hauberk gets trimmed, let's add to the description indicating that it stops at the waist. I'm perfectly okay with updating designs as long as they remain practical. Chainmail is probably too heavy, I only updated the existing suit materials, so they could use an overall review.

Didn't know about this feature, that's cool! I will update protection for chain suits as well then. That's nice, considering that most leg guards don't cover hips.

2022-10-12 13:25 UTC, Dan1ss1mo commented
@Drew4484 what about only keeping suit recipe that reqire chain shirt\Haubergeon(still undesided about ulternative mame)

2022-10-12 16:52 UTC, Drew4484 commented
> @Drew4484 what about only keeping suit recipe that reqire chain shirt\Haubergeon(still undesided about alternative name)
> 

You can add as many combinations as you want, honestly. As long as they're clearly defined for players so they know what they're crafting. We can also have as many alternate recipes as are needed, as long as the result is the same you don't need to worry about menu bloat.

2022-10-12 19:51 UTC, Dan1ss1mo commented
> > @Drew4484 what about only keeping suit recipe that reqire chain shirt\Haubergeon(still undesided about alternative name)
> 
> You can add as many combinations as you want, honestly. As long as they're clearly defined for players so they know what they're crafting. We can also have as many alternate recipes as are needed, as long as the result is the same you don't need to worry about menu bloat.

well, i think that menu bloat is a realy big problem for new players. It is realy hard to navigate through it if you dont already know what you need

2022-10-16 09:49 UTC, Dan1ss1mo commented
@Drew4484 i also recalculate armor weight using approximated values from diagram that i show you, could you check if new values seems reasonable to you, please?

2022-10-16 10:37 UTC, Drew4484 commented
> @Drew4484 i also recalculate armor weight using approximated values from diagram that i show you, could you check if new values seems reasonable to you, please?
> Edit: would be glad if you also help me to figure out what cousing the error

Here's the error, will need to double check that the xs ch chainmail hauberk is listed correctly in the recipe below. I'll have to check the weight later on Sunday.

2022-10-16T10:19:54.0843077Z (~[slow] ~[.],starting_items)=> 10:19:23.036 ERROR : src/requirements.cpp:597 [void component::check_consistency(const std::string &) const] xs_ch_chainmail_hauberk in inline_recipe_ch_chainmail_suit_xs_hauberk is not a valid item template

2022-10-16 11:33 UTC, Dan1ss1mo commented
> > @Drew4484 i also recalculate armor weight using approximated values from diagram that i show you, could you check if new values seems reasonable to you, please?
> > Edit: would be glad if you also help me to figure out what cousing the error
> 
> Here's the error, will need to double check that the xs ch chainmail hauberk is listed correctly in the recipe below. I'll have to check the weight later on Sunday.
> 
> 2022-10-16T10:19:54.0843077Z (~[slow] ~[.],starting_items)=> 10:19:23.036 ERROR : src/requirements.cpp:597 [void component::check_consistency(const std::string &) const] xs_ch_chainmail_hauberk in inline_recipe_ch_chainmail_suit_xs_hauberk is not a valid item template

i don't know who the fuck has put xs at the end of hauberk and suit id, instead of at the beggining like with all other such items, but that was REALLY confusing. That was what one of the cause of the problem

2022-10-19 18:35 UTC, Drew4484 approved these changes

2022-10-19 22:06 UTC, merged