Add some more tabletop fluff
CleverRaven/Cataclysm-DDA pull request #61616
Opened 2022-10-11 18:37 UTC by GuardianDll

#### Summary
Content "Added more tabletop games, by u/MuscleAgile5442 aka @Cosmic"

#### Purpose of change

add some more board games into the game

#### Describe the solution

<details>
  <summary>added some tabletop games:</summary>

- Senet
- Mahjong
- Chaturanga Chess
- Backgammon
- Latrunculi
- Go
- Shogi
- Hnefatafl
- Alquerque
- Domino
- Jack Straws
- Snakes And Ladders
- Ludo
- Pop-Up Pirate
- Ambuscade! (aka Ambush)
- Patrol Leader (aka Ranger)
- War Tanks (aka Open Fire)
</details>
added them to existed loot groups
added oriental games to dojo
added Hnefatafl to Norse Evangelical trader (because that sounds fun)

#### Testing

Game works, loot spawns, i guess the density test will fail, because most of them are boxes with a lot of empty space

#### Additional context

All items were maded by @Cosmic#8484 aka u/MuscleAgile5442, i just polished it for a bit

2022-10-12 19:30 UTC, MNG-cataclysm requested changes
There are several errors caused by several items being denser than they should. I'd check the material entry which the board games use, and use the d = m/v equation to recalculate, either lowering the mass or increasing the volume.

(d = m/v is density = mass/volume)

2022-10-12 19:30 UTC, MNG-cataclysm commented on data/json/items/fluff.json
> +    "description": "Patrol Leader is a tactical solitaire board game.  Is this game, the player is put in the role of a patrol leader in different modern battlefield scenarios, performing missions, c
```suggestion
    "description": "Patrol Leader is a tactical solitaire board game.  Is this game, the player is put in the role of a patrol leader in different modern battlefield scenarios, performing missions, capturing or killing enemies, protecting its teammates and advancing in the map.  Very accurate and realistic, guaranteed fun if you like board games.",
```
Final spacing error to fix.

2022-10-12 22:20 UTC, MNG-cataclysm requested changes

2022-10-12 22:20 UTC, MNG-cataclysm commented on data/json/items/fluff.json
> +    "weight": "5530 g",
```suggestion
    "weight": "4000 g",
```
This was the last thing that gave a density error. Lowering the weight will fix this.

2022-10-13 06:05 UTC, GuardianDll commented on data/json/items/fluff.json
> +    "volume": "3033 L",
```suggestion
    "volume": "3033 ml",
```

2022-10-13 11:53 UTC, GuardianDll commented on data/json/items/fluff.json
> +    "weight": "2871 g",
```suggestion
    "weight": "2571 g",
```

2022-10-14 03:08 UTC, MNG-cataclysm commented
If you could, I'd recommend kicking the Ubuntu test. 
@Maleclypse If GuardianDll can't, could you restart the GCC 11 test, please?

2022-10-15 17:27 UTC, MNG-cataclysm approved these changes

2022-10-17 01:03 UTC, merged