Hub 01 intercom dialogue refinement, October edition
CleverRaven/Cataclysm-DDA pull request #61793
Opened 2022-10-19 00:55 UTC by Ilysen

#### Summary
Content "Touched up some of the intercom's dialogue"

#### Purpose of change

In the past PRs of touching up dialogue, I've written a buncha stuff about how standardization and good grammar benefits immersion and believability, and that's still the case here. ;P

#### Describe the solution

* Rewrote a bunch of the intercom's dialogue for grammar and tonal consistency. In general, they are less chummy and more clinical, and especially odd and suspicious when speaking about the Exodii.
* After the exotic barrel is researched, the Hub will start selling new 60-round box magazines for 12.3 ln, in addition to the current behavior of being able to slot in standard ones. Two of these are also provided with the conversion kit itself.
* Added more branching dialogue to a few topics, including the exotic barrel research (where the response is different if you've already met with Rubik) and the HWP requisition.
* You can now provide a PS md. 71z and its magazine to the intercom, instead of a PA md. 68 and its magazine. The old option is still there; now you can just use either rifle if you don't have access to the other.

#### Describe alternatives you've considered

Nothing major, but I've thought significantly of how to tackle the way dialogue is handled right now. There's no kind of standardization of dialogue and variable IDs and formatting, and I'm really not sure what the most elegant way to handle it is. Progress continues.

#### Testing

Talked a whole bunch with the intercom, using quicksaves and quickloads to go through dialogue at certain points. I made sure that all the new dialogue looked okay and I thiiink I got the typos out.

#### Additional context

![cataclysm-tiles_GgTupDHjpt](https://user-images.githubusercontent.com/47678781/196572201-26deb4f2-520a-460d-a38c-f9ffb2ad40c9.png)
![cataclysm-tiles_8xUWyD3lL7](https://user-images.githubusercontent.com/47678781/196572223-519c2562-efe2-415e-9da1-a6d0dcb3a535.png)

2022-10-19 04:07 UTC, andrei8l commented on data/json/npcs/robofac/robofac_intercom/robofac_intercom_prototypes.json
> +          { "u_consume_item": "exodiiBRmag", "count": 1, "popup": true },
```suggestion
          { "u_consume_item": "pamd71z", "count": 1, "popup": true },
          { "u_consume_item": "exodiiminimag", "count": 1, "popup": true },
```

2022-10-19 13:11 UTC, MNG-cataclysm requested changes

2022-10-19 13:11 UTC, MNG-cataclysm commented on data/json/npcs/robofac/robofac_intercom/robofac_intercom_prototypes.json
> +    "dynamic_line": "As before, each Platform is made to order. This is a slow process for several reasons.  First, the parts must be printed to spec; this takes a great degree of precision, and so t
```suggestion
    "dynamic_line": "As before, each Platform is made to order.  This is a slow process for several reasons.  First, the parts must be printed to spec; this takes a great degree of precision, and so the process is lengthy.  The remainder of the week is spent running reliability tests as each conversion kit finishes production.  I understand that it isn't an ideal option, but I believe the quality of the product is worth that investment."
```

2022-10-19 13:11 UTC, MNG-cataclysm commented on data/json/npcs/robofac/robofac_intercom/robofac_intercom_prototypes.json
> +    "dynamic_line": "As before, each Platform is made to order. This is a slow process for several reasons.  First, the parts must be printed to spec; this takes a great degree of precision, and so t
Spacing fix

2022-10-19 21:16 UTC, John-Candlebury commented on data/json/items/gun/robofac_gun.json
> +    "id": "robofac60_123ln",
You need to add a migration for this one to the generic guns mod. Should be good for merging after that

2022-10-19 21:29 UTC, Ilysen commented
generic guns migration put in. I'm not in a place where I can test right now (only have my laptop, which needs a recompile; my usual machine is occupied) so you can try it yourself or I can give it a go in a few hours

2022-10-20 02:32 UTC, MNG-cataclysm approved these changes

2022-10-20 14:38 UTC, bombasticSlacks approved these changes
Looks good to me but I haven't tested in game

2022-10-24 18:34 UTC, merged