More gun variants, part the second
CleverRaven/Cataclysm-DDA pull request #61893
Opened 2022-10-24 09:45 UTC by DoctorBoomstick

#### Summary
None

#### Purpose of change
Continues work started in PR #61598, flushing out the current in game guns which make use of the variants system.

#### Describe the solution
I’ve worked through some of the more commonly encountered and simpler in game 9x19mm guns and added variants for them. In no particular order, the guns I have modified are
1.	The Calico M960.
2.	The Berretta M9A1 and Berretta 90-two.
3.	The Cx4 Storm.
4.	 The Glock 17.
5.	The Glock 18C.
6.	The Glock 19.
7.	The M17.
8.	The M18.
In doing so, I have also added variants for the three compatible M17 and M18 magazines, whilst also merging the Berretta M9A1 and 90-two under a single variant due to their similar stats.
Apart for these changes, I have also revised the variant shotgun names I created in PR #57140, taking into account suggestions and advice gained from a lengthy discussion in the discord chat. As a miner aside, I have also altered some of the grammar used in the variant descriptions, with the goal of making them more readable and cutting down on giant, never ending sentences.

#### Describe alternatives you've considered
I considered finishing work on adding variants to all the 9x19mm guns before putting out this PR, but decided against it as I was feeling the impending doom of burn out on the horizon. Regardless, I also wanted to put the additions out for inspection.

#### Testing
I haven’t tested these changes yet, due to personal time constraints, but there doesn’t seem to be any syntax issues that the lint tool has thrown a fit on, and most of the changes are simply miner text edits regardless.

#### Additional context
consult PR #61598 for the first part of this expansion to the existing gun variants.

2022-11-03 07:03 UTC, GuardianDll approved these changes
Good job!

2022-11-04 20:31 UTC, anothersimulacrum approved these changes
Just need the migration, then this looks great!

Merged guns:
| id | weight | volume | length | ammotype | modes | magazines | dispersion | recoil | damage | 
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | 
| 90two | 921 | 554 | 250 | 9mm | 1 | ['m9mag', 'm9mag_10rd', 'm9mag_17rd', 'm9mag_18rd', 'm9mag_20rd', 'm9bigmag', 'm9mag_32rd', 'm9mag_35rd'] | 480 | 0 | 0 | 
| m9 | 961 | 570 | 249 | 9mm | 1 | ['m9mag', 'm9mag_10rd', 'm9mag_17rd', 'm9mag_18rd', 'm9mag_20rd', 'm9bigmag', 'm9mag_32rd', 'm9mag_35rd'] | 480 | 0 | 0 |

2022-11-04 20:31 UTC, anothersimulacrum commented on data/json/items/gun/9mm.json
> -    "id": "90two",
This needs a migration, see https://github.com/CleverRaven/Cataclysm-DDA/blob/a2e692099ce1d4f3c21354977b2d02e66c315fa8/data/json/items/migration.json#L1156-L1161 for an example.

2022-11-04 23:11 UTC, TheShadowFerret requested changes

2022-11-04 23:11 UTC, TheShadowFerret commented on data/json/items/gun/9mm.json
> +        "description": "A selective fire variation on the Glock 17, originally designed for Austria's EKO Cobra unit.  It has compensator cuts along its barrel to make recoil more manageable.",
```suggestion
        "description": "A selective-fire variation on the Glock 17, originally designed for Austria's EKO Cobra unit.  It has compensator cuts along its barrel to make recoil more manageable.",
```

2022-11-04 23:11 UTC, TheShadowFerret commented on data/json/items/gun/9mm.json
> +    "description": "The general issue military handgun of the United States army before the Cataclysm, this is a sizable pistol that fires 9x19mm cartridges.  Based off successful civilian designs an
```suggestion
    "description": "The general-issue military handgun of the United States army before the Cataclysm, this is a sizable pistol that fires 9x19mm cartridges.  Based off successful civilian designs and capable of taking magazines of various round capacities, the gun features a plastic polymer frame which helps to reduce overall weight.",
```

2022-11-04 23:11 UTC, TheShadowFerret commented on data/json/items/gun/9mm.json
> +        "description": "The M17 is a semi-automatic, short recoil operated pistol derived from the SIG Sauer P320.",
I would have kept the military usage in this variant desc., like what you put for the M18.

2022-11-04 23:11 UTC, TheShadowFerret commented on data/json/items/gun/9mm.json
> +    "description": "A more petite version of the United States army’s general issue sidearm, this is a modestly sized pistol firing 9x19mm rounds.  Making use of the same magazines as its larger brot
```suggestion
    "name": { "str": "compact service handgun" },
    "description": "A more petite version of the United States army’s general issue sidearm, this is a modestly-sized pistol firing 9x19mm rounds.  Making use of the same magazines as its larger brother, the weapon features a shorter barrel and frame which helps to reduce its overall profile and make it more concealable as a result.",
```

2022-11-04 23:11 UTC, TheShadowFerret commented on data/json/items/gun/shot.json
> +    "//": "Not exactly a combat shotgun, but I was hard-pressed to think of a name which wasn’t just, “6-round shotgun.” in its proper descriptions its referenced as often being used by militaries, t
```suggestion
    "//": "Not exactly a combat shotgun, but I was hard-pressed to think of a name which wasn’t just, “6-round shotgun.” In its proper descriptions it's referenced as often being used by militaries, therefore I’m calling this a combat shotgun.",
```

2022-11-04 23:11 UTC, TheShadowFerret commented on data/json/items/gun/shot.json
> +    "description": "A military oriented spin on the classic pump-action shotgun recipe, this firearm features an extended magazine tube capable of fielding 9 rounds of 12 gauge shotshells.  Sporting
```suggestion
    "description": "A military oriented spin on the classic pump-action shotgun recipe, this firearm features an extended magazine tube capable of fielding nine rounds of 12 gauge shotshells.  Sporting a heavier barrel and a bayonet lug, it makes for a highly intimidating weapon, as well as a satisfying answer to most of the nasties you're liable to find in the post-apocalypse.",
```

2022-11-04 23:11 UTC, TheShadowFerret commented on data/json/items/gun/shot.json
> +    "description": "Looking more like some form of sci-fi prop gun than an actual firearm, this weapon uses a system of triple magazines to field 15 12-gauge shotgun shells within a comparatively com
"Triple magazine" says "one conjoined object made of three individual magazines" to me

2022-11-05 01:38 UTC, DoctorBoomstick commented on data/json/items/gun/9mm.json
> +        "description": "The Calico M960 is an automatic carbine with a unique circular magazine that allows for high capacities and reduced recoil.",
Would it be best if I took a buzzsaw to the variant descriptions and trimmed off a few sentences to make them more compact, or would switching them and the regular descriptions be a better answer? I don’t want to tread on anyone’s toes here, but I also do like me my bloated, overcooked and pointlessly rambling descriptions.

2022-11-05 18:04 UTC, TheShadowFerret approved these changes

2022-11-14 04:38 UTC, merged