Xedra new spell Heal Fatigue
CleverRaven/Cataclysm-DDA pull request #61913
Opened 2022-10-25 06:31 UTC by KymasTuran

#### Summary
Content "New spell Heal Fatigue"

#### Purpose of change
I think its a "must have"

#### Describe the solution
Just a new spell, a bit harder to find, as a long casting cost.

#### Describe alternatives you've considered
A potion or dream coffee. Or a dream coffee maker that consume dreams to make supercoffee.

#### Testing
Find or spawn the spell, study it, cast. Not for combat.

#### Additional context
Perhaps spells learned in dreams, and/or wake up after a nightmare summon a shadow. This mod as many possibilities.

2022-10-25 06:38 UTC, KymasTuran commented
There is an extra file that I cant remove. 
This site as a nasty learning curve.

2022-10-25 07:33 UTC, GuardianDll requested changes
Nope, that's a bad pr, it removes few bugfixes and edit things in aftershock (the spell itself is good, you just need to add an artifact into a loot group). Try again. If you have problems with github, welcome to our discord, i kindly guide you how to do it properly.

2022-10-25 15:23 UTC, Maleclypse commented
Oh I do like this.  I hope you can get the github part fixed, I still have a number of PRs I need to finish.

2022-10-25 21:18 UTC, MNG-cataclysm requested changes

2022-10-25 21:18 UTC, MNG-cataclysm commented on data/mods/Xedra_Evolved/items/spell_learning_items/spell_learning_items_eater.json
> +    "description": "A small jar with coffee, it is moving in weird patterns even without being touch. After watching the movement of the dark liquid for some time you are sure that repeat a certain p
```suggestion
    "description": "A small jar with coffee, moving in weird patterns with no apparent cause.  After watching the swirls for some time you are sure that it loops back on it's movements, like some sort of message.",
```

2022-10-26 00:41 UTC, KymasTuran commented
> Nope, that's a bad pr, it removes few bugfixes and edit things in aftershock (the spell itself is good, you just need to add an artifact into a loot group). Try again. If you have problems with github, welcome to our discord, i kindly guide you how to do it properly.

The Aftershock one are not supposed to be here. 
Thank you for your kind offer.

2022-10-26 01:14 UTC, closed without merging