Added millwall brick
CleverRaven/Cataclysm-DDA pull request #62025
Opened 2022-10-30 21:50 UTC by bean-b

#### Summary
Content "Added millwall Brick"

#### Purpose of change
Wanted to add this item as a weak early game improvised weapon.

#### Describe the solution

Added the millwall brick, a improvised weapon only obtained through crafting (autolearned at level 0)

#### Describe alternatives you've considered

I'm not sure if this is acceptable as newspapers only represent singular sheets in this game, but there doesn't seem to be any item that represents a full newspaper so i figured it would be okay considering a millwall brick only needs a few sheets of newspaper? Alternatives of course include not adding this item, allowing it to be crafted with paper/newspapers etc.. Other versions of the millwall brick have a rock or a coins as added weights, but I figured I would go with the simplest version since this item is crafted out of convenience not power. I wasn't sure if it should have the plastic material tag, but with only paper it would break in about three hits, and while it shouldn't be durable, it was breaking way to quick without it. 

#### Testing

#### Additional context
Research:
https://en.wikipedia.org/wiki/Millwall_brick
https://www.youtube.com/watch?v=y7dL2U7Ub2I

2022-10-30 22:22 UTC, TheShadowFerret commented on data/json/items/melee/bludgeons.json
> +    "name": { "str": "millwall brick" },
```suggestion
    "name": { "str": "Millwall brick" },
```
Millwall refers to Millwall Football Club, so it could be capitalized.

2022-10-30 22:25 UTC, TheShadowFerret commented on data/json/items/melee/bludgeons.json
> +    "to_hit": { "grip": "solid", "length": "short", "surface": "any", "balance": "neutral" }
```suggestion
    "to_hit": { "grip": "none", "length": "hand", "surface": "any", "balance": "neutral" }
```

2022-10-30 22:31 UTC, TheShadowFerret commented on data/json/items/melee/bludgeons.json
> +    "description": "An improvised club, made of a tightly rolled newspaper, folded with lengthwise and duct-taped. It packs a surprising punch for what is essentially paper.",
```suggestion
    "description": "An improvised club, made of a tightly rolled newspaper, folded lengthwise and duct-taped. It packs a surprising punch for what is essentially paper.",
```

2022-10-31 07:14 UTC, RAldrich commented
I watched the video you linked, but 10 bashing for a bit of rolled up newspaper and tape? I just don't buy it - that's the same damage as a wooden club.

2022-10-31 12:56 UTC, MNG-cataclysm requested changes

2022-10-31 12:56 UTC, MNG-cataclysm commented on data/json/items/melee/bludgeons.json
> +    "bashing": 10,
```suggestion
    "bashing": 3,
```
This should be more reasonable for rolled-up newspaper.

2022-10-31 14:11 UTC, NetSysFire commented
The reason they pack a punch is because they are usually filled with hard objects, like spare change. I think pebbles would work, too since there is no one searching you for weapons and they should be the right size.

2022-10-31 15:19 UTC, bean-b commented
I think modifying the recipe to require some weights, i.e. pebbles makes sense. In that case what would be a reasonable damage? I realize 10 was defintly too high for just the paper version, but would like 7 be good for the paper + pebble version?

2022-10-31 18:11 UTC, bean-b commented
Ok i changed the stats up to reflect the changes, I did end up changing the length back to short, because although the first google image result of them is very short, many are longer, i.e. 
https://www.reddit.com/r/weapons/comments/avuphz/made_a_millwall_brick_a_week_or_so_ago_its/

But can ofc change it back to hand to if that seems like it would be better

2022-11-03 18:41 UTC, closed without merging