More gun variants, part the third.
CleverRaven/Cataclysm-DDA pull request #62074
Opened 2022-11-04 08:43 UTC by DoctorBoomstick

#### Summary
None

#### Purpose of change
Continues work started in #61598 and #61893, carrying on the inexorable march towards extending the variants system across more firearms which currently lack a more generic variation.

#### Describe the solution
I’ve created variants for all the weapons in .22 calibre, 7.62x25mm, 9x18mm, and 5.7x28mm. I’ve also slightly adjusted the existing variants present across the 5.7mm guns (the FN P90, Kel-Teck P50, and FN PS90), to make the names more compact and the descriptions less wordy. In doing these changes, many of the magazines have also been given appropriate variants were applicable.

#### Describe alternatives you've considered
No real alternatives to speak of, save for perhaps finding ways to cut down on the number of magazine variants.

#### Testing
Due to time constraints, I haven’t tested these changes. That being said, the lint tool clears them with no syntax errors, and most of the work involved writing text descriptions and punching my control c and control v keys, many, many times. Providing that I didn’t overlook anything before submitting this PR, the changes should work just fine.

#### Additional context
Consult #61598 and #61893 for the first two parts to this expansion of the existing gun variants.

2022-11-04 13:16 UTC, MNG-cataclysm approved these changes

2022-11-04 20:32 UTC, anothersimulacrum approved these changes

2022-11-04 22:37 UTC, TheShadowFerret requested changes
~~Who dares bring British spellings to my American apocalypse~~

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/gun/22.json
> +    "description": "a lightweight and modular pistol calibre hunting carbine, firing the low power .22 LR cartridge.  Before the Cataclysm, a mix of high customizability, cheep ammunition, and low re
```suggestion
    "description": "A lightweight and modular pistol caliber hunting carbine, firing the low power .22 LR cartridge.  Before the Cataclysm, a mix of high customizability, cheep ammunition, and low recoil made this a very popular varmint rifle amongst civilian shooters.",
```

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/gun/22.json
> +    "description": "a compact, .22 calibre semi-automatic pistol.  Built from aluminum and polymer componence, the weapon is light weight and concealable.  Unfortunately, much like its namesake, this
```suggestion
    "description": "a compact, .22 caliber semi-automatic pistol.  Built from aluminum and polymer componence, the weapon is lightweight and concealable.  Unfortunately, much like its namesake, this pistol mostly poses a mild annoyance to most hostiles that the Cataclysm is liable to direct into your path.",
```

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/gun/22.json
> +    "description": "Made from only the cheapest of budget metals, firing one of the weakest cartridges, and having a hearty laugh at the concept of user safety, this .22 calibre pocket pistol is of q
```suggestion
    "name": { "str": "cheap .22 caliber pistol" },
    "description": "Made from only the cheapest of budget metals, firing one of the weakest cartridges, and having a hearty laugh at the concept of user safety, this .22 caliber pocket pistol is of questionable utility at best.  Affordably priced before the Cataclysm, the pistol’s price point was arguably its only positive element, an element which pertains zero bearing on your current situation.",
```

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/gun/57.json
> +    "description": "Firing the armour-piercing 5.7x28mm round, this light-weight handgun was developed for NATO use as a sidearm capable of penetrating body armour.  Its proprietary and nonprolific a
```suggestion
    "description": "Firing the armor-piercing 5.7x28mm round, this lightweight handgun was developed for NATO use as a sidearm capable of penetrating body armor.  Its proprietary and nonprolific ammunition kept it comparatively rare amongst both civilian and militant use, but the gun’s ability to ignore most forms of conventional ballistic armor can’t be argued with.  Given that its tiny bullets have next to no stopping power, its armor-penetrating capability comes at a considerable trade-off.",
```

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/gun/57.json
> +    "description": "A late 90s manufactured personal defence weapon (PDW), this automatic firearm fires the high-velocity and proprietary 5.7x28mm cartridge.  Making use of top-mounted 50-round custo
```suggestion
    "description": "A late 90s manufactured personal defense weapon (PDW), this automatic firearm fires the high-velocity, proprietary 5.7x28mm cartridge.  Making use of top-mounted 50-round custom magazines which lock into the receiver of the weapon behind the grip, this little submachine gun packs quite the nasty payload.  Its small, high-speed caliber makes it excellent at both defeating armored opponents and firing short bursts manageably.",
```

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/gun/57.json
> +        "description": "The first in a new genre of guns, termed \"personal defence weapons.\"  FN designed the P90 to use their proprietary high-velocity 5.7x28mm ammunition.  Made to fulfill NATO r
```suggestion
        "description": "The first in a new genre of guns, termed \"personal defense weapons.\"  FN designed the P90 to use their proprietary high-velocity 5.7x28mm ammunition.  Made to fulfill NATO requests for a weapon chambered in a more suitable cartridge for defeating body armor than standard 9x19mm submachine guns, the FN P90 is excellent at firing short and controllable bursts manageably.  The PDW’s small and high-speed 5.7mm ammunition, of which 50 rounds fit in the P90’s top mounted magazine, packs quite the lethal payload for any armored opponent, whilst the firearm’s bullpup design makes it commendably compact to boot.",
```

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/gun/57.json
> +    "description": "Produced by the Ruger gun company, this full-sized pistol makes use of the 5.7x28mm cartridge.  one of the first pistols to both make use of the unusual round and achieve market s
```suggestion
    "description": "Produced by the Ruger gun company, this full-sized pistol makes use of the 5.7x28mm cartridge.  One of the first pistols to both make use of the unusual round and achieve market success within the civilian world, it opened the door for accessible 5.7mm shooting due to its low price and reliable design.",
```

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/gun/762x25.json
> +    "description": "A bulky and simple Second World War submachine gun of Russian manufacture, composed from a basic wooden buttstock, steel barrel shroud, and the hopes and prayers of soviet soldier
```suggestion
    "description": "A bulky and simple Second World War submachine gun of Russian manufacture, composed from a basic wooden buttstock, steel barrel shroud, and the hopes and prayers of Soviet soldiers under threat of German invasion.  Designed for mass production with limited materials, the weapon is notable for its high-capacity drum magazines, capability of rapidly depleting said magazines, and vicious 7.62x25mm chambering.",
```

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/gun/762x25.json
> +        "description": "The Soviet-made PPSh-41 is a mass-produced selective-fire submachine gun.  It has a relatively high rate of fire.",
Why is the non-generic description less detailed than the generic one 🤔

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/gun/9x18.json
> +    "description": "A svelte, Cold War era handgun of Russian heritage, this former military pistol fires the Soviet 9x18mm cartridge.  Constructed completely out of steel components and experiencing
```suggestion
    "description": "A svelte, Cold War era handgun of Russian heritage, this former military pistol fires the Soviet 9x18mm cartridge.  Constructed completely out of steel components and experiencing relative popularity throughout eastern European countries, it was a favored backup weapon amongst USSR security forces, soldiers, and covert units.",
```

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/gun/9x18.json
> +        "description": "The Pistolet Makarova was developed by the Soviet Union to replace the WWII-era TT-33 pistol.  It uses the 9x18mm cartridge, which remains in use among various former Soviet c
This description is also more brief than the generic version 🤔

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/gun/9x18.json
> +    "description": "A compact submachine gun hailing from Czechoslovakia during the Cold War, featuring a suppressively high rate of automatic fire and shooting the soviet 9x18mm round.",
```suggestion
    "description": "A compact submachine gun hailing from Czechoslovakia during the Cold War, featuring a suppressively high rate of automatic fire and shooting the Soviet 9x18mm round.",
```

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/magazine/22.json
> +    "description": "an unusually shaped pan magazine for use with .22 calibre submachine guns.",
```suggestion
    "description": "An unusually-shaped pan magazine for use with .22 caliber submachine guns.",
```

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/magazine/22.json
> +        "description": "An unusually shaped pan magazine for the American-180.",
```suggestion
        "description": "An unusually-shaped pan magazine for the American-180.",
```

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/magazine/22.json
> +    "description": "an unusually shaped polymer constructed pan magazine for use with .22 calibre submachine guns.",
```suggestion
    "description": "An unusually-shaped polymer constructed pan magazine for use with .22 caliber submachine guns.",
```

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/magazine/22.json
> +        "description": "An unusually shaped pan magazine for the American-180, made of polymer.",
```suggestion
        "description": "An unusually-shaped, polymer pan magazine for the American-180.",
```

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/magazine/22.json
> +    "description": "an unusually shaped pan magazine for use with .22 calibre submachine guns.",
```suggestion
    "description": "An unusually-shaped pan magazine for use with .22 caliber submachine guns.",
```

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/magazine/22.json
> +        "description": "An unusually shaped pan magazine for the American-180",
```suggestion
        "description": "An unusually-shaped pan magazine for the American-180.",
```

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/magazine/22.json
> +    "description": "an unusually shaped polymer constructed pan magazine for use with .22 calibre submachine guns.",
```suggestion
    "description": "An unusually-shaped polymer pan magazine for use with .22 caliber submachine guns.",
```

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/magazine/22.json
> +        "description": "An unusually shaped pan magazine for the American-180, made of polymer.",
```suggestion
        "description": "An unusually-shaped polymer pan magazine for the American-180.",
```

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/magazine/22.json
> +        "description": "An unusually shaped pan magazine for the American-180, made of polymer.",
```suggestion
        "description": "An unusually-shaped polymer pan magazine for the American-180.",
```

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/magazine/22.json
> +    "description": "an unusually shaped polymer constructed pan magazine for use with .22 calibre submachine guns.",
```suggestion
    "description": "An unusually-shaped polymer pan magazine for use with .22 caliber submachine guns.",
```

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/magazine/22.json
> +    "description": "An extended capacity 25-round magazine, for use with .22 calibre varmint rifles.",
```suggestion
    "description": "An extended capacity 25-round magazine, for use with .22 caliber varmint rifles.",
```

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/magazine/22.json
> +    "description": "A flush fitting 10-round rotary magazine, for use with .22 calibre varmint rifles.",
```suggestion
    "description": "A flush fitting 10-round rotary magazine, for use with .22 caliber varmint rifles.",
```

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/magazine/22.json
> +    "description": "A 10-round handgun magazine for use with Smith and Wesson’s .22 calibre pocket pistol.",
```suggestion
    "description": "A 10-round handgun magazine for use with Smith and Wesson’s .22 caliber pocket pistol.",
```

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/magazine/22.json
> +    "description": "A cheaply built, low quality 6-round magazine, for use in only the most ineffectual of .22 calibre pocket pistols.",
```suggestion
    "description": "A cheaply built, low quality 6-round magazine, for use in only the most ineffectual of .22 caliber pocket pistols.",
```

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/magazine/22.json
> +    "description": "A 10-round handgun magazine for use with Walther's .22 calibre pocket pistol.",
```suggestion
    "description": "A 10-round handgun magazine for use with Walther's .22 caliber pocket pistol.",
```

2022-11-04 22:37 UTC, TheShadowFerret commented on data/json/items/magazine/57.json
> +        "description": "A standard capacity magazine for use with the FN Five-seveN.",
```suggestion
        "description": "A standard-capacity magazine for use with the FN Five-seveN.",
```
Many New England states would consider this legally highcap(FN makes a ten rounder for those states). It is standard for the firearm tho

2022-11-06 00:16 UTC, nopenoperson commented
i read the first pr and i dont really understand the problem that this is trying to fix.  also the variant system makes sense for t shirts, not for mosin nagants made 100 years apart with wildly different materials and qa standards.  functionally different guns should have functionally different stats!

2022-11-06 04:21 UTC, TheShadowFerret requested changes

2022-11-06 04:21 UTC, TheShadowFerret commented on data/json/items/gun/22.json
> +    "name": { "str": ".22 calibre submachine gun" },
```suggestion
    "name": { "str": ".22 caliber submachine gun" },
```

2022-11-06 04:21 UTC, TheShadowFerret commented on data/json/items/gun/22.json
> +    "description": "A venerable .22 calibre lever-action rifle, with a 19-round tube magazine and a classic design that dates back over a century.  Generally used for the hunting of small game like r
```suggestion
    "description": "A venerable .22 caliber lever-action rifle, with a 19-round tube magazine and a classic design that dates back over a century.  Generally used for the hunting of small game like rabbits, the strict taxonomic classification of zombies as 'small game' is debatable, but this decades-old weapon can still be counted upon to help manage the undead population.",
```

2022-11-06 04:21 UTC, TheShadowFerret commented on data/json/items/gun/22.json
> +    "description": "a compact, .22 caliber semi-automatic pistol.  Built from aluminum and polymer componence, the weapon is lightweight and concealable.  Unfortunately, much like its namesake, this
```suggestion
    "description": "A compact, .22 caliber semi-automatic pistol.  Built from aluminum and polymer componence, the weapon is lightweight and concealable.  Unfortunately, much like its namesake, this pistol mostly poses a mild annoyance to most hostiles that the Cataclysm is liable to direct into your path.",
```

2022-11-06 05:34 UTC, DoctorBoomstick commented
@nopenoperson, I’m not the one who implemented gun variants from the onset, so I might get the reasoning wrong and/ or fuck up the intended point. As such, I’d advise consulting Pr #46814 for further information about the system. That being said, as far as I understand, gun variants are aimed at cutting down on the gigantic number of similar, near-identical, functionally the same guns we currently have in the game. For some folks, coming across five different types of assault rifles that are basically the same save in name and description can be overwhelming, especially if they’re not versed in some basic gun terminology. The system can be toggled on to simplify matters for non-gun people who do not want to deal with many different types of practically the same gun, and/ or who don’t understand the weapon gun nut talk present in some of the descriptions and name. on the other hand, if you enjoy rolling around in heaps of different guns Scrooge Mick Duck style, you can just leave it off and have your armoury’s Werth of different guns.
Why do variants make sense for t-shirts? Simply cause all it’s doing is changing around descriptors, an inconsequential element. Why does gun variants make sense for guns? Simply because it sometimes takes near-identical weapons gameplay wise, like the M9 and 90two, were the only real differences are a name, description, and a few teeny tiny grams of weight and ML of volume, and puts them together under one name. again, if you don’t like this, you can just turn it off. For types of variants like the ones added in this PR, you do not even have any merging going on. It literally just makes the names and descriptions simpler, easier to understand, and holds the player’s hand a little if they don’t know what some gun terminologies are meant to mean.

2023-04-16 16:21 UTC, bombasticSlacks commented
This looks good to me, could you add the barrel lengths to the guns? #64961 gives an example.

2023-04-16 16:24 UTC, merged