Added airsoft gear, updated paintball field itemgroups
CleverRaven/Cataclysm-DDA pull request #62125
Opened 2022-11-07 20:26 UTC by bean-b

#### Summary
Content "Added airsoft gear, updated paintball field itemgroups"

#### Purpose of change
The current paintball field only spawned paintballs, paintball guns and swim goggles. Swim goggles didint make much sense in terms of protective paint ball gear, and I figured the modular headgear system would be perfect, as plastic face shield, plastic mandible protector etc. would be perfect for this.

#### Describe the solution
A fancy miltiary headgear didint make much sense, so I added an airsoft headgear, which is a plastic headgear that has military rail mounting capabilities. I also added airsoft gloves. I also changed the spawn groups of the paintball field to spawn more protective gear, hopefully making it a bit more intersting to loot. 

Also made the balistic/plastic mandible protectors just a little less encumbering, because mouth encumbrance is really rough, and they didn't seem like they needed to be that high, especialy since they dont have great protection values

#### Describe alternatives you've considered

It's a little strange to see all the airsoft gear in the paintball arena, but it makes more sense then seeing swim goggles. 
There are more airsoft/paintball gear that could be added, such as steel mandible protector etc.
I think it would be cool to have a seperate airsoft arena, but that seemed out of the scope of this pr

#### Testing
Opened the items in game, teleported to a paintball arena, and checked the spawns

#### Additional context
gloves : https://www.etsy.com/listing/974154578/tactical-hard-knuckle-half-finger-gloves
helmet without attachments : https://www.evike.com/products/38914/%5D
helmet with attachemnts: https://toptacticalgear.com/products/anti-fog-airsoft-full-face-mask-helmet

2022-11-07 22:31 UTC, MNG-cataclysm requested changes

2022-11-07 22:31 UTC, MNG-cataclysm commented on data/json/itemgroups/Locations_MapExtras/locations_commercial.json
> +    "id": "paintball_cloths",
```suggestion
    "id": "paintball_clothes",
```
"Cloths" seems like an out-of-place name, at least to me.

2022-11-07 22:31 UTC, MNG-cataclysm commented on data/json/itemgroups/Locations_MapExtras/locations_commercial.json
> +          { "group": "paintball_cloths", "prob": 30 }
```suggestion
          { "group": "paintball_clothes", "prob": 30 }
```

2022-11-09 19:09 UTC, MNG-cataclysm approved these changes

2022-11-24 18:44 UTC, I-am-Erk commented
because of the 'fluff' nature of this I think I'll put in freeze for now.

2023-03-02 12:54 UTC, Fris0uman commented on data/json/items/armor/head_attachments.json
> +    "armor": [ { "encumbrance": 10, "coverage": 100, "covers": [ "mouth" ] } ]
Not sure it needs to be less encumbering *and* more protective. This feels out of place for this PR, if you want to rebalance this gear you should probably do it in a different PR dedicated to this. Same for the two other similar buffs

2023-03-04 12:54 UTC, merged