Create the polesaw.
CleverRaven/Cataclysm-DDA pull request #62217
Opened 2022-11-14 15:58 UTC by Bluarianknight

#### Summary
Content "Adds Polesaws to the game."

#### Purpose of change

Pure content addition - adding a polesaw to the game.

Done due to popular interest for such a tool on reddit, and as a first attempt to adding content to CDDA as a whole for the coder.

#### Describe the solution

Adds polesaws to the game, a reach-based chainsaw with somewhat less damage but increased range. Spawns in similar spots as chainsaws, but slightly less or equal.

#### Testing

Tested the weapon itself, spawn rates, and crafting - it spawns in the world in the appropiate spots, it can be crafted, and it's damage is equal to it's contemporaries. 

#### Additional context

2022-11-14 18:28 UTC, Daved27hundred commented
Are you sure it'd do 60 damage while on? I have never seen one of these tools being used but I imagine the blade is way smaller than the blade of a full on chainsaw, due to being used to cut through branches rather than trunks as well as for ease of use.

2022-11-14 18:51 UTC, Bluarianknight commented
> 

I did some testing - I kept it at 60 for two reasons.

1. Even with a decrease to 40, it becomes incredibly weak - it's just too big and clunky. Given my testing, an average character swings it roughly 250-300 move cost, even a pipe or a plank - or even weaker spears, just beat them. I didn't think it'd make sense for a polesaw to be beaten by a pointy stick in damage output. 

2. It's still a chainsaw in design. With the models I looked at, while it's a little smaller, it's still the same mechanisms - it'd still cut through reasonably well through dead. 

I'm just a little worried that decreasing it's damage output would make it completely inept in combat - which, while it surely shouldn't be a combat weapon, it should at least beat many of the weakest used weapon options, given it's fuel cost. 

I'll happily decrease it, but I thought I'd give my reasons to explain why first.

2022-11-14 23:05 UTC, TheShadowFerret requested changes

2022-11-14 23:05 UTC, TheShadowFerret commented on data/json/items/tool/woodworking.json
> +    "to_hit": -4,
```suggestion
    "to_hit": { "grip": "solid", "length": "long", "surface": "line", "balance": "clumsy" },
```

2022-11-14 23:05 UTC, TheShadowFerret commented on data/json/items/tool/woodworking.json
> +    "to_hit": -5,
"to_hit": { "grip": "solid", "length": "long", "surface": "line", "balance": "clumsy" },

2022-11-14 23:06 UTC, TheShadowFerret commented on data/json/items/tool/woodworking.json
> +    "to_hit": -5,
```suggestion
    "to_hit": { "grip": "solid", "length": "long", "surface": "line", "balance": "clumsy" },
```

2022-11-14 23:06 UTC, TheShadowFerret commented on data/json/items/tool/woodworking.json
> +    "description": "This is a lumbering tool intended for trimming hedges and tree branches. If loaded with gas, using this item will cause it to turn on, making it into an unwieldy polearm.",
```suggestion
    "description": "This is a lumbering tool intended for trimming hedges and tree branches.  If loaded with gas, using this item will cause it to turn on, making it into an unwieldy polearm.",
```

2022-11-15 06:57 UTC, PatrikLundell commented
The argument that a tool used to cut branches is a worse weapon than a primitive but actual weapon is a poor one.

Such a tool would be incredibly unwieldy given how top heavy it is (like trying to use a sledge hammer as a spear). It works fine against stationary trees (the only kind we have IRL), but to swing it around trying to hit moving targets would be rather difficult. The reach would probably not be of much value given that the enemy can close the distance during the time it takes you to move it.
It can also be noted that these tools are intended to use their reach upwards at an angle, rather than horizontally, where you'd probably struggle to keep it up at full reach.
It's probably quite dangerous if it does connect though, but good luck managing to actually score a hit.

2022-11-15 10:48 UTC, fairyarmadillo commented
The reason something like this hasn't already been added is that it would be a terrible weapon. 60 damage is way too high and there's no way it should have the impale technique- the blade is not going to slide cleanly through an enemy like a spear would and the pole is too flimsy to stand up to somebody ramming it through a human body even it could.

2022-11-15 12:43 UTC, Bluarianknight commented
Is 35 a reasonable level of damage for this weapon, then? Given previous testing, it is quite bad.

2022-11-15 12:46 UTC, Zireael07 commented
I'd fully expect it to be 'quite bad' in line with previous commenters

2022-11-15 12:46 UTC, Bluarianknight commented
I've changed it to a smaller version - No more REACH3, as well as limited the damage to 35 damage - which was a value I used previously in testing. It should be far less powerful as expected.

2022-11-15 13:07 UTC, Bluarianknight commented
From what I've looked at - a polesaw is still dangerous while on. Gas powered polesaws - which is what I've based the item on - are built to handle thicker branches. It's unwieldy, but if it can cut through large tree branches, it should deal at least some significant damage while pressing through a person.

2022-11-15 15:05 UTC, Knut-Aage-Hofseth commented
I think the idea is cool. The item is something that exist, and we should be able to press it into service as an improvised weapon. The problem is game balance. There is a huge difference between how much damage a tool can inflict to an unlucky user and how good it is as a weapon.
And how good it is as a weapon is connected to things that are difficult to model. There is of course the to-hit property. But other things like how well it bites into a target or glance off. How often the chain jams with flesh or clothes getting caught. Does the engine turning makes it harder to use. This has to be abstracted into to-hit, damage and swing speed. 

My personal thought is slow, low damage, not durable but with high crit damage (I do not know if that is possible) to represent the potential damage when it hits just right. Those horrible accidents you see on the news and not all the ones no-one hears about because it went well.

2022-11-15 15:52 UTC, Bluarianknight commented
That's true - I still think 35 is somewhat reasonable, given testing - I would certainly prefer to make to-hit harder if possible (which it already is with the spear property (I think) that makes near-attacks far harder. Given it's large action-cost, it's a risk to swing far, and not great at close.

2022-11-16 22:25 UTC, nopenoperson commented
is it based on a particular model of electric pole saw that exists irl? it seems quite heavy when compared to the models ive looked at online.

2022-11-17 00:47 UTC, Bluarianknight commented
It's based on gas-powered polesaws - which seem to be the longest and heaviest type of polesaws.

2022-11-17 05:18 UTC, Bluarianknight commented
If anyone has any more concerns, do let me know and I'll try to fix it - otherwise I'll mention it in the merge channel in the server if everyone thinks the changes make it work.

2022-11-17 22:58 UTC, Paprika-H commented on data/json/items/tool/woodworking.json
> +    "flags": [ "NONCONDUCTIVE", "FRAGILE_MELEE", "REACH_ATTACK" ]
```suggestion
    "flags": [ "NONCONDUCTIVE", "FRAGILE_MELEE", "REACH_ATTACK", "POLEARM" ]
```
If the powered version should have polearm I think the off version should have it too

2022-11-17 23:05 UTC, Paprika-H requested changes

2022-11-17 23:05 UTC, Paprika-H commented on data/json/items/tool/woodworking.json
> +    "description": "This is a lumbering tool intended for trimming hedges and tree branches.  If loaded with gas, using this item will cause it to turn on, making it into an unwieldy polearm.",
```suggestion
    "description": "This is a lumbering tool intended for trimming hedges and tree branches at a distance.  If loaded with gas, using this item will cause it to turn on, making it into an unwieldy polearm.",
```

2022-11-17 23:05 UTC, Paprika-H commented on data/json/items/tool/woodworking.json
> +    "price": 9000,
```suggestion
    "price": 40000,
```
Price is in decimals, and I couldn't find a gas one for $90, $400 seems a bit more reasonable, but that's just my opinion.

2022-11-17 23:05 UTC, Paprika-H commented on data/json/items/tool/woodworking.json
> +    "flags": [ "NONCONDUCTIVE", "FRAGILE_MELEE", "REACH_ATTACK" ]
```suggestion
    "flags": [ "POLEARM", "NONCONDUCTIVE", "FRAGILE_MELEE", "REACH_ATTACK" ]
```
Both versions should have the polearm flag

2022-11-17 23:05 UTC, Paprika-H commented on data/json/items/tool/woodworking.json
> +    "revert_to": "chainsaw_off",
```suggestion
    "revert_to": "polesaw_off",
```
Otherwise it'd turn into a chainsaw

2022-11-18 02:56 UTC, Bluarianknight commented
Done!

2022-11-18 18:41 UTC, Daved27hundred commented
This got me thinking, should chainsaws and similar weapons have a special attack? I don't think you'd slice or stab with them like a normal blade, You'd probably dig through a large portion of the enemy before pulling the saw back.

2022-11-18 21:58 UTC, Paprika-H commented
> This got me thinking, should chainsaws and similar weapons have a special attack? I don't think you'd slice or stab with them like a normal blade, You'd probably dig through a large portion of the enemy before pulling the saw back.

I think a realistic attack would probably be the first swing and the continuous damage until you retreat, or more realistically it getting gummed up

2023-03-07 07:58 UTC, merged