Crudebattleaxe
CleverRaven/Cataclysm-DDA pull request #62403
Opened 2022-11-26 15:02 UTC by GenericDwarf

#### Summary
Content "New sheet metal battleaxes, based upon the sheet metal swords."

#### Purpose of change

I really love the ability to make crude but functional swords out of sheet metal and limited tools. While not the ideal equipment, they fill a really nice role between repurposed tools and "proper" melee weaponry, and feel way more likely to be what a person surviving the end of the world would learn to make rather than setting up a full blacksmith shop. But, for a while I've noticed the lack of options for hooking weaponry until you reach the point you're smithing your weapons.

#### Describe the solution

So, that's why I decided to take a shot on crude, sheet metal battle axes! They fill a very niche gap between the sheet metal greatswords, who pack quite a punch but are really unwieldy, and the sheet metal sword, who is lighter and doesn't hit as hard, while also being okay options for Fior Di Battaglia/Barbaran Montante users! 

#### Describe alternatives you've considered

My original idea, which was a Fallout inspired tire iron hatchet. But that wouldn't fit any missing roles, wouldn't be good enough to be worth adding, and honestly, it's a pretty bad idea anyway.

#### Testing

Tested if the game loaded, it did, tested if I could spawn the weapons, I could, tested if the weapons were craftable, they were, and tested them in combat in middle of a town, and got obliterated by the horde. So everything went according to plan, I suppose!

#### Additional context

This isn't the most pratical tool in the shed, I'm gonna be honest here. But it's not supposed to be! At least in the way I see it, smithing actual war weapons should be a luxury few have acess to, either by limiting the necessary tools, knowledge, or both. So I find it useful that the community keep foccusing on adding more improvised, expedient and/or crude equipment, and hopefully, we can slowly shift from basement bunkering for an entire ingame season getting ready to smith a state-of-the-art zweihander, and more towards crafting early on being measures of desperation so players can go out and explore that beautiful, doomed world created to be suffered through!

2022-11-27 05:11 UTC, TheShadowFerret requested changes

2022-11-27 05:11 UTC, TheShadowFerret commented on data/json/items/melee/bludgeons.json
> +    "description": "A savage looking battle axe made out of layered sheet metal welded into two pipes held together with fittings, vaguely forming a upside down L shape. This should be structurally s
```suggestion
    "description": "A savage-looking battle axe made out of layered sheet metal welded into two pipes held together with fittings, vaguely forming a upside-down L shape.  This should be structurally stable.  Hopefully.",
```

2022-11-27 05:11 UTC, TheShadowFerret commented on data/json/items/melee/bludgeons.json
> +    "description": "A savage looking battle axe made out of layered sheet metal bolted to two pipes held together with fittings, vaguely forming a upside down L shape. Swing it with all your might."
```suggestion
    "description": "A savage-looking battle axe made out of layered sheet metal bolted to two pipes held together with fittings, vaguely forming a upside-down L shape.  Swing it with all your might."
```

2022-11-28 13:55 UTC, MNG-cataclysm approved these changes

2023-03-02 06:42 UTC, merged