New "Calliphorid" mutation tree - become a carrion eating flyperson.
CleverRaven/Cataclysm-DDA pull request #62505
Opened 2022-12-01 00:18 UTC by Daved27hundred

#### Summary
Content "Adds a new Fly mutation tree, a cross between insect and rat."

#### Purpose of change

New mutation lines are always nice, I've wanted something that makes use of the Eater of the Dead mutation from the rat tree.
The Calliphorid has the ability to eat rotten, mutated and even zombified corpses like the rat, but instead of having the utility of stainless claws and burrowing, the Calliphorid has enhanced perception and mobility, along with a small amount of armor.

This is still a work in progress and is very likely to change.

#### Describe the solution

What's done:
- Added required new mutation category
- Added threshold mutation
- Added unique mutagen, including the recipe, vitamins and samples needed

Todo:
- Add mutations to the category
- Create tree-specific mutations
- Create unique dreams for the tree
- Put samples and premade mutagens in lab spawnpools
- Put samples into mutant fly dissection pools
- Add the vitamins to mutagenic slurry's `decays_into` list
- Anything I forgot to list here

#### Describe alternatives you've considered

I very much appreciate any feedback, recommendations or criticisms.

#### Testing

I plan to start testing this as soon as I have something of substance to test.

#### Additional Context

No I didn't make this PR just to make the joke in the branch name

2022-12-01 02:25 UTC, Daved27hundred commented
of course I forget to lint it.

2022-12-01 03:35 UTC, TheShadowFerret requested changes
> No I didn't make this PR just to make the joke in the branch name

I don't believe you :3

2022-12-01 03:35 UTC, TheShadowFerret commented on data/json/items/comestibles/mutagen.json
> +    "description": "A processed mutagenic primer resembling blackened, rotted fat",
```suggestion
    "description": "A processed mutagenic primer resembling blackened, rotted fat.",
```

2022-12-01 03:35 UTC, TheShadowFerret commented on data/json/items/mutagen_ingredients.json
> +    "description": "A slurry of decay",
```suggestion
    "description": "A slurry of decay.",
```

2022-12-01 05:08 UTC, Venera3 commented
I'm not terribly enthusiastic about turning every single family into its own category. This would work just as well, be more easily attainable, and keep mutations from being 100% deterministic as an Insect subline. Something like
```
[ "CATEGORY_SUBTYPE" ] mutation category to make sure you're only on one subpath at any one time
"Calliphorid/Hymenopteran/Lepidopteran/Whatever Affinity" subfategory traits as a prereq for suitably fly-y/wasp-y/butterfly-y traits, with a second non-purifiable posttresh version to lock you into a phenotype for good
Some high-level traits sprinkled on top for those who go all the way
```
For Fly the Intestinal Fortitude and the basic Insect Wings line sounds right, but I'm drawing a blank on potential bad muts.

2022-12-02 09:20 UTC, Venera3 commented
To keep a limited scope and restrict it to fly stuff:
1) Make a new mutation type `SUB_CATEGORY` in mutation_types.json
2) Make a `Fly Affinity` trait with the `SUB_CATEGORY` type, dependent on one of the chitin traits and maybe the immature insect limbs - it doesn't need to have any effects on its own, this is your lower "threshold"
3) Have Fly-y traits need `Fly Affinity` (depending on which non-Insect trait you want to use you might need some duplicates) 
4) (extra credit) Add a nonpurifiable `Phly Phenotype` (requires affinity and the Fly traits) to lock you into your new flyperson body and/or unlock some highly flyy traits

2022-12-02 13:50 UTC, fairyarmadillo commented
How about an acid barf attack using the spell system? Flies do that to their food, and so did Dr. Brundle. It could splash an adjacent target and make a puddle on the ground, hitting the player with the nausea effect for a bit afterwards.

Flies are pretty ugly and people don't like them, maybe they could pick up deformed or badly deformed as downsides. You could also give them their own version of the proboscis mutation, as house and carrion fly mouthparts are adapted for slurping up food they liquify by regurgitating digestive enzymes on it, but this might be too annoying since the player can't make meat soup this way, and would have to make protein shakes or something.

They could also get fast reflexes, 'cause flies are really good at dodging.

2022-12-02 18:28 UTC, Daved27hundred commented
@fairyarmadillo  the improved dodge and the eating is part of what I plan to do. I didn't intend to make the proboscis upgrade prevent you from eating solids: You'd just take much longer to eat, because you'd need to vomit on the pemmican first.

As for the acid thing, I'm not entirely sure. I wanted to balance this mutation line by not giving it any natural weapons (claws, teeth and whatnot) like other ones. I'll think about it after I do what Venera said.

2022-12-03 19:36 UTC, Daved27hundred commented
@Venera3 should I remove the `THRESH_CALLIPHORID` along with the mutagen recipes I wrote for it? since I'm making this a subcategory.

2022-12-06 01:13 UTC, Daved27hundred commented
It's already set to a draft, but I'll put it in the PR name as well.

2022-12-07 09:55 UTC, Venera3 commented
> @Venera3 should I remove the `THRESH_CALLIPHORID` along with the mutagen recipes I wrote for it? since I'm making this a subcategory.

Yes, they will stay under Insect. Longish-term I could see a thing where subcategories like this have their own vitamins (so you either luck into them randomly or use mutagen made from flies to weigh the scales in their favor), but that's just idle musing at this stage.

2022-12-08 23:42 UTC, Daved27hundred commented
Having an "issue" with putting saprovore + eater of the dead into this subcategory, I say that in quotations because I didn't actually try yet.
I thought I'd add `INSECT` to the categories they're available for and put `SUB_CALLIPHORID` as a prerequisite (so that a non-fly insect doesn't get it) but I'm worried that that would mess with the other mutation trees that use it. am I overthinking this?

2022-12-15 05:07 UTC, Venera3 commented
I'm pretty sure extra categories won't impact the base traits, though you want to test that the original categories are capable of gaining them still.

2023-05-07 09:04 UTC, closed without merging