[Innawood] alternators!
CleverRaven/Cataclysm-DDA pull request #63108
Opened 2023-01-14 14:49 UTC by Devengel

#### Summary
Content "Add Innawood-friendly recipe for alternators"

#### Purpose of change
Manual power, for the woodlands!

#### Describe the solution
Simple recipe addition in recipe_vehicles.json.

#### Describe alternatives you've considered

#### Testing
opened the game, gave myself electronics and fabrication skills, found the recipe with the correct ingredients

#### Additional context

2023-01-14 17:06 UTC, anoobindisguise commented
You could honestly even add makeshift alternators with lower inefficiency since innawood if you feel up to it

2023-01-15 02:01 UTC, Light-Wave requested changes

2023-01-15 02:01 UTC, Light-Wave commented on data/mods/innawood/recipes/recipe_vehicle.json
> +    "components": [ [ [ "cable", 15 ] ], [ [ "makeshift_transformer", 4 ] ] ]
```suggestion
    "components": [ [ [ "cable", 30 ] ], [ [ "makeshift_transformer", 4 ] ] ]
```

2023-01-15 02:32 UTC, Light-Wave approved these changes

2023-01-15 16:11 UTC, Devengel commented
👍 
about makeshift alternators, i'm not really interested in doing that but if you want to, or anyone, Good luck!

2023-01-16 12:42 UTC, merged