Add two-piece and telescoping fishing rods
CleverRaven/Cataclysm-DDA pull request #63104
Opened 2023-01-14 01:25 UTC by cake-pie

#### Summary
Content "Add two-piece and telescoping fishing rods"

#### Purpose of change
Resolves #56474 
:warning: Requires #62945

The pro fishing rod has the best fishing tool quality, but is also incredibly unwieldy, inconvenient to transport and store.
More portable options exist in the real world and should be available in-game.

Also updates melee `to_hit` stat for the existing fishing rods to newer format

#### Describe the solution

- [x] add two-piece and telescoping fishing rods, with same tool quality as the pro fishing rod
- [ ] add disassembly for new fishing rods
- [ ] spawn new fishing rods in relevant locations
- [x] on existing `fishing_rod_basic` and `fishing_rod_professional`, change `to_hit` stat from legacy to newer format.

#### Describe alternatives you've considered
More detailed implementations such as:
- Instead of using same tier as pro fishing rod, fine tune tool quality of rods to account for details about the fishing rod characteristics like length, "action" (jargon: how much they flex), sensitivity, etc. that affect fishing success rate due to impact on factors like how far you can accurately cast and how well you can detect when a fish bites.
- Complex system similar to gunmods so that on top of a base fishing rod of whichever type we can have interchangeable parts: reel, line, hook, sinker, bait/lure, etc. These may affect what fish might be caught, e.g. appropriately sized hook; suitable bait/lure; line rating caps max weight (and may snap if overloaded)....

Would require far more work and too complex for our purposes; this isn't a fishing simulator.

#### Testing
Debug spawn the new fishing rods, test ability to assemble/disassemble, extend/retract and fish with them; place on ground to check that they are using correct `looks_like` sprites in both states.

2023-01-14 03:38 UTC, TheShadowFerret requested changes

2023-01-14 03:38 UTC, TheShadowFerret commented on data/json/items/tool/fishing.json
> +    "name": { "str": "two-piece fishing rod (packed)" },
```suggestion
    "name": { "str": "two-piece fishing rod (packed)", "str_pl": "two-piece fishing rods (packed)" },
```

2023-01-14 03:38 UTC, TheShadowFerret commented on data/json/items/tool/fishing.json
> +    "name": { "str": "telescoping fishing rod (packed)" },
```suggestion
    "name": { "str": "telescoping fishing rod (packed)", "str_pl": "telescoping fishing rods (packed)" },
```

2023-01-23 13:03 UTC, cake-pie commented
This PR [passed checks](https://github.com/CleverRaven/Cataclysm-DDA/actions/runs/3982607010) at caf64cd which included squashed merge of #62945 for testing purposes, so I've taken out the extra commit and declaring this ready to go whenever that also gets merged.

2023-03-02 09:56 UTC, cake-pie commented
Rebased to resolve conflicts. No longer blocked by #62945; ready to merge.

2023-03-03 14:43 UTC, merged