Made it possible to scan spellbooks into ereader
CleverRaven/Cataclysm-DDA pull request #63508
Opened 2023-02-09 20:49 UTC by Skrassh

#### Summary
Features "Removed the has_identified requirement from ebookscan, allowing the scanning of spellbooks and spell scrolls."

#### Purpose of change
Spell books currently cant be scanned into e-readers because you have to identify a book before being able to scan it. Removing this check allows you to scan spell books and spell scrolls into the e-reader.

#### Describe the solution
I removed the has_identified requirement from ereader scan. I also added a check when finishing a scan to mark the book as identified if it isn't already marked.

#### Describe alternatives you've considered
Making spell books spawn unidentified so they could be identified and then scanned in, that felt like an awkward band-aid to the problem.

#### Testing
1. Create new character
2. Spawn in a smartphone
3. Spawn in a spell book and scan it in
4. Spawn in a unidentified book and scan it in, marvel that the book you scanned is now identified.

#### Additional context
![image](https://user-images.githubusercontent.com/9900620/217935927-3f2ebb23-3de1-4476-94e7-a94eba080c14.png)

2023-02-09 22:06 UTC, Maleclypse requested changes
I'd prefer if this was jsonized so that mod creators can choose whether their "spell books" are capable of being added to an e-reader because otherwise I'm going to be receiving bug reports about "ball of pain was copied into my e-reader, how do you copy a 'ball of pain'?"

2023-02-09 23:54 UTC, Skrassh commented
I'm ok with doing a Json addition then, I'll go and add a field for it.

2023-02-10 05:59 UTC, Skrassh commented
Do we want to default the scannable field to true or false? If we want to default to false for books what's the best way to update the existing json aside from manually?

2023-02-10 13:43 UTC, MNG-cataclysm commented
> Do we want to default the scannable field to true or false? If we want to default to false for books what's the best way to update the existing json aside from manually?

I think it should default to true and add a bool value to items that individuals don't want to be scannable. Something like `scannable: true/false` to item JSON that the game could check for.

2023-02-10 14:32 UTC, Skrassh commented
> > Do we want to default the scannable field to true or false? If we want to default to false for books what's the best way to update the existing json aside from manually?
> 
> I think it should default to true and add a bool value to items that individuals don't want to be scannable. Something like `scannable: true/false` to item JSON that the game could check for.

That's what I was thinking, I'll go ahead and default that to true and get this wrapped up then.

2023-02-10 18:09 UTC, Maleclypse commented
> > > Do we want to default the scannable field to true or false? If we want to default to false for books what's the best way to update the existing json aside from manually?
> > 
> > 
> > I think it should default to true and add a bool value to items that individuals don't want to be scannable. Something like `scannable: true/false` to item JSON that the game could check for.
> 
> That's what I was thinking, I'll go ahead and default that to true and get this wrapped up then.

As an in repo example please add `"scannable": false` to the Xedra Evolved spellbooks.  That way there's at least somewhere beyond docs it's visible.

2023-02-10 23:57 UTC, Skrassh commented on src/activity_actor.cpp
> +        }
I moved it to before the scan 👍

2023-02-10 23:58 UTC, Skrassh commented
> > > > Do we want to default the scannable field to true or false? If we want to default to false for books what's the best way to update the existing json aside from manually?
> > > 
> > > 
> > > I think it should default to true and add a bool value to items that individuals don't want to be scannable. Something like `scannable: true/false` to item JSON that the game could check for.
> > 
> > 
> > That's what I was thinking, I'll go ahead and default that to true and get this wrapped up then.
> 
> As an in repo example please add `"scannable": false` to the Xedra Evolved spellbooks. That way there's at least somewhere beyond docs it's visible.

I added scannable false to all the Xedra Evolved spell learning items.

2023-02-11 10:51 UTC, Maleclypse approved these changes
Thank you! This is a good enhancement!

2023-02-13 16:51 UTC, Skrassh commented
Noticed when playing earlier that spellbooks report 0 mins to read on the identify check. Should we set a value for the spellbooks time to read or just not print the time if it's 0?

2023-02-21 00:37 UTC, merged