More Mexican foods (real)
CleverRaven/Cataclysm-DDA pull request #63847
Opened 2023-02-28 22:29 UTC by onura46

#### Summary
Content "More Mexican foods"

#### Purpose of change
Adds 3 new Mexican foods, tweaks item spawns, tweaks recipes to allow new items to be used.

#### Describe the solution
Adds three new foods with recipes learnable through the Mexican cookbook:
- Flour tortillas
- Salsa
- Horchata (cannot be autolearned)

These items have been added to item spawn groups in kitchens, restaurants, fridges, and pantries where appropriate. A new food requirement called `tortilla_any` has been created so you can now use either type of tortilla for some recipes!

This is effectively half an implementation of #61697. I have decided that elote and gorditas are just too similar to existing foods to be meaningfully different, barely off from "corn on the cob" and "deluxe sandwich", respectively. Though the real-world differences are obvious, the difference in-game is negligible.

This PR also removes `autolearn` from hominy, which I intended to do in the initial PR. Hominy is made with lye or slaked lime using a chemical process called nixtamalization to loosen the hull and treat the kernel. For most people, this is not a colloquially-known process because it involves real chemistry knowledge and non-standard ingredients. Perhaps because of this or because of how long it takes to make, hominy is normally store-bought rather than made at home.

#### Describe alternatives you've considered

#### Testing
Many spawns and repeated testing to make sure recipes were balanced correctly and everything spawned as expected.

#### Additional context
No more stale draft PRs for me lmao.

2023-03-06 04:25 UTC, Maleclypse requested changes
Weights are just estimates of what I think might make the density tests pass.  Calorie checks should be fixed by these changes though. :)

2023-03-06 04:25 UTC, Maleclypse commented on data/json/items/comestibles/bread.json
> +    "calories": 64,
```suggestion
    "calories": 100,
```

2023-03-06 04:25 UTC, Maleclypse commented on data/json/items/comestibles/drink.json
> +    "calories": 200,
```suggestion
    "calories": 225,
```

2023-03-06 04:25 UTC, Maleclypse commented on data/json/items/comestibles/drink.json
> +    "weight": "257 g",
```suggestion
    "weight": "237 g",
```

2023-03-06 04:25 UTC, Maleclypse commented on data/json/items/comestibles/bread.json
> +    "weight": "24 g",
```suggestion
    "weight": "18 g",
```

2023-03-06 04:33 UTC, onura46 commented
> Weights are just estimates of what I think might make the density tests pass. Calorie checks should be fixed by these changes though. :)

Thank you so much for your suggestions! I was getting ready to reassess this and ask for details/docs about correcting item densities literally as you shared them <3

2023-03-08 03:47 UTC, onura46 commented
The item densities should be properly fixed now. Sorry for all the commits; I was just confused alternating with lazy trying to figure out the math I had to do, but turns out I was just reading the log incorrectly.

The default calories for flour tortillas still seem way too high, maybe twice as much, compared to reality. I'm guessing its just a byproduct of the ingredients and materials.

2023-03-09 03:33 UTC, merged