Luliya
CleverRaven/Cataclysm-DDA pull request #64040
Opened 2023-03-07 20:10 UTC by LyleSY

#### Summary
Content "Exodii NPC Luliya"

#### Purpose of change

Flesh out Exodii, make base more interesting

#### Describe the solution

New NPC Luliya with Exodii faction, intended to spawn in a broom closet with a broom and a broken exodii quad. She doesn't speak English but eventually the player can figure out that she likes music and if the player brings an instrument she can sing with him and give a small morale boost.

#### Describe alternatives you've considered

Let her clean CBMs for the player for free with a small delay. No code support for that yet but I'd like to do that when it's available. Explain her backstory which I've thought way too much about, but her language facilities aren't really there. I'd like to add some dialogue at some point for the player to teach her English to learn more about her deal.

#### Testing

WIP

#### Additional context

Thanks to Erk for talking this through with me.

2023-03-07 21:38 UTC, MNG-cataclysm requested changes
Choosing to kick Luliya repeatedly should probably cause her to become upset with the player, rather than doing nothing. 

<P.S, If she does become a possible romance, choosing to play the saxophone in the music dialogue should make any related checks automatically pass in your favor.>

2023-03-07 21:38 UTC, MNG-cataclysm commented on data/json/npcs/exodii/exodii_Luliya.json
> +        "text": "Speak American robot.  We don't take kindly to that kind of thing here.  <You frown menacingly>",
```suggestion
        "text": "Speak English ya <swear> robot.  We don't take kindly to that kind of thing here.  <You frown menacingly>",
```

2023-03-07 21:38 UTC, MNG-cataclysm commented on data/json/npcs/exodii/exodii_Luliya.json
> +        "text": "[HAS SAXOPHONE] I happen to have a nice trumpet, want to hear something?",
```suggestion
        "text": "[HAS SAXOPHONE] I happen to have a nice saxophone, want to hear something?",
```

2023-03-08 08:21 UTC, PatrikLundell commented
I'm not sure romance with an Exodii cyborg would make sense, as the body parts that would have been involved are likely sacrificed and replaced with robotic parts that lack the now unneeded capabilities.

I'm also not sure the Exodii would be too keen to lose some of their limited staff on one of their temporary stops, unless sufficiently payed for in an increased trade and a decent chance of recruitment of suitable locals into their faction. However I don't think there's any system for an NPC to influence the player to do what factions want, beyond punishment/rewards.

That setting might allow for quests where the player provides Luliya with items used to repair the quad. That could be done through a "dialog" where hand writing and drawing are used to convey the message of what's needed and what the reward would be, possibly gated behind skill checks to understand what the parts needed are (and an option to guess what they might be if the skill isn't sufficient, although that might lead to meta gaming). It might be possible to make a quest chain where language gradually is introduced, to simulate the learning of a local language.

2023-03-08 12:55 UTC, MNG-cataclysm commented
> I'm not sure romance with an Exodii cyborg would make sense, as the body parts that would have been involved are likely sacrificed and replaced with robotic parts that lack the now unneeded capabilities.

I suppose romance with the Exodii could occur through the Great Gray or other networks, relying a dream-like trance between two or more cyborgs. Otherwise, there could be certain bionic modules that replace the parts needed with mechanical equivalents, or augment them with some sort of *enhancement*. It is one of the most marketable things around, it's possible one or more worlds the Exodii visited had something like that available.

Considering that Lulia is described as vain, she probably would want to install one or more of these.

2023-03-08 15:33 UTC, Maddremor commented
Remember that outsiders are ephemeral and disposable. I doubt anyone that formed strong emotional attachments that easily could cope with the Exodii lifestyle.

2023-03-08 15:56 UTC, harakka commented
> Considering that Lulia is described as vain, she probably would have installed one or more of these.

That is hell of a conclusion to jump to.

> Considering that Lulia is described as vain, she probably would have installed one or more of these.

That is, uh, quite a conclusion to jump into.

2023-03-08 16:15 UTC, MNG-cataclysm commented
> That is hell of a conclusion to jump to.

Would the mechanical dream-trance work better for this?

2023-03-08 16:21 UTC, Maddremor commented
I don't think sex and eroticism is especially interesting or relevant here.

2023-03-08 16:22 UTC, I-am-Erk commented
I'd like to leave any concept of romancing a cyborg from another dimension in the vague clouds of your imagination for the moment pls.

Exodii are not really good candidates to become followers.

2023-03-08 18:58 UTC, kevingranade commented
The exodii do not need a cleaning lady. They have the resources for a better roomba if they want that, they definitely don't need to dedicate a member and their highly capable robot body to that task.
The kicking options are right out,  if they're not meaningful interactions the player can feel free to imagine doing it.

2023-03-08 19:01 UTC, MNG-cataclysm commented
What if Luilya oversaw material recovery and management, instead of cleaning?

2023-03-09 09:00 UTC, fairyarmadillo commented
Putting aside romance, which I don't think the game is set up to handle, a long-running questline/plot where the player forms a bond with a member of a faction as remote as the Exodii is a pretty cool idea. It probably happens frequently enough that a member of the faction will get inappropriately (from the faction's point of view) attached to an outsider which leads to some angst when it comes time to jump to a new world and leave said outsider behind.

A story like that could easily be expressed through dialog with Rubik and Luliya, especially if the player ever gets a language implant or proficiency to communicate with the latter. The current gameplay loop encourages re-visiting this faction frequently, so giving them more things to say and do over time might make this more interesting.

2023-03-12 00:01 UTC, MNG-cataclysm requested changes

2023-03-12 00:01 UTC, MNG-cataclysm commented on data/json/npcs/exodii/exodii_Luliya.json
> +      "no": "[You see a tall golden figure in the closet with female features.  Strapped to the back of the head with copper wire is a glass cylinder containing long frizzy black hair.  The body stan
```suggestion
      "no": "[You see a tall golden figure with female features.  Strapped to the back of the head with copper wire is a glass cylinder containing long frizzy black hair.  The body stands still and emits an unpleasant beeping sound.  On the back there is a large red button with strange markings.  There is a golden harp of some kind.]"
```
She's not in a closet, so this intro probably shouldn't introduce her as being inside a closet.

2023-03-18 04:19 UTC, Maleclypse commented on data/json/npcs/exodii/exodii_Luliya.json
> +        "text": "[HAS COWBELL] I happen to have a nice cowbell, want to play with me?",
`"I have a fever and the only cure is cowbell, want to play with me?"`

2023-03-18 04:19 UTC, Maleclypse reviewed
This is really cool, I like it a lot!

2023-03-18 08:21 UTC, MNG-cataclysm approved these changes

2023-04-17 23:47 UTC, merged