a few new child notes and video snippets.
CleverRaven/Cataclysm-DDA pull request #65085
Opened 2023-04-15 06:45 UTC by DoctorBoomstick

#### Summary
Content "Adds a collection of new snippets, both child notes and E-logs."
#### Purpose of change
More variety in present snippets.
#### Describe the solution
Adds 10 new snippets: 2 child notes and 8 e-logs, with the latter being quite sizable.
#### Describe alternatives you've considered
Not adding anything, or trying to keep the snippets shorter, the latter of which I have already tried to do to the best of my ability without jeopardizing the meaning behind the snipits.
#### Testing
They’re simple text additions.
#### Additional context

2023-04-17 23:02 UTC, sparr commented
test failure is related to json not changed by this PR

2023-04-18 04:45 UTC, Daved27hundred commented on data/json/snippets/e_logs.json
> +    "text": "untitled2047-1564.mp4\n\nIn what might be the first cheerful voices you’ve heard since the Cataclysm, a muddle of laughs and good-natured conversation fills the recording’s audio.  The v
add "GET WELL SOON!" to the string of lines migo can say ingame, as a reference to this snippet.

2023-04-18 14:19 UTC, Inglonias commented
This is some well written stuff. Good job.

2023-04-19 01:10 UTC, Maleclypse requested changes
Figured out why your tests were failing.

2023-04-19 01:10 UTC, Maleclypse commented on data/json/snippets/children_notes.json
> +  },
You've added these below outside of the snippet object above.  Get rid of the `]` on line 139.

2023-04-19 01:10 UTC, Maleclypse commented on data/json/snippets/e_logs.json
>      ]
Same problem with the closing bracket as above.  Delete line 95

2023-04-21 18:30 UTC, merged