New location: Survivor Forest Camp
CleverRaven/Cataclysm-DDA pull request #65535
Opened 2023-05-07 23:02 UTC by Nebnis

#### Summary
Content "Added a new location called survivor forest camp"

#### Purpose of change
A new type of camp that have a primitive and isolated focus in  the game.

#### Describe the solution
I always imagined a survivor that has gone completely isolated from the city and the horrors from them with nothing but what they can carry on their back. 

I did my best to tell a little story with this place by making most of the items with a primitive and scavenging outlook. Someone who brought their family with them as they fled, a situation that even can be repeated. So  as bonus, i added a small chance for a fleshy shambler to spawn instead to signify a person that has gone completely blobbed. I also made the place unique since this is probably not something you will see it very often.

#### Describe alternatives you've considered
Probably add a chance based spawn for the child stuff? I do like a place that has some story attached though, and i made this unique anyway.

#### Testing
Logged and met many of the camps, everything seems to be working

#### Additional context
I have no idea what the fuck im doing.

2023-05-08 01:32 UTC, NetSysFire requested changes, later dismissed
I am unsure what story you want to tell, but given the human bones and the skulls (there is an ordinary version of it, too), likely something about one of said family being killed by one of their own. Probably because of a mortal/infected wound or something.

Use zombies or one of the ferals. If you want to indicate someone got "ritually" butchered, place the bits of human flesh, organs and also fields such as fd_blood and the scraps of flesh one there. In your case I would spawn the skull some tiles away to signal that it was an intentional beheading.

If that is not your intention, spawn a human corpse (I very recently made an itemgroup for corpses who died of an infected wound, might fit here) and *optionally* the fields I mentioned above to imply any struggle there might have been while said death occurred.

Environmental storytelling is not easy, especially if this is one of your first rodeos, so do not be afraid to ask for help here.

2023-05-08 01:32 UTC, NetSysFire commented on data/json/overmap/overmap_terrain/overmap_terrain.json
> +    "sym": "S",
Campsites usually use "+" as a symbol.

2023-05-08 01:32 UTC, NetSysFire commented on data/json/mapgen/survivor_forest_camp.json
> +        { "item": "etched_skull", "x": 19, "y": 7, "chance": 100 },
This is a very specific quest item, used for `MISSION_INVESTIGATE_CULT`.

2023-05-08 01:32 UTC, NetSysFire commented on data/json/mapgen/survivor_forest_camp.json
> +        { "monster": "mon_fleshy_shambler", "x": 12, "y": 9, "spawn_data": { "patrol": [ { "x": 12, "y": 9 } ] } },
I heavily disagree with your choice of monster here. A "person who has gone completely blob" is a zombie. Yes, we do have mutations caused by the blob, relevant in your case would be the collapsed tower and the meat cocoons for example.

2023-05-08 02:23 UTC, Nebnis commented
> I am unsure what story you want to tell, but given the human bones and the skulls (there is an ordinary version of it, too), likely something about one of said family being killed by one of their own. Probably because of a mortal/infected wound or something.
> 
> Use zombies or one of the ferals. If you want to indicate someone got "ritually" butchered, place the bits of human flesh, organs and also fields such as fd_blood and the scraps of flesh one there. In your case I would spawn the skull some tiles away to signal that it was an intentional beheading.
> 
> If that is not your intention, spawn a human corpse (I very recently made an itemgroup for corpses who died of an infected wound, might fit here) and _optionally_ the fields I mentioned above to imply any struggle there might have been while said death occurred.
> 
> Environmental storytelling is not easy, especially if this is one of your first rodeos, so do not be afraid to ask for help here.

I mostly wanted the bones to be someone who belonged to the feral who resides there, as for the choice of that one skull, i was just thinking the feral did as sorta half symbolism/animalistic instinct trying to make the remains of their loved ones "special", hence etched :P. I will give a look at your group spawn, you raised very good points about it, and i also believe it would fit better with the randomizing.

As for the fleshy shambler, i was under the assumption he was some sort of heavily mutated/zombiefied human. And since NPC give us quests about the upgraded version of that monster, i thought it would be okay to do it here too. i will find one of the collapsed tower monsters or something else.

Originally i wanted to make this feral neutral. And give a small dialogue when you interact with him about his eyes darting everywhere but not really being an immediate danger to you. Basically a feral who is almost transitioning to full kill mode. But i'm not sure how i could do that, i think i need to make a brand new cunning feral and set it to neutral and then try to trigger an eoc when interacting? Either that or give the monster a npc chatter, but i'm not sure if i want it to be too involved.

2023-05-08 03:31 UTC, NetSysFire commented
>to be someone who belonged to the feral who resides there

Definitely use one of the corpse item(group)s then.

>he was some sort of heavily mutated/zombiefied human. And since NPC give us quests about the upgraded version of that monster

More mutated than zombified. It is more of a horror than a zombie really, but also much more uncommon. Without checking, it might even be unique and/or spawned by the jabberwock.

>make this feral neutral
>Basically a feral who is almost transitioning to full kill mode

I have an open PR for civilians, taking care of just that. However, I do not think it would fit here. I am still unsure what caused the initial death, but so far it sounds like someone of the little group turned and then went after the others. In that case there are multiple monstergroups you can pick from which have both ferals and zombies in them. Making one yourself is trivial, too if there is nothing that fits your needs.

Place say two corpses (as items, not as actual corpses), one from the `corpse_child` item group (beware: that includes a gunned one and I do not know if that fits the lore of your little encounter, although it sounds plausible for one of them to carry a gun), and one from whatever flavored corpse item group you want. Then place a monster from your desired monster group who will randomly either be a zombie or a feral. Simple environmental story telling accomplished.

If you want to get into advanced™ stuff, try a nested mapgen. Create two: one for the monster, one for the corpse.

```json
"#": { "chunks": [ [ "survivorcamp_corpse", 50 ], [ "survivorcamp_monster", 50 ] ] },
```

This way you either get a corpse OR a monster, never both. Unfortunately this gets complex really quickly but it does add some depth at least.

2023-05-08 17:02 UTC, NetSysFire commented
>How do i place a pulped corpse that don't revive right away?

When playing around with corpses in #65359, I noticed it being random, too. I do not think you can influence that behavior right now unfortunately.

2023-05-08 19:42 UTC, LovamKicsiGazsii reviewed
Right now the camp doesn't seem to mesh well with the surrounding forestry. I'd recommend adding survivor_forest_camp terrain to the list of "forest_thick" terrains in regional_map_settings so that the forest actually connects to neighboring forest tiles. (so something similar to #55735)

2023-05-08 19:42 UTC, LovamKicsiGazsii commented on data/json/mapgen/survivor_forest_camp.json
> +      },
You'll need to regionalize your terrains here (`t_dirt` --> `t_region_soil`, `t_grass` --> `t_region_groundcover`)

2023-05-08 20:01 UTC, Nebnis commented on data/json/mapgen/survivor_forest_camp.json
> +      ],
Eh i dont mind the overriding as at least guarantee a few of them and they looked nice enough anyway

2023-05-08 20:33 UTC, LovamKicsiGazsii commented
> Does it look better? I'm imagining they cut a bunch of vegetation there to make way for passage.

Guess you could use the sparser "forest" instead, perhaps for both "predecessor_mapgen" and regional_map_settings.

2023-05-08 21:56 UTC, NetSysFire commented
Also, given they try to live off the land, how about a vegetable patch?

2023-05-08 23:35 UTC, Nebnis commented
> Also, given they try to live off the land, how about a vegetable patch?

Pretty homely secluded camp now eh? Thank you for all the help folks, this is way better than i originally started with. Even if it doesn't get merged i learned a lot and had a ton of fun with this. 

Just one question though, i noticed the map tended to generate in forest edges, is there a way to make it spawn deeper into forests?
![survivor camp](https://user-images.githubusercontent.com/104400556/236959039-b0f0d555-9df0-4348-9a4e-07de9e721595.jpg)

2023-05-09 00:14 UTC, NetSysFire commented on data/json/mapgen/survivor_forest_camp.json
> +      "sealed_item": { "=": { "items": { "item": "farming_seeds", "chance": 100 }, "furniture": "f_plant_harvest" } },
You probably want to make this `f_plant_seedling` instead, since those plants will be more or less freshly planted.

2023-05-09 00:19 UTC, Nebnis commented
Is there any reason why the tests keep failing? or has nothing to do with me?

2023-05-09 00:20 UTC, NetSysFire commented
>is there a way to make it spawn deeper into forests?

You want `forest_center`, instead of just forest.

See https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/OVERMAP.md#overmap_location and data/json/overmap/special_locations.json

2023-05-09 00:28 UTC, NetSysFire commented
I have looked into the failing tests and it appears that they are just broken again. I determined this since it is complaining about things you have not touched.

2023-05-19 05:12 UTC, merged