Urns and memorial items no longer spawn in bookstores
CleverRaven/Cataclysm-DDA pull request #65710
Opened 2023-05-18 07:58 UTC by Br1ght0ne

#### Summary
Bugfixes "Urns and memorial items no longer spawn in bookstores"

#### Purpose of change

Fixes #65450.

#### Describe the solution

Removes the `memorial_mansion` items group, as it was only used for books inside the `mansion_books` group, which only appears in bookstores.

#### Describe alternatives you've considered
Adding `mansion_books` or `memorial_mansion` item groups to mansions somewhere.

#### Testing

Did not do testing yet, but this looks like a straightforward change.

#### Additional context

2023-05-18 13:33 UTC, RenechCDDA commented
> the `mansion_books` group, which only appears in bookstores.

This is... not really correct. It's also a component of `mansion_bookcase` which appears in mansions.

https://github.com/CleverRaven/Cataclysm-DDA/blob/18fe8ad6ea5cfa84a99aa5753933ebcda2d45721/data/json/itemgroups/Locations_MapExtras/mansion.json#L436-L447

https://github.com/CleverRaven/Cataclysm-DDA/blob/18fe8ad6ea5cfa84a99aa5753933ebcda2d45721/data/json/mapgen/mansion.json#L606

2023-05-18 13:37 UTC, Br1ght0ne commented
@RenechCDDA Thanks, did not find this usage with search for some reason. I'll apply your suggestion.

2023-05-22 12:57 UTC, bombasticSlacks requested changes
Blocking merge until suggested change has been resolved

2023-06-28 15:05 UTC, Maleclypse commented
Closing as obsoleted by https://github.com/CleverRaven/Cataclysm-DDA/pull/66490

2023-06-28 15:05 UTC, closed without merging