set player_display to false on some NPC traits that were missing them
CleverRaven/Cataclysm-DDA pull request #66397
Opened 2023-06-23 00:58 UTC by Daved27hundred

#### Summary
None

#### Purpose of change

The NPC traits "ignore sounds" and "will not bash" were not set to be invisible in the traits menu, meaning NPCs with them that could be recruited (Meteorologist mostly) would display them if you asked to know about them.

#### Describe the solution

added `player_display: false` to both traits

2023-06-23 01:09 UTC, Maleclypse commented
The correct fix for this would be to remove those traits when the character becomes a follower.   This would break things further by making follower NPCs have weird behaviour that is impossible to easily identify.  Those two traits break followers regularly.  Sorry :(

2023-06-23 01:09 UTC, Maleclypse requested changes
Do not merge as is.

2023-06-23 01:49 UTC, Daved27hundred commented
Understood, what do you suggest I do instead?

2023-06-23 02:57 UTC, Maleclypse commented
```
"success": {
          "topic": "TALK_AGREE_FOLLOW",
          "effect": "follow",
          "opinion": { "trust": 1, "value": 1 },
          "npc_lose_trait": [ "RETURN_TO_START_POS", "NO_BASH", "IGNORE_SOUND" ]
        },
```
Update the meteorologist follow dialogue to include the npc_lose_trait line.  Same for any other characters that have any of  those three traits.  Make sure to only remove the traits they already have.

2023-06-23 03:03 UTC, Daved27hundred commented
got it - I'll start this tomorrow, it's quite late.

2023-06-23 16:25 UTC, Daved27hundred commented
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/56202842/9de5c5f0-f2e2-4f0b-b9c3-612780ca03ba)
@Maleclypse Is this where it should go? I'm not very familiar with NPC code.

2023-06-23 20:12 UTC, Maleclypse commented
> 

Ah ha.  So you're going to want to go to `TALK_COMMON_OTHER.json` and then any effect that includes `follow` your going to want to add `"npc_lose_trait": [ "RETURN_TO_START_POS", "NO_BASH", "IGNORE_SOUND" ]` apparently I didn't realize when I did the first one that the different reasons to persuade an npc to follow you used different talk topics.  Which I should have. Sorry

2023-06-24 02:15 UTC, Daved27hundred commented
Should I remove the `player_display: false` lines I added?

2023-06-24 02:45 UTC, Maleclypse commented
> Should I remove the `player_display: false` lines I added?

Yes please.  That way if other people add new follows we'll know something has gone wrong.

2023-06-24 19:15 UTC, merged