Add double holsters
CleverRaven/Cataclysm-DDA pull request #66498
Opened 2023-06-27 21:28 UTC by Paprika-H

#### Summary
Content "Double Decker Holsters"

#### Purpose of change

Wanted to be able to carry more guns that were easy access
#### Describe the solution

Adds two double holsters, one that has each holster side by side, and the other with two holsters front and back.
#### Describe alternatives you've considered

Having a belt which can have multiple holsters attached to it.
#### Testing

Tested locally, works fine.

#### Additional context

2023-06-27 21:41 UTC, GuardianDll commented
Why not add it into loot groups to spawn in game?

2023-06-27 21:44 UTC, Paprika-H commented
> Why not add it into loot groups to spawn in game?

I cannot find any real world examples of this stuff, so it's a survivor craft exclusive

2023-06-27 22:54 UTC, TheShadowFerret requested changes

2023-06-27 22:54 UTC, TheShadowFerret commented on data/json/items/armor/holster.json
> +    "name": { "str": "side by side double holster" },
```suggestion
    "name": { "str": "side-by-side double holster" },
```

2023-06-27 22:54 UTC, TheShadowFerret commented on data/json/items/armor/holster.json
> +    "name": { "str": "front to back double holster" },
```suggestion
    "name": { "str": "front-to-back double holster" },
```

2023-06-28 13:18 UTC, Termineitor244 commented
> > Why not add it into loot groups to spawn in game?
> 
> I cannot find any real world examples of this stuff, so it's a survivor craft exclusive

You could always add it to the survivor zombies then.

2023-06-28 15:00 UTC, merged