Condom Variants
CleverRaven/Cataclysm-DDA pull request #66529
Opened 2023-06-29 13:27 UTC by Paprika-H

#### Summary
Content "Condom Varieties"

#### Purpose of change

Felt weird that every single condom was the exact same, so I added some colour.

#### Describe the solution

Adds condom variants

#### Describe alternatives you've considered

Enacting a strict abstinence policy in the cataclysm

#### Testing

Tested locally, works fine.

#### Additional context

2023-06-29 22:00 UTC, TheShadowFerret requested changes
CDDA is set in America, no extra letters for the British.

Also

> Enacting a strict abstinence policy in the cataclysm

Should've done this

![bonk-doge](https://github.com/CleverRaven/Cataclysm-DDA/assets/99621099/31c86283-f2a5-4b68-8731-d4da1253f07b)

2023-06-30 02:38 UTC, Paprika-H commented
> CDDA is set in America, no extra letters for the British.
> 
> Also
> 
> > Enacting a strict abstinence policy in the cataclysm
> 
> Should've done this
> 
> ![bonk-doge](https://user-images.githubusercontent.com/99621099/249906411-31c86283-f2a5-4b68-8731-d4da1253f07b.gif)

Thank you so much for saving my ass lmao

2023-06-30 03:04 UTC, TheShadowFerret commented on data/json/items/containers.json
> +        "description": "For those who need to spice up their sex life, are masochistic, or just hate themselves, this condom is flavored after jalapenos.",
```suggestion
        "description": "For those who need to spice up their sex life, are masochistic, or just hate themselves, this condom is flavored after jalapeños.",
```

2023-06-30 15:44 UTC, MNG-cataclysm approved these changes

2023-06-30 18:21 UTC, merged