New fish
CleverRaven/Cataclysm-DDA pull request #66600
Opened 2023-07-02 07:50 UTC by Karol1223

#### Summary
Content "New fish"

#### Purpose of change
I like fish

#### Describe the solution

**NEW SPECIES**
- [x] Burbot
- [x] Yellow Bullhead
- [x] Longnose Gar
- [x] Lake Sturgeon
- [x] Shortnose Sturgeon
- [x] Round Whitefish
- [x] Splake
- [x] American Pickerel
- [ ] Amur Carp
- [x] Goldfish

#### Describe alternatives you've considered

#### Testing

#### Additional context

2023-07-03 13:29 UTC, TheShadowFerret commented on data/json/monsters/fish.json
> +    "description": "An american pickerel.  It looks like a pike, but way smaller.",
```suggestion
    "name": { "str": "American pickerel" },
    "description": "An American pickerel.  It looks like a pike, but way smaller.",
```

2023-07-03 15:01 UTC, Karol1223 commented on data/json/monsters/fish.json
> +    "description": "An american pickerel.  It looks like a pike, but way smaller.",
Good catch! Forgot about that!

2023-07-05 16:47 UTC, Karol1223 commented
I'll point this out here right now - "cods" is a real word if used to refer to multiple TYPES of codfish. I'm not as stupid as I look, just fish and grammar don't really get along well.

2023-07-05 17:03 UTC, harakka requested changes
Minor copyedit suggestions

2023-07-05 17:03 UTC, harakka commented on data/json/monsters/fish.json
> +    "description": "While the shortnose sturgeon it is still large, it is nothing compared to its cousin - the lake sturgeon.  What really sets it apart, however, is its signature shorter snout.",
```suggestion
    "description": "While the shortnose sturgeon is still large, it is nothing compared to its cousin - the lake sturgeon.  What really sets it apart, however, is its signature shorter snout.",
```

2023-07-05 17:03 UTC, harakka commented on data/json/monsters/fish.json
> +    "description": "An American pickerel.  It looks like a pike, but unlike its chain cousin, this one is way smaller.",
```suggestion
    "description": "An American pickerel.  It looks like a pike, but unlike its chain pickerel cousin, this one is way smaller.",
```
Reads better to people not familiar with the fish species

2023-07-05 17:03 UTC, harakka commented on data/json/monsters/fish.json
> +    "description": "Yes, this is that common pet fish.  Though, given its size and the fact that it's still alive you can take a wild guess that this one is feral.",
```suggestion
    "description": "Yes, this is that common pet fish.  Though, given its size and the fact that it's still alive, you can take a wild guess that this one is feral.",
```

2023-07-06 04:39 UTC, merged

2023-07-06 09:43 UTC, Theawesomeboophis commented
I would love to be able to tame certain types of fish in the future with fishfood and put them in a tank, I think my survivor being able to have a pet goldfish or other type of fish would be really cool, in vanilla or tamable wildlife depending on consensus.