Initial Commit
CleverRaven/Cataclysm-DDA pull request #66864
Opened 2023-07-13 01:10 UTC by RanikOrtega

#### Summary
Content "Slightly mutated dog variants"

#### Purpose of change
To create extra content for "Pet-Keeper" playstyles and additional mutation options for dogs as they only had mongrels.

#### Describe the solution
Created some variations of dog mutations. Names subject to better suggestions: Loper = Dog with mutated legs, can jump short distances and climb objects. Mauler = Rottweiler with a wider and even more tooth filled mouth. Thrasher = small slower dogs that can dig.  

#### Describe alternatives you've considered
Not adding extra variants.

#### Testing
Spawned dogs in world with debug. Teleported to TCL-Lab finales and checked for dog variant spawns in Tier 2 mutagen labs.

#### Additional context
![CDDA-Lab-Mutant](https://github.com/CleverRaven/Cataclysm-DDA/assets/14862800/f5e5b3c1-e739-43f9-8ab4-fb0c71f92c96)

2023-07-13 03:49 UTC, TheShadowFerret requested changes
Its

2023-07-13 03:49 UTC, TheShadowFerret commented on data/json/monsters/mutant_mammal.json
> +    "description": "This dog has undergone visible mutation. While it's body is larger than normal it's legs are noticeably elongated, muscular and covered in long cord-like fur. It easily stands as
```suggestion
    "description": "This dog has undergone visible mutation.  While its body is larger than normal, its legs are noticeably elongated, muscular and covered in long cord-like fur.  It easily stands as tall as you and watches your every move closely with reflective eyes.",
```

2023-07-13 03:49 UTC, TheShadowFerret commented on data/json/monsters/mutant_mammal.json
> +    "description": "An adorable, but unusual puppy. It wags it's tail happily but something about it's legs seems off. ",
```suggestion
    "description": "An adorable, but unusual puppy.  It wags its tail happily but something about its legs seems off. ",
```

2023-07-13 03:49 UTC, TheShadowFerret commented on data/json/monsters/mutant_mammal.json
> +    "description": "This stocky dog has undergone visible mutation. It's jaw has widened and features more teeth than any dog should ever have. While it's toothy grin is unnerving, it's tail wags as
```suggestion
    "description": "This stocky dog has undergone visible mutation.  Its jaw has widened and features more teeth than any dog should ever have.  While its toothy grin is unnerving, its tail wags as energetically as ever. ",
```

2023-07-13 03:49 UTC, TheShadowFerret commented on data/json/monsters/mutant_mammal.json
> +    "description": "An adorable, but unusual puppy. It wags it's tail happily but something about it's body seems off about it's mouth. ",
```suggestion
    "description": "An adorable, but unusual puppy.  It wags its tail happily but something about its mouth seems off. ",
```

2023-07-13 03:49 UTC, TheShadowFerret commented on data/json/monsters/mutant_mammal.json
> +    "description": "This dog has undergone visible mutation. It's paws have developed long digging nails and it's fur is patchily replaced with leathery skin. ",
```suggestion
    "description": "This dog has undergone visible mutation.  Its paws have developed long digging nails and its fur is patchily replaced with leathery skin.",
```

2023-07-13 03:49 UTC, TheShadowFerret commented on data/json/monsters/mutant_mammal.json
> +    "description": "An adorable, but unusual puppy. It wags it's tail happily but something about it's paws seems off. ",
```suggestion
    "description": "An adorable, but unusual puppy.  It wags its tail happily but something about its paws seems off. ",
```

2023-07-14 01:34 UTC, RanikOrtega commented on data/json/monsters/mutant_mammal.json
> +    "description": "This dog has undergone visible mutation. While it's body is larger than normal it's legs are noticeably elongated, muscular and covered in long cord-like fur. It easily stands as
Changes updated in new commit.

2023-07-16 11:26 UTC, sadenar commented
Might make snippets for them in a later PR, aside from that, good work.

2023-07-20 00:58 UTC, RanikOrtega commented
Requesting review when possible. Thanks

2023-07-25 03:29 UTC, Maleclypse commented
I'm not sure that these should be tameable as adults but with the other mutant mongrel being tameable I will go with it.

2023-07-25 03:29 UTC, merged

2023-07-25 12:03 UTC, RanikOrtega commented
> I'm not sure that these should be tameable as adults but with the other mutant mongrel being tameable I will go with it.

These are the most normal of all mutant dogs. Essentially one or two things slightly off about them. Otherwise 90% dog. Anything more severe than these will be non-tameable unless paired with mods.