Add additional refrigerated tanks
CleverRaven/Cataclysm-DDA pull request #67465
Opened 2023-08-05 20:13 UTC by Zoraman26

#### Summary
Content "Add larger refrigerated tank"

#### Purpose of change
Add a larger refrigerated tank and rename existing one to include its capacity

#### Testing
Spawned in, crafted and used

2023-08-05 20:21 UTC, Procyonae commented on data/json/items/vehicle/utilities.json
> +    "insulation": 10,
```suggestion
    "description": "A 100L refrigerated tank for keeping liquids cool.  Provides some insulation from outside weather.",
    "looks_like": "fridgetank",
    "insulation": 10,
```

2023-08-05 21:13 UTC, Maleclypse commented on data/json/items/vehicle/utilities.json
> +    "name": { "str": "refrigerated tank (60L)" },
```suggestion
    "name": { "str": "refrigerated tank (60L)", "str_pl": "refrigerated tanks (60L)" },
```

2023-08-05 21:14 UTC, GuardianDll commented on data/json/items/vehicle/utilities.json
> +    "name": { "str": "refrigerated tank (60L)" },
```suggestion
    "name": { "str": "refrigerated tank (60L)", "str_pl": "refrigerated tanks (60L)" },
```"

2023-08-05 21:14 UTC, GuardianDll commented on data/json/items/vehicle/utilities.json
> +    "name": { "str": "refrigerated tank (100L)" },
```suggestion
    "name": { "str": "refrigerated tank (100L)", "str_pl": "refrigerated tanks (100L)" },
```"

2023-08-05 21:14 UTC, Maleclypse commented on data/json/items/vehicle/utilities.json
> +    "name": { "str": "refrigerated tank (100L)" },
```suggestion
    "name": { "str": "refrigerated tank (100L)", "str_pl": "refrigerated tanks (100L)" },
```

2023-08-05 21:15 UTC, Maleclypse commented on data/json/vehicleparts/tanks.json
> +    "name": { "str": "refrigerated tank (100L)" },
```suggestion
    "name": { "str": "refrigerated tank (100L)", "str_pl": "refrigerated tanks (100L)" },
```

2023-08-05 21:15 UTC, GuardianDll commented
@Maleclypse 60L also

2023-08-05 23:22 UTC, Maleclypse commented
> @Maleclypse 60L also

Do vehicle parts even use string plural outside of item form?

2023-08-06 07:34 UTC, Karol1223 requested changes

2023-08-06 07:34 UTC, Karol1223 commented on data/json/items/vehicle/utilities.json
> +  },
This will be material steel ingame but is made of aluminum in the recipe. Don't.

2023-08-06 07:34 UTC, Karol1223 commented on data/json/vehicleparts/tanks.json
> +      { "item": "scrap", "count": [ 1, 5 ] }
Yet again, item made of aluminum but breaks into steel. Don't swap materials like that.

2023-08-07 12:32 UTC, merged

2023-08-11 17:37 UTC, AmarinReyny commented
Should the same be done for heated tanks, as well?