AFS TSKBEM STEED
CleverRaven/Cataclysm-DDA pull request #67802
Opened 2023-08-21 05:56 UTC by Drew4484

#### Summary
Content "Cyberhorse... CYBERHORSE!"

#### Purpose of change
Walking around sucks, trying to drive over treacherous ice fields and ravines also sucks.

#### Describe the solution
Adds the TSKBEM STEED, an atomic-powered robotic horse, capable of traversing the harshest terrain.

#### Describe alternatives you've considered
None. Robot horses rock. Why would I consider anything else.

#### Testing
WIP

#### Additional context
Will need harness/saddlebags.

2023-08-21 07:48 UTC, Karol1223 requested changes

2023-08-21 07:48 UTC, Karol1223 commented on data/mods/Aftershock/mobs/robots.json
> +    "description": "Found on nearly every frontier planet, the ubiquitous TSKBEM STEED (Surface Traversing Equine Emulating Drone) is an incredibly rugged quadrapedal machine based on old Earth horse
```suggestion
    "description": "Found on nearly every frontier planet, the ubiquitous TSKBEM STEED (Surface Traversing Equine Emulating Drone) is an incredibly rugged quadrupedal machine based on old Earth horses and mules.  Capable of crossing the roughest terrain, powered by a compact atomic reactor, generous storage capacity, light armor, and a lifetime warranty, the STEED is a priceless tool for prospectors and homesteaders.  This version has been ruggedized against Salus IV's extreme cold, but does not keep you warm while riding.",
```

"ruggedized" should be added to the dictionary, though.

2023-08-21 07:48 UTC, Karol1223 commented on data/mods/Aftershock/mobs/robots.json
> +    "color": "silver",
```suggestion
    "color": "light_gray",
```

2023-10-28 04:43 UTC, Maleclypse commented
Woot!

2023-10-28 04:43 UTC, merged