[Xedra Evolved] Eater Sixth Sense
CleverRaven/Cataclysm-DDA pull request #67898
Opened 2023-08-26 00:55 UTC by Maleclypse

#### Summary
None

#### Purpose of change
Give Eater an advanced ability once they've gained some experience in the Class.

#### Describe the solution
Adds a sixth sense enchantment to the Eater class in order to sense creatures of the Nether.  I'll see if I can get someone to add a spell school count condition and if not I'll comment it out and add a spell that you learn upon reaching any Eater spell level of 15.   That spell will then give you the trait that powers the enchantment.

#### Describe alternatives you've considered
None

#### Testing

#### Additional context

2023-08-30 19:26 UTC, dseguin commented on data/mods/Xedra_Evolved/effects/effect_on_condition.json
> +        "u_add_trait": "EATER_SIXTH_SENSE"
```suggestion
      },
      {
        "u_add_trait": "EATER_SIXTH_SENSE"
```

2023-08-30 20:28 UTC, Maleclypse commented on data/mods/Xedra_Evolved/effects/effect_on_condition.json
>  ]
```suggestion
]

```

2023-08-31 04:51 UTC, Maleclypse commented on data/mods/Xedra_Evolved/effects/effects.json
> +        "values": [ { "value": "SIGHT_RANGE_NETHER", "add": { "math": [ "(( u_val('spell_level', , 'school: EATER') * 1.5) + 3)" ] } } ]
```suggestion
        "values": [ { "value": "SIGHT_RANGE_NETHER", "add": { "math": [ "(( u_val('spell_level', 'school: EATER') * 1.5) + 3)" ] } } ]
```

2023-09-01 02:49 UTC, Maleclypse commented
@Standing-Storm do you see what I've done wrong here?

2023-09-01 03:22 UTC, Standing-Storm requested changes

2023-09-01 03:22 UTC, Standing-Storm commented on data/mods/Xedra_Evolved/effects/effect_on_condition.json
> +    "condition": { "compare_num": [ { "u_val": "spell_count", "school": "EATER" }, "=", { "const": 6 } ] },
> "condition": { "compare_num": [ { "u_val": "spell_count", "school": "EATER" }, "=", { "const": 6 } ] },

"condition": { "compare_num": [ { "u_val": "spell_count", "school": "EATER" }, ">=", { "const": 6 } ] },

2023-09-01 03:22 UTC, Standing-Storm commented on data/mods/Xedra_Evolved/enchantments/mutations.json
> +    "effect": "sense_unnatural",
> "effect": "sense_unnatural",
"effect": "attack",
"effect_str": "sense_unnatural",

Needs a duration as well.

2023-09-01 03:22 UTC, Standing-Storm commented on data/mods/Xedra_Evolved/enchantments/mutations.json
> +    "effect": "sense_unnatural",
I don't know how to do the fancy Github changes form so I just used quotes. 🥴

2023-09-01 05:16 UTC, Maleclypse commented on data/mods/Xedra_Evolved/effects/effect_on_condition.json
> +    "condition": { "compare_num": [ { "u_val": "spell_count", "school": "EATER" }, "=", { "const": 6 } ] },
```suggestion
    { "math": [ "u_val('spell_count', 'school: EATER')", ">=", "6" ] }
```

2023-09-01 05:18 UTC, Maleclypse commented on data/mods/Xedra_Evolved/enchantments/mutations.json
> +    "effect": "sense_unnatural",
```suggestion
    "effect": "attack",
    "effect_str": "sense_unnatural",
    "duration": 86000
```

2023-09-01 20:17 UTC, Standing-Storm commented on data/mods/Xedra_Evolved/effects/effect_on_condition.json
> +    { "math": [ "u_val('spell_count', 'school: EATER')", ">=", "6" ] }
```suggestion
    "condition": { "math": [ "u_val('spell_count', 'school: EATER')", ">=", "6" ] }
```

2023-09-02 00:06 UTC, Maleclypse commented on data/mods/Xedra_Evolved/effects/effect_on_condition.json
> +    "condition": { "math": [ "u_val('spell_count', 'school: EATER')", ">=", "6" ] }
```suggestion
    "condition": { "math": [ "u_val('spell_count', 'school: EATER')", ">=", "6" ] },
```

2023-09-04 16:34 UTC, Maleclypse commented on data/mods/Xedra_Evolved/enchantments/mutations.json
> +  },
```suggestion
  }
```

2023-09-04 18:07 UTC, Maleclypse commented on data/mods/Xedra_Evolved/effects/effect_on_condition.json
> +    "effect": [
```suggestion
    "deactivate_condition": { "u_has_trait": "EATER_SIXTH_SENSE" },
    "effect": [
```

2023-09-04 18:07 UTC, Maleclypse commented on data/mods/Xedra_Evolved/effects/effect_on_condition.json
> +      "and": [
```suggestion
```

2023-09-04 18:07 UTC, Maleclypse commented on data/mods/Xedra_Evolved/effects/effect_on_condition.json
> +        { "not": [ { "u_has_trait": "EATER_SIXTH_SENSE" } ] }
```suggestion
```

2023-09-04 18:07 UTC, Maleclypse commented on data/mods/Xedra_Evolved/effects/effect_on_condition.json
> +        { "math": [ "u_val('spell_count', 'school: EATER')", ">=", "6" ] },
```suggestion
        { "math": [ "u_val('spell_count', 'school: EATER')", ">=", "6" ] }
```

2023-09-04 18:08 UTC, Maleclypse commented on data/mods/Xedra_Evolved/effects/effect_on_condition.json
> +      ]
```suggestion
```

2023-09-04 18:08 UTC, Maleclypse commented on data/mods/Xedra_Evolved/effects/effect_on_condition.json
> +    "condition": {
```suggestion
    "condition": 
```

2023-09-04 18:08 UTC, Maleclypse commented on data/mods/Xedra_Evolved/effects/effect_on_condition.json
> +    },
```suggestion
```

2023-09-04 20:13 UTC, merged