Martial arts homebook jsoning
CleverRaven/Cataclysm-DDA pull request #68566
Opened 2023-10-08 19:56 UTC by Aracken43

Going to make it a extremely small chance for any martial arts book to spawn in any house. Emphasis on "extremely small".
Found it weird no houses really had any chance for MA's so here we are. 3 months in the makin. Feel free to comment as I'm still running tests on the code to make sure it doesn't do a kickflip and spawn like 80 MA books

2023-10-12 06:03 UTC, Dan1ss1mo requested changes

2023-10-12 06:03 UTC, Dan1ss1mo commented on data/json/itemgroups/books.json
> +      { "item": "home_martial_arts_books", "prob": 1 },
```suggestion
      { "group": "home_martial_arts_books", "prob": 1 },
```

2023-10-12 06:03 UTC, Dan1ss1mo commented on data/json/itemgroups/books.json
> +      { "item": "home_martial_arts_books", "prob": 1 },
```suggestion
      { "group": "home_martial_arts_books", "prob": 1 },
```

2023-10-14 06:32 UTC, merged

2023-10-18 11:46 UTC, Aracken43 commented
It is le mysanchezgamer, gamer of the....sanchezs?
THE PR GOT MERGED THANKS!