Add more prosthetics and their recipes
CleverRaven/Cataclysm-DDA pull request #68819
Opened 2023-10-22 20:10 UTC by MNG-cataclysm

#### Summary
Content "Add more prosthetics and recipes to make them."

#### Purpose of change
Add some more prosthetics to increase functionality and variety for the player, and some recipes to make them.

#### Describe the solution
Add basic wooden peg legs with some cushioning on the inside. These don’t work as well as a regular prosthetic, but they’re the easiest to craft and require basic materials. Antique iron prosthetics have been added too, which work quite well but are difficult to make, and are quite heavy. Wooden peg legs are autolearned at fabrication 3, while iron ones come in “Arms and Armor”.

#### Describe alternatives you've considered
Not doing this, or only having a single type of prosthetic.

#### Testing
Loaded up the game and played around with these, everything works great.

#### Additional context
I plan on adding a recipe for modern prosthetics, I just still need to find out how they are made. I’ll eventually add arm prosthetics too.

2023-10-22 20:49 UTC, dood198 commented
nice

2023-10-22 22:10 UTC, MNG-cataclysm commented
> nice

Thank you.

2023-10-23 12:51 UTC, Brambor requested changes
typos

2023-10-23 12:51 UTC, Brambor commented on data/json/items/armor/legs_prosthetics.json
> +    "description": "A prosthetic leg, used as a replacement limb for those missing one.  Dating back to the Middle Ages and the Renaissance, this prosthetic is made of iron placed over a framework, a
```suggestion
    "description": "A prosthetic leg, used as a replacement limb for those missing one.  Dating back to the Middle Ages and the Renaissance, this prosthetic is made of iron placed over a framework, and is attached with leather straps to the leg, padding placed inside for comfort.  Made in a better fashion than more common prosthetics at the time, this limb is incredibly durable, with many noble warriors wearing these into battle.  However, they were incredibly expensive, time-consuming to make, and quite heavy, leaving them out of the hands of poorer individuals.  This one is for the right leg.",
```

2023-10-23 12:51 UTC, Brambor commented on data/json/items/armor/legs_prosthetics.json
> +    "description": "A prosthetic leg, used as a replacement limb for those missing one.  Dating back to the Middle Ages and the Renaissance, this prosthetic is made of iron placed over a framework, a
```suggestion
    "description": "A prosthetic leg, used as a replacement limb for those missing one.  Dating back to the Middle Ages and the Renaissance, this prosthetic is made of iron placed over a framework, and is attached with leather straps to the leg, padding placed inside for comfort.  Made in a better fashion than more common prosthetics at the time, this limb is incredibly durable, with many noble warriors wearing these into battle.  However, they were incredibly expensive, time-consuming to make, and quite heavy, leaving them out of the hands of poorer individuals.  This one is for the left leg.",
```

2023-10-23 19:50 UTC, merged