Exodii Launcher Sidearms
CleverRaven/Cataclysm-DDA pull request #68914
Opened 2023-10-26 02:07 UTC by tenmillimaster

#### Summary
Content"Adds Long awaited Exodii Sidearms"

#### Purpose of change

The Exodii deserve sidearms. The Exodii, doing their best to adapt to fighting an enemy that does not easily succumb to non-mortal wounds, would have sidearms different to ours. Since our sidearms take on massive penalties to lethality in the name of portability, I sought to cherry pick a technological scenario that could plausibly produce such a firearm as the Exodii would want -- As a rule almost all exodii equipment is not purpose built for the task, after all, but rather adapted.

#### Describe the solution

On the civilian side:
Punt guns are heavy fowling pieces that are used to take on scores of birds  to bring to market in commercial hunting.
Big game guns are heavy rifles/smoothbores that are used to shoot at dangerous game.
On the martial side:
Swivel guns are light cannon mounted to the deck for shooting at other seamen.
Wall guns are heavy guns/light cannon that are mounted to battlements for shooting at oncoming troops.

So what if you had a nation of avid hunters and fowlers who had to push their civilian firearms into service during a war? You get light swivel/wall guns.  And these are about the right bore diameter for useful payload launching capability, and the actions are plenty strong enough less powerful launching of explosives, whose payloads aren't kinetic energy dependent.

So you chop down a number of these guns for use as launchers and sidearms (howdahs). You get a gun that the humans would have used with the smaller launcher cartridges, but the exodii chamber the original cartridges in.

The numbers for the large cartridge are based on the 4-bore cartridge, a 1 inch bore caliber that was popular pre- expressgun for taking dangerous game and itself evolved from 4-gauge shotguns.

The numbers for the smaller cartridge are based on the the sturmpistole, an adapted flare pistol that was used for launching flares and grenades. An additional rifle grenade of the same origin is also included.

#### Describe alternatives you've considered

Chopped down shotguns, but then these would not have such an extensive array of military loads available.

#### Testing

Ongoing. There's a lot of stuff I need to doublecheck.
#### Additional context

In draft for a bit longer. Need to figure out how to add addn'l  trader levels right now.

2023-10-26 02:47 UTC, TheShadowFerret reviewed
Not in comments:
1) 27.3x110/44 *whats*? Units good 😛
2) Consistency with vanilla gun/ammo/magazine files is that these new items should be split from 12.3ln(file for which should probably be renamed to 123ln.json)

2023-10-26 02:47 UTC, TheShadowFerret commented on data/json/items/ammo/exodii.json
> +    "description": "These flare cartridges are for use in 27.3x44 Diyua guns, or perhaps in 27.3x110 Diyua guns.  They are employed by Exodii for emergency signalling when their usual communications
```suggestion
    "description": "These flare cartridges are for use in 27.3x44 Diyua guns, or perhaps in 27.3x110 Diyua guns.  They are employed by Exodii for emergency signaling when their usual communications systems are suffering interference, breakdown, or are being jammed.",
```

2023-10-26 02:47 UTC, TheShadowFerret commented on data/json/items/ammo/exodii.json
> +    "description": "A 27.3x44 Diyua cartridge with a minute amount of liquid fuel encasing a fuel dispersing explosive charge, and a secondary ignition charge.  On impact the fuel is dispersed, creat
```suggestion
    "description": "A 27.3x44 Diyua cartridge with a minute amount of liquid fuel encasing a fuel dispersing explosive charge, and a secondary ignition charge.  On impact the fuel is dispersed, creating a fuel-air mixture which is ignited a few milliseconds later.  In a cartridge like 27.3x44 Diyua, the pressure wave produced is rather diminutive, yet it makes the most of what little payload is available.",
```

2023-10-26 02:47 UTC, TheShadowFerret commented on data/json/items/ammo_types.json
> +    "name": "2.73x110 Diyua",
```suggestion
    "name": "27.3x110 Diyua",
```

2023-10-26 02:47 UTC, TheShadowFerret commented on data/json/items/ammo_types.json
> +    "name": "2.73x44 Diyua",
```suggestion
    "name": "27.3x44 Diyua",
```

2023-10-26 02:47 UTC, TheShadowFerret commented on data/json/items/ammo_types.json
> +    "name": "2.73x44 Diyua Grenade",
```suggestion
    "name": "27.3x44 Diyua Grenade",
```
No skinny grenades for you

2023-10-26 02:47 UTC, TheShadowFerret commented on data/json/items/generic/casing.json
> +    "name": { "str": "27.3 x 110 Diyua casing" },
```suggestion
    "name": { "str": "27.3x110 Diyua casing" },
```

2023-10-26 02:47 UTC, TheShadowFerret commented on data/json/items/generic/casing.json
> +    "name": { "str": "27.3 x 44 Diyua casing" },
```suggestion
    "name": { "str": "27.3x44 Diyua casing" },
```

2023-10-26 02:47 UTC, TheShadowFerret commented on data/json/items/gun/exodii.json
> +        "description": "Originating from big game express smoothbores and heavy fowling pieces adapted for wallguns, the Brogyeki '23 is an over/under break action 'pistol' that is (unfortunately?) c
```suggestion
        "description": "Originating from big game express smoothbores and heavy fowling pieces adapted for wallguns, the Brogyeki '23 is an over/under break action 'pistol' that is (unfortunately?) capable of launching its original 27.3x110 Diyua express slug and shot loads as well as the wide array of payloads in 27.3x44 Diyua.  A simple wire stock collapses neatly along its octagonal barrels, which feature a combination of sighting devices necessary for launching its numerous loads, in addition to the usual Exodii retrofits.  Unless you are a quadrupedal cyborg with this gun in a shock absorbing mount, recoil with the 27.3x110 Diyua shells will be *stout*.",
```

2023-10-26 02:47 UTC, TheShadowFerret commented on data/json/items/gun/exodii.json
> +    "description": "An over/under fowling piece with a long barrel, Brogyaga were favored for their versatility in taking large game and fowl with their 27.3 x 110 Diyua shells.  They would be presse
```suggestion
         "description": "An over/under fowling piece with a long barrel, Brogyaga were favored for their versatility in taking large game and fowl with their 27.3x110 Diyua shells.  They would be pressed into combat during two global conflicts, initially as 'light' wall guns, and later as the downsized and down-loaded Brogyeki '23, before being brought along by the Exodii to dimensions unknown.  Though unwieldy in combat as either a primary or secondary, Brogyaga serve as useful parts donors for Brogyeki counterparts, fantastic pieces for the occasional hunting party, and popular trade goods for the locals.",
```

2023-10-26 02:47 UTC, TheShadowFerret commented on data/json/items/gun/exodii.json
> +        "description": "The Sapra '36 is a short smoothbore bolt-action grenade launcher, fitted with a 5-round box magazine and a large, efficent muzzle brake.  Designed in the interwar period follo
```suggestion
        "description": "The Sapra '36 is a short smoothbore bolt-action grenade launcher, fitted with a 5-round box magazine and a large, efficient muzzle brake.  Designed in the interwar period following the proliferation of Brogyeki '23, the Sapra was intended to assist in riots, ambushes and assaulting in urban operations, where explosives applied in quick succession could make short work of targets.  To further assist in riot operations, the Sapra can be fitted with a bayonet, a frivolity that the Exodii almost immediately discarded.  Unlike the Brogyeki, the Sapra is incapable of chambering the longer 27.3x110 Diyua shells.  The Exodii have replaced the stock with an aluminum alloy chassis, leaving behind the original wood ones as they became damaged.",
```

2023-10-26 02:47 UTC, TheShadowFerret commented on data/json/items/magazine/exodii.json
> +    "description": "A large, 5 round single stack magazine for the Sapra '36.",
```suggestion
    "description": "A large, five round single stack magazine for the Sapra '36.",
```
Proper gramma' demands <10 is spelt

2023-10-26 10:40 UTC, tenmillimaster commented
> Not in comments:
> 
> 1. 27.3x110/44 _whats_? Units good 😛

Where Ln is the unit of measurement for 1.23 Ln, Diyua is the unit of measurement for 27.3x44/110. (27.3 Diyua is about 1 inch, or 25.4mm.)
> 2. Consistency with vanilla gun/ammo/magazine files is that these new items should be split from 12.3ln(file for which should probably be renamed to 123ln.json)
Eh, I thought about this but figure the file was named Exodii for a reason. Looking at the Hub guns, they're all in one file too.

2023-10-28 17:25 UTC, harakka requested changes

2023-10-28 17:25 UTC, harakka commented on data/json/items/ammo/exodii.json
> +    "description": "27.3x110 Diyua slug loads similiar to these were employed by colonists on some alternate earth to take extremely dangerous game.  This heavy slug load however, was used almost ent
```suggestion
    "description": "27.3x110 Diyua slug loads similar to these were employed by colonists on some alternate earth to take extremely dangerous game.  This heavy slug load however, was used almost entirely by recoil enthusiasts and braggarts, until the Exodii came upon them.",
```

2023-10-28 17:25 UTC, harakka commented on data/json/items/ammo/exodii.json
> +    "description": "A long 27.3 Diyua cartridge loaded with a propelling charge, attached to a large high explosive shaped charge grenade several times larger in diameter.  It was designed to be muzz
```suggestion
    "description": "A long 27.3 Diyua cartridge loaded with a propelling charge, attached to a large high explosive shaped charge grenade several times larger in diameter.  It was designed to be muzzle loaded into 27.3x44 Diyua guns.  Though the grenade's penetration and fragmentation were ultimately deemed insufficient, this was of no matter to the Exodii who saw value in the explosive potential the grenade added to the Brogyeki '23.",
```

2023-11-15 16:12 UTC, tenmillimaster commented
Did the generic guns stuff.

2023-11-18 01:01 UTC, merged