[MoM] Psychic Animal Redux
CleverRaven/Cataclysm-DDA pull request #69430
Opened 2023-11-16 04:48 UTC by Maleclypse

#### Summary
Mods "Additional psychic fauna"

#### Purpose of change
Adds a couple of additional psychic fauna to MoM

#### Describe the solution
Birds man.  I feel possessed by the spirit of Alfred Hitchcock

#### Describe alternatives you've considered
Not psychic birds

#### Testing

#### Additional context

2023-11-16 04:54 UTC, Maleclypse commented
@Standing-Storm I'm wanting to give the pigeon passengers an area of effect aura that is provides a vitamin to any PC/NPCs inside the aura.  I want that effect to provide a vitamin to the characters slowly while they are in the aura and that vitamin as it increases increases strength while decreasing intelligence. I can make the vitamin effects work but I can't figure out how to make the aura/area of effect that impacts the pc whether they have tamed the pigeon passengers or not.  Any ideas?

2023-11-16 04:54 UTC, Maleclypse commented on data/mods/MindOverMatter/monsters/animal_psychics.json
> +  }
```suggestion
  },
```

2023-11-16 04:55 UTC, Maleclypse commented on data/mods/MindOverMatter/monsters/monster_overrides.json
> +    "upgrades": { "half_life": 30, "into_group": "GROUP_PIGEON_UPGRADE" },
```suggestion
    "upgrades": { "half_life": 30, "into_group": "GROUP_PIGEON_UPGRADE" }
```

2023-11-16 06:14 UTC, Maleclypse commented on data/mods/MindOverMatter/monsters/animal_psychics.json
> +    "description": "A gentle, plump, small-billed bird with a third eye, between its bill and forehead.  On the ground, it struts about with a characteristic bobbing of the head.  It is a strong, swi
```suggestion
    "description": "A gentle, plump, small-billed bird with a third eye, between its bill and forehead.  On the ground, it struts about with a characteristic bobbing of the head.  It is a strong, swift flier thanks to its long wings and powerful flight muscles.  Is it following you?",
```

2023-11-16 16:00 UTC, Standing-Storm commented
hmm...is that problem that the aura only applies when not tamed, only when tamed, or neither?

2023-11-17 23:02 UTC, Maleclypse commented
> hmm...is that problem that the aura only applies when not tamed, only when tamed, or neither?

Haven't even started on the aura part not sure where to start with that lol.  I know what I want to do, I'm not sure if there is any way to do it beyond creating an invisible field they emit, but would that tank performance?

2023-11-17 23:02 UTC, Maleclypse commented on data/mods/MindOverMatter/monstergroups/monster_faction.json
> +]
```suggestion
]

```

2023-11-19 15:01 UTC, Standing-Storm commented
Another possibility would be the way I did dragon breath in #68035--give them a spell on a cooldown that fires and, it it hits a target, gives them an effect, then make casting the aura contingent on them having the effect. So if there's anyone nearby, they'll stack up the aura until the effect allowing them to cast it fades, but they won't be constantly trying to spam the aura in combat and it won't have the performance problems lots of fields do.

2023-11-26 20:18 UTC, Maleclypse commented on data/mods/MindOverMatter/monstergroups/monster_faction.json
> +    "hates": [ "corvid", "ratkin" ]
```suggestion
    "hate": [ "corvid", "ratkin" ]
```

2023-11-26 20:18 UTC, Maleclypse commented on data/mods/MindOverMatter/monstergroups/monster_faction.json
> +    "hates": "fear_hawk"
```suggestion
    "hate": "fear_hawk"
```

2023-11-26 20:18 UTC, Maleclypse commented on data/mods/MindOverMatter/monstergroups/monster_faction.json
> +    "hates": "fear_hawk"
```suggestion
    "hate": "fear_hawk"
```

2023-11-26 23:19 UTC, Maleclypse commented on data/mods/MindOverMatter/monsters/monster_special_attacks.json
> +    "miss_msg_u": "%s's shriek radiates at you, but you dodge!",
```suggestion
    "miss_msg_u": "%s's shriek radiates at you, but you dodge!"
```

2023-12-09 07:29 UTC, Maleclypse commented on data/mods/MindOverMatter/effects/effects_monster.json
> +    "decay_messages": [ [ "" ] ],
```suggestion
    "decay_messages": [ [ "" ] ],
```

2023-12-11 06:35 UTC, Maleclypse commented on data/mods/MindOverMatter/effects/effects_monster.json
> +    "apply_message": [ [ "" ] ],
```suggestion
```

2023-12-11 18:07 UTC, Maleclypse commented on data/mods/MindOverMatter/effects/effects_monster.json
>      "id": "effect_feral_regeneration",
```suggestion
    "type": "effect_type",
    "id": "effect_feral_regeneration",
```

2023-12-13 03:10 UTC, Maleclypse commented on data/mods/MindOverMatter/monsters/monster_eoc_spells.json
> +    "condition": { "u_is_character": true },
```suggestion
    "condition": { "u_is_character" },
```

2023-12-15 02:44 UTC, Maleclypse commented on data/mods/MindOverMatter/monsters/monster_eoc_spells.json
> +    "condition": { "u_is_character" },
```suggestion
    "condition": "u_is_character",
```

2023-12-15 04:09 UTC, Maleclypse commented
@Standing-Storm did you move this ` delete_nullifying_fields_monster (spell_type) has two definitions from the same source (mindovermatter)!` or have I duplicated it in conflict resolution?

2023-12-15 04:10 UTC, Standing-Storm commented
> @Standing-Storm did you move this ` delete_nullifying_fields_monster (spell_type) has two definitions from the same source (mindovermatter)!` or have I duplicated it in conflict resolution?

I did--I moved it over to death_effects (since it's only used on zombie null death)

2023-12-15 05:42 UTC, Maleclypse commented on data/mods/MindOverMatter/monsters/monsters_spells.json
> +  },
```suggestion
```

2023-12-15 14:33 UTC, Maleclypse commented
@Standing-Storm please review.  Feel free to make any changes you want :)

2023-12-15 19:52 UTC, Standing-Storm requested changes
Just a couple changes but looks great! I especially love the pigeons--MoM needs more psionic animals that aren't predatory (either on humans or on other animals).

2023-12-15 19:52 UTC, Standing-Storm commented on data/mods/MindOverMatter/effects/effects_monster.json
> +    "blood_analysis_description": "Blood sample contains psionic steroid particles and pigeon dander.",
```suggestion
    "blood_analysis_description": "Blood sample contains noetic steroid particles and pigeon dander.",
```

2023-12-15 19:52 UTC, Standing-Storm commented on data/mods/MindOverMatter/monsters/animal_psychics.json
> +        "range": 3,
```suggestion
        "range": 3,
        "condition": { "not": { "u_has_effect": "effect_psi_null" } },
```

2023-12-15 19:52 UTC, Standing-Storm commented on data/mods/MindOverMatter/monsters/monsters_spells.json
> +    "skill": "deduction",
```suggestion

```

2023-12-15 19:52 UTC, Standing-Storm commented on data/mods/MindOverMatter/monsters/monsters_spells.json
> +    "description": "You consume human blood to keep the thirst at bay.",
```suggestion
    "description": "Anyone nearby will get stronger.",
```
Those are some hardcore pigeons

2023-12-16 17:37 UTC, Maleclypse commented on data/mods/MindOverMatter/monsters/monsters_spells.json
> +    "description": "You consume human blood to keep the thirst at bay.",
Oops thanks for catching that!

2023-12-27 21:41 UTC, merged

2023-12-28 00:19 UTC, prharvey commented
This is breaking the build: `mon_pigeon` is duplicated.

2023-12-28 00:42 UTC, BrettDong commented
I'm puzzled how basic build test passed here while `mon_pigeon` is duplicated in `data/mods/MindOverMatter/monsters/monster_overrides.json` and `data/mods/MindOverMatter/monsters/monster_overrides_tameable.json`.

2023-12-28 01:17 UTC, Standing-Storm commented
Fix up: #70487

2023-12-28 01:46 UTC, Maleclypse commented
> I'm puzzled how basic build test passed here while `mon_pigeon` is duplicated in `data/mods/MindOverMatter/monsters/monster_overrides.json` and `data/mods/MindOverMatter/monsters/monster_overrides_tameable.json`.

Basic build test passed at least a week ago before the monster_overrides_tameable.json even existed.  So the Tameable monsters PR was merged this PR suffered no-conflicts and tests weren't rerun. Simple timing.