More Mycus Monsters
CleverRaven/Cataclysm-DDA pull request #69523
Opened 2023-11-18 20:38 UTC by zdlpoppa

#### Summary
Content "Adds more fungal monsters"

#### Purpose of change
Adds more fungal content, i.e. new fungalized zombie variants, including human and animal. 

#### Describe the solution
Most monsters turned into the generic fungal zombie when spored, with this contribution there will be more specialized monsters.

#### Describe alternatives you've considered
Not making the fungal fellas.

#### Testing
Tested on multiple worlds with multiple different characters, never experienced crashes or errors during the tests, even when fungalizing into other monsters.

#### Additional context
This is my first contribution, so feedback and criticisms would be very appreciated!

2023-11-18 22:20 UTC, carlarctg commented on data/json/monsters/fungus_zombie.json
> +    "description": "The rotten skin that flakes from the host's body seems to be covered in tiny blue dots; occasional popping and crackling sounds are heard, like cracking wood. this corpse can't be
```suggestion
    "description": "The rotten skin that flakes from the host's body seems to be covered in tiny blue dots; occasional popping and crackling sounds are heard, like cracking wood. this corpse can't be discerned as human by the naked eye.",
```

2023-11-19 01:10 UTC, detahramet requested changes
Looks good! Mostly just a few style tweaks, but its all around pretty solid!

2023-11-19 01:10 UTC, detahramet commented on data/json/monsters/fungus_zombie.json
> +    "name": { "str": "fungal dog" },
```suggestion
    "name": { "str": "fungal dog" },
```

2023-11-19 01:10 UTC, detahramet commented on data/json/monsters/fungus_zombie.json
> +    "name": { "str": " rotten fungal horse" },
```suggestion
    "name": { "str": " rotten fungal horse" },
```

2023-11-19 01:10 UTC, detahramet commented on data/json/monsters/fungus_zombie.json
> +    "description": "This hulking horse-figure seems to re-learn galloping with every step, as large fungi cling and sprout off of it's mane. It travels towards anything moving, even though in the cen
The poor baby!

2023-11-19 01:10 UTC, detahramet commented on data/json/monsters/fungus_zombie.json
> +    "description": "The deformed, animated, and again reanimated corpse of a what looked like the concept of a canine. It's lost almost all of it's dog-like features, except for it's constant aggress
```suggestion
    "description": "The deformed, animated, and again reanimated corpse of a what looked like the concept of a canine.  It's lost almost all of it's dog-like features, except for it's constant aggressive growling, and tendency to bite. It shakes it's fur like a wet dog, sending tiny spore clouds everywhere.",
```

2023-11-19 01:10 UTC, detahramet commented on data/json/monsters/fungus_zombie.json
> +    "description": "This hulking horse-figure seems to re-learn galloping with every step, as large fungi cling and sprout off of it's mane. It travels towards anything moving, even though in the cen
```suggestion
    "description": "This hulking horse-figure seems to re-learn galloping with every step, as large fungi cling and sprout off of it's mane.  It travels towards anything moving, even though in the center of each eye lies multiple fungi blooms.",
```

2023-11-19 01:10 UTC, detahramet commented on data/json/monsters/fungus_zombie.json
> +    "description": "This rotting tiger has lost it's stumble, and large fungi bulbs seem to have extended it's pawpads throughly. It's head crackles when trying to turn, seemingly stuck facing forwar
```suggestion
    "description": "This rotting tiger has lost it's stumble,as large fungi bulbs seem to have extended it's pawpads throughly.  It's head crackles when trying to turn, seemingly stuck facing forward.",
```

2023-11-19 01:10 UTC, detahramet commented on data/json/monsters/fungus_zombie.json
> +    "description": "This bumpy, discolored reindeer resembles a malformed rudolph, it's nose having a faintly glowing red fungi sprout. It'd look almost comical if it wasn't mutilating bodies with it
```suggestion
    "description": "This bumpy, discolored reindeer resembles a malformed rudolph, it's nose having a faintly glowing red fungi sprout.  It'd look almost comical if it wasn't mutilating bodies with it's innate strength.",
```

2023-11-19 04:21 UTC, TheShadowFerret requested changes
Its

2023-11-19 04:21 UTC, TheShadowFerret commented on data/json/monsters/fungus_zombie.json
> +    "description": "Fungal sprouts seem to support the host's broken legs like crude splints.  even with it's eyes shrouded with tiny spores, it darts towards anything that seems to move in a small r
```suggestion
    "description": "Fungal sprouts seem to support the host's broken legs like crude splints.  Even with its eyes shrouded with tiny spores, it darts towards anything that seems to move in a small radius.",
```

2023-11-19 04:21 UTC, TheShadowFerret commented on data/json/monsters/fungus_zombie.json
> +    "description": "This terrifying fungal construct seems to have lost all facial features, it's face covered in thick fungal sprouts.  It's arms end in jagged points as fungal tendrils burst forth.
```suggestion
    "name": { "str": "fungal bulk" },
    "description": "This terrifying fungal construct seems to have lost all facial features, its face covered in thick fungal sprouts.  Its arms end in jagged points as fungal tendrils burst forth.",
```

2023-11-19 04:21 UTC, TheShadowFerret commented on data/json/monsters/fungus_zombie.json
> +    "description": "This fungal monster struggles to move as bulbous mushrooms grow from it's exposed back.  Its leg's seem to be wrapped in sturdy tendrils, and it's arms visibly swell and pop grues
```suggestion
    "description": "This fungal monster struggles to move as bulbous mushrooms grow from its exposed back.  Its leg seems to be wrapped in sturdy tendrils, and its arms visibly swell and pop gruesomely with each drag along the ground.",
```

2023-11-19 04:21 UTC, TheShadowFerret commented on data/json/monsters/fungus_zombie.json
> +    "description": "Patches of fungal growths emerge from the soft, unscarred skin of the host, as visible dent's are made into the tough callouses and scar tissue, attempting to break through.",
```suggestion
    "description": "Patches of fungal growths emerge from the soft, unscarred skin of the host, as visible dents are made into the tough callouses and scar tissue, attempting to break through.",
```

2023-11-19 04:21 UTC, TheShadowFerret commented on data/json/monsters/fungus_zombie.json
> +    "description": "The deformed, animated, and again reanimated corpse of a what looked like the concept of a canine.  It's lost almost all of it's dog-like features, except for it's constant aggres
```suggestion
    "description": "The deformed, animated, and again reanimated corpse of a what looked like the concept of a canine.  It's lost almost all of it's dog-like features, except for its constant aggressive growling, and tendency to bite. It shakes its fur like a wet dog, sending tiny spore clouds everywhere.",
```

2023-11-19 04:21 UTC, TheShadowFerret commented on data/json/monsters/fungus_zombie.json
> +    "description": "This formerly-majestic beast has lost any semblance of what a moose is, aside from it's outgrown antlers, now covered in writhing fungal tendrils, seemingly trying to break into t
```suggestion
    "description": "This formerly-majestic beast has lost any semblance of what a moose is, aside from its outgrown antlers, now covered in writhing fungal tendrils, seemingly trying to break into the cracking bone.  The animated corpse seems in a state of constant disrepair, held together by strange, sticky blue orbs.",
```

2023-11-19 04:21 UTC, TheShadowFerret commented on data/json/monsters/fungus_zombie.json
> +    "description": "This four legged, oversized cat seems to spew spores from it's pawpads with each clusmy landing, as if constantly gaining and losing balance in air.",
```suggestion
    "description": "This four legged, oversized cat seems to spew spores from its pawpads with each clusmy landing, as if constantly gaining and losing balance in air.",
```

2023-11-19 04:21 UTC, TheShadowFerret commented on data/json/monsters/fungus_zombie.json
> +    "description": "This hulking horse-figure seems to re-learn galloping with every step, as large fungi cling and sprout off of it's mane.  It travels towards anything moving, even though in the ce
```suggestion
    "description": "This hulking horse-figure seems to re-learn galloping with every step, as large fungi cling and sprout off of its mane.  It travels towards anything moving, even though in the center of each eye lies multiple fungi blooms.",
```

2023-11-19 04:21 UTC, TheShadowFerret commented on data/json/monsters/fungus_zombie.json
> +    "description": "This rotting tiger has lost it's stumble,as large fungi bulbs seem to have extended it's pawpads throughly.  It's head crackles when trying to turn, seemingly stuck facing forward
```suggestion
    "description": "This rotting tiger has lost its stumble, as large fungi bulbs seem to have extended its pawpads thoroughly.  Its head crackles when trying to turn, seemingly stuck facing forward.",
```

2023-11-19 04:21 UTC, TheShadowFerret commented on data/json/monsters/fungus_zombie.json
> +    "description": "This deer's thick fur is spotted with blue orbs that seem to pop and ooze every few minutes, and it's rotten skin seem's unable to fall off, held together by thick fungal bedding
```suggestion
    "description": "This deer's thick fur is spotted with blue orbs that seem to pop and ooze every few minutes, and its rotten skin seems unable to fall off, held together by thick fungal bedding underneath.",
```

2023-11-19 04:21 UTC, TheShadowFerret commented on data/json/monsters/fungus_zombie.json
> +    "description": "This bumpy, discolored reindeer resembles a malformed rudolph, it's nose having a faintly glowing red fungi sprout.  It'd look almost comical if it wasn't mutilating bodies with i
```suggestion
    "description": "This bumpy, discolored reindeer resembles a malformed Rudolph, its nose having a faintly glowing red fungi sprout.  It'd look almost comical if it wasn't mutilating bodies with its innate strength.",
```

2023-11-19 23:19 UTC, Spicyshadow commented
Should the fungal variants of zombies keep thier eyesight and speed? The current zombies ingame all lose part of their speed and eyesight by the process of fungalization. The runner doesn´t lose any speed dispite having broken legs. The dog, horse, cougar, deer and moose keep thier speed dispite their fungalization process. The moose and maybe deer also gets too keep its eyesight which is strange as every other fungal creature losses much of thiers.

I also think that the zero bleedrate on ALL creatures get is an oversight. The normal variants of these creatures still have a normal bleed rate and cardiovascular system. Getting a fungal infection doesn´t change that. So the fungal variants should have the same bleedrate.

2023-11-20 19:29 UTC, zdlpoppa commented
> Should the fungal variants of zombies keep thier eyesight and speed? The current zombies ingame all lose part of their speed and eyesight by the process of fungalization. The runner doesn´t lose any speed dispite having broken legs. The dog, horse, cougar, deer and moose keep thier speed dispite their fungalization process. The moose and maybe deer also gets too keep its eyesight which is strange as every other fungal creature losses much of thiers.
> 
> I also think that the zero bleedrate on ALL creatures get is an oversight. The normal variants of these creatures still have a normal bleed rate and cardiovascular system. Getting a fungal infection doesn´t change that. So the fungal variants should have the same bleedrate.
1: some of the non-speed changes were oversights on my part, as well as the sight issues.

2: fungal monsters bleeding wouldn't make as much sense, as mushrooms can't bleed, and the host is only carried by the fungal infection, having everything except it's form (I.E: meat, skin, some organs, ect) stripped, for the most part.

2023-11-21 21:46 UTC, closed without merging