More Mycus Monsters 2: Electric Bogaloo
CleverRaven/Cataclysm-DDA pull request #69631
Opened 2023-11-21 22:01 UTC by zdlpoppa

#### Summary
Content "Adds more fungalized humanoid/animal zombie variants."

#### Purpose of change
Fungal creature variety is simply underwhelming currently, being able to encounter different types of fungal enemies/friends would make the faction/race a bit more interesting.

#### Describe the solution
Mainly adds more monster blocks, while adding the appropriate "fungalize_into": for normal humanoid/animal monsters so the monsters can appear properly in game.

#### Describe alternatives you've considered
Not making the fungal fellas.

#### Testing
A few test runs on my own world, haven't encountered any errors yet.

#### Additional context
This is the 2nd version of More Mycus Monsters, and my first technical contribution. Any additional critiques/help would be greatly appreciated!

2023-11-22 11:58 UTC, TheShadowFerret commented on data/json/monsters/fungus_zombie.json
> +    "description": "The deformed, animated, and again reanimated corpse of a what looked like the concept of a canine.  It's lost almost all of it's dog-like features, except for its constant aggress
```suggestion
    "description": "The deformed, animated, and again reanimated corpse of a what looked like the concept of a canine.  It's lost almost all of its dog-like features, except for its constant aggressive growling, and tendency to bite.  It shakes its fur like a wet dog, sending tiny spore clouds everywhere.",
```

2023-11-25 12:50 UTC, NetSysFire commented on data/json/monsters/fungus_zombie.json
> +    "description": "The rotten skin that flakes from the host's body seems to be covered in tiny blue dots; occasional popping and crackling sounds are heard, like cracking wood.  this corpse can't b
```suggestion
    "description": "The rotten skin that flakes from the host's body seems to be covered in tiny blue dots; occasional popping and crackling sounds are heard, like cracking wood.  This corpse can't be discerned as human by the naked eye.",
```

2023-11-25 12:50 UTC, NetSysFire commented on data/json/monsters/fungus_zombie.json
> +    "description": "The deformed, animated, and again reanimated corpse of a what looked like the concept of a canine.  It's lost almost all of its dog-like features, except for its constant aggressi
```suggestion
    "description": "The deformed, animated, and again reanimated corpse of a what looked like the concept of a canine.  It has lost almost all of its dog-like features, except for its constant aggressive growling, and tendency to bite.  It shakes its fur like a wet dog, sending tiny spore clouds everywhere.",
```

2023-11-26 17:35 UTC, Maleclypse requested changes, later dismissed

2023-11-26 17:35 UTC, Maleclypse commented on data/json/monsters/fungus_zombie.json
> +    "families": [ "prof_intro_biology", "prof_wp_zombie" ],
Just noticed you aren't using the fungal weakpoints from #69583.

2023-11-26 17:36 UTC, Maleclypse commented on data/json/monsters/fungus_zombie.json
> +    "families": [ "prof_intro_biology", "prof_wp_zombie" ],
Otherwise this looks really close to merging.

2023-11-26 20:23 UTC, merged