Missed Christmas
CleverRaven/Cataclysm-DDA pull request #70469
Opened 2023-12-27 01:04 UTC by The-Anjelo-Guy

Added Mall Santa as a profession, I'll be adding items in the following job.

#### Summary
Content  "Mall Santa profession and Santa items"

#### Purpose of change
I thought it would be cool to have a Mall Santa profession in Christmas, even though I'm probably too late.

#### Describe the solution

#### Describe alternatives you've considered

#### Testing

#### Additional context

2023-12-27 01:41 UTC, Termineitor244 commented
Most of the items you are using for the profession don't actually exist... And I would know it since I added the ones that are in the game right now! Also, if you are planning to add them in this PR, then most of them should be just variants of existing items, like the necklace or the wristwatch, like how I added vampire rings/necklace and the like, they are small and similar enough to be represented with a variant.

2023-12-27 03:13 UTC, The-Anjelo-Guy commented
> Most of the items you are using for the profession don't actually exist... And I would know it since I added the ones that are in the game right now! Also, if you are planning to add them in this PR, then most of them should be just variants of existing items, like the necklace or the wristwatch, like how I added vampire rings/necklace and the like, they are small and similar enough to be represented with a variant.
> 
> Oh, and if you add the new items/variants please add them to the cosplays itemgroups like the rest of the santa items, there are some new santa itemdrops too for Christmas so those groups are a good idea for these items too.

Hey hello gentleman. I'll be adding the items soon once I get some free time. Don't worry, I'll do everything properly.

2023-12-27 07:10 UTC, GuardianDll commented
Please don't add santa_knifr

2023-12-27 07:16 UTC, The-Anjelo-Guy commented
> Please don't add santa_knife

It is a novelty item that Mrs. Claus use in the kitchen, but I'm open for ideas of weaponry for them other than a large novelty candy cane.

2023-12-28 11:55 UTC, Qrox commented on data/json/items/armor/boots.json
> +    "description": "A delightful pair of comfortable red and white shoes with Christmas adornments.  For either Mrs. Claus or Santa style and comfort.",
FYI you can suppress this and similar false positives with the following changes:

```suggestion
    "description": {
        "str": "A delightful pair of comfortable red and white shoes with Christmas adornments.  For either Mrs. Claus or Santa style and comfort.",
        "//NOLINT(cata-text-style)": "Mrs. does not end with a period"
    },
```

2023-12-29 04:54 UTC, Qrox commented on data/json/items/armor/boots.json
> +    "copy_from": "boots",
```suggestion
    "copy-from": "boots",
```

2023-12-29 04:54 UTC, Qrox commented on data/json/items/armor/boots.json
> +    "copy_from": "sneakers",
```suggestion
    "copy-from": "sneakers",
```

2023-12-29 04:54 UTC, Qrox commented on data/json/items/armor/boots.json
> +    "copy_from": "socks",
```suggestion
    "copy-from": "socks",
```

2023-12-29 04:54 UTC, Qrox commented on data/json/items/armor/boots.json
> +        "description": "A comfortable pair of red, white and green stockings with Christmas patterns on it, for Mrs. Claus style.",
```suggestion
        "description": {
          "str": "A comfortable pair of red, white and green stockings with Christmas patterns on it, for Mrs. Claus style.",
          "//NOLINT(cata-text-style)": "Mrs. does not end with a period"
        },
```

2023-12-29 04:54 UTC, Qrox commented on data/json/items/armor/jewelry.json
> +    "description": "A festive, lightweight and simple pair of earrings made of string and tiny plastic candycanes.  For Mrs. Claus style.",
```suggestion
    "description": {
      "str": "A festive, lightweight and simple pair of earrings made of string and tiny plastic candycanes.  For Mrs. Claus style.",
      "//NOLINT(cata-text-style)": "Mrs. does not end with a period"
    },
```

2023-12-30 19:41 UTC, harakka commented on data/json/professions.json
> +    "description": "Everything was set for Christmas, you where just waiting for the call.  The children's happiness and joy where lost due to the Cataclysm, but you are decided to keep the Christmas
This does not depict someone working as a mall santa. Neither does the skill set.

2023-12-30 19:42 UTC, GuardianDll requested changes
copy from our discord discussion:

santa_undershirt, santa_socks, santa_briefs, santa_bra, santa_panties should be gone, unless you want to make them a mundane items, not related to santa set

everything else should go into variants of mundane items with weight 0 (so they don't spawn naturally, it can be reverted if we decide to make more variants for said clothes), and itemgroups should call this variant

2024-01-02 18:07 UTC, The-Anjelo-Guy commented
I think I done it properly now. The Santa undergarment and Santa knife are gone, fixed the description and skillset for the Mall Santa profession, fixed volume, weight and material of the other items, instead of doing variants, for logistics and also because these items have different materials and physical values than their variant-intended base items. I would like to thank Guardiandl and Harakka for their help and support in this PR, nothing would be achieved without them.

2024-01-04 07:49 UTC, GuardianDll approved these changes
looks good for me now, test error seems unrelated

2024-01-04 15:26 UTC, merged