Carnivore warns you about Scurvy fixing #70474
CleverRaven/Cataclysm-DDA pull request #70553
Opened 2023-12-31 05:17 UTC by Maleclypse

#### Summary
None

#### Purpose of change
Players shouldn't be caught offguard when they catch scurvy as carnivores.  Fixed #70474

#### Describe the solution
Adds an extra sentence in the carnivore trait.

#### Describe alternatives you've considered

#### Testing

#### Additional context

2024-01-03 13:04 UTC, Fris0uman commented
Isn't this a bit too long? Half the description is now bout scurvy.

2024-01-04 03:40 UTC, Maleclypse commented
> Isn't this a bit too long? Half the description is now bout scurvy.

Fair I'll see if anyone can come up with a better description.

2024-01-04 15:30 UTC, MNG-cataclysm requested changes

2024-01-04 15:30 UTC, MNG-cataclysm commented on data/json/mutations/mutations.json
> +    "description": "Your body's ability to digest fruits, vegetables, grains and nuts is severely hampered.  You cannot eat anything besides meat.  While your vitamin C needs are lowered, its still n
```suggestion
    "description": "Your body's ability to digest fruits, vegetables, grains and nuts is severely hampered.  You cannot eat anything besides meat.  While your vitamin C needs are lowered, it's still needed and can be found often in organ meat.",
```

Alternatively, you could use `"Your body's ability to digest fruits, vegetables, grains and nuts is severely hampered.  You cannot eat anything besides meat.  While your vitamin C needs are lowered, it's still needed and can be found in organ meat."`

2024-01-24 06:22 UTC, Maleclypse commented on data/json/mutations/mutations.json
> +    "description": "Your body's ability to digest fruits, vegetables, grains and nuts is severely hampered.  You cannot eat anything besides meat.  While your vitamin C needs are lowered, it's still
```suggestion
    "description": "Your body's ability to digest fruits, vegetables, grains and nuts is severely hampered.  You cannot eat anything besides meat.  While your vitamin C needs are lowered, it's still needed and can be found often in organ meat."
```

2024-01-24 06:22 UTC, Maleclypse commented on data/json/mutations/mutations.json
> +    "description": "Your body's ability to digest fruits, vegetables, grains and nuts is severely hampered.  You cannot eat anything besides meat.  While your vitamin C needs are lowered, it's still
```suggestion
    "description": "Your body's ability to digest fruits, vegetables, grains and nuts is severely hampered.  You cannot eat anything besides meat.  While your vitamin C needs are lowered, it's still needed and can be found often in organ meat.",
```

2024-02-02 04:02 UTC, merged