Pickaxe List Fix #70710
CleverRaven/Cataclysm-DDA pull request #70790
Opened 2024-01-09 05:41 UTC by Maleclypse

#### Summary
None

#### Purpose of change
Fix #70710

#### Describe the solution
Makes a pickaxe list.  Should make a jackhammer standard while I'm here but I didn't.

#### Describe alternatives you've considered
Making a jackhammer list too

#### Testing

#### Additional context

2024-01-09 08:05 UTC, Karol1223 requested changes

2024-01-09 08:05 UTC, Karol1223 commented on data/mods/innawood/recipes/recipe_deconstruction.json
> +    "tools": [ [ [ [ "surface_heat", 1, "LIST" ] ], [ "jackhammer", 1 ], [ "elec_jackhammer", 50 ] ] ],
```suggestion
    "tools": [ [ [ [ "pickaxe_list", 1, "LIST" ] ], [ "jackhammer", 1 ], [ "elec_jackhammer", 50 ] ] ],
```
I'm assuming you didn't intend to break rocks with a hotplate?

2024-01-10 04:57 UTC, Maleclypse commented on data/json/requirements/toolsets.json
> +    "tools": [ [ [ [ "pickaxe_list", 1, "LIST" ] ], [ "jackhammer", 300 ], [ "elec_jackhammer", 3960 ] ] ]
```suggestion
    "tools": [ [ [ "pickaxe_list", 1, "LIST" ] ], [ "jackhammer", 300 ], [ "elec_jackhammer", 3960 ] ] ]
```

2024-01-10 04:59 UTC, Maleclypse commented on data/json/uncraft/generic.json
> +    "tools": [ [ [ [ "pickaxe_list", 1, "LIST" ] ], [ "jackhammer", 5 ], [ "elec_jackhammer", 66 ] ] ],
```suggestion
    "tools": [ [ [ "pickaxe_list", 1, "LIST" ], [ "jackhammer", 5 ], [ "elec_jackhammer", 66 ] ] ],
```

2024-01-16 04:30 UTC, Maleclypse commented on data/json/requirements/toolsets.json
> +      [ [ [ "pickaxe_list", 1, "LIST" ] ], [ "jackhammer", 140 ], [ "elec_jackhammer", 1848 ] ],
```suggestion
      [ [ "pickaxe_list", 1, "LIST" ], [ "jackhammer", 140 ], [ "elec_jackhammer", 1848 ] ],
```

2024-01-16 05:27 UTC, Maleclypse commented on data/json/requirements/toolsets.json
> +    "tools": [ [ [ "pickaxe_list", 1, "LIST" ], [ "jackhammer", 300 ], [ "elec_jackhammer", 3960 ] ] ]
```suggestion
    "tools": [ [ [ "pickaxe_list", -1, "LIST" ], [ "jackhammer", 300 ], [ "elec_jackhammer", 3960 ] ] ]
```

2024-01-16 05:27 UTC, Maleclypse commented on data/json/requirements/toolsets.json
> +      [ [ "pickaxe_list", 1, "LIST" ], [ "jackhammer", 140 ], [ "elec_jackhammer", 1848 ] ],
```suggestion
      [ [ "pickaxe_list", -1, "LIST" ], [ "jackhammer", 140 ], [ "elec_jackhammer", 1848 ] ],
```

2024-01-16 05:27 UTC, Maleclypse commented on data/json/uncraft/generic.json
> +    "tools": [ [ [ "pickaxe_list", 1, "LIST" ], [ "jackhammer", 5 ], [ "elec_jackhammer", 66 ] ] ],
```suggestion
    "tools": [ [ [ "pickaxe_list", -1, "LIST" ], [ "jackhammer", 5 ], [ "elec_jackhammer", 66 ] ] ],
```

2024-01-16 05:27 UTC, Maleclypse commented on data/mods/innawood/recipes/recipe_deconstruction.json
> +    "tools": [ [ [ [ "pickaxe_list", 1, "LIST" ] ], [ "jackhammer", 1 ], [ "elec_jackhammer", 50 ] ] ],
```suggestion
    "tools": [ [ [ [ "pickaxe_list", -1, "LIST" ] ], [ "jackhammer", 1 ], [ "elec_jackhammer", 50 ] ] ],
```

2024-01-16 05:58 UTC, Maleclypse commented on data/json/requirements/toolsets.json
> +    "tools": [ [ [ "pickaxe_list", -1, "LIST" ], [ "jackhammer", 300 ], [ "elec_jackhammer", 3960 ] ] ]
```suggestion
   "tools": [ [ [ "pickaxe", -1 ], [ "bronze_pickaxe", -1 ], [ "jackhammer", 300 ], [ "elec_jackhammer", 3960 ] ] ]
```

2024-01-16 06:01 UTC, Maleclypse commented on data/mods/Magiclysm/requirements/crafting.json
> +    "//": "Pickaxe tools",
```suggestion
     "//": "mining",
```

2024-01-16 06:32 UTC, Maleclypse commented on data/json/requirements/toolsets.json
> +        [ [ "pickaxe_list", 1, "LIST" ] ],
```suggestion
        [ "pickaxe", -1 ],
        [ "bronze_pickaxe", -1 ],
```

2024-01-16 06:32 UTC, Maleclypse commented on data/json/requirements/toolsets.json
> +      [ [ "pickaxe_list", -1, "LIST" ], [ "jackhammer", 140 ], [ "elec_jackhammer", 1848 ] ],
```suggestion
      [ [ "pickaxe", -1 ], [ "bronze_pickaxe", -1 ], [ "jackhammer", 140 ], [ "elec_jackhammer", 1848 ] ],
```

2024-01-16 06:36 UTC, Maleclypse commented on data/mods/Magiclysm/requirements/crafting.json
>    }
```suggestion
  },
    {
    "id": "concrete_removal_standard",
    "type": "requirement",
    "//": "Tools for removing concrete",
    "extend": { "tools": [ [ [ "pickaxe_plus_one", -1 ] ], [ [ "pickaxe_plus_two", -1 ], [ "eshaper_pickaxe", -1 ] ] ] }
  },
    {
    "id": "road_removal_standard",
    "type": "requirement",
    "//": "Tools for removing road / sidewalk",
    "extend": { "tools": [ [ [ "pickaxe_plus_one", -1 ] ], [ [ "pickaxe_plus_two", -1 ], [ "eshaper_pickaxe", -1 ] ] ] }
  }
```

2024-01-19 23:35 UTC, merged