Create standards for gun variants and enforce through CI
CleverRaven/Cataclysm-DDA pull request #71533
Opened 2024-02-05 15:53 UTC by anothersimulacrum

#### Summary
Infrastructure "Clarify and enforce standards for gun names and variants"

#### Purpose of change
I said I should do this a while ago in https://github.com/CleverRaven/Cataclysm-DDA/issues/60184

No I'm doing it.

#### Describe the solution
Write documentation clarifying why variants were add, and how they should be used to name guns in game.
Write a script enforcing these standards.

#### Testing
I've set the script to run in CI.
Right now, there is an example left to fail each of the three tests, so CI will fail on this PR.

#### Additional context
Thanks to @tenmillimaster for writing the documentation on rarity.

2024-02-05 17:46 UTC, tenmillimaster requested changes, later dismissed

2024-02-05 17:46 UTC, tenmillimaster commented on doc/GUN_NAMING_AND_INCLUSION.md
> +- Silencers: Should be genercized into types of silencers. Shotgun silencer, rimfire silencer, pistol silencer, ~~pistol (wipe) silencer~~, hybrid rifle/pistol silencer, rifle silencer, rifle (flow t
```suggestion
- Silencers: Should be genercized into types of silencers. Shotgun silencer, rimfire silencer, pistol silencer, hybrid rifle/pistol silencer, rifle silencer, rifle (flow through) silencer, big bore silencer. Specific models should be avoided.
```

2024-02-05 17:46 UTC, tenmillimaster commented on doc/GUN_NAMING_AND_INCLUSION.md
> +Thompsons, M16/M4, Lightning link (living in an AR), or an actual AK-47, then
```suggestion

```

2024-02-05 17:46 UTC, tenmillimaster commented on doc/GUN_NAMING_AND_INCLUSION.md
> +SW76/Swedish K, American 180, HK autosear (living in an mp5, HK33, HK53, HK91),
```suggestion
```

2024-02-05 17:46 UTC, tenmillimaster commented on doc/GUN_NAMING_AND_INCLUSION.md
> +Civilian Machineguns: If it's not a MAC 10, MAC 11, Full size UZI, STEN gun,
```suggestion
Civilian Machineguns: If it's not a MAC 10, MAC 11, Full size UZI, STEN gun, or a Reising, then
```

2024-02-05 17:46 UTC, tenmillimaster commented on doc/GUN_NAMING_AND_INCLUSION.md
> +no. No post samples.
```suggestion
no. No post samples.  All civilian machine guns have a collective rarity of approximately 175,977 machineguns: 393347000 total guns in the US.
```

2024-02-12 04:42 UTC, TheShadowFerret commented on doc/GUN_NAMING_AND_INCLUSION.md
> +to prevent gun names that are obsccure strings of letters and numbers.
```suggestion
to prevent gun names that are obscure strings of letters and numbers.
```

2024-02-12 04:42 UTC, TheShadowFerret commented on doc/GUN_NAMING_AND_INCLUSION.md
> +As of writing, names are considiered to be acceptable if the gun name contains
```suggestion
As of writing, names are considered to be acceptable if the gun name contains
```

2024-02-12 04:42 UTC, TheShadowFerret commented on doc/GUN_NAMING_AND_INCLUSION.md
> +all types of mosin-nagant longarms, the entire MDR rifle family, etc. This is
```suggestion
all types of Mosin-Nagant longarms, the entire MDR rifle family, etc. This is
```

2024-02-12 04:42 UTC, TheShadowFerret commented on doc/GUN_NAMING_AND_INCLUSION.md
> +some problems. Each item has it's own stat block, and this invites all sorts of
```suggestion
some problems. Each item has its own stat block, and this invites all sorts of
```

2024-02-18 03:53 UTC, Maleclypse commented on data/json/itemgroups/Locations_MapExtras/locations_commercial.json
>        [ "ruger_redhawk", 3 ],
```suggestion
```

2024-02-28 06:07 UTC, merged