add figs and fig trees
CleverRaven/Cataclysm-DDA pull request #72150
Opened 2024-03-03 20:55 UTC by juur

#### Summary
Content "Add figs and fig trees, etc."

#### Purpose of change
Add figs, fig trees and similar changes.

#### Describe the solution
I looked at plums and grapes and adjusted based on them.

#### Describe alternatives you've considered
Not having figs: bad.

#### Testing
Boot up. Map edit a tree. Travel in time. Harvest the tree.

#### Additional context

2024-03-03 21:21 UTC, TheShadowFerret commented on data/json/furniture_and_terrain/terrain-flora.json
> +    "description": "An example of 'Ficus Carica' - the common edible fig tree. Not normally native to New England, but seems to be doing okay.",
```suggestion
    "description": "An example of 'Ficus Carica' - the common edible fig tree.  Not normally native to New England, but seems to be doing okay.",
```

2024-03-03 21:21 UTC, TheShadowFerret commented on data/json/furniture_and_terrain/terrain-flora.json
> +    "description": "An example of 'Ficus Carica' - the common edible fig tree. Not normally native to New England, but seems to be doing okay. This one appears to have been picked.",
```suggestion
    "description": "An example of 'Ficus Carica' - the common edible fig tree.  Not normally native to New England, but seems to be doing okay.  This one appears to have been picked.",
```

2024-03-03 22:06 UTC, Maleclypse commented
Pretty sure fig trees are already in Xedra Evolved so please migrate them if that’s accurate.

2024-03-04 20:02 UTC, juur commented
> Pretty sure fig trees are already in Xedra Evolved so please migrate them if that’s accurate.

Yup, let me have a go later in the week and deprecating/migrating to the base game.

2024-03-06 00:33 UTC, RenechCDDA requested changes
Orphaned content should not be committed without very good reason. Please add the fig tree terrain to relevant mapgen or remove them from your PR.

Note that the New England climate seems too cold for a fig crop. http://www.hort.cornell.edu/4hplants/Fruits/Fig.html

2024-03-09 09:07 UTC, juur commented
> Orphaned content should not be committed without very good reason. Please add the fig tree terrain to relevant mapgen or remove them from your PR.
> 
> Note that the New England climate seems too cold for a fig crop. http://www.hort.cornell.edu/4hplants/Fruits/Fig.html

The terrain is used by Xendra Evolved (and maybe planting?). Is that OK or should I add it in somewhere?

It is possible for some varieties of this species to grow in the UK, which I think is a little cooler than New England: https://www.rhs.org.uk/fruit/figs/grow-your-own

2024-03-09 09:08 UTC, juur commented
> Pretty sure fig trees are already in Xedra Evolved so please migrate them if that’s accurate.

Done, I think.

2024-03-13 02:04 UTC, Maleclypse commented
Add them as a potential line of trees grown at a tree farm or something.  They do need to at least spawn somewhere in vanilla to justify adding them to mainline.

2024-03-14 19:12 UTC, kevingranade requested changes
> It is possible for some varieties of this species to grow in the UK, which I think is a little cooler than New England: https://www.rhs.org.uk/fruit/figs/grow-your-own

One,  check your source,  it's saying with extra extra special care,  up to moving the tree indoors for the winter,  you can maybe grow figs in some parts of the uk. That doesn't really qualify as working.

Two, simply asserting that the uk is cooler than new england (I have no idea if this is at all true) is insufficient, we're looking for a source that says that it should work.

Three, for plants that have marginal survivability in the area, what should be added is a version of the plant that does not produce fruit without manual intervention.

2024-03-14 19:36 UTC, closed without merging