Autodrivable meadow and streams
CleverRaven/Cataclysm-DDA pull request #72448
Opened 2024-03-17 14:06 UTC by Procyonae

#### Summary
Bugfixes "Meadow and streams are now navigable and traversable by autodriving"

#### Purpose of change
Fixes #71910

#### Describe the solution
Meadows, streams, evac centre field and special_field now have the field travel_cost_type to enable autodrive to navigate them
The autodrive code no longer views terrain flagged as SHALLOW_WATER as untravesable for land vehicles just because they're flagged LIQUID so streams can be traversed by autodrive
Added meadows to the field and land special_locations so most specials can spawn over them
Made meadow_core NO_ROTATE and migrated the rotations to it

#### Describe alternatives you've considered
Adding a new land vehicle navigable travel_cost_type specifically for streams and or meadows but that seems overkill

#### Testing
Tested autodriving through meadows and streams

#### Additional context

2024-03-17 15:38 UTC, kevingranade commented
I don't think autodriving through shallow water is at all reasonable. This isn't a couple of inches of water in the ground,  this is everything from that to chest- deep water, add int in the likelihood of the bottom being mud or loose sand and the chance of getting stick is incredibly high. 

If we don't have a high chance of getting stuck in shallow water already that's something to look into.

2024-03-17 15:43 UTC, Procyonae commented
> I don't think autodriving through shallow water is at all reasonable. This isn't a couple of inches of water in the ground, this is everything from that to chest- deep water, add int in the likelihood of the bottom being mud or loose sand and the chance of getting stick is incredibly high.
> 
> If we don't have a high chance of getting stuck in shallow water already that's something to look into.

You can drive through shallow water just fine currently this is just bringing autodrive in line with what the player can do anyway, it's a 2 line change if someone implements difficulty in driving through it in the future

2024-03-17 16:07 UTC, SurFlurer commented
Does this change how evac center field looks like? IMO it has a high density of trees, shrubs and bushes, which makes it almost impossible to autodrive through, if not at all.

2024-03-17 17:11 UTC, Procyonae commented
> Does this change how evac center field looks like? IMO it has a high density of trees, shrubs and bushes, which makes it almost impossible to autodrive through, if not at all.

Oops yep you're quite right, I only added that bc I found it while looking for the regular "field" OMT

2024-03-20 02:44 UTC, kevingranade requested changes
> You can drive through shallow water just fine currently this is just bringing autodrive in line with what the player can do anyway

If we don't have a high chance of getting stuck in shallow water already that's something to look into.

2024-03-20 11:33 UTC, Procyonae commented
> > You can drive through shallow water just fine currently this is just bringing autodrive in line with what the player can do anyway
> 
> If we don't have a high chance of getting stuck in shallow water already that's something to look into.

I don't see how this is remotely relevant to a QOL PR but whatever

2024-03-20 15:08 UTC, kevingranade commented
> I don't see how this is remotely relevant to a QOL PR but whatever

It's because the precedent you're using to justify the QoL fix is a bug.

2024-03-20 16:06 UTC, merged