Typo Fix
CleverRaven/Cataclysm-DDA pull request #72584
Opened 2024-03-24 07:40 UTC by Uwuewsky

#### Summary
None

#### Purpose of change
Fix #72520

#### Describe the solution

#### Describe alternatives you've considered

#### Testing
In addition to simple changes to the lines themselves, there are a couple more changes.
pistols are now plural
![!pistols](https://github.com/CleverRaven/Cataclysm-DDA/assets/99945024/28a29361-1800-4c87-b93b-a8c942e3896d)
deleted descriptions are copied correctly
![!dino](https://github.com/CleverRaven/Cataclysm-DDA/assets/99945024/811f2364-c74e-44aa-b3ee-5b5448dfc1e1)
I CANNOT check the attack messages from void weaver. I don't know under what conditions they are printed. the screenshot shows regular messages, not a unique attack.
![!waver](https://github.com/CleverRaven/Cataclysm-DDA/assets/99945024/69cb527b-88a5-40a9-a47d-4d9b94fa8ff6)

#### Additional context

2024-03-24 08:31 UTC, Karol1223 requested changes

2024-03-24 08:31 UTC, Karol1223 commented on data/json/items/bionics.json
> +    "description": "A broken CBM that has been leaking radiation into its user. The danger seems to have been sealed off during the removal process, but you definitely shouldn't put it back.",
```suggestion
    "description": "A broken CBM that has been leaking radiation into its user.  The danger seems to have been sealed off during the removal process, but you definitely shouldn't put it back.",
```

You lost the double spaceh ere

2024-03-25 00:59 UTC, Qrox commented on data/json/items/book/spiritual.json
> +    "name": { "str": "The Orphic Gold Tablets", "str_pl": "copies of the Orphic Gold Tablets" },
```suggestion
    "name": { "str": "The Orphic Gold Tablets", "str_pl": "copies of The Orphic Gold Tablets" },
```
`The` is part of the book title.

2024-03-25 00:59 UTC, Qrox commented on data/json/items/book/spiritual.json
> +    "name": { "str": "The Mithraic Inscriptions", "str_pl": "copies of the Mithraic Inscriptions" },
```suggestion
    "name": { "str": "The Mithraic Inscriptions", "str_pl": "copies of The Mithraic Inscriptions" },
```

2024-03-26 18:40 UTC, merged