Honk your clown nose and convert "Make Some Noise" into EOC
CleverRaven/Cataclysm-DDA pull request #73165
Opened 2024-04-21 07:25 UTC by BarndoBoi

#### Summary
Content "Honk your clown nose and change 'manualnoise' into EOC_make_some_noise"

#### Purpose of change

Clown noses couldn't be honked, which devastated me. In addition compressed air horns, whistles, and a few other items don't use EOC so I figured I'd swap those over as well.

#### Describe the solution

Adds a new EOC that will replace all uses of 'manualnoise' that exist, and remove it once all the cleanup is done.

#### Describe alternatives you've considered

The clown nose must honk, there is no alternative.

#### Testing

The current two commits have been tested by spawning in a whistle and using the item, which worked. Same thing with spawning in the clown nose and giving it a honk. :D

#### Additional context

Thanks to @GuardianDll for suggesting using an EOC to implement the clown nose honking. Please let me know if I should instead split this PR into two parts: one handling removing the 'manualnoise' occurrences with the new EOC and a second updating the clown nose, or if this is fine as is.
I'm submitting this as a draft so I can finish it tomorrow after I get some sleep.

2024-04-21 09:40 UTC, GuardianDll commented
oh, so we have json function for this 
didn't know that, but it doesn't matter now, since EoC is made already
good job

2024-04-21 16:20 UTC, anothersimulacrum requested changes
> Adds a new EOC that will replace all uses of 'manualnoise' that exist, and remove it once all the cleanup is done.

Don't do this, just use `manualnoise`.

2024-04-21 17:26 UTC, anothersimulacrum approved these changes

2024-04-21 17:26 UTC, anothersimulacrum commented on data/json/items/armor/misc.json
> +    "description": "A red latex nose often worn by clowns. Squeezing the nose makes it honk.",
```suggestion
    "description": "A red latex nose often worn by clowns.  Squeezing the nose makes it honk.",
```

2024-04-23 04:29 UTC, merged

2024-04-23 04:31 UTC, Maleclypse commented
I was explaining the development process of DDA to a work friend today and honestly this PR is one of the most accurate embodiments of that process.  "I found a weird thing that you can do in the real world, and it could not be done in DDA.  This will not stand."  Thank you!