(Draft) Fingerless Wool Gloves
CleverRaven/Cataclysm-DDA pull request #73524
Opened 2024-05-05 15:05 UTC by SomeGuyIGues

#### Summary
Content "Added Fingerless Wool Gloves, in XL and XS sizes and recipes for it. Additionally, renamed the Fingerless Gloves to Fingerless Leather Gloves."

#### Purpose of change

The wool gloves hasn't received nearly as much love as its other siblings. The leather gloves, survivor gloves and even the denim gloves have a fingerless variant. I intend to change that.

#### Describe the solution

- Introducing the "Fingerless Wool Gloves." Providing significantly less encumbrance, but less warmth in exchange.
- New recipes to make the item as well as its XL and XS variants.
- Changed the name of the fingerless gloves to the fingerless leather gloves to make it more obvious what the material is.
- The item can be naturally found in the world

#### Describe alternatives you've considered

- Don't introduce the item and recipe to some degree or altogether, if you hate being warm in style.
- The fingerless wool gloves provides 40 warmth and 7 encumbrance. These values could be changed, but I think they are reasonable considering I own a pair and can reasonably interact with my environmental with minimal difficulties.
- I choice 67 yarn for the fingerless wool gloves because it covers up 67% of your hands, makes sense. I found for the XL and XS wool gloves they were 1.40 or .75 in size compared to the normal variant, respectively. Doing some more math give me 85 yarn and 50 yarn for each item, rounding to the closest integer. These values could also be changed. 

#### Testing

(WIP) Pulling this into the main game will break it, I don't know how I managed to do that. I'm too tired as of posting this initially to find and correct what the hell I've done. God help me.

#### Additional context

Maybe

2024-05-05 15:08 UTC, XygenSS commented on data/json/items/armor/gloves.json
> +        "specifically_covers": [ "hand_fingers_l", "hand_fingers_r" ]
They shouldn't be covering the fingers right?

2024-05-05 15:12 UTC, XygenSS commented on data/json/recipes/armor/hands.json
You also need a recipe where you take an existing pair of wool gloves and just cut off the fingers.

2024-05-05 15:14 UTC, SomeGuyIGues commented on data/json/recipes/armor/hands.json
I thought I did, it's in hands.json

2024-05-05 15:17 UTC, XygenSS commented
IIRC 1 hand encumb = 1% slower crafting, the encumbrance needs to be lower for it to be more attractive as crafting gloves imo.

2024-05-07 13:37 UTC, BalthazarArgall requested changes
This is what I spotted. Also please be careful about formatting issues that may arise from committing from suggestions, you may have to relint the files. I didn't review stuff outside of the items and recipes but you may want to make sure the XS and XL versions are spawning porperly.

2024-05-07 13:37 UTC, BalthazarArgall commented on data/json/recipes/armor/hands.json
> +    "id_suffix": "from_patchwork",
You don't need an id_suffix for the "base recipe", it's used to differentiate multiple recipes for the same item.

```suggestion
```

2024-05-07 15:57 UTC, BalthazarArgall commented
If you feel that your PR is ready you can open it, the tests will reset anyway. And it looks fine, I'm assuming you did your due diligence and everything outside items/recipes is fine, stuff like itemgroups etc. of course.

2024-05-08 04:31 UTC, merged