Add a "shock touch" mutation
CleverRaven/Cataclysm-DDA pull request #73620
Opened 2024-05-10 08:54 UTC by BalthazarArgall

#### Summary
Content "Add a 'shock touch' mutation"

#### Purpose of change
I'm looking to add a new mutation line (or maybe "subline") to the game, while I'm still in the process of making different ideas coalesce into a fully coherent line, at this point I'm pretty sure I want to build it around the ability to stun stuff through an eel-like shocking touch which doesn't yet exists in the game.

#### Describe the solution
I aim to create the mutation itself and everything to make it function although no mutation line will be added at this time.

#### Describe alternatives you've considered

#### Testing

#### Additional context
This draft is extremely rough, everything is TODO and the only reason I'm posting it is to have it up for 9t to look at.

2024-05-10 18:21 UTC, Kamejeir requested changes
alright, fleshing it out

2024-05-10 20:35 UTC, Kamejeir reviewed
mending those discussed things

2024-05-11 21:39 UTC, BalthazarArgall commented on data/json/mutations/mutation_spells.json
> +    "effect_str": "blind",
Why not stunned too?

2024-05-15 12:58 UTC, Kamejeir reviewed
Still need to find out how to make it combo into itself. At least it seems reapplying effects is not necessary (somewhat nulling my point about not including stun), so maybe it's as simple as calling for one shock_touch variant that zaps if not downed, and one that zaps + downs otherwise.

2024-06-12 14:29 UTC, BalthazarArgall commented
Oops, forgot to reinstall vcpkg

2024-06-12 15:19 UTC, Kamejeir commented
assuming you refer to the windows build failing at vcpkg, it has irked me too throughout seemingly random commits. I would guess it is not going to matter - the merger kicked that test until that part was successful

2024-06-12 18:37 UTC, BalthazarArgall commented
> assuming you refer to the windows build failing at vcpkg, it has irked me too throughout seemingly random commits. I would guess it is not going to matter - the merger kicked that test until that part was successful

Uh, you're right, it worked this time, that's the first time this test flakes on me.

2024-06-12 19:43 UTC, kevingranade commented
This MUST
Not work as well on larger targets. 
Not work as well or more likely at all on targets without exposed skin. This includes clothes and tougher exteriors like chitin or even hide.
Require you to physically attack/grapple the target, a "blast" is wildly innapropriate.

2024-06-13 07:46 UTC, BalthazarArgall commented
> This MUST Not work as well on larger targets. Not work as well or more likely at all on targets without exposed skin. This includes clothes and tougher exteriors like chitin or even hide. Require you to physically attack/grapple the target, a "blast" is wildly innapropriate.

I'll make it work the same way as bite attacks then, this should give it a more appropriate behavior. It means the shocks will be dealt randomly instead of having a deliberate usage though.

2024-12-09 06:18 UTC, Night-Pryanik commented
Closing as stale. If you wish to continue working on this, ping me to reopen.

2024-12-09 06:18 UTC, closed without merging