Silly little item
CleverRaven/Cataclysm-DDA pull request #74320
Opened 2024-06-04 22:23 UTC by BlackFira

What survivor wont need a bit of luck to stave off all the fear and hunger of the new world!

#### Summary
Content "Addition of a simple fluff item"

#### Purpose of change

Absolutely no good reason.

#### Describe the solution
N/A

#### Describe alternatives you've considered
N/A

#### Testing
Crafted it to check for proper handling
Picked up some items with it in my backpack
(I have no idea how to test this thing)

#### Additional context
N/A

2024-06-05 01:32 UTC, KeremBabaG commented
holy shit funger

2024-06-05 07:27 UTC, Karol1223 requested changes

2024-06-05 07:27 UTC, Karol1223 commented on data/json/recipes/other/other.json
> +    "components": [ [ [ "pinecone", 1 ], [ "stick", 1 ] ] ],
This should probably take twigs, not a stick, otherwise you're losing an absurd amount of mass

2024-06-05 07:27 UTC, Karol1223 commented on data/json/items/generic.json
> +    "price_postapoc": "10 cent",
```suggestion
    "price_postapoc": "0 cent",
```

There's no way in hell people would pay for this

2024-06-05 08:20 UTC, Karol1223 requested changes

2024-06-05 08:20 UTC, Karol1223 commented on data/json/items/generic.json
> +    "description": "A pinecone with four small sticks shoved between its scales. An amulet of good luck and fortune, good thing it's so easy to make.",
```suggestion
    "description": "A pinecone with four small sticks shoved between its scales.  An amulet of good luck and fortune, good thing it's so easy to make.",
```

2024-06-05 10:00 UTC, SomeGuyIGues commented
Funger reference

2024-06-05 10:15 UTC, harakka commented
You need to match the PR template, remove the extraneous comment at the beginning.

2024-06-05 11:52 UTC, RenechCDDA commented
> You need to match the PR template, remove the extraneous comment at the beginning.

@BlackFira That formatting is required for the PR Validator check to pass, which is also a requirement for getting your PR merged. There is no need to 👎 people who are trying to help.

2024-06-05 15:29 UTC, Kantonine commented
pinecone pig my beloved

2024-06-07 05:00 UTC, Maleclypse commented on data/json/items/generic.json
> +    "type": "GENERIC",
```suggestion
    "type": "GENERIC",,
```
Making changes to rebase and reset tests

2024-06-07 05:01 UTC, Maleclypse commented on data/json/items/generic.json
> +    "type": "GENERIC",,
```suggestion
    "type": "GENERIC",
```

2024-06-09 02:33 UTC, kevingranade commented
Sorry no. Items that make no sense other than as references to other games are out.

2024-06-09 02:33 UTC, closed without merging

2024-06-09 10:46 UTC, Kantonine commented
R.i.p. Pinecone pig 6/4/2024 - 6/9/2024 you shall be missed