Even More Tied Appliances
CleverRaven/Cataclysm-DDA pull request #74407
Opened 2024-06-09 01:06 UTC by Holli-Git

#### Summary
Content "Even more tied appliances"

#### Purpose of change

There was more stuff that could be tied.

#### Describe the solution

Adds it, also removes the EXTRA_DRAG flag as it didn't seem give extra drag or lower fuel consumption in this context, and gave an annoying descriptor in the install menu.

#### Describe alternatives you've considered

#### Testing

Lo and behold!
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/78005870/6714d26b-9c4a-4c90-9f5e-f60626d9a2a3)

#### Additional context

As evidence the EXTRA_DRAG flag doesn't do anything for air drag, here's a vehicle with 8 jointers that have the EXTRA_DRAG flag
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/78005870/aafc4d86-617c-463b-8a49-9aace85d539c)
Here's one without EXTRA_DRAG flag
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/78005870/f53b7351-aa40-4b26-9593-7fc2b1cf1375)

2024-06-11 18:23 UTC, Maleclypse requested changes
```
  if( vp.part().enabled && vpi.has_flag( "EXTRA_DRAG" ) ) {
            extra_drag += vpi.power;
        }
        if( vpi.has_flag( "EXTRA_DRAG" ) && ( vpi.has_flag( "WIND_TURBINE" ) ||
                                              vpi.has_flag( "WATER_WHEEL" ) ) ) {
            extra_drag += vpi.power;
```
Extra Drag is in code as doing "something" so it's either broken in code or displaying without the changes it is applying.    Two very different states neither of which is solved by removing EXTRA_DRAG flags.   Better to put them back and make an issue explaining that it's either not applying changes despite math in code or not displaying those changes to the player.

2024-06-11 23:28 UTC, Holli-Git commented
> ```
>   if( vp.part().enabled && vpi.has_flag( "EXTRA_DRAG" ) ) {
>             extra_drag += vpi.power;
>         }
>         if( vpi.has_flag( "EXTRA_DRAG" ) && ( vpi.has_flag( "WIND_TURBINE" ) ||
>                                               vpi.has_flag( "WATER_WHEEL" ) ) ) {
>             extra_drag += vpi.power;
> ```
> 
> Extra Drag is in code as doing "something" so it's either broken in code or displaying without the changes it is applying. Two very different states neither of which is solved by removing EXTRA_DRAG flags. Better to put them back and make an issue explaining that it's either not applying changes despite math in code or not displaying those changes to the player.

Alright, though I am worried the message about "When turned on, it will stop the vehicle unless it has a strong engine" confusing people

2024-06-13 05:13 UTC, Maleclypse commented
OK so I went and spent some time learning about what adds drag to a vehicle https://www.autospeed.com/cms/a_113227/article.html is a solid breakdown.   And the wake of a vehicle which is reduced by the modern shape of a car is by far the largest producer of drag on a vehicle making up 70-80% of total drag.  And as shown by the picture of the wagon/hatchback, you can see how changing the shape of the roof has a massive impact on drag, and tied objects change the shape of the roof in comparison to normal vehicle design.  So I'm going to put the extra drag flags back on then let the tests run on this and hopefully they all pass and it merges and I can create an issue for "whether or not extra drag is working and if not why" if it doesn't already exist.  :)  Thanks for putting up with me on this.

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
>      "breaks_into": [ { "item": "apartment_fridge" }, { "item": "rope_30" } ],
```suggestion
    "breaks_into": [ { "item": "apartment_fridge" }, { "item": "rope_30" } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
>      "breaks_into": [ { "item": "minifridge" }, { "item": "rope_30" } ],
```suggestion
    "breaks_into": [ { "item": "minifridge" }, { "item": "rope_30" } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
>      "breaks_into": [ { "item": "minifridge" }, { "item": "rope_30" } ],
```suggestion
    "breaks_into": [ { "item": "minifridge" }, { "item": "rope_30" } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
>      "breaks_into": [ { "item": "glass_fridge" }, { "item": "rope_30" } ],
```suggestion
    "breaks_into": [ { "item": "glass_fridge" }, { "item": "rope_30" } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
>      "breaks_into": [ { "item": "glass_fridge_double" }, { "item": "rope_30" } ],
```suggestion
    "breaks_into": [ { "item": "glass_fridge_double" }, { "item": "rope_30" } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
>      "breaks_into": [ { "item": "heavy_duty_fridge" }, { "item": "rope_30", "count": [ 2, 2 ] } ],
```suggestion
    "breaks_into": [ { "item": "heavy_duty_fridge" }, { "item": "rope_30", "count": [ 2, 2 ] } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
>      "breaks_into": [ { "item": "display_fridge" }, { "item": "rope_30" } ],
```suggestion
    "breaks_into": [ { "item": "display_fridge" }, { "item": "rope_30" } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
>      "breaks_into": [ { "item": "apartment_freezer" }, { "item": "rope_30" } ],
```suggestion
    "breaks_into": [ { "item": "apartment_freezer" }, { "item": "rope_30" } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
>      "breaks_into": [ { "item": "minifreezer" }, { "item": "rope_30" } ],
```suggestion
    "breaks_into": [ { "item": "minifreezer" }, { "item": "rope_30" } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
>      "breaks_into": [ { "item": "chest_minifreezer" }, { "item": "rope_30" } ],
```suggestion
    "breaks_into": [ { "item": "chest_minifreezer" }, { "item": "rope_30" } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
>      "breaks_into": [ { "item": "big_portable_freezer" }, { "item": "rope_30" } ],
```suggestion
    "breaks_into": [ { "item": "big_portable_freezer" }, { "item": "rope_30" } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
>      "breaks_into": [ { "item": "chest_freezer" }, { "item": "rope_30" } ],
```suggestion
    "breaks_into": [ { "item": "chest_freezer" }, { "item": "rope_30" } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
>      "breaks_into": [ { "item": "heavy_duty_freezer" }, { "item": "rope_30", "count": [ 2, 2 ] } ],
```suggestion
    "breaks_into": [ { "item": "heavy_duty_freezer" }, { "item": "rope_30", "count": [ 2, 2 ] } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
>      "breaks_into": [ { "item": "glass_freezer" }, { "item": "rope_30" } ],
```suggestion
    "breaks_into": [ { "item": "glass_freezer" }, { "item": "rope_30" } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
>      "breaks_into": [ { "item": "display_freezer" }, { "item": "rope_30" } ],
```suggestion
    "breaks_into": [ { "item": "display_freezer" }, { "item": "rope_30" } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
> +    "breaks_into": [ { "item": "oven" }, { "item": "rope_30" } ],
```suggestion
    "breaks_into": [ { "item": "oven" }, { "item": "rope_30" } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
> +    "breaks_into": [ { "item": "arcade_machine" }, { "item": "rope_30" } ],
```suggestion
    "breaks_into": [ { "item": "arcade_machine" }, { "item": "rope_30" } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
> +    "breaks_into": [ { "item": "drill_press" }, { "item": "rope_30" } ],
```suggestion
    "breaks_into": [ { "item": "drill_press" }, { "item": "rope_30" } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
> +    "breaks_into": [ { "item": "tablesaw" }, { "item": "rope_30" } ],
```suggestion
    "breaks_into": [ { "item": "tablesaw" }, { "item": "rope_30" } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
> +    "breaks_into": [ { "item": "mitresaw" }, { "item": "rope_30" } ],
```suggestion
    "breaks_into": [ { "item": "mitresaw" }, { "item": "rope_30" } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
> +    "breaks_into": [ { "item": "bandsaw" }, { "item": "rope_30" } ],
```suggestion
    "breaks_into": [ { "item": "bandsaw" }, { "item": "rope_30" } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
> +    "breaks_into": [ { "item": "router" }, { "item": "rope_30" } ],
```suggestion
    "breaks_into": [ { "item": "router" }, { "item": "rope_30" } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
> +    "breaks_into": [ { "item": "planer" }, { "item": "rope_30" } ],
```suggestion
    "breaks_into": [ { "item": "planer" }, { "item": "rope_30" } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
> +    "breaks_into": [ { "item": "jointer" }, { "item": "rope_30" } ],
```suggestion
    "breaks_into": [ { "item": "jointer" }, { "item": "rope_30" } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
> +    "breaks_into": [ { "item": "hydraulic_press" }, { "item": "rope_30" } ],
```suggestion
    "breaks_into": [ { "item": "hydraulic_press" }, { "item": "rope_30" } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
> +    "breaks_into": [ { "item": "air_compressor" }, { "item": "rope_30" } ],
```suggestion
    "breaks_into": [ { "item": "air_compressor" }, { "item": "rope_30" } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
> +    "breaks_into": [ { "item": "oxygen_concentrator" }, { "item": "rope_30" } ],
```suggestion
    "breaks_into": [ { "item": "oxygen_concentrator" }, { "item": "rope_30" } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:18 UTC, Maleclypse commented on data/json/vehicleparts/stowed_parts.json
> +    "breaks_into": [ { "item": "hd_compressor_unit" }, { "item": "rope_30" } ],
```suggestion
    "breaks_into": [ { "item": "hd_compressor_unit" }, { "item": "rope_30" } ],
    "flags": [ "EXTRA_DRAG" ],
```

2024-06-13 05:20 UTC, Maleclypse approved these changes
I was the change I wished to see in the world

2024-06-14 14:34 UTC, merged

2024-06-15 00:21 UTC, Holli-Git commented
> I was the change I wished to see in the world

Ah, thank you!