More Mutagen Testing Logs: Part I
CleverRaven/Cataclysm-DDA pull request #74606
Opened 2024-06-16 19:55 UTC by DoctorBoomstick

#### Summary
None
#### Purpose of change
Once upon a time, @GuardianDll  mentioned they would like some more mutagen testing logs to complement the existing contingent. I here present an appetiser.
#### Describe the solution
I have added 2 fresh logs as well as, with Guardian's blessing, rewritten logs 1, 2, and 5 for the time being to establish formal consistency with these reports. I have also added conditional names to the report document; however, I have not made it use an EOC pop-up, though I believe this would be better, as touching variant IDs scares me and I don’t know how to do it in a manner that doesn’t cause the game to detonate.
#### Describe alternatives you've considered
I considered writing more logs before publishing this PR, but these documents, due to my own fault, take quite a long time to produce, and I am juggling them along with other work. As such, I thought it better to put something out there, both to get feedback on what I’ve written, if the style’s good, if the lore’s alright, if the snippets are trash, etc., and to start putting out small bundles at a time. If it is deemed better to change everything in a single PR to avoid a transitional period, I have no issues with putting this in draft until such time as I am able to replace all the pre-existing mutagen logs.
#### Testing
I’ve not tested the new logs in the game; however, they’re simple snippet additions.
#### Additional context
For reference, my grasp on biology extends to the mighty knowledge that animals have bones in them, so if anybody with actual knowledge finds something incongruently stupid (there’s probably a healthy selection) I will, obviously, change accordingly.
Also, thanks to @Venera3 for vetting my proof of concept and workshopping what these snippets should convey, information-wise, and what their overall mood should be.

2024-06-16 21:47 UTC, anoobindisguise commented
"Unnecessary torchers" -> "torture"?

2024-06-23 10:04 UTC, Venera3 commented
I'll look them over soonish. 
Tying them to the pop-up shouldn't be too hard, and the worst that can happen is it not working (since these probably spawn under other IDs than the other test logs).

2024-06-27 06:59 UTC, Venera3 requested changes
General procedure stuff:
The way to set volunteer studies up is either awake studies with a mild sedative or under general anesthesia - you'd want a complete monitoring in either case and the option to switch over immediately. You'd also have somebody *in the room* to both support the poor sap and *intervene* if the weird science gets off the rails.

The volunteers might get fed a line about hallucinogens or whatever, and remember that most low-level mutations *are purifiable* - it is completely possible that XEDRA set the studies up with the expectation of being able to just turn them back afterwards before they ran into some unpurifiable traits. 

Re: first log
- going with an awake study refer to oral sedation (anesthesia is something else), monitoring telemetry and Research Assistant Johnny Whatsisface being there - you can also do a later log where he's made head researcher and *doesn't do the evil shit* for extra points.
- subcutaneus + "under the epidermis"is redundant
- the snip about "3 times the size of normal papilla" is superfluous
- You don't need thermal imaging, you're doing on-subject monitoring
- Change the flow of the drama a bit - subject gets itchy, monitoring staff tries getting them to calm down, stuff gets hectic and Santana decides against additional sedation for "subjective data gathering" reasons. Include something about the monitoring staff protesting and refer to a scary external incident report / Admin inquiry / similar bureaucratspeak and Santana getting reprimanded to a dead-end / thrown in XEDRA jail.
- Have a snippet about post-study subject care - debrief, examination, that sort of stuff.
- The line about mental health of observation stuff is extremely on the nose. "Santana got reprimanded, study protocols amended, further human tests get more observers/scientist screening/whatever" would suffice.

I'll try to read the others later today, but it will be a piecemeal review.

2024-07-28 10:38 UTC, DoctorBoomstick commented
Setting this as a draft to:

- Apply the requested changes from Venera’s review across the already written logs.

- Adjust the EOC around the document to make them present a pop-up.

- Add some extra odds and ends that I think would be fun: subject pictures and the like.

- Perhaps make a documentation file with all the glossaries for mutagen-related stuff, because this is getting extensive and buried in a giant snippets file. This might be considered scope creep, however.

2024-12-09 06:21 UTC, Night-Pryanik commented
Closing as stale. If you wish to continue working on this, ping me to reopen.

2024-12-09 06:21 UTC, closed without merging