More skeletal zombie upgrades
CleverRaven/Cataclysm-DDA pull request #74676
Opened 2024-06-19 17:36 UTC by SirPendrak

#### Summary
Content "Three new skeletal zombe evolutions"

#### Purpose of change

More variety and endgame enemies

#### Describe the solution

Skeletal slasher - can evolve from skeletal zombie. Similar armor, a tiny bit faster, better melee skill and token 1 dodge. "Attack cost" makes it attack once per turn despite speed lower than 100. Can smell. Has good ammount of cut damage to its attack.

Skeletal executioneer - slasher upgrade. Looses grab and bite. Has very good melee skill, a lot of cut DMG and tries to decapitate you with powerfull "cut_throat" attack. Otherwise has some minor stat upgrades.

Skeletal reaper - the blob got serious. Extreme melee skill and cutting damage. From time to time can perform armor-penetrating stab. Larger, faster, stronger. Probably the longest zombie evolution chain so far. Looses smell due to its nostrills being overgrown with bone. Can push small vehicles.

#### Describe alternatives you've considered

Fighting Skeletal juggernaut again

#### Testing

Despite big numbers they are not that deadly for survivor that has at least some preparation. Cutting damage is easiest to negate with armor. 

Tested that zombie masters upgrade skeletons into slashers at about 12% rate. 

Fought skeletal slasher. Endgame armor can make you impervious to their attacks. They loose fight to a standard Mi-go, leaving it with about half HP.

Fought skeletal executioneer. As long as you have good armor and can block or parry, youre fine. Otherwise you loose your head fast. It looses fight with Mi-go guard, leaving it at 10% HP left. 

Fought skeletal reaper. Their speed makes them more annoyig and overwhelming. As above, parry and armor should keep player safe, but melee skill of 9 makes pure dodge builds risky. It looses to a Mi-go myrmidon, but barerly, with Mi-go having about 5% HP left. In bigger numbers, or when they attack with some grabbers or similar they pose true endgame threat if ignored. 

#### Additional context

I am not native english speaker. Any points about zombie descrieptions are welcome

2024-06-19 19:23 UTC, Karol1223 requested changes

2024-06-19 19:23 UTC, Karol1223 commented on data/json/monsters/zed_skeletal.json
> +    "flags": [
Handle this via ``extend``/``delete``, not manually defining flags.

2024-06-19 19:23 UTC, Karol1223 commented on data/json/monsters/zed_skeletal.json
> +    "flags": [
As above

2024-06-22 17:02 UTC, RAldrich commented
Why is the slasher able to smell? None of the other skeletons do so, and I thought we were reserving that ability for monsters that evolved from things like dogs (or the stalker series of zombies). I think it would make sense to remove that ability.

2024-06-22 17:46 UTC, Karol1223 commented
> Why is the slasher able to smell? None of the other skeletons do so, and I thought we were reserving that ability for monsters that evolved from things like dogs (or the stalker series of zombies). I think it would make sense to remove that ability.

It's been significantly more restricted than it used to be, but smell is pretty common around the brute-tier of enemies still, including both skeletal brutes and juggernauts.

2024-06-23 10:35 UTC, Karol1223 requested changes
You gotta leave double spaces after periods

2024-06-23 10:35 UTC, Karol1223 commented on data/json/monsters/zed_skeletal.json
> +    "description": "The fingers of this bone-clad zombie have turned into ossified blades the size of large knives. Most of the soft tissue on its head is gone, exposing a significantly thickened sku
```suggestion
    "description": "The fingers of this bone-clad zombie have turned into ossified blades the size of large knives.  Most of the soft tissue on its head is gone, exposing a significantly thickened skull.",
```

2024-06-23 10:35 UTC, Karol1223 commented on data/json/monsters/zed_skeletal.json
> +    "description": "The hands and forearms of this tall, bone-clad zombie have transformed into sword-like ossified blades. Its jaw is partially fused with the bone mask covering its face, leaving si
```suggestion
    "description": "The hands and forearms of this tall, bone-clad zombie have transformed into sword-like ossified blades.  Its jaw is partially fused with the bone mask covering its face, leaving sinister-looking gaps.  Its movements are stiff but precise.",
```

2024-06-23 10:35 UTC, Karol1223 commented on data/json/monsters/zed_skeletal.json
> +    "description": "This large, bone-armored zombie has scythe-like blades in place of its hands, resembling a praying mantis. Its face is covered by a thick, ossified mask, with its only remaining f
```suggestion
    "description": "This large, bone-armored zombie has scythe-like blades in place of its hands, resembling a praying mantis.  Its face is covered by a thick, ossified mask, with its only remaining facial features being eyes that ooze black goo.  Its movements are filled with unnatural rage.",
```

2024-06-26 05:10 UTC, merged