Regenerating zombie evolutions
CleverRaven/Cataclysm-DDA pull request #74880
Opened 2024-07-03 17:22 UTC by Daved27hundred

#### Summary
Content "Expands the regenerating zombie into it's own line"

#### Purpose of change

The regenerating zombie was one of my first contributions to the game, 4 years ago. Since then I've seen people encounter it on occasions and they've stated that it was somewhat of a pushover despite it's threatening appearance. Probably because it doesn't have anything it upgrades into.

#### Describe the solution

I set to make the regenerating zombie's line into something that conveys how unstable it's mutation is - It first transforms into a hunter analogue, a hunched and deformed humanoid capable of leaping and climbing, before its regenerative abilities degrade it into a misshapen creature that loses it's ability to leap, but gains several ranged melee attacks in its stead. I was initially going to go with a regular zombie > hunter > predator line, but I wasn't satisfied with it.

#### Describe alternatives you've considered

I could return the final evolution to it's original predator design, but I also had other, more out-there ideas. Initially I thought "wouldn't it be cool if the predator ejected it's skeleton on death, and became something similar to a hollow?" But I decided against it due to it being too silly. 

#### Testing

Will test right after I publish this PR

#### Additional context

2024-07-03 20:22 UTC, Karol1223 requested changes

2024-07-03 20:22 UTC, Karol1223 commented on data/json/monsters/zed_misc.json
> +    "description": "This zombie hardly resembles a human anymore - Its skeleton has been repeatedly dismantled and reassembled into a horrid quadrapedal shape, like some sort of mismatched action fig
```suggestion
    "description": "This zombie hardly resembles a human anymore - Its skeleton has been repeatedly dismantled and reassembled into a horrid quadrupedal shape, like some sort of mismatched action figure.  Slick, bloodied flesh writhes on its frame with an almost viscous quality, digesting and reconstituting itself in an endless ouroboros of undead flesh.",
```

2024-07-03 22:30 UTC, ADekema commented
I like that instead of going down the standart combine line with other line you instead make it something unique. I also like the direction of regeneration becoming more unstable over time. A extra form that takes the regeneration even further would be cool. 

An example you could use for inspiration would be:

¨Churning abonination¨
¨This creature regenerates so quickly it is impossible to discern what this creature might once have been. Muscles emerge in seconds violently ripping their way through before snapping by the next muscles emerging form beneath. Loud cracks and pops sound as limbs and features  violently bend and deform only to snap back into place. Any surface features such as skin, hair or orifices have long been torn apart by the churning tissues underneath. The only feature remaning are a pair of eyes whose pupiles seem to constantly deform, split and join agian only for a eye to accationally pop out as it is pushed out by a new one behind it.¨

It would be inferior in every way from it´s predicesor with the exeption of HP and regeneration. What makes it dangerous would be the fact that when damaged the regeneration would reach explosives levels spreing scrapnal in the form of bone  fregments everywhere. This would make it extremely dangerous in mellee or could be used to your advantage if you have a ranged attack.

2024-07-04 01:46 UTC, Daved27hundred commented
> I like that instead of going down the standart combine line with other line you instead make it something unique. I also like the direction of regeneration becoming more unstable over time. A extra form that takes the regeneration even further would be cool.

thx :) I consider the abomination the endpoint for the line, but If I ever make another upgrade, it's going to be a sidegrade rather than an evolved form of the abomination

2024-07-08 21:16 UTC, merged