Calcium phosphate
CleverRaven/Cataclysm-DDA pull request #75059
Opened 2024-07-17 06:58 UTC by Rocket-F-1024

#### Summary

Content "Add calcium phosphate and related recipes"

#### Purpose of change

Based on a discussion in another PR(https://github.com/CleverRaven/Cataclysm-DDA/pull/74997).

#### Describe the solution

Add calcium phosphate.
Add recipes that use bones to produce calcium phosphate.
Changing the raw material for the recipe to produce white phosphorus from bone meal to calcium phosphate.
Modify the data and related recipes for white phosphorus.

#### Describe alternatives you've considered

None.

#### Testing

Go into the game, check the recipe and item, and all is well.

#### Additional context

None,

2024-07-23 17:24 UTC, Maleclypse commented
Can you link to recipes from journals or other places that list the actual equipment needed and amount of heat applied etc so I can review the new recipes compared to that?  That will make reviewing this much faster.

2024-07-24 00:38 UTC, kevingranade requested changes
This is very abbreviated compared to what even wikipedia outlines, please look into what is entailed, both in tools and components in some actual production methods.

2024-07-24 00:38 UTC, kevingranade commented on data/json/recipes/recipe_medsandchemicals.json
> +    "tools": [ [ [ "surface_heat", 30, "LIST" ] ], [ [ "water", 1 ], [ "water_clean", 1 ] ] ],
This needs distillation apparatus and several other pieces of equipment, please do some research here.

2024-07-24 00:38 UTC, kevingranade commented on data/json/recipes/recipe_medsandchemicals.json
> +    "tools": [ [ [ "surface_heat", 20, "LIST" ] ] ],
What process is this supposed to be? I'm not aware of a process where heating bone meal on a stove is productive.

2024-12-09 06:24 UTC, Night-Pryanik commented
Closing as stale. If you wish to continue working on this, ping me to reopen.

2024-12-09 06:24 UTC, closed without merging