add ar-15 .22 conversion kit
CleverRaven/Cataclysm-DDA pull request #75210
Opened 2024-07-24 13:52 UTC by GuardianDll

#### Summary
None
#### Purpose of change
ar-15 is funky, and multiple brands offers the kits to convert it into .22 round. why not?
#### Describe the solution
Add a conversion kit, with 10 and 28 round mags offered (stats delivered from chiappa production)

2024-07-24 14:50 UTC, GuardianDll commented on data/json/items/gunmod/conversions.json
> +    "description": "This is a complete upper receiver assembly containing a barrel, handguard, and bolt carrier group that, given the right knowledge, is installable upon an AR-15-style rifle's lower
```suggestion
    "description": "This is a complete upper receiver assembly containing a barrel, handguard, and bolt carrier group that, given the right knowledge, is installable upon an AR-15-style rifle's lower frame.  Swappable uppers enable compatible firearms to be retooled for different cartridges and barrel lengths, with this kit furnishing a weapon with a 16-inch barrel chambered for .22 rounds.",
```

2024-07-24 15:44 UTC, Hyperseeker commented
The M4-22 [might not be the best choice](https://reddit.com/r/22lr/comments/sz64b5/chiappa_m422_gen_ii_post_mortem/) unless you're decidedly making the .22LR conversion dangerous:

> Huge wall of text so tl;dr, my Chiappa M4-22 Gen II with ~4500 rounds through it had a catastrophic failure that resulted in the upper falling to pieces in my hand during a routine cleaning.

The [PSA upper](https://palmettostatearmory.com/psa-16-22-lr-1-16-nitride-13-5-lightweight-m-lok-upper-with-bcg-ch-516446934.html) might be a better choice. [The reviews](https://www.pewpewtactical.com/psa-22lr-upper-review/) aren't exceptional, but the primary complaint is a lack of compatibility with some lowers, which the game doesn't model.

2024-07-25 06:26 UTC, DoctorBoomstick requested changes

2024-07-25 06:26 UTC, DoctorBoomstick commented on data/json/items/magazine/22.json
> +    "description": "A black polymer magazine for ten of .22 rounds, for AR-platform rifles with conversion kit.",
```suggestion
    "description": "A black, 10-round polymer magazine for AR-platform rifles converted to fire .22 Long Rifle ammunition.",
```

2024-07-25 06:26 UTC, DoctorBoomstick commented on data/json/items/magazine/22.json
> +    "description": "A black polymer magazine for 28 of .22 rounds, for AR-platform rifles with conversion kit.",
```suggestion
    "description": "A black, 10-round polymer magazine for AR-platform rifles converted to fire .22 Long Rifle ammunition.",
```

2024-07-25 09:43 UTC, harakka commented
> The M4-22 [might not be the best choice](https://reddit.com/r/22lr/comments/sz64b5/chiappa_m422_gen_ii_post_mortem/) unless you're decidedly making the .22LR conversion dangerous

This is not meant to be that specific item, the stats are just taken from there. It stands in for AR .22lr kits in general, just like we don't have other brand+model kits.

2024-07-26 05:36 UTC, GuardianDll commented on data/json/items/gunmod/conversions.json
> +    "//": "AR has too big recoil for .22 round, 83 is right on the edge of being able to use blackpowder loaded and ratshot",
```suggestion
    "//0": "AR has too big recoil for .22 round, 83 is right on the edge of being able to use blackpowder loaded and ratshot",
```

2024-07-26 05:37 UTC, GuardianDll commented on data/json/items/gunmod/conversions.json
> +    "//": "AR has too big recoil for .22 round, 83 is right on the edge of being able to use blackpowder loaded and ratshot",
```suggestion
    "//0": "AR has too big recoil for .22 round, 83 is right on the edge of being able to use blackpowder loaded and ratshot",
```

2024-07-28 17:48 UTC, Holli-Git commented on data/json/items/magazine/22.json
> +    "description": "A black, 10-round polymer magazine for AR-platform rifles converted to fire .22 Long Rifle ammunition.",
```suggestion
    "description": "A black, 28-round polymer magazine for AR-platform rifles converted to fire .22 Long Rifle ammunition.",
```

2024-07-28 17:48 UTC, Holli-Git commented on data/json/items/gunmod/conversions.json
> +    "min_skills": [ [ "weapon", 2 ] ],
```suggestion
    "min_skills": [ [ "weapon", 2 ] ],
    "damage_modifier": 2,
```
![image](https://github.com/user-attachments/assets/ced00871-a168-4ea4-b9a7-657250e707f3)
.22 LR doesn't have the special ballistic by the inch data yet, so damage modifiers need to be calculated/added manually.

2024-07-28 21:57 UTC, GuardianDll commented on data/json/items/gunmod/conversions.json
> +    "magazine_adaptor": [ [ "22", [ "22_ar15mag_10", "  22_ar15mag_28" ] ] ],
```suggestion
    "magazine_adaptor": [ [ "22", [ "22_ar15mag_10", "22_ar15mag_28" ] ] ],
```

2024-07-29 21:17 UTC, merged