remove mutations by radiations option
CleverRaven/Cataclysm-DDA pull request #75497
Opened 2024-08-07 04:11 UTC by sonphantrung

#### Summary
None

#### Purpose of change
Getting yourself ridiculously high radiation (in order to get mutated in the first place) is something one fucks around and find out, not really something on accident.

#### Describe the solution
Remove the option

#### Describe alternatives you've considered
None

#### Testing
Will try and compile later, but mostly, should work.

#### Additional context
I'm quite surprised this option hasn't been looked over during the "Option removal spree" period.

2024-08-07 05:55 UTC, Maleclypse requested changes
Eh, this could change from a world option but we’d still want it as a json editable option for mods to make use of.

2024-08-07 06:44 UTC, Venera3 commented
> Eh, this could change from a world option but we’d still want it as a json editable option for mods to make use of.

That would be pretty simple to hook up in a tiny EoC, there's no real need to keep it as a hardcoded option - and that way mods can change the behavior to taste (like mutating decrementing radiation levels or applying different effects on top of a straight mutation).

2024-08-07 11:12 UTC, sonphantrung commented
> Eh, this could change from a world option but we’d still want it as a json editable option for mods to make use of.

Yeah, that is what I plan to do, but I'm wondering if there already exists the rad value in JSON, and the fact that whether you can compare between variables in the EOC?

2024-08-20 13:13 UTC, GuardianDll commented
Yes, it is possible to make it via radiation, i personally am okay with it being yeeted completely

2024-12-15 04:12 UTC, Maleclypse commented
```That would be pretty simple to hook up in a tiny EoC, there's no real need to keep it as a hardcoded option - and that way mods can change the behavior to taste (like mutating decrementing radiation levels or applying different effects on top of a straight mutation).
```
I'll close this for stale but I'm open to the above solution getting PRed in it's place.

2024-12-15 04:12 UTC, closed without merging