NPCs Will Forgive the Player Over Time
CleverRaven/Cataclysm-DDA pull request #75535
Opened 2024-08-09 02:31 UTC by MNG-cataclysm

#### Summary
Content "NPCs will forgive the player over time."

#### Purpose of change
For a very long time now, once an NPC became hostile to the player, there was no way for them to calm down, remaining angry forever. Under certain circumstances, this blocked off many actions with that NPC and was also unrealistic; people don't stay mad forever. As such, I decided it was time to change that.

#### Describe the solution
Using an EOC, have an NPC's anger value periodically decrease based on a timer. This effect is sped up based on how friendly you are with the NPC, how much they trust you, and is slowed down based on their anger. At high anger values, this can take a while, though it progressively gets faster the more anger is lost. Additionally, if the NPC has an anger threshold around hostile levels, they will calm down and exit their attacking to kill state.

#### Describe alternatives you've considered
Not doing this.

#### Testing
So far, everything works as I intended it to.

#### Additional context
Right now, I'm having trouble getting the final EOC to only run on NPCs and not the character. This will be fixed soon.

2024-08-09 06:28 UTC, harakka commented
Does the anger reduction apply to literally all NPCs? Won't this eventually make bandits nonhostile?

2024-08-09 11:04 UTC, Entity-y commented
If only there was a way to talk to hostile NPCs and have a percent chance to defuse their hostility, if you fail then have to run away and wait out a cooldown to try again much like asking an NPC to become a follower. Maybe the chance would be increasingly more difficult with every failed attempt but could slightly increase the chance by dropping your weapon or offering them something valuable from your inventory.

2024-08-09 19:52 UTC, kevingranade commented
There's a pretty big difference between, "stop being angry at someone" presumably for a social gaffe or something,  and "forget someone tried to kill you".

The minimum thing I could see working for this is tracking "anger from social sources" seperately from "anger from combat actions" and "anger from faction triggers", the social anger could decay over time but not the combat anger or faction anger.

2024-08-11 05:10 UTC, kevingranade commented
I'm not clear how what you changed relates to what I suggested.  I was saying add two different variables that are updated seperately.

Also on further review values related to anger don't have a very wide range,  one point an hour seems excessively fast.

2024-08-12 03:57 UTC, MNG-cataclysm commented
> I'm not clear how what you changed relates to what I suggested. I was saying add two different variables that are updated seperately.

I decided to only have this EOC track social anger and leave combat anger for something different. 

> Also on further review values related to anger don't have a very wide range, one point an hour seems excessively fast.

The EOC doesn't trigger for one point every hour, it just checks NPC anger each hour and sees if the forgiveness EOC has been queued or not. The actual forgiveness occurs several days after that.

2024-08-12 22:00 UTC, kevingranade commented
This needs a lot more grounding and clarity about what's happening and why, and I'm thinking EOC is not where it belongs.

The original goal was "hostile NPCs should stop being hostile", but we're dropping that because the #1 reason for that is "the player physically attacked you", which I'm asserting isn't a forgettable event.

Now it's, if you (repeatedly?) push a NPC too far they might, what not want to talk to you? What social interactions are you having that are angering NPCs enough for us to track it, but little enough that they're just going to forget about it in a few days?

That's the other layer here, I don't think simply decrementing a value is a reasonable approach here, if we want anger-inducing actions to have a "life cycle", we need to do something like stuff anger-causing events on a list, where they may or may not decay, depending on their details, not just "ehh people forget so eventually we're back at a blank slate no matter what the cause was".

2024-08-13 01:09 UTC, MNG-cataclysm commented
> Now it's, if you (repeatedly?) push a NPC too far they might, what not want to talk to you? What social interactions are you having that are angering NPCs enough for us to track it, but little enough that they're just going to forget about it in a few days?

That's the sort of thing I'm tracking with this, social gaffes. This would include things like being generally unpleasant towards NPC's in conversations (name calling, telling someone to go fuck themselves, etc.), attempting to intimidate somebody, failing certain missions of small scale (i.e not doing something in time), and other things of that nature. #75392 demonstrates some of what I was going for and what you previously mentioned, with certain NPC's refusing to talk to you above certain anger thresholds. I made this partially as a way to avoid permanent lockouts with NPC's in that PR, so that you can talk to them again after some time.

2024-08-13 02:34 UTC, kevingranade commented
I'm concerned about several aspects of this:

Lumping together failure to deliver on missions, intentionally giving offence, threats/intimidation, "just saying the wrong thing", etc. These are all very different interactions you would expect to have very different consequences,  even if recovery is scaled differently it feels weird that these are being scored on the same axis in the first place. 

I'll repeat,  I'm concerned about doubling down in EoC here,  that is not what it's for,  this is far more complex and fundamental than what EoC is supposed to handle in the game and I'm not comfortable extending things in the direction you're talking them.

Both the narrative and game purpose here are weak, it's better to be forgiving of the player acting badly indefinitely? No it isn't. It's this something people uniformly do? Not at all.

I'm kind of thinking this would only be suitable for a system where immediately after an anger causing event the npc has some increase to their anger score,  then after some time it might drop to 1/2 or 1/4 or so if the original,  basically relatively small events could cause the npc to stop talking to you immediately or even kick you out of a settlement, they might calm down over time but you never fully erase the impact. Then the next time it could trigger an even worse immediate response, and with enough times you're simply cut out.

I think that's the thing that bugs me the most here, fully erasing the impact of bad behavior doesn't make sense. If you're going to have ways explicitly outlined to make npcs angry,  you're going to eventually pass a point of no return. Otherwise why even have them get angry in the first place,  this should be serious stuff, not window dressing.

2024-08-13 08:56 UTC, Alm999 commented
I am concerned about this scenario: a player has met a new NPC (not a bandit, just a survivor).This NPC "decided" that the PC is weak and demanded to surrender. The player refused and failed skill/stat check. Now NPC is "attacking to kill". In this case PC did nothing "irredeemable" (apart refusing to comply with robbery) but NPC now thinks it is OK and totally justifiable to murder PC. :( And I repeat, that NPC is not a bandit: if reload earlier save and succeed in skill/stat check then you can learn that this NPC was just an office clerk and actually wanted to harvest some cattails.

Shall NPC (that caused the conflict in the first place) be able to "forgive" PC in this case?

2024-08-13 16:56 UTC, kevingranade commented
You are asking about a completely unrelated scenario. This isn't related to the proposed mechanic,  the way it works just needs to be overhauled. 


Since you brought it up just a brief outline of the problems:
Regardless of NPC role or personality they're opportunistically robbing other survivors. It should be possible that random NPCs are willing to turn mugger opportunistically, but it shouldn't be universal.
The transition from,  "attempt robbery" to "NPC definitely attacks" is problematic,  some people might try to bluff to get something but give up before it comes to combat.  People that will outright attack to kill in this situation would IMO be relatively rare.
Those are the issues to focus on (in a new issue), not the interacting between a forgiveness mechanic and the broken npc mugger system.

2024-08-23 17:29 UTC, kevingranade requested changes
I previously said "I'm thinking EOC is not where it belongs."
This is a very big deal,  we can NOT have core systems like this defined entirely in EOCs.

2024-08-23 18:40 UTC, MNG-cataclysm commented
> I previously said "I'm thinking EOC is not where it belongs." This is a very big deal, we can NOT have core systems like this defined entirely in EOCs.

Would it be alright if part of it was defined in EOC's, or is it better to convert all of the code to C++?

2024-08-24 00:06 UTC, MNG-cataclysm commented
> I previously said "I'm thinking EOC is not where it belongs." This is a very big deal, we can NOT have core systems like this defined entirely in EOCs.

Would it be possible to have some parts of this defined in EOC's, and some in C++, or is it preferable to have all of the existing code for this converted into C++? If the former is true, I'm planning to keep (most of) the effects defined in an EOC and converting the triggers to C++, in the form of a new `required_event` that would run when an NPC's opinion values change, allowing this to work without having to replace all other forms of changing anger values with `run_eoc_with`. That would also allow it to work with other hardcoded forms of opinion changes through trade and such. Other EOCs could also work off of this trigger. What's your opinion on this?

Also, how much JSON is usually acceptable for core systems to rely on before C++ is needed?

2024-08-24 07:02 UTC, kevingranade commented
The whole thing with multiple types of anger needs to be in code.
Honestly I'm very much questioning if any of this should actually happen.
You're not adressing any of the issues I'm bringing up either, I'm running out of effort I'm willing to expend on explaining myself.
Review *all* of the concerns I have brought up and see if you can come up with rationales and solutions that address all of them. At this point I'm strongly leaning toward "we don't actually need this".

2025-06-13 23:40 UTC, closed without merging