Baseball bat recipe
CleverRaven/Cataclysm-DDA pull request #75693
Opened 2024-08-15 03:05 UTC by brodbowl

#### Summary
Features "Adds a baseball bat recipe"

#### Purpose of change
You can't make a baseball bat in the game. It shouldn't be too hard to do for someone with some basic tools.

#### Describe the solution
1.Add a recipe for a baseball bat. See the image for details.
2.Remove the reference to a plastic handle on baseball bats. You don't need one.

I thought these were treated and was going to add a soaking period but apparently not.

#### Describe alternatives you've considered
Maybe some additional tools should be required?

#### Testing
Tested on my computer in debug mode.

#### Additional context
![Screenshot](https://github.com/user-attachments/assets/f0790d9a-311b-4568-99d9-843f1d8fe83a)

2024-08-15 09:04 UTC, Karol1223 requested changes

2024-08-15 09:04 UTC, Karol1223 commented on data/json/recipes/weapon/bashing.json
> +    "byproducts": [ [ "splinter", 10 ] ],
```suggestion
    "byproducts": [ [ "splinter", 30 ] ],
```

You're losing mass

2024-09-09 03:22 UTC, x-qq commented
I think this recipe needs filing 1 (= require sandpaper) and also include flame treatment for durability (= require fire). Real bats also undergo some sort of chemical treatment but I'm not sure how to represent it here.

Reference: https://www.youtube.com/watch?v=zwK4qdbWwdw

2024-09-21 20:10 UTC, bloodbowel commented
> I think this recipe needs filing 1 (= require sandpaper), include flame treatment for durability (= require fire) and require wood cutting 2. Real bats also undergo some sort of chemical treatment but I'm not sure how to represent it here.

I've been doing some research to parse out what is the best way to treat the bat. Originally I was going to have it be soaked like a spear shaft, but saw they didn't all do this. Not all are flame tempered either. The oldest method is bone rubbing which is just pressing it down with a hard object. This probably should require better tools including actual files.

2024-09-29 05:39 UTC, Maleclypse commented
Yeah go ahead and add either sand paper or wood filing or both as you see fit and this is mergeable.

2024-09-29 17:53 UTC, bloodbowel commented
I added the level 1 file. That should be good enough.

2024-10-01 15:37 UTC, merged

2024-10-02 23:37 UTC, Brambor commented
Looking at the commit history, this PR should have been `git merge --squash`ed, if the GitHub interface allows it.