turn off ATMs
CleverRaven/Cataclysm-DDA pull request #76051
Opened 2024-08-30 13:23 UTC by GuardianDll

#### Summary
None
#### Purpose of change
ATMs are still working. That's odd
#### Describe the solution
move ATM from terrain to furniture
update it's deconstuction and bash drops
make a copy that is turned off
replace all vanilla instances (and one in no hope) of powered one with off version

2024-08-30 15:35 UTC, Karol1223 requested changes

2024-08-30 15:35 UTC, Karol1223 commented on data/json/furniture_and_terrain/furniture_misc.json
> +    "description": "Design to withdraw money from your bank accoun, this this is completely dead now, both from having no more power, and having no internet connection to do any withdraws.  While you
```suggestion
    "description": "Designed to withdraw money from your bank account, this machine is completely dead now, both from having no more power, and having no internet connection to do any withdraws.  While you can deconstruct it, it's effectively just a big pile of metal.",
```

2024-09-01 19:33 UTC, x-qq commented
How do you load currency bundles onto your cash card now after this?

2024-09-01 20:04 UTC, GuardianDll commented
you don't, and you shouldn't

2024-09-01 20:54 UTC, x-qq commented
I think it's a fun feature and at least one working ATM somewhere should be kept operational.

2024-09-01 20:56 UTC, GuardianDll commented
only in aftershock, with working internet connection

2024-09-01 21:00 UTC, x-qq commented
An ATM inside a bank building will not need internet, it is connected directly into bank network, and can stay powered for a very long time by bank's backup genrator (practically indefinitely assuming advanced enough technology).

2024-09-01 21:02 UTC, GuardianDll commented
> connected directly into bank network

what makes bank network working? what holds servers of the bank miles away still online? grid is dead in the whole country

2024-09-01 21:03 UTC, x-qq commented
The bank server is inside the bank building. The ATM is connected to it by cable. It is all powered by backup power.

2024-09-02 04:54 UTC, harakka commented
> can stay powered for a very long time by bank's backup genrator (practically indefinitely assuming advanced enough technology).

We don't have any particularly advanced technology. A random bank office doesn't have backup power to keep it running indefinitely or indeed for any notable length of time.

2024-09-03 17:06 UTC, Kozakow commented
As of right now, cash cards are only useful for vending machines and gas stations, former of which can be relatively easily broken into. Since the ammo vending machines received the SHIFT+DELETE treatment, there really is no other use for electronic money (robot helper is just a gimmick, and maybe a good source of electronic parts). 

Since gas stations working are also a grey area, i doubt there really is any reason to keep inventing excuses for why ATMs should be operational. Once there is a way to siphon fuel from the underground tanks (or those located on the surface, which our 15 INT post-treshold Alpha mutant survivor still can't get into), cash cards as a whole will lose all purpose.

2024-09-04 05:37 UTC, merged

2024-11-20 21:03 UTC, Little-119 commented
>Once there is a way to siphon fuel from the underground tanks (or those located on the surface, which our 15 INT post-treshold Alpha mutant survivor still can't get into), cash cards as a whole will lose all purpose.

That's not true!
...they'll still be usable as arrow fletching.