Add TRANSLUCENT terrain flag which blocks vision but not light
CleverRaven/Cataclysm-DDA pull request #76290
Opened 2024-09-08 18:06 UTC by GuardianDll

#### Summary
None
#### Purpose of change
Reopen #61872
#### Describe the solution
Fix conflicts mostly
#### Testing
![image](https://github.com/user-attachments/assets/d9cbdf78-2401-41d9-87bb-abbf02049e87)
#### Additional context
Previous PR was drafted because it was pointed terrain should not require TRANSPARENT flag, i'm still fixing it

2024-09-08 18:40 UTC, ashGlaw commented
Excellent idea! I've wanted this functionality for a while

2024-09-09 08:49 UTC, GuardianDll commented on tests/vision_test.cpp
> +TEST_CASE( "vision_translucent_blocks_vision_but_not_light" "[shadowcasting][vision]" )
```suggestion
TEST_CASE( "vision_translucent_blocks_vision_but_not_light", "[shadowcasting][vision]" )
```

2024-09-09 11:10 UTC, CLIDragon requested changes

2024-09-09 11:10 UTC, CLIDragon commented on src/lightmap.cpp
> +    for( const tripoint &loc : points_in_radius( p, 60 ) ) {
May as well use `MAX_VIEW_DISTANCE`, that's what it's there for.

2024-09-10 12:39 UTC, merged