Remove THRESH_ELF from ANIMALEMPATH2
CleverRaven/Cataclysm-DDA pull request #76647
Opened 2024-09-24 16:26 UTC by Psithief

#### Summary
Bugfixes: "Remove Magiclysm elf threshold requirement on Animal Kinship"

#### Purpose of change

The base `ANIMALEMPATH2` trait does not have a threshold requirement and is in the LUPINE and ELFA categories. When Magiclysm is enabled, it adds the `SPECIES_ELF` category, but it also adds the `THRESH_SPECIES_ELF` requirement, blocking the `ELFA` and `LUPINE` categories from accessing it. This seems to be unintentional.

#### Describe the solution

This commit removes the threshold requirement introduced by Magiclysm.

#### Describe alternatives you've considered

There is no alternative, as the effects of the `ANIMALEMPATH` and `ANIMALEMPATH2` traits are hard-coded.
Adding the THRESH_ELF and THRESH_LUPINE requirements is not acceptable.

#### Testing

1. Create a character
2. Debug add the debug mutations for HP, regen and needs
3. Debug add 100000 mutagen, 100000 primer for either `ELFA` or `LUPINE`
4. Verify ANIMALEMPATHY2 can be obtained by passing a lot of time.

#### Additional context

-

2024-09-24 22:19 UTC, Maleclypse commented
It would be preferable if you flagified the effects in c++ to this.

2024-09-25 03:33 UTC, Maleclypse requested changes, later dismissed
The section you need to change in order to flagify is as follows.
```
if( u->has_trait( trait_ANIMALEMPATH ) ) {
                effective_anger -= 10;
                if( effective_anger < 10 ) {
                    effective_morale += 55;
                }
            } else if( u->has_trait( trait_ANIMALEMPATH2 ) ) {
                effective_anger -= 20;
                if( effective_anger < 20 ) {
                    effective_morale += 80;
                }
            } else if( u->has_trait( trait_ANIMALDISCORD ) ) {
                if( effective_anger >= 10 ) {
                    effective_anger += 10;
                }
                if( effective_anger < 10 ) {
                    effective_morale -= 5;
                }
            } else if( u->has_trait( trait_ANIMALDISCORD2 ) ) {
                if( effective_anger >= 20 ) {
                    effective_anger += 20;
                }
```
you'll also want to add the flags and delete the static const traits at the top of the file.  Super easy.

2024-09-25 03:56 UTC, Psithief commented
> It would be preferable if you flagified the effects in c++ to this.

I don't write C++

2024-09-25 09:07 UTC, Psithief commented
Your loss.

2024-09-25 12:27 UTC, Aerin-of-the-Toast commented
> Your loss.
> 
> I find it bizarre you'd try to strong-arm me into doing this.

That's because he's not trying to "strong-arm" you. He's saying do it right or don't do it at all and let someone else do it right.

And the suggestion to make an issue so someone else can do it right was just that, a suggestion. Suggestions aren't "strong-arming." 

You are not obligated to do anything.

2024-09-25 14:36 UTC, Maleclypse commented
> Your loss.
> 
> I find it bizarre you'd try to strong-arm me into doing this.

Well if you'd made the issue instead of assuming malice I'd have fixed it for you over the weekend since it's like a 20 minute thing I didn't have time to do last night.

2024-09-25 19:24 UTC, Maleclypse commented
Great news. Standing Storm reached out to me and said that he was both flagifying it and that the Magiclysm threshreq was an accident.  This will be mergeable while we wait for his PR to finish.

2024-09-25 21:53 UTC, merged