Allow rot_spawn use monster id directly
CleverRaven/Cataclysm-DDA pull request #76845
Opened 2024-10-05 22:24 UTC by GuardianDll

#### Summary
None
#### Purpose of change
Close #76785
#### Describe the solution
Slightly redo the way json is read, add few new field
load_min_max() is moved above because i wanted to use it, and didn't want to use forward declaration
json is churned using regex and few manual edits
#### Describe alternatives you've considered
If we have some way to inline monster group defintion, it can be used instead, but i am not aware we have such
#### Testing
Tested new syntax, tested it's inheritance, seems to work same as before
11 calfs born out of 9 eggs with 70% chance to spawn and [ 1 ,3 ] count:
![image](https://github.com/user-attachments/assets/0f617adc-d25b-4f1d-a5ff-ea64b7906734)
#### Additional context
regex used, in order:
```
"rot_spawn": "([A-Za-z0-9_]*)",[\n ]*"rot_spawn_chance": ([0-9]{1,3})
"rot_spawn": { "group": "$1", "chance": $2 }

"rot_spawn": "([A-Za-z0-9_]*)",[\n ]*"rot_spawn_chance": ([0-9]{1,3})
"rot_spawn": { "group": "$2", "chance": $1 }

"rot_spawn_chance": ([0-9]{1,3})
"rot_spawn": { "chance": $1 }

"rot_spawn": "([A-Za-z0-9_]*)"
"rot_spawn": { "group": "$1" }
```

2024-10-06 08:37 UTC, Karol1223 commented
Guardian you silly fellow you linked the wrong issue

2024-10-06 08:40 UTC, Karol1223 requested changes

2024-10-06 08:40 UTC, Karol1223 commented on data/json/items/comestibles/egg.json
> +    "spoils_in": "20 minutes",
```suggestion
    "spoils_in": "20 minutes",
```

Nuh huh. That's your testing changes you never reverted.

2024-10-06 09:21 UTC, Karol1223 requested changes

2024-10-06 09:21 UTC, Karol1223 commented on doc/JSON_INFO.md
> +"rot_spawn": {                    // Defines what creature would be spawned when this item gonna rot. Mostly used for eggs
```suggestion
"rot_spawn": {                    // Defines what creature would be spawned when this item rots away. Primarily used for eggs
```

2024-10-06 09:21 UTC, Karol1223 commented on doc/JSON_INFO.md
> +  "amount": 2,                    // if "monster" is used, defines how many of this monster will be spawned;
```suggestion
  "amount": 2,                    // if "monster" is used, defines how many instances of this monster will be spawned; 
```

2024-10-06 09:21 UTC, Karol1223 commented on doc/JSON_INFO.md
> +  "chance": 70                    // chance for animal to spawn from single item
```suggestion
  "chance": 70                    // chance for the monster to spawn from a single item
```

2024-10-10 18:51 UTC, Maleclypse commented
conflicts

2024-10-11 21:12 UTC, merged