Resolve Milling Issues/Errors
CleverRaven/Cataclysm-DDA pull request #76999
Opened 2024-10-12 22:46 UTC by TheMurderUnicorn

#### Summary
Bugfixes "Resolve Milling Issues/Errors"

#### Purpose of change
When harvesting certain skulls/debug spawning them, errors were received stating they had missing milling recipes.  I have added these milling recipes, as well as some skull requirement groups. 

#### Describe the solution
This solution was pulled from #76334 which outlined a solution for two of the three errors.  Most of what I've done here is exactly what was outlined.  I added two requirement groups so that we can call similarly sized skulls from the milling recipes.  Then I added the milling recipes.  2 small skulls = 1 bone meal, 1 medium skull = 1 bone meal, and 20 rodent skulls = 1 bone meal.

Just as a heads up, the small canine skull has the id with 'medium' in it, and the tiny canine skull has an id with 'small' in it, these are not issues with what I've done here, they are issues with their names and ids not matching up.

#### Describe alternatives you've considered
Making Karol do it.

Debated changing the name/ids of the skulls so they match but that's out of scope and I was cautioned against fucking with IDs.  Although now that I look at it, it looks like these would be name changes not ID changes.

#### Testing
Once I wrapped my head around how milling works, I basically just did the changes and made sure that the mill took the right number of skulls and that it output the right amount of bone meal.  I also tested to see if this resolved the errors, which it seems to have fixed correctly.  Additionally, I originally got the error from #76332 but did not get it again after making my changes, though I can't tell if this is just me or if I also fixed that issue.

#### Additional context
closes #76334 

Possibly is also a fix for #76332 but I'm hesitant to say that when I don't fully understand that cause.  To my understanding it's an imgui failure when trying to output an in-game error message -- that error may have been related to the lack of a milling recipe, and so it's conceivable it was fixed here.  Again, I'm no coder, barely know what I'm doing, so I'm not going to mark this as closed when I have no idea if it's actually fixed.

Was going to ping Karol but let's be honest, your ass is already looking at this.

And here's my TLDR/checklist in case someone wants a quickly readable version
![image](https://github.com/user-attachments/assets/53080577-d17d-44f1-9725-4b5260585e2b)

2024-10-12 23:40 UTC, TheMurderUnicorn commented
I'll be honest, I'm very confused why the test failed and why it's even testing these skulls as having calories.  The skulls have no calories, but the bone meal does.  But also the bone meal's calories fall in line with the tests calorie bounds, so I have no idea what any of this means and will probably need a little help understanding. 

This is the Cataclysm Windows build/ Build (pull_request) failure and idk what to do about it.
![image](https://github.com/user-attachments/assets/65cd5985-424f-49ee-bc87-95d5e91522a9)
The changes I've made are basically identical copies to existing recipes that don't trigger this, and I'm not seeing anything that indicates the skulls are somehow wrongly identified as food or anything? Anyone know what I should be doing here?

2024-10-13 01:17 UTC, AudBobb commented
Does it need the force override tag for calories, since the ingredients have 0, causing the output to have 0, when it is expecting output to have non-zero?

Just a wild guess

2024-10-13 01:40 UTC, TheMurderUnicorn commented
Unfortunately, Nutrient override flag can only be applied to the item itself (bone meal) afaik.  This can't be done because the other bone meal recipes use different items that do have inherent calories, and this would stop bonemeal from inheriting calories from those items.  If there's a flag that's usable to prevent recipes from pushing their calories or adds them to the base calories, I couldn't find it.  So, unless we want all bonemeal clamped at 35 calories regardless of source, I don't know how to do this.

2024-10-13 01:47 UTC, AudBobb commented
Hmm didn't realize that flag was applied directly to the item. Looking through the other milling recipes related to bones, the bone skewer to bone meal recipe also turns an item that has no calories into one that does, and follows the exact format as your entries. I loaded up a test world and spawned a windmill, and bone skewers, and the bone meal it produces does in fact have 0 calories. 

I think the solution to this issue is to modify the ingredient items to include calories, like bone does.

2024-10-13 01:59 UTC, TheMurderUnicorn commented
Looking at previous PRs I don't see why the skewers didn't trigger the same test issue, there was some discussion in the initial PR but I'm not really understanding it.  If it's a matter of adjusting skull calories (which it shouldn't be imo) that's above what I'll be doing.  I don't see why them inheriting 0 calories actually matters at all and it's my opinion that the test should not care if they output 0 calories unless I'm missing something glaring.

2024-10-13 02:02 UTC, AudBobb commented
It's not a major issue tbh, the test is more a sanity check for actual food items, this is just a weird edge case. I can go in and fix the skulls real quick to have calories so that it fixes your issue. Just submitted a fix for the bone skewers, so I'm in the files anyways

2024-10-13 10:43 UTC, Karol1223 commented
Give them nutrient override. Bone meal has values based off irl bone meal, it can have that.

2024-10-13 11:22 UTC, TheMurderUnicorn commented
This does not work, I already tried it when it was suggested earlier.  It produces bone meal with 0 calories even with NUTRIENT_OVERRIDE
![image](https://github.com/user-attachments/assets/ce90f841-03fa-4fc1-887f-420534e560e3)
Unless I put it in the wrong place somehow:
![image](https://github.com/user-attachments/assets/2c9ff3fc-c76d-4206-a828-08ea22ad5191)

2024-10-13 11:50 UTC, Karol1223 commented
You did. It's an item flag, not a recipe flag. You put it in the item definition.

2024-10-13 12:10 UTC, TheMurderUnicorn commented
This makes me nervous, I thought there was a reason I didn't want to clamp bonemeal to 35.  It has so many sources and I'm worried it'll mess something up but honestly I turned what I thought was a simple PR into a shitshow so whatever, this should do it.

2024-10-13 12:13 UTC, Karol1223 commented
> This makes me nervous, I thought there was a reason I didn't want to clamp bonemeal to 35. It has so many sources and I'm worried it'll mess something up but honestly I turned what I thought was a simple PR into a shitshow so whatever, this should do it.

This will nerf manual bone meal crafting recipes and tbh that's fine. You won't get 100% of the calories out of a bone if you grind it into powder, because you'll lose some powder along the way and all that. This way hand-crafted bonemeal will go from being ~43kcal a piece to 35kcal a piece. That is fine.

2024-10-13 14:02 UTC, Karol1223 commented
Oh god, nevermind, I really put you on a trap with asking you to do this one for me.

``NUTRIENt_OVERRIDE`` will break cannibalism from human bones. This is a mess.

2024-10-13 14:21 UTC, AudBobb commented
Feels like we need a flag for recipes that forces the recipe output to have the items default calories.

2024-10-13 14:26 UTC, Karol1223 commented
> Feels like we need a flag for recipes that forces the recipe output to have the items default calories.

I'd even go as far as to say that this should be automatic and not handled by a flag - if a comestible is crafted from items that cannot have calories at all (so no comestibles as ingredients), it should be crafted with its default values instead of trying to inherit something that doesn't exist.

2024-10-13 20:20 UTC, TheMurderUnicorn commented
When you think you can be productive ;-; Closing PR

2024-10-14 00:13 UTC, RenechCDDA commented
> > Feels like we need a flag for recipes that forces the recipe output to have the items default calories.
> 
> I'd even go as far as to say that this should be automatic and not handled by a flag - if a comestible is crafted from items that cannot have calories at all (so no comestibles as ingredients), it should be crafted with its default values instead of trying to inherit something that doesn't exist.

...Remind me for this

2024-10-31 11:04 UTC, Karol1223 commented
Wake up, Murder, fix for this just got merged

2024-10-31 11:05 UTC, Karol1223 requested changes

2024-10-31 11:05 UTC, Karol1223 commented on data/json/items/resources/bone.json
> +    "flags": [ "EDIBLE_FROZEN", "NUTRIENT_OVERRIDE" ],
```suggestion
    "flags": [ "EDIBLE_FROZEN" ],
```

It must be done

2024-11-13 20:08 UTC, Karol1223 commented
> Yeah, so, I saw you kicked the tests, unfortunately, this is still failing due to the test being unhappy that the expected calories don't fall in line properly, and as far as I know, this has not been resolved/I don't know how to fix it despite other people having contributed to 'fix' it. So, the PR is dead until something changes and I'm not the one to resolve these issues. Should I just close the PR?

Everything is evil. I have no clue what's going on anymore. According to all known laws of aviation, the tests should not be failing, but the tests fail anyway because they don't care.

2024-11-18 04:52 UTC, merged