party toilet only for flushing illegal stuff
CleverRaven/Cataclysm-DDA pull request #77086
Opened 2024-10-16 09:16 UTC by Kamejeir

#### Summary
None

#### Purpose of change
![image](https://github.com/user-attachments/assets/b04af801-812c-4910-8440-3ade04ed9db5)
mr harakka suggested this, and I chose to pick it up. After further deliberation, it turned into removing stuff that didn't make sense to hide

#### Describe the solution
New "stash_drugs_illegals" itemgroup for use in private resort toilets. I am keeping in tobacco pipes and glass pipes (bongs) because I guess they would be able to be crushed and flushed, and the party people didn't want the police to find traces.

#### Describe alternatives you've considered

#### Testing
Added various debug items to the itemgroup in question to know that the private resort toilets (like in picture) are the ones currently being changed, then removed said debug items along with all other nonsensical items after making sure by seeing. Then did a non-exhaustive test to see that weird legals aren't spawning.
![image](https://github.com/user-attachments/assets/ca456a31-3c34-40e4-82c4-7f278e4d7e47)

#### Additional context
Please correct me on missing illegal stuff and potentially kept legal stuff, I only made very shallow searches.

2024-10-16 12:43 UTC, Karol1223 requested changes

2024-10-16 12:43 UTC, Karol1223 commented on data/json/itemgroups/stashes.json
> +      { "prob": 5, "group": "melatonin_tablet_bottle_plastic_pill_supplement_1_30" },
Why is like the most normal sleep medication in the universe in a group with illegal drugs

2024-10-16 12:51 UTC, PatrikLundell commented
If people were flushing drugs down the toilets you wouldn't be able to find them, as they'd be flushed away. However, if they hid it in the toilet tanks in some kind of water proof containers it would make some kind of sense (the "sense" being that police would be too ignorant or, more probably, lazy or subject to accepting incentives, to look in such obvious hiding spots).

2024-10-17 07:53 UTC, Kamejeir commented
huh why github. why did you do that

2024-10-17 07:53 UTC, closed without merging