Use for loops to enumerate glyphs needed by font
CleverRaven/Cataclysm-DDA pull request #77300
Opened 2024-10-24 17:14 UTC by ehughsbaird

#### Summary
None

#### Purpose of change
Remove 34kLOC. 

#### Describe the solution
Instead of having a line (or more than one) for each glyph that a language will need in a font, sort them and collapse adding adjacent characters into a for loop.

Don't collapse short spans, which will require as many or more lines with a for loop.

#### Describe alternatives you've considered
There are perhaps other patterns that could be detected than immediately adjacent, but detecting those are more difficult.

#### Testing
I don't have a tiles build handy to test.

2024-10-25 01:22 UTC, akrieger commented
I guess it's... not more broken than before?

2024-10-25 17:26 UTC, akrieger commented
Ok technically clang-tidy needs another suppression.

2024-10-26 08:16 UTC, CLIDragon commented
Lines 13 - 39 could be made into one multiline string which would be much more readable.

2024-10-27 17:26 UTC, db48x requested changes

2024-10-27 17:26 UTC, db48x commented on build-scripts/get_translation_characters.py
> +    print("#if defined(__GNUC__) or defined(__clang__)")
Can you tidy this up by moving the preprocessor nonsense into a separate function?

2024-11-29 16:42 UTC, ehughsbaird commented
It seems good to me.
![image showing language selection screen with properly rendered names of languages](https://github.com/user-attachments/assets/a714ce00-f89f-4cf2-9169-9a75523a2647)
![image showing the item info page for a fire hydrant in Japanese](https://github.com/user-attachments/assets/7ae6e547-d734-4f65-882c-c813bc44292e)
![image showing the item info page for the same fire hydrant in Russian](https://github.com/user-attachments/assets/e73e4868-7a99-4144-b4fe-4ddf23690f89)

2024-11-29 20:57 UTC, db48x approved these changes

2024-11-30 12:38 UTC, merged