[Request Comment] Adding new batch craft recipes for glass crafting
CleverRaven/Cataclysm-DDA pull request #77336
Opened 2024-10-25 17:48 UTC by AudBobb

See additional context. Hoping for comment on how I could improve this.

#### Summary

Features "Add new batch crafting recipes for glass items using the glassblower's crucible"

#### Purpose of change

To implement batch crafting savings to crafting of glass items

#### Describe the solution

Use fancy math to determine how long it should take to melt glass.
<details>Took 4 data points gathered from a users of r/glassblowers on reddit for how long a kiln takes to melt glass, and determined that the data had a (nearly) linear relationship in the second derivative. This seemed reasonable to me, so despite the limited data I had to work with, I opted to proceed. I then used this information to extrapolate some more data points on the low end. I used a service to form a best fit equation on this data, and form a new graph off of that equation. I could then use this graph to calculate how long it should take to melt a given amount of glass.<details>

Then I split up the time to craft each item into time to melt the glass and time to craft the item once the glass has melted.

Then assuming an 8 hour day of crafting a given item, figure out how many crafts could be done in a day, and how much of those 8 hours is waiting for glass to melt, and how much is crafting.
<details>I honestly did this through trial and error. I took the time to melt the glass for 1 item, subtracted it from 8 hours, divided the remaining time by the time to craft 1 item to get the number of crafts for the day, multiplied that by volume of glass to craft that number of items, and then checked time to melt that volume of glass, and then reran this process from step 2 using this new number. I repeated this process 5 or 6 times, till the numbers stopped showing any appreciable change. Yeah, there was probably a more elegant way to do this, but using excel it was honestly only like 5 minutes so meh<details>

Calculate the time spent melting glass for 8 hours of crafting the item as a percent for use in the batch crafting definition

#### Describe alternatives you've considered

Assigning a flat value to how long it takes to melt 1L of glass and calculating everything linearly from that value, saving myself 4-6 hours of work figuring up a graph for the relationship of glass volume to time to melt, and then doing all the calculations for crafts in a day, and really just making everything infinitely simpler, and probably more logical based on limitations of the crafting system. But where's the fun in that? 

Adding a flat 2 hours to melt glass for all batch craft recipes (even though that doesn't really make sense), then removing that 2 hours using the batch craft % because that would make this 10x easier. 

#### Testing

WIP

#### Additional context

Starting to think this isn't the best way to do this and would like some input from other people before continuing. I think my main issue boils down to this. The relationship of a volume of glass to how long it takes to melt is not linear, plus there is a portion of the craft time that always remains constant. The way batch crafting is implemented doesn't really allow for an accurate way to represent this relationship. And because of that, I'm having to use a kind of janky implementation where I assume the user is going to craft a given number of items, and then work backwards from there to work out the times. These leaves the recipe in a state where if you are crafting under a certain number of items, you actually are worse off than just crafting them one at a time.

2024-10-25 17:49 UTC, Karol1223 requested changes

2024-10-25 17:49 UTC, Karol1223 commented on data/json/recipes/tools/containers.json
> +    "time": " m",
What's going on here

2024-10-25 17:51 UTC, AudBobb commented on data/json/recipes/tools/containers.json
> +    "time": " m",
There should be an 8 there, my bad.

2024-11-23 23:26 UTC, Brambor commented
> there is a portion of the craft time that always remains constant

There is a whole issue about changing the way the crafting works, splitting crafting into parts:
 - #62616

2024-12-18 21:54 UTC, Maleclypse commented
Is this intended to still be in draft?

2024-12-20 01:18 UTC, AudBobb commented
> Is this intended to still be in draft?

Sorry, lost motivation a bit after not being sure how to progress with it, and now with PoE2 released I don't know when I'll get back to looking at this. If anyone has any advice on how to proceed with it, it would help a lot.

2026-07-15 03:35 UTC, closed without merging

2026-07-16 15:08 UTC, Brambor commented
If you get back to it, this can now use the merged multistep recipes.