[Magiclysm] Update proficiency families and weakpoints for Magiclysm monsters
CleverRaven/Cataclysm-DDA pull request #77766
Opened 2024-11-11 20:20 UTC by jpfalk1

#### Summary
Mods "Reviewed Magiclysm Monsters and added proficiency families and weakpoints when missing."

#### Purpose of change
Two related issues noted missing proficiencies and weakpoints in Magiclysm monsters. Resolves #70307, resolves #77361. Black Dragons deserve a custom set of weakpoints, so will be addressed with a separate PR.

#### Describe the solution
Added existing applicable proficiency families (mostly "prof_gross_anatomy", "prof_intro_biology", and "prof_physiology") and weakpoints (mostly "wps_humanoid_body", and "wps_animal_quadruped") to Magiclysm monsters. Using existing proficiency and weakpoint sets from similar base CDDA monsters (i.e. Owlbear has similar proficiencies and weakpoints as a Bear, since it doesn't fly)
Demon Spiders also received applicable bug/spider proficiencies and weakpoints. Some of their general data was also moved to the mod-wide file that was appropriate (i.e. Demon Spider species data moved to data/mods/Magiclysm/species.json). An abstract monster type for demon spiders was also created, although this may have been unnecessary complexity.
Demihuman monsters were updated to consistently include "prof_gross_anatomy" and "prof_intro_biology". Most already had weakpoints defined and the "demihuman" proficiency.
Black Dragons deserve their own unique weakpoints and proficiencies so will be addressed with a separate PR as this one only used existing proficiencies and weakpoints.
Spirits, holograms, summons, and other related monsters that don't leave a corpse or were primarily intended as player summons were left undefined.
Golems were left undefined for proficiencies / weakpoints, consistent with robots in base CDDA.

#### Describe alternatives you've considered
Considered a new set of proficiencies for all Magiclysm monsters (i.e. "Magical Creature") but this seemed overkill for the majority of the creatures so existing proficiencies were used instead (again, except Black Dragons).
Considered leaving undefined, treating Magiclysm monsters are "too different" to have weakpoints. A lot of the demi-human monsters already had proficiencies/weakpoints defined, it was the odd creatures like Yule Cats and such that did not.

#### Testing
Created a local mod and spawned a sampling of affected monsters to confirm dissection provided the relevant proficiency training. Did not have a good consistent test to assess weakpoints, or appropriateness of selected weakpoints.

#### Additional context

2024-11-12 00:13 UTC, jpfalk1 commented
> Spell checker encountered unrecognized words in the in-game text added in this pull request. See below for details.

Fixed.

In general did not do as good a job as I thought in setting up the editor to match the JSON style guide. Will be sure to use the linter in the future.

2024-11-12 01:54 UTC, jpfalk1 commented
Basic build didn't like the "." in the abstract description. Removed.

2024-11-12 06:27 UTC, Night-Pryanik commented on data/mods/Magiclysm/monsters/demon_spider.json
> +    "description": "abstract demon spider you shouldn't see this",
```suggestion
    "description": { "str": "abstract demon spider you shouldn't see this", "//~": "NO_I18N" },
```

2024-11-13 04:10 UTC, Maleclypse requested changes

2024-11-13 04:10 UTC, Maleclypse commented on data/mods/Magiclysm/monsters/monsters.json
> +    "families": [ "prof_gross_anatomy", "prof_intro_biology", "prof_wp_demihuman" ],
```suggestion
```
Demons of shadow and fire aren't mortal and  shouldn't have mortal weakpoints.  At most they should have unique weakpoint sets like Dragons.

2024-11-13 04:10 UTC, Maleclypse commented on data/mods/Magiclysm/monsters/monsters.json
> +    "families": [ "prof_gross_anatomy", "prof_intro_biology", "prof_physiology", "prof_wp_ungulate" ],
```suggestion
```
Too unique for these.

2024-11-13 17:08 UTC, jpfalk1 commented on data/mods/Magiclysm/monsters/monsters.json
> +    "families": [ "prof_gross_anatomy", "prof_intro_biology", "prof_wp_demihuman" ],
Good suggestion, changed the families as suggested and also changed the weakpoint_set to "quadruped".

2024-11-18 09:52 UTC, merged