Add missing longest_side
CleverRaven/Cataclysm-DDA pull request #77850
Opened 2024-11-14 19:56 UTC by xcdxbaxa9

#### Summary
Balance "Add missing longest_side"

#### Purpose of change
Closes #77839

#### Describe the solution
Added missing longest_side fields, updated volume and weight to more reasonable values.

#### Describe alternatives you've considered

#### Testing

#### Additional context

2024-11-14 20:09 UTC, IdleSol commented
I would like to ask for an additional modification to the throwing knife sheaths.

https://github.com/CleverRaven/Cataclysm-DDA/blob/65b3721c1e4624b323d0bd9d69e8f1bdee5a0183/data/json/items/armor/sheath.json#L115

```diff
--        "max_item_length": "10 cm"
++        "max_item_length": "20 cm"
```
Thank you.

2024-11-15 17:10 UTC, RedMisao commented
Regarding the weight change: have you tested the before and after against a target? Weight is used in the throwing formula, and increasing it may break the item.

2024-11-15 17:16 UTC, IdleSol commented
>Regarding the weight change: have you tested the before and after against a target? Weight is used in the throwing formula, and increasing it may break the item.

You mean the axe? Isn't thrown_damage used for damage?
https://github.com/CleverRaven/Cataclysm-DDA/blob/45a67eacdd749fedb6d2e0f7baef2ed036366c0f/data/json/items/ranged/throwing.json#L119

2024-11-15 18:15 UTC, xcdxbaxa9 commented
> Regarding the weight change: have you tested the before and after against a target? Weight is used in the throwing formula, and increasing it may break the item.

Do you mean break as in damage the item? Or break as in make it too powerful or too weak?
I've tested throwing axe before and after, it didn't break. As for effectiveness it didn't look like much changed to me.

2024-11-15 18:24 UTC, RedMisao commented
> You mean the axe? Isn't `thrown_damage` used for damage?

Yes, that is used to calculate damage. I'm referring to the distance and accuracy of the thrown item. Items A heavier than B, is less accurate, and seems to "glance" more (although I'm not sure about this, could be due being less accurate).


> Do you mean break as in damage the item? Or break as in make it too powerful or too weak? I've tested throwing axe before and after, it didn't break. As for effectiveness it didn't look like much changed to me.

As in make it too weak for use as a throwing weapon. If you tested it and found no difference then nvm.

2024-11-16 01:39 UTC, Maleclypse requested changes
Thanks for doing this!

2024-11-16 01:39 UTC, Maleclypse commented on data/json/items/ranged/throwing.json
> +    "longest_side": "20 cm",
```suggestion
    "longest_side": "35 cm",
```
World Knife Throwing League (WKTL) requires that they are between 13.5 and 16 inches long. This length allows throwers of different heights and arm lengths to hit targets at distances of 10 and 15 feet.

2024-11-16 01:39 UTC, Maleclypse commented on data/json/items/armor/sheath.json
> +        "max_item_length": "20 cm"
```suggestion
        "max_item_length": "35 cm"
```

2024-11-16 01:39 UTC, Maleclypse commented on data/json/items/armor/sheath.json
> +        "max_item_length": "20 cm"
```suggestion
        "max_item_length": "35 cm"
```

2024-11-16 01:39 UTC, Maleclypse commented on data/json/items/armor/sheath.json
> +        "max_item_length": "20 cm"
```suggestion
        "max_item_length": "35 cm"
```

2024-11-16 01:39 UTC, Maleclypse commented on data/json/items/armor/sheath.json
> +        "max_item_length": "20 cm"
```suggestion
        "max_item_length": "35 cm"
```

2024-11-16 01:39 UTC, Maleclypse commented on data/json/items/armor/sheath.json
> +        "max_item_length": "20 cm"
```suggestion
        "max_item_length": "35 cm"
```

2024-11-16 01:39 UTC, Maleclypse commented on data/json/items/armor/sheath.json
> +        "max_item_length": "20 cm"
```suggestion
        "max_item_length": "35 cm"
```

2024-11-16 01:39 UTC, Maleclypse commented on data/json/items/armor/sheath.json
> +        "max_item_length": "20 cm"
Change `made to hold 6 very small knives` to `made to hold 6 very thin knives`

2024-11-16 05:19 UTC, IdleSol commented
@Maleclypse

If you increase the length, you have to increase the weight (~500g). And a throwing knife becomes a copy of a combat knife. Only worse.

USMC bayonet:
https://github.com/CleverRaven/Cataclysm-DDA/blob/156cf135f3508ad1b8896c1749a45a36c882a976/data/json/items/melee/swords_and_blades.json#L306-L307

2024-11-16 07:25 UTC, Maleclypse commented
> @Maleclypse
> 
> If you increase the length, you have to increase the weight (~500g). And a throwing knife becomes a copy of a combat knife. Only worse.
> 
> USMC bayonet:
> 
> https://github.com/CleverRaven/Cataclysm-DDA/blob/156cf135f3508ad1b8896c1749a45a36c882a976/data/json/items/melee/swords_and_blades.json#L306-L308

I came up with 340 grams for a 35 cm throwing knife.  But if our system is unable to differentiate between made to be thrown items versus not designed for throwing I suppose these are the limits of the system.

2024-11-16 11:22 UTC, xcdxbaxa9 commented
> > @Maleclypse
> > If you increase the length, you have to increase the weight (~500g). And a throwing knife becomes a copy of a combat knife. Only worse.
> > USMC bayonet:
> > https://github.com/CleverRaven/Cataclysm-DDA/blob/156cf135f3508ad1b8896c1749a45a36c882a976/data/json/items/melee/swords_and_blades.json#L306-L308
> 
> I came up with 340 grams for a 35 cm throwing knife. But if our system is unable to differentiate between made to be thrown items versus not designed for throwing I suppose these are the limits of the system.

Can you elaborate on how you came up with 340 grams for 35 cm throwing knife? If we assume that average density of stainless steel is 7.85 g/cm^3 and volume remains the same (56 ml,) then weight gets around 450 grams, give or take.

2024-11-17 07:58 UTC, Maleclypse commented
> > > @Maleclypse
> > > If you increase the length, you have to increase the weight (~500g). And a throwing knife becomes a copy of a combat knife. Only worse.
> > > USMC bayonet:
> > > https://github.com/CleverRaven/Cataclysm-DDA/blob/156cf135f3508ad1b8896c1749a45a36c882a976/data/json/items/melee/swords_and_blades.json#L306-L308
> > 
> > 
> > I came up with 340 grams for a 35 cm throwing knife. But if our system is unable to differentiate between made to be thrown items versus not designed for throwing I suppose these are the limits of the system.
> 
> Can you elaborate on how you came up with 340 grams for 35 cm throwing knife? If we assume that average density of stainless steel is 7.85 g/cm^3 and volume remains the same (56 ml,) then weight gets around 450 grams, give or take.
> 
> upd: Tested 200 g and 450 g throwing knifes. On average 200 g variants were dealing around 14 points of damage to regular zombies and 450 g variants were dealing somewhere in the range of 20-25 points of damage. I don't know if it makes them too overpowered though.

Volume could change.  Our volumes are generally overstated for objects because it's not displacement volume but a rough estimate of how much volume a thing would take jumbled in a bag.  So for items with any portrusions it's different.  Either way I'm not super interested in this so I'm not pushing my view on you.  If you tell me this is right I'm going to believe you compared to my quick googling that could have been pulling details from multiple different sources in inappropriate ways.

2024-11-17 10:32 UTC, IdleSol commented
#77839 :
>https://worldknifethrowingleague.com/best-throwing-knife/
>
>The overall length of the knife ranges from 13.5 inches to 16 inches or 34 to 40 centimeters. These are the knives they sell and most likely use in competitions.
>
>An additional internet search finds smaller knives: about 20 centimeters long
>
>- JXE JXO Throwing Spikes: https://www.amazon.com/JXE-JXO-Throwing-Spikes-Stainless/dp/B0BN11QJMH
9.4 inch ~ 24 cm, 0.44lbs ~ 200 g
>- MedievalDepot Midnight Flyer Triple Threat Throwing Knives https://www.amazon.com/MedievalDepot-Midnight-Triple-Threat-Throwing/dp/B0188S17S4
7.5 inch ~ 19 cm

2024-11-17 11:57 UTC, xcdxbaxa9 commented
I've left the weight unchanged as in my opinion then throwing knives become too strong.

2024-11-18 01:35 UTC, merged