Fixedbatteryrecipes
CleverRaven/Cataclysm-DDA pull request #78752
Opened 2024-12-24 07:08 UTC by kekwlboy12469

#### Summary
Bugfixes"changes the issue regarding recipes of battery mistake"

#### Purpose of change
#78641 
Mistakes in battery recipes

#### Describe the solution
well i corrected the issue now well i have copied battery recipes from vanila to innawood in new file and i also edited vanila recipes according to user need

#### Additional context

corrected the file data\json\recipes\electronics\toolmod.json
created a new file data\mods\innawood\recipes\battery recipes.json

2024-12-24 07:14 UTC, moxian commented on data/json/recipes/electronics/toolmod.json
> +]
Translation: please add a newline at the end of the file (same with the other one.

2024-12-24 23:59 UTC, Kilvoctu commented
A recipe for car battery already exists. Its id is `battery_car`
https://github.com/CleverRaven/Cataclysm-DDA/blob/47faee4dbe458b4a636c7620b5e62fa4612c63b6/data/json/recipes/electronics/parts.json#L3-L17
![Screenshot 2024-12-24 175035](https://github.com/user-attachments/assets/3991fb0f-5c17-4b58-940c-ee20265f39bd)

2024-12-26 00:57 UTC, RenechCDDA requested changes
I do not understand what you are trying to do here.

You are removing recipes from vanilla. Why?

You are adding them to innawoods, where they will not be accessible. Why?

From the linked issue, it appears that the problem you are trying to resolve is an *inaccurate recipe*. Moving an inaccurate recipe from vanilla to innawoods (where it cannot even be acquired) does not... solve anything.

2024-12-26 07:46 UTC, kekwlboy12469 commented
> I do not understand what you are trying to do here.
> 
> You are removing recipes from vanilla. Why?
> 
> You are adding them to innawoods, where they will not be accessible. Why?
> 
> From the linked issue, it appears that the problem you are trying to resolve is an _inaccurate recipe_. Moving an inaccurate recipe from vanilla to innawoods (where it cannot even be acquired) does not... solve anything.

Thank you for your feedback, and I understand now that my initial solution wasn’t addressing the core issue. The original problem was about inaccurate recipes, not their location. Moving the recipes to Innawood was unnecessary and created accessibility issues.
I’ll make the following changes:
Revert the recipes back to their original vanilla location.
Correct the inaccuracies in the recipes 
I’ll submit an updated version of the PR shortly. Thank you again for pointing this out!

2025-01-04 09:31 UTC, HadeanLake commented
Sorry, I didn't dig deep enough to find this PR before creating mine. I thought I was up to date with current issues and prs but I was not. Are you intend to fix this PR?

2025-01-04 09:33 UTC, kekwlboy12469 commented
U can fix if u want

On Sat, Jan 4, 2025, 3:01 PM HadeanLake ***@***.***> wrote:

> Sorry, I didn't dig deep enough to find this PR before creating mine. I
> thought I was up to date with current issues and prs but I was not. Are you
> intend to fix this PR?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/CleverRaven/Cataclysm-DDA/pull/78752#issuecomment-2570964760>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BLSOFYGLBPBYMDSZXW3HWOT2I6TA5AVCNFSM6AAAAABUEIF4CWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNZQHE3DINZWGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2025-01-05 11:57 UTC, GuardianDll commented
Superseded by #78929

2025-01-05 11:57 UTC, closed without merging