Save compression: 10-15x+ smaller maps, faster saves, corruption resistant, also makes julienne fries.
CleverRaven/Cataclysm-DDA pull request #78857
Opened 2024-12-30 19:33 UTC by akrieger

#### Summary
Infrastructure "Zstandard compressed save data for disk space savings."

#### Purpose of change
Long games get big. Very big. I've been given a sample of one which is almost 4GB of just `maps/` data, not including map memory. Sky Islands mod type games also generate lots of terrain. Multiple dimensions are coming. All of these incur more disk pressure from save data. Compression is the natural answer for this, because save data is almost never meant to be read or modified by humans anyway.

#### Describe the solution
The solution is multipart.

- First, pick a compression algorithm.
  - gzip is terrible and slow.
  - lzma is good but slow.
  - Zstandard (`zstd`) is a modern compression algorithm that generally beats both at speed or performance, and sometimes both at once. It seemed like a plausible option to shoot for first. The library source is not large and is straightforward to integrate with the project due to only having internal dependencies.
  - I chose `zstd`.

- Next, pick a format. Part of the problem with saves is the many large files which individually end up less than a page large, but because modern hard disks have a minimum allocation size of 4KB end up wasting large amounts of disk. So some sort of archive format like zip or tar should be used.
  - Tar is not suitable because it does not support random access to compressed entries. Map data is aggregated in folders where only subsets are loaded / accessed at a time. Linearly decompressing from the beginning would be slow and wasteful.
  - Zip supports random access, but I could not find a good open source library for it.
  - [dar](http://dar.linux.free.fr/) was considered as it does support random access to entries, but overall it seems like an extremely overkill library as it is intended for _disk_ archiving, not just a grabbag of files.
  - So I settled on a proprietary format. There are many advantages. They will be detailed in `Additional context`.

#### Describe alternatives you've considered
- Using a database: ew. Enormous dependency, don't need a query language for functionally a key/value store.
- Saving saves as flexbuffer binary: doesn't really get good space savings.

#### Testing
Create worlds, run around, save, load, it works. Enable and disable compression on these worlds and others. Intentionally hack the zzip implementation to not save a footer, and confirm the data is successfully recovered through the scan and checksumming. Test compaction works by setting a low compaction threshhold and saving after every step in a game, seeing sizes bounce up and down. Fix many bugs I hit along the way.

#### Additional context

2024-12-30 20:20 UTC, akrieger commented on Makefile
> +	$(CXX) -x c $(CPPFLAGS) $(DEFINES) $(CFLAGS) -w -MMD -MP -c $< -o $@
Need to figure out the right answer for -w here.

2024-12-30 23:18 UTC, ZhilkinSerg commented
I've tried zstd with MA overmaps:

| Method | Size  | Disk size |
|--------|--------|--------|
| gz | 8 744 047 | 11 485 184 | 
| zstd -1 | 13 407 208 | 16 068 608 |
| zstd -3 | 12 106 198 | 14 794 752 |
| zstd -3 -D | 12 300 415 | 14 962 688 |
| zstd-19  | 6 893 311  | 9 363 456 |

Dictionary trained with `zstd --train` on all uncompressed omap files with output:

```
Trying 5 different sets of parameters
k=50
d=8
f=20
steps=4
split=75
accel=1
Save dictionary of size 66802 into file dictionary
```

Did not benchmark speed at all.

2024-12-30 23:44 UTC, akrieger commented
Advantage of this format is aggregating sub-4k files together to avoid wasted bytes in the allocation.

I found the best dictionary was with d=20 with the slow cover training params, but on Windows that hits a pessimal behavior in qsort so you should train on windows or fix it like I did (rewrite into c++ and use std::stable_sort parallel).

2024-12-31 04:03 UTC, akrieger commented
> I've tried zstd with MA overmaps:
> ...
> Did not benchmark speed at all.

An interesting thing happens with json around the -13 level (I saw this in development too). With no dictionary:
```
$ zstd/contrib/VS2005/bin/x64/Release/zstd.exe -b1e15 -r MA_overmap/
 1# 1337 files       : 140286061 ->  13401860 (x10.47),  385.8 MB/s,  688.8 MB/s
 2# 1337 files       : 140286061 ->  12869576 (x10.90),  398.4 MB/s,  733.8 MB/s
 3# 1337 files       : 140286061 ->  12100850 (x11.59),  423.8 MB/s,  839.0 MB/s
 4# 1337 files       : 140286061 ->  11375873 (x12.33),  224.8 MB/s,  812.2 MB/s
 5# 1337 files       : 140286061 ->  10260613 (x13.67),  156.1 MB/s, 1218.4 MB/s
 6# 1337 files       : 140286061 ->   9877264 (x14.20),  109.1 MB/s, 1170.0 MB/s
 7# 1337 files       : 140286061 ->   9593546 (x14.62),   68.7 MB/s,  977.8 MB/s
 8# 1337 files       : 140286061 ->   9339853 (x15.02),   54.5 MB/s, 1091.4 MB/s
 9# 1337 files       : 140286061 ->   8858622 (x15.84),   45.3 MB/s, 1195.7 MB/s
10# 1337 files       : 140286061 ->   8444538 (x16.61),   31.6 MB/s, 1214.4 MB/s
11# 1337 files       : 140286061 ->   7770721 (x18.05),   11.0 MB/s, 1820.7 MB/s
12# 1337 files       : 140286061 ->   7568403 (x18.54),   8.83 MB/s, 1816.9 MB/s
13# 1337 files       : 140286061 ->   8586961 (x16.34),   7.04 MB/s, 1342.8 MB/s
14# 1337 files       : 140286061 ->   8044176 (x17.44),   6.06 MB/s, 1972.9 MB/s
15# 1337 files       : 140286061 ->   7033479 (x19.95),   4.57 MB/s, 1962.8 MB/s
```
With dictionary `zstd.exe --train-cover=steps=512,d=20 -r MA_overmap/ -o ma_overmap.dict -M1000MB --maxdict=100KB -T0 -7` (ignore compression/decompression speeds, I changed laptop performance profile in between, just look at ratios):
```
 1# 1337 files       : 140286061 ->  13349825 (x10.51),  664.3 MB/s, 1222.7 MB/s
 2# 1337 files       : 140286061 ->  13690522 (x10.25),  651.0 MB/s, 1210.5 MB/s
 3# 1337 files       : 140286061 ->  12177767 (x11.52),  719.9 MB/s, 1377.6 MB/s
 4# 1337 files       : 140286061 ->  12182817 (x11.52),  618.9 MB/s, 1357.1 MB/s
 5# 1337 files       : 140286061 ->  10714637 (x13.09),  262.3 MB/s  1447.7 MB/s
 6# 1337 files       : 140286061 ->   9801734 (x14.31),  162.1 MB/s, 1901.7 MB/s
 7# 1337 files       : 140286061 ->   9644614 (x14.55),  128.4 MB/s, 1939.1 MB/s
 8# 1337 files       : 140286061 ->   9187718 (x15.27),  106.6 MB/s, 2168.8 MB/s
 9# 1337 files       : 140286061 ->   8702472 (x16.12),   73.8 MB/s, 2345.5 MB/s
10# 1337 files       : 140286061 ->   8274563 (x16.95),   45.5 MB/s, 2595.5 MB/s
11# 1337 files       : 140286061 ->   7556593 (x18.56),   23.8 MB/s, 3356.1 MB/s
12# 1337 files       : 140286061 ->   7322328 (x19.16),   15.9 MB/s, 3476.0 MB/s
13# 1337 files       : 140286061 ->   9136798 (x15.35),   14.8 MB/s, 2419.2 MB/s
14# 1337 files       : 140286061 ->   7879967 (x17.80),   10.8 MB/s, 3081.3 MB/s
15# 1337 files       : 140286061 ->   6781610 (x20.69),   6.44 MB/s, 3444.2 MB/s
```

Thing is, compression speed is irrelevant because the mod content is static. Or static enough. Generally better rations compress better and decompress faster.

Oh and just for fun, as a zzip at compression level 7:
```
$ du -shb save/Timersbaby/maps/ma_overmap.zzip
9776444 save/Timersbaby/maps/ma_overmap.zzip
```

And at 15:
```
$ du -shb save/Timersbaby/maps/ma_overmap.zzip
6913392 save/Timersbaby/maps/ma_overmap.zzip
```

2024-12-31 09:48 UTC, PatrikLundell commented
As far as I understand, this will cause two potential issued:
1. Compressed debug saves. I assume the logic allows for ripping out the unwanted files/folders from a copy of the archive in a modification to the corresponding code (or just copying selected parts), though.
2. Fault finding and hacking. It's not that rare to have the need to examine what's in the save files in order to understand why things misbehave, or remove/fix things that causes a save to blow up when loaded. Thus, there's a need for a tool that allows for the unpacking and repacking of the data in a file. However, having to do that will make the threshold to attempting such activities higher, resulting in poorer support.

2024-12-31 13:12 UTC, akrieger commented
1) yes, good point. However given the size savings it's unclear whether we need to support trimming or just package the dictionary with the subset of bundled maps folders needed. The implementation compresses each subfolder of maps/ separately.
2) there is an option in the main menu for enabling/disabling compression for the whole world at once. It's so fast on normal sized worlds it may as well be instant. For the enormous sample world I have with the 3.5ishGB of data, it takes a couple minutes.

2024-12-31 14:54 UTC, akrieger commented
I wouldn't change anything about the bug report upload, just the maps files inside the save, which would still be a tarball or whatever. Is GitHub complaining about the archive containing those? Like it doesn't support uploading that because it can't virus scan it or something?

2024-12-31 15:12 UTC, PatrikLundell commented
I'd suggest testing if github is uncooperative by tar:ing up a save compressed with your format and post it in a comment.

2024-12-31 16:58 UTC, akrieger commented
Well yes that is the empirical method, but if I could do that right now I would have :)

2024-12-31 22:58 UTC, akrieger commented
> I'd suggest testing if github is uncooperative by tar:ing up a save compressed with your format and post it in a comment.

[Maunawili.zip](https://github.com/user-attachments/files/18283913/Maunawili.zip)

Yeah github dgaf.

2025-01-16 06:43 UTC, akrieger commented
Marking ready for review so the full test suites run, but still need to integrate this with the Android build.

2025-01-16 08:44 UTC, GuardianDll commented
And resolve conflicts

2025-01-17 17:27 UTC, akrieger commented
I split out the zstd source drop into #79220 so this can be more reviewable.

2025-01-18 07:43 UTC, moxian reviewed
Read through the code left some comments.
The only important one is that we might not be particularly corruption-resistant if flexbuffers can segfault when trying to parse garbage data.


The other note that I feel strongly about (and that doesn't fit into github code comments) is please please please don't put the dict files into the root project folder, we have enough random junk there as is. `data/raw/zstd_dicts` or something would be a much nicer place.

2025-01-18 07:43 UTC, moxian commented on src/zzip.cpp
> +    get_file_to( zzip_relative_path, buf.data(), size );
There's no way `get_file_to` returns an error now with the current implementation, but it's probably still a good idea to check the return value and zero-out the return `buf` on failure.

2025-01-18 07:43 UTC, moxian commented on src/zzip.cpp
> +    // TODO should we checksum the file before attempting decompressing?
Flagging a TODO, in case you intended to address it but missed it.
(I don't have a strong opinion on whether or not it's a blocker for the PR, but I doubt anyone except you would touch this part after it lands.
To answer the stated question - yes, we should. Otherwise there's little point for the checksums being there in the first place)

2025-01-18 07:43 UTC, moxian commented on src/zzip.cpp
> +    if( delta < 4 * 1024 ) {
consider factoring out `4 * 1024` page size into a constant (since it's used like 4 times in the file).
(it doesn't save any typing of course, just weird seeing raw constant repeated that much)

Relatedly, and more importantly, the `1024` size  for the footer size estimate is very magical, and definitely needs its own named constant. I only happen to know what it means because I read the other function with the comment about it first.

2025-01-18 07:43 UTC, moxian commented on src/zzip.cpp
> +    }
`do { } while()` would be a bit more concise way to handle retries, IMO

Separately, MSDN [says](https://learn.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-unmapviewoffile):
> Modified pages in the unmapped view are not written to disk until their share count reaches zero, or in other words, until they are unmapped or trimmed from the working sets of all processes that share the pages. Even then, the modified pages are written "lazily" to disk; that is, modifications may be cached in memory and written to disk at a later time. To minimize the risk of data loss in the event of a power failure or a system crash, applications should explicitly flush modified pages using the FlushViewOfFile function.

So I wonder if maybe explicitly flushing it before unmapping (i.e. dropping) would make the rename errors go away?..

2025-01-18 15:44 UTC, akrieger commented
My thinking is, because the flexbuffer validates the object is an object/dict when we create it, and it does that from the last byte(s) of the file, if that passes then everything before those bytes is also still valid. The initial validation just checks some tag bytes and doesnt seek anywhere else in the file so I believe it should work out.

I'll move the dicts, that makes sense.

2025-01-18 15:45 UTC, akrieger commented on src/zzip.cpp
> +    bool needs_recovery = true;
>.< oops, debug code.

2025-01-18 15:48 UTC, akrieger commented on src/zzip.h
> +         * If given, the dictionary is used to compress the files.
It makes compression worse.

Training a dictionary is kinda nontrivial, although technically zstd also supports a dictionary in the form of an arbitrary sequence of 'prefix bytes', but then you pay the cpu cost of parsing it every time you load it. This is somewhat mitigated by the dictionary caching I added. But also I'm not sure if a separate api is needed to load them...

2025-01-18 15:51 UTC, akrieger commented on src/zzip.cpp
> +    // At present, we write two frames:
Two skippable frames.

2025-01-18 16:26 UTC, akrieger commented on src/zzip.cpp
> +    }
The issues I run into are from when I mount my saves in Dropbox. Dropbox locks the file in some fashion so the system can't rename it until the lock is dropped.

My reading from other docs is that ntfs journaling is only for metadata so I believe the pages getting flushed can't block anything, but eg. file names and sizes would.

2025-01-18 16:27 UTC, akrieger commented on src/zzip.cpp
> +    // TODO should we checksum the file before attempting decompressing?
Yeah that was a vestigial comment. Thanks!

2025-01-18 17:21 UTC, akrieger commented on src/zzip.cpp
> +            root = flexbuffer_root_from_storage( storage );
So, we know `end` will be valid. The last byte is `byte_width` which is only used when trying to read data. The next byte is 6 bits of `type` and 2 bits of internal data byte width.
```
    byte_width_ = 1U << static_cast<BitWidth>(packed_type & 3);
    type_ = static_cast<Type>(packed_type >> 2);
```

So if `type_` is not exactly `FBT_MAP` (1 out of 64 possibilities) we would detect that immediately. That doesn't require reading wild bytes.

I'm trying to think of ways we end up with data that looks like a flexbuffer here but isn't. Pages either flush or don't flush. Freshly allocated pages after the compressed data will be all zeroes. So I suppose if the second-to-most-recent insert was a large item with a large estimated buffer, that would leave a lot of padding bytes. The most recent insert is small enough that it fits within that padding so we don't expand the file more, but we then overwrite all of the existing footer minus the last two bytes? Then we unmap the view (to grow the file to write the new footer), the system flushes the pages before we have a chance to grow the file, and then crashes.

Any other way I'm thinking of, we just end up with zeroes everywhere.

We could try wrapping the flexbuffer in a zstd frame, which has a footer, as extra insurance, but then we do have to skip through the whole file to get to the final frame, which I was trying to avoid.

TBH I don't recall measuring the cost of FlushViewOfFile. It's entirely likely it's relatively constant time and non blocking. msync has to be called with MS_SYNC to have any effect though.

(Windows Internals states the filesystem cache flushes to disk at worst in 8 seconds. Each second 1/8th of dirty pages are queued to be written, I'm guessing based on some tag byte value of the address or idk).

2025-01-18 17:24 UTC, db48x commented on src/zzip.cpp
> +    tmp_path.replace_extension( ".zzip.tmp" ); // NOLINT(cata-u8-path)
Shouldn't you use `mkstemp` here?

2025-01-18 17:45 UTC, akrieger commented on src/zzip.cpp
> +    }
I guess another option would be to have a/some fixed sized frames at the head of the file which are footer length + checksum and just use that.

2025-01-18 17:50 UTC, akrieger commented on src/zzip.cpp
> +    // TODO should we checksum the file before attempting decompressing?
Actually imo, the checksums are there for detecting corruption in the frame in the case of a power loss event. xxh3 is not super fast. I could benchmark what it would add to access times to always checksum though.

2025-01-18 17:51 UTC, akrieger commented on src/zzip.cpp
> +    tmp_path.replace_extension( ".zzip.tmp" ); // NOLINT(cata-u8-path)
The old save path always wrote the .tmp file adjacent to its replacement.

2025-01-18 18:15 UTC, moxian commented on src/zzip.cpp
> +    // TODO should we checksum the file before attempting decompressing?
The xxh3 [marketing materials](https://github.com/Cyan4973/xxHash) say that it is, in fact, super fast

2025-01-18 18:26 UTC, moxian commented on src/zzip.cpp
> +            root = flexbuffer_root_from_storage( storage );
Actually, i like your other comment
> I guess another option would be to have a/some fixed sized frames at the head of the file which are footer length + checksum and just use that. That eliminates the guesswork and 'maybes' from the equation.

Except it doesn't need to be at the *start* of the file. We can have it at the end, as it is now, just wrap it into a fixed-size block (`1024` bytes perhaps 🙃 ) with a checksum attached. I don't think it needs to be a "real" zstd frame.

2025-01-18 18:45 UTC, db48x requested changes, later dismissed

2025-01-18 18:45 UTC, db48x commented on src/zzip.cpp
> +    tmp_path.replace_extension( ".zzip.tmp" ); // NOLINT(cata-u8-path)
Yea, that’s why I suggested `mkstemp` rather than `std::tmpfile`; it lets you specify the path. It's not so much about security (in this case) as it is about avoiding a filename that any other process is using for any reason, such as Dropbox. As an alternative, consider calling `open` with the `O_TMPFILE` flag on Linux. This gives you an unnamed file that Dropbox can’t see until you name it in the final step; I assume there’s something similar on other platforms.

2025-01-18 21:00 UTC, akrieger commented on src/zzip.cpp
> +    // TODO should we checksum the file before attempting decompressing?
I mean, I guess. We're not using the asm accelerated versions I don't think. But bench first and complain later I suppose.

2025-01-18 21:01 UTC, akrieger commented on src/zzip.cpp
> +            root = flexbuffer_root_from_storage( storage );
> it might be tricky updating it each time

Nah. The frame and content size is constant. It'll just be two packed 64 bit ints.

2025-01-19 05:40 UTC, akrieger commented on src/zzip.cpp
> +        while( entry_begin < file_len ) {
It is supposed to be entry_offset. Good catch.

2025-01-19 23:43 UTC, akrieger commented on src/zzip.cpp
> +    tmp_path.replace_extension( ".zzip.tmp" ); // NOLINT(cata-u8-path)
Ok, on Windows std::filesystem::rename is implemented with MoveFileEx with MOVEFILE_REPLACE_EXISTING which is atomic (enough) on a same-volume move https://github.com/microsoft/STL/blob/main/stl/src/filesystem.cpp#L722. The linux rename api is guaranteed atomic.

The issue with Dropbox isn't that it's using the filename, it's that it briefly locks the file after it is closed before the rename so it can index it.

2025-01-20 00:01 UTC, db48x commented on src/zzip.cpp
> +    tmp_path.replace_extension( ".zzip.tmp" ); // NOLINT(cata-u8-path)
Right, the point is to prevent it from being able to do that.

2025-01-20 01:54 UTC, akrieger commented on src/zzip.cpp
> +    tmp_path.replace_extension( ".zzip.tmp" ); // NOLINT(cata-u8-path)
There's not really a way to do that which preserves atomicity on all platforms. There's no guarantee we have a writeable location on the same volume that isn't watched by another process.

2025-01-20 02:33 UTC, akrieger commented on src/zzip.cpp
> +    tmp_path.replace_extension( ".zzip.tmp" ); // NOLINT(cata-u8-path)
I tested this code a bunch and for whatever reason, the zzip codepaths do not trigger issues with dropbox, despite repeatedly having issues with eg. map memory or other misc files in the root of the save folder. I never hit a case of needing to retry the save here.

2025-01-20 21:10 UTC, akrieger commented
Addressed review comments. Significant refactoring due to inserting a footer checksum frame at the front of the file, DRYing some of frame reading/writing code into private functions, added delete functionality, more comments, just a nontrivial amount got changed.

2025-01-22 04:39 UTC, akrieger commented
Actually, overmaps are easy. They are never deleted and only read/generated in like one place. I can handle those in this PR.

Map memory, maybe slightly more complicated. But I haven't looked too closely. If it's not bad then we can just do everything relevant in this PR and not need any followup.

2025-01-29 06:42 UTC, GuardianDll commented
Is it still WIP?

2025-01-29 18:17 UTC, akrieger commented
Yep.

2025-03-06 14:21 UTC, sonphantrung commented
On a side note, I'm actually highly curious about the origin of the "zzip" format. The closest thing I could find on Google is [this thing](https://github.com/ddebin/zzip/).

2025-03-06 17:20 UTC, akrieger commented
It's my own design.

2025-03-06 17:24 UTC, akrieger commented
I might rename it to .zstz to avoid confusion but given that one is 9 years old (and I have no plans for making it a separate library) I'm not sure I care.

2025-04-09 03:06 UTC, akrieger commented
I'm just on fire IRL so I haven't had time or brainpower to code.

2025-05-19 01:44 UTC, akrieger commented
I had an idea I want to try for map memory to make it a bit better but otherwise this is pretty good to review.

2025-05-27 04:33 UTC, Maleclypse commented
Conflicts and still far beyond my scope of merging

2025-06-07 09:39 UTC, GuardianDll commented
/home/runner/work/Cataclysm-DDA/Cataclysm-DDA/Cataclysm-DDA/src/zzip.h:15:1: error: superfluous '#include "std_hash_fs_path.h"'
/home/runner/work/Cataclysm-DDA/Cataclysm-DDA/Cataclysm-DDA/src/zzip_stack.h:15:1: error: superfluous '#include "std_hash_fs_path.h"'

2025-06-07 12:40 UTC, akrieger commented
Yeah well IWYU can suck it (I can write that header in a way which IWYU won't complain about). I need to touch it to fix Mac too.

2025-06-09 12:28 UTC, merged

2025-06-09 12:28 UTC, GuardianDll commented
🫡